### ISSUE TITLE
game.world.bounds.intersects(body) does not work for left bounds (x<0)

### ISSUE THREAD

**Issue by valueerrorx** [photonstorm/phaser#1203]
i am using this function to check if  a body that jumped over a ramp (and therefore was set to sensor=true) has left the worldbounds and should be killed.

this works for all edges of the world except for the left one..

 

i can manage to make it work by asking for 

    if (body.x <0) {killit }

but if i use the intersects method it will always return true even if  x is much smaller than 0  

 

if i console.log the game.world.bounds i get:

    b.Rectangle {x: 0, y: 0, width: 3200, height: 2560, offset: function…} 

so with the worldbounds it seems everything is ok.

**Comment by photonstorm** [comment]
Rectangle.intersects expects 2 Rectangle objects in order to work. Failing that, it needs 2 objects that provide all of the following properties (which must be accurate and in the same local space as each other)

```
width
height
x
y
bottom
right
```

P2.Body does not provide any of these (except x and y). You could perhaps get them from p2.Body.aabb (via conversion of the upper and lower bounds back to px).

Either that or your `body` in the code above is actually a Sprite and not a physics body at all?

**Comment by valueerrorx** [comment]
so the problem is that i am using a p2 body ? in this special case it also is a circle!
i just read the docs carefully.. it definitely says that it needs 2 rectangles.. i must have overlooked this..  sorry..  this is no bug :)
