### ISSUE TITLE
audio sprites don't work on opera

### ISSUE THREAD

**Issue by enriqueto** [photonstorm/phaser#1262]
using phaser 2.1.3

http://coldcherry.com/test/opera-audio-sprites/

**Comment by photonstorm** [comment]
Sorry this took a while, but I've tested the Phaser Audio Sprite example in Opera 21 and Opera 27 on Windows 7 and they're working fine. So I'm afraid it must be something specific to your example / audio files causing it (or quite likely a problem with Phaser around the time you reported this, that has since been fixed)
