### ISSUE TITLE
parseTiledJSON fails if using tileset with type of 'collection of images'

### ISSUE THREAD

**Issue by jfraleigh** [photonstorm/phaser#1339]
Error is : TileSet image dimensions do not match expected dimensions. Tileset width/height must be evenly divisible by Tilemap tile width/height.

This new type allows for different sized images to be placed in a tileset, unfortunately  Phaser is still trying to verify the height/widths. There is no imageheight or imagewidth property in the JSON file when using this type.
I'm using this new type to populate the map with images on an Object Layer that will be animated from within Phaser.

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)

**Comment by maxpa1n87** [comment]
Hi. I cloned the dev branch. Build it without custom build steps. I created a map in Tiled using image collection. But when parseTiledJSON is called it shows me an error 'Uncaught TypeError: Cannot read property '2' of undefined' @phaser.js:93337. Checking the line is states sid = map.tiles[tile.index][2];. Was it fixed in the dev branch? I'am using version 2.4.5-dev. Any reply would be nice. Thanks.
