### ISSUE TITLE
phaser v2.2.0-RC12 camerafollow bug with arcade physics (sprite jitters)

### ISSUE THREAD

**Issue by jpcloud** [photonstorm/phaser#1377]
Hi Phaser-Team,

I am testing phaser v2.2.0-RC12 (Built: Thu Nov 27 2014 21:10:45) and I am experiencing the following problem with camera follow:

Set the camera to follow a sprite, move this sprite via setting it's arcade body velocity.

Expected behavior:
As long as the cam has not reached any bounds I would expect the sprite to be absolutely still in the middle of the screen.

what actually happens:
the sprite around jitters by a pixel

jsfiddle: 
http://jsfiddle.net/jppresents/ab4r7ekv/

(hold cursor right to see the effect, there is no actual sprite, but the green-error-box jitters instead of beeing still).

also: if you move the sprite by setting x or y every frame, then there is no jitter.

I would consider this bug critical, because it makes camera follow with arcade physics unusable.

Another user has found this problem too in a phaser 2.x version:
http://www.html5gamedevs.com/topic/10377-bodyvelocity-camerafollow-is-choppy/
(unresolved, only workarounds posted)

**Comment by photonstorm** [comment]
I've spent some time looking into this today - and the solution proposed in the PR doesn't actually solve the issue. Pixi *by default* works on sub-pixel boundaries when rendering. It does not compensate for this, and setting `camera.roundPx = true` won't make any difference in the jsfiddle above, because the Sprite itself is still at a non-integer position.

The solution is to tell Pixi to not render sub-pixels. This only needs doing once in the renderSession, and will stop all the 'jiggling' going on without having to round any values internally (physics, camera or otherwise):

`game.renderer.renderSession.roundPixels = true`

Add that line to the jsfiddle and notice the difference! I'm going to close this issue off as the above should be the way this is handled. I'm half-tempted to turn it on by default, but that's a considerable change and doesn't suite all art styles, so maybe not for now. I will however mention it in the Camera part of the docs.

**Comment by jpcloud** [comment]
thanks for looking into it and providing a solution :)

**Comment by hocuspucus** [comment]
We started a game in Phaser two years ago and had to leave the project because this. It's a shame that two years later nothing changed at all, even with `game.renderer.renderSession.roundPixels = true;` Check this out: http://jsfiddle.net/7LLqnxw1/16/
