### ISSUE TITLE
"Render Texture Starfield" fails in IE 11 under WebGL

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser#1381]
Demo on dev: http://examples.phaser.io/_site/view_full.html?d=display&f=render%20texture%20starfield.js&t=render%20texture%20starfield&phaser_version=dev&

There is a TypeMismatchError from `gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, texture.source);` in `PIXI.WebGLRenderer.prototype.updateTexture`.

This problem does not occur in CANVAS mode.

**Comment by photonstorm** [comment]
This bug is specific to the version of IE11 being used. In short it means you're using an older version of IE11 that doesn't support UNSIGNED_BYTE. This is fixed in the current public release of IE11.

There's no (known) clean way to detect this automatically, and it won't be done by Pixi either  (https://github.com/GoodBoyDigital/pixi.js/issues/1383) so I'm reluctantly closing this off.

**Comment by photonstorm** [comment]
Actually the above isn't correct. But I've since fixed it, so all is right in the world of IE again.
