### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by ahumphreys87** [photonstorm/phaser#1434]
Great library by the way! One glaring thing thats missing for me is unit tests. Phaser is used by thousands now and people rely on it for their apps, I think adding unit tests to the build step will give people more confidence going forward.

Do you guys have a plan for adding them? I will be happy to contribute a PR with a setup for mocha similar to what we have in the backbone.marionette project. Would you accept the PR before I spend some time on it?

I appreciate it may take some time to boost the test coverage and testing drawing the graphics on the canvas would be difficult but even basic tests that look at setting property values or ensuring events are fired would be a welcome addition.

Thoughts?

**Comment by ahumphreys87** [comment]
just come across this: https://github.com/CreateJS/EaselJS/tree/master/tests could be useful to look here and see how they have handled testing their canvas. Thoughts @photonstorm ?

**Comment by photonstorm** [comment]
This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)

(and yeah I quite like the cjs way of matching against pngs, will give it a go in v3!)

**Comment by formigone** [comment]
I came across this feature request after trying to figure out how the tilemap stuff works. Since a lot of the documentation is mostly the phaser-examples repo, I think some unit tests for those non-visual components would go a long ways. 

Would you still accept PR against the Dev branch with some unit tests for components like that (geometry, math, etc., as well as some of the core classes)?

**Comment by photonstorm** [comment]
I'm a bit worried about this - while at the same time I really want to do it.

My worry is that we would need *so many* tests to accurately cover the framework that it would take months of hard work to create them all. My other worry is that by implying we have tests we lull contributors into a false sense of security if they submit a change and run the tests and they all pass, but just because the tests don't even touch the part of the framework they contributed to.

On the flip-side perhaps some tests are better than none at all?

**Comment by georgiee** [comment]
> On the flip-side perhaps some tests are better than none at all?

Absolutely! With those basic tests on hand it can grow pretty large and cover all the extra features- driven by you or the community. And please don't care for lulling the contributors in false security. Because of having some tests, this might be the first time that a contributor is thinking about side effects at all :)

**Comment by formigone** [comment]
Exactly. I think if there's already a set of tests in place, then it'd be pretty easy to add more tests that cover more of the framework. 

With that in place, you could require (or strongly encourage) that contributors include passing tests that cover their new code and/or bug fix.

**Comment by photonstorm** [comment]
I couldn't require it until the framework is covered fully (it would just be unfair). But I could ask them to do it.

Ok fine, if someone wants to kick this off then go for it.

**Comment by formigone** [comment]
Very well. I'll have my PR ready by the end of the day.

**Comment by photonstorm** [comment]
Don't rush it. I'd rather it be a really good solid foundation for other tests to be built from, than something squeezed out in an evening.

**Comment by luchillo17** [comment]
Definitely not "rushed" as finding resources on testing phaser games is nigh impossible.
