### ISSUE TITLE
When the game starts with a small window and then resized to full window performance is good. When starts in the full window performance is bad.

### ISSUE THREAD

**Issue by bitplanets** [photonstorm/phaser#1480]
I don't know why but if I start the game in a small window and then resize to full screen I have 60fps. If I start the game already big my fps are 50 with a lot of 30fps in the chrome dev graph.

Why that? What code do you need to see? My game is quite big so a quick example is not possible.

Strangely the snapshot also has changes:

 - Open in small window and then resize: 19.8MB;
 - Open big window: 36.8MB;

This difference is quite consistent. I once got the game running in full screen from start and got 60fps.

The data is allocated in:

 - JSArrayBufferData +6.8MB, delta +226 (PIXI->defaultRenderer->spriteBatch->vertices->backing_store)

I think is better to download the [heapfiles](http://wikisend.com/download/263780/Desktop.rar) or [mirror](http://www.files.com/set/54986ba302dfa) (use them in chrome). Unzip them.

# Start big
![start big profile](https://cloud.githubusercontent.com/assets/9990869/5529651/ab59b81e-8a0e-11e4-8d0f-2fbf53daff09.jpg)
![start big snapshot](https://cloud.githubusercontent.com/assets/9990869/5529655/ab634762-8a0e-11e4-8f01-1bac122ecfb1.jpg)
![start big](https://cloud.githubusercontent.com/assets/9990869/5529652/ab5e38f8-8a0e-11e4-90d6-91273665c7a2.jpg)

# Start small
![start small profile](https://cloud.githubusercontent.com/assets/9990869/5529670/d68cb7d4-8a0e-11e4-9957-5ff057cd7854.jpg)
![start small snapshot comparison](https://cloud.githubusercontent.com/assets/9990869/5529671/d691f898-8a0e-11e4-8fdf-66ee86453fde.jpg)

**Possible trick which increase the odds to get better fps**

Start the game with 50x50 px and then resize. I can't use this in production because my camera uses 

    data.game.world.pivot.x  = data.cameraStore.getCurrentX();
    data.game.world.pivot.y  = data.cameraStore.getCurrentY();

`game.world.pivot.x` to scroll. Which is needed in order to zoom in the center of the world. With this trick it zooms at top left center.

The scaling is done like this:

    data.game.camera.scale.x = data.cameraStore.getCurrentZoom();
    data.game.camera.scale.y = data.cameraStore.getCurrentZoom();

# Update

Strangely on another machine works ok even if it starts in a bigger resolution.

**Comment by photonstorm** [comment]
I'm wondering if this isn't environment specific, i.e. something to do with browser-side GPU handling on a specific machine, rather than a global thing that happens (because it's not something I can reproduce here).

The only way I can see resizing making a difference would be if:

1) Phaser is using a RESIZE / % based canvas, so it's just creating a load more pixels in the first place - although I doubt that's the cause here as you would have realised it yourself.

2) Something in the new Scale Manager is causing it to try to adjust the canvas or parent size maybe (hard to profile without an example though).

Feel free to re-open this if you can provide a use-case.
