### ISSUE TITLE
Problem with example Button Open Popup

### ISSUE THREAD

**Issue by kakawi** [photonstorm/phaser#1487]
the problem near 
  closeButton.inputEnabled = true;
when I comment this line the example start to work, only button 'close' don't work

**Comment by pnstickne** [comment]
I can reproduce with latest dev + physics patch applied (so that bit is out of the way).

**Comment by photonstorm** [comment]
This is now fixed in the examples repo (although not on the web site yet).

There's something going wrong re: input handling when a sprite has a scale of zero (it thinks it is taking over the entire display). This is a new manifestation, it certainly never used to happen, so will need to dig deeper.
