### ISSUE TITLE
Input "Over" events do not trigger when a Sprite moves into / under a Pointer

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser#1508]
Reproduce by running [Pixel Perfect Click Detection](http://examples.phaser.io/_site/view_full.html?d=input&f=pixel+perfect+click+detection.js&t=pixel%20perfect%20click%20detection) or [Rotated Buttons](http://examples.phaser.io/_site/view_full.html?d=buttons&f=rotated%20buttons.js&t=rotated%20buttons).

Verify that the "Over" event works when the pointer is moved, by moving the pointer over the spinning sprite. Then place the pointer off the sprite, but to a location the sprite will turn into.

Problem: the "Over" event is not triggered when the sprite/button rotates under the pointer.

**Comment by photonstorm** [comment]
It's not really anything to do with rotation or sprite motion as such, it's just that the mouse didn't move, so no movement event was triggered, so the input handler didn't re-check anything.

If you think about it the alternative is to re-check every single input enabled object against *all* pointers previous x/y coordinates, every single frame. That would account for the point not having moved, but the objects doing so.

Part of me thinks that's a horrendous idea (because performance wise, it is) - the other part things it could possibly be a user-defined setting.

**Comment by photonstorm** [comment]
I'm going to mark this as a v3 feature (that users can easily disable!) as I don't plan on refactoring v2 enough to support this.

This feature request has been moved to the [Phaser 3 feature list](http://www.html5gamedevs.com/topic/7949-the-phaser-3-wishlist-thread) (so is being closed here)
