### ISSUE TITLE
Context becomes null when creating buffer

### ISSUE THREAD

**Issue by ConradKurth** [photonstorm/phaser#1539]
There is an issue on mobile when phaser games are created over and over again with routes.
After a few games the sound managers context will become null and will throw an error when createBuffer is called in the sound manager. I can 100 percent recreate this bug for testing purposes

**Comment by photonstorm** [comment]
As I replied on the forum thread about the same subject, it basically runs out of AudioContexts for the sound card / browser. If you know of a way to cleanly remove an in-use AudioContext (beyond `nulling` it, which we do already!) then let me know and we'll add it to the code, otherwise am a bit stumped really.

**Comment by photonstorm** [comment]
Ok I've worked on this a bit and Phaser will now automatically re-use the same audio context it created the first time around if you destroy and re-create a game. To do this you need to ensure there is a global (window level) var called `PhaserGlobal`:

```
var window.PhaserGlobal = {};
```

If this exists then the SoundManager will write its audio context to `PhaserGlobal.audioContext` when it is destroyed. When re-started it will look to see if this property exists and if it does, it'll use that context.

This should give you the ability you need to keep re-using the same audio context over and over.

**Comment by ConradKurth** [comment]
Awesome!! Thank you so much. You rock!
