### ISSUE TITLE
Better handling of 'Texture Error: frame does not fit inside the base Texture dimensions'

### ISSUE THREAD

**Issue by fyyyyy** [photonstorm/phaser#1556]
Hey there
I have a game where users can upload their own spritesheets. However when they make a mistake, e.g. a sprite that is 1 pixel too narrow, the error 'Texture Error: frame does not fit inside the base Texture dimensions' is thrown in the console. And the entire game stops loading. I currently do not see a way to try/catch that inside my game code. Is it possible to allow the the game developer to handle this exception ?
Or to provide a function to "test" assets before loading them

Thanks :+1: 

My current workaround is

```javascript
PIXI.Texture.prototype.setFrame = function(frame)
{

   ...

    if (!this.trim && (frame.x + frame.width > this.baseTexture.width || frame.y + frame.height > this.baseTexture.height))
    {
        this.valid = false;
        return;
        //throw new Error('Texture Error: frame does not fit inside the base Texture dimensions ' + this);
    }

**Comment by pnstickne** [comment]
I would check the user-supplied texture first.
The same logic check can be used - but applied sooner, and then resulting in a "friendly error".

However, if the texture *is* used then I think it is fitting that it's a should-not-be-handled exception: it's a programming boo boo.

**Comment by fyyyyy** [comment]
Thanks, @pnstickne . Unfortunately it happens on the game.load[method] callback. So i have no chance to check anything before the texture is actually loaded. I would need to write a custom loader and then pass the texture to phaser. Seems a bit clumsy or do you have another solution?

**Comment by photonstorm** [comment]
The error doesn't come as the result of a load operation though - it arises when you try to apply it to a sprite. So you can easily load the image and manually check its dimensions well before you ever need to actually use it as a texture.

**Comment by photonstorm** [comment]
Actually scratch that - if it's a sprite sheet then you *would* need to specify the correct dimensions on load. However as you can't guarantee it just load it as an image. Then manually check the dimensions. If they're correct you can then pass it over to the sprite sheet parser and add it to the cache directly (just look at what load.spritesheet does when it completes - you can do the exact same call from your own code).

**Comment by fyyyyy** [comment]
Ok cool thanks.
So i guess i will write a load.validateSpritesheet, and then have load.spriteSheet dispatch to that for the validity check.

**Comment by photonstorm** [comment]
If you look at `Cache.addSpriteSheet` that is all you need. You can simply call that *after* you've verified the image is correct and it'll parse and add the sprite sheet to the cache quite happily.

**Comment by fyyyyy** [comment]
Ok i've tried but it gets uglier by the minute.
First of all, the setFrame check is per frame, so i have to reimplement walking through every frame in the spritesheet and checking it against the image's width supplied by the game.cache.

The other problem is that the engine doesn't really care about adding the Cache.addSpriteSheet after load, it will just use the image that got loaded with the same key.
Any ideas?

**Comment by fyyyyy** [comment]
I also checked game.load.onFileError, unfortunately it doesn't fire otherwise i could catch the error and notify the user that his spritesheet is wrong. It would be really convenient if PIXI fired an event in case the  frame cant be set.

**Comment by photonstorm** [comment]
It's not a file error though, so the loader shouldn't fire it. The image *loaded* fine. It's just that you gave it bogus dimensions so the sprite sheet parser can't chop it up the way you've told it to. You need to give it accurate dimensions. If that means taking the source image width/height and doing a little simple division to work out if the given frame dimensions are right or not, then so be it - that's what needs to be done.

Alternatively patch your copy of Pixi to get around the error it throws, but it's not something that should be done on a framework level - because fundamentally the dimensions it was given were *wrong*. I think it's fair of Pixi to expect it is given the correct frame dimensions when creating a texture, and if there's any possibility they might be wrong then they need validating in userland code before it's asked to make a texture with them.

**Comment by pnstickne** [comment]
@fyyyyy If you could get the "on load" of the resource, would that be sufficient to handle this problem easily?

**Comment by photonstorm** [comment]
I assume not because it's trivial to get the load event for a specific
asset already. The issue is surely that you don't know the dimensions are
wrong until you try and make a sprite sheet from it, by which point it's
too late.


On Monday, January 26, 2015, pnstickne <notifications@github.com> wrote:

> @fyyyyy <https://github.com/fyyyyy> If you could get the "on load" of the
> resource, would that be sufficient to handle this problem easily?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/1556#issuecomment-71409073>.
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by fyyyyy** [comment]
I guess an onSpritesheetError event would be a candidate. I tried writing the logic for validating the spritesheet but its actually quite complex. Sometimes the image is like 2 pixels to wide and im not sure if the frames wrap around that or not, and wether the wrapping causes errors in itsself. Also it was difficult to add a spritesheet after the image had been loaded and notify pixi about that. It always added the image instead of frames in game. So in the end i gave up and just added one line of event firing to the phaser code :D lazy but at least it works. Maybe i'll make a request at pixi for adding another event.

**Comment by photonstorm** [comment]
There you go - it's not an event, but it at least doesn't crash your entire game any more and gives you the chance to do something about it.
