### ISSUE TITLE
Missing drawEllipse() Method on Phaser.Graphics

### ISSUE THREAD

**Issue by jackrugile** [photonstorm/phaser#1574]
When trying to draw an ellipse with Phaser.Graphics, it doesn't seem to exist the way drawCircle() does.

The example below will draw the circle, but not the ellipse. [View Demo](http://codepen.io/jackrugile/pen/92a1f3b3e2e525d57bda60d7edb0f1d2)

    var game = new Phaser.Game(800, 600, Phaser.AUTO, '', { create: create });

    function create() {
      var graphics = game.add.graphics(0, 0);
  
      graphics.beginFill(0xff0000);
      graphics.drawCircle(470, 200, 100);
      graphics.endFill();
  
      graphics.beginFill(0x00ff00);
      graphics.drawEllipse(270, 200, 100, 100);
      graphics.endFill();
    }

I assumed it would be the next method after drawCircle(): https://github.com/photonstorm/phaser/blob/master/src/gameobjects/Graphics.js#L206

I tried adding it myself, but it still doesn't seem to work. Is there a reason it's not attached to Phaser.Graphics? Do I have to call it directly from PIXI?

Testing with Phaser 2.2.2

**Comment by davidfig** [comment]
There's definitely a problem with the drawEllipse. I managed to get it working by changing the type in the constructor:

Phaser.Ellipse = function (x, y, width, height) {
    this.type = PIXI.Graphics.ELIP; //Phaser.ELLIPSE;
...

I haven't dug deep enough into the code to figure out what's going on. The Phaser.Graphics.drawEllipse call is missing, as Jack mentioned. Not sure if that was intentional, but it's not needed if the type is properly set (probably because it relies on the PIXI library for the rendering).

The change above is a hack. The Phaser.Circle did not need a PIXI type, so I'm confused why the Ellipse does.

**Comment by photonstorm** [comment]
I can confirm this is now working in 2.3-dev properly.
