### ISSUE TITLE
Nesting fixedToCamera objects seems to double the effect

### ISSUE THREAD

**Issue by P0rnflake** [photonstorm/phaser#1596]
Dear Phaser team,

I have recently discovered a strange behaviour of nested fixedToCamera objects.

Please take a look at the example at http://codepen.io/anon/pen/MYEGbz?editors=001.

As you can see I have a fixed red rectangle at the top of the stage. A tween moves the camera down and up again (the blue rectangle seems like it is moving, but it is still at its original coordinates).

The red rectangle is also part of a group (line 29). 

If you set the group also fixed to camera (e.g. uncomment line 32) you can see the red rectangle moving down. Probably the fixedToCamera stacks the effect for each nested layer, or am I wrong?

Is this a bug or a desired behaviour?

**Comment by photonstorm** [comment]
Thank you for the test case. While undesirable I'm happy to fix this by just changing the documentation, rather than doing anything in the code. I don't want to get into the realm of searching the entire display list to see if any parent is also fixed. In short, it a parent is fixed, don't fix the children too. This is now reflected in the docs.
