### ISSUE TITLE
Tween interpolation default, incorrect context

### ISSUE THREAD

**Issue by FridayMarch26th** [photonstorm/phaser#1618]
A tween's interpolationFunction property defaults to Phaser.Math.linearInterpolation, like this:

`
this.linearInterpolationFunction = Phaser.Math.linearInterpolation
`

This results in an error "Uncaught TypeError: undefined is not a function", I think because the above line of code shifts the context of .linearInterpolation from Phaser.Math to the tween. Should the above not be set as it is by tween.interpolation, like this?:

`
function(v, k) {
return Phaser.Math.linearInterpolation(v, k);
})
`

**Comment by photonstorm** [comment]
True, this is relatively easy to fix - however the bigger problem imho is that I don't think it should be using the interpolation function at all. In the original tween.js if you provided an array it copied the two arrays together and then passed it to the ip function in Tween.update, which only ever worked on the first element in the array.

In my mind I think if you give an array of values it should apply the tween to all elements of that array (providing they have correspondingly set start values), rather than just the first element of an array.

Also you should still provide an object to Tween.to, it should never be an array  (although I guess technically it won't hurt).

**Comment by photonstorm** [comment]
Here's another thought.. maybe the interpolation function should only ever be used if you give an array to Tween.to. For example this would use the approach I outlined above:

```
    obj = { "data": [ 100, 200, 300 ] };

    var tween = game.add.tween(obj).to( { data: [ 200, 300, 400 ] }, 2000, "Linear", true);
```

Whereas this would use interpolation:

```
    var tween = game.add.tween([ 100, 200, 300 ]).to( [ 200, 300, 400 ], 2000, "Linear", true);
```

**Comment by photonstorm** [comment]
Ignore the above :) I'm going with the way tween.js does it and this is now working properly in the dev branch.
