### ISSUE TITLE
Inconsistent onHold between Keys and Inputs

### ISSUE THREAD

**Issue by AlexMouton** [photonstorm/phaser#1660]
Hi folks.

I am looking into touch, swipe, and gestural input for a game and I noticed that _inputs do not have a repeating onHold call like Keys_.  Keys also use what looks like an old style Callback/Callback-Context pattern where Input gives onHold as a Signal.

Touches are reasonably satisfied by onTouch.
Swipes can be gleaned from onDown,onUp.
A broader gesture gets some help from moveCallback, but fails to give a callback when motion stops.

I personally would like to see onHold be repeating in both context as they are a continuing conduit into the update loop for input processing code.  Also It would be nice if onHold and moveCallback could converge on Signal.

Is there any development going on here?

Thanks.
Alex Mouton

**Comment by photonstorm** [comment]
Phaser often uses callbacks instead of signals in areas that are likely to generate excessively high volumes of events, such as mouse movement. The cost of dispatching so many signals at such a high frequency isn't warranted, so a callback syntax is used instead.

However I did quite a bit of work this week on button handling (from mouse or PointerEvent), allowing far more fine-grained polling of actual button states on a per button basis, where-as before this was impossible to do. You can now monitor booleans such as `Pointer.leftButton` etc, which personally I think is more useful than a constantly dispatched onHold signal.
