### ISSUE TITLE
Paused audio marker does not resume as a marker.

### ISSUE THREAD

**Issue by AnderbergE** [photonstorm/phaser#1669]
Steps to repeat bug:
1) Create a sound object with markers.
2) Play the sound marker.
3) Pause when it is not in start position.
4) Resume.

Expected behaviour:
Sound object should resume the current marker and stop when marker ends.

Actual behaviour:
Sound object resumes where it is paused, but then runs for the duration of the marker, not the time positions of the marker. (That is, if the sound marker is 7 seconds, from say 0s to 7s, and you resume at position 4s, the sound plays until 11s.)

Possible cause:
The pause function calls the stop function. That function sets the currentMarker to empty string. The resume function does not set the currentMarker again.

(Using dev-branch from 2015-03-11)

**Comment by pnstickne** [comment]
Patches welcome!

**Comment by photonstorm** [comment]
I'll have a look, but this is only reliably fixable in Web Audio.

**Comment by photonstorm** [comment]
Ok this is fixed as far as it can go really. You were right, if you called Sound.pause and then Sound.resume it would bleed into the marker following it (depending on how long it was paused for) under Web Audio. I have no fixed this and it will no longer do it. Under Legacy Audio it should ironically be fine already because it was using time based duration counting.

If you stop the Sound (i.e. by pausing the entire game) then it doesn't resume it anyway, it's just stopped dead. This probably isn't perfect behaviour, but it's consistent with how it worked before so I'm considering this one solved.

**Comment by AnderbergE** [comment]
Works for me :+1:
