### ISSUE TITLE
Sound problem in iOS, Chrome

### ISSUE THREAD

**Issue by Erik3000** [photonstorm/phaser#1715]
hello, I have problem with sound when I run my phaser game on iOS in Chrome browser. Problems are:
- when I lock device, music keeps playing
- when I minimize browser, music keeps playing.

it happens on iOS7 and iOS8.

I tried events game.onPause.add(....); and game.onResume.add(....);. It works on android, but doesnt work on iOS. 

How can I make this work?  Thank you

**Comment by photonstorm** [comment]
Just adding that I can confirm that audio correctly pauses if you 'home screen' while Safari is running in Phaser 2.4-dev (and Phaser 2.3 actually, but we've made a few significant changes to the way 2.4 audio works so it's worth using that as the benchmark now). Feel free to re-open with a specific test case if you can prove otherwise though.
