### ISSUE TITLE
this.load.audio() with Opera and mp3

### ISSUE THREAD

**Issue by noidexe** [photonstorm/phaser#1718]
The docs say that if you specify an array of URIs when loading a sound, then the first one that's device-compatible will be loaded. 

I don't know if this is Opera misinforming which formats it can play or Phaser misdetecting it, but if you put the mp3 first in the URI array the game will get stuck trying to decode the audio. The workaround is putting the ogg(or some other format supported by Opera) first.

**Comment by photonstorm** [comment]
The problem is that Opera returns a result of 'probably' for `Audio.canPlayType('audio/mpeg;')` rather than a more definitive 'yes' or 'no'. It reports the same thing for 'ogg' too, so it's impossible to know to pick one over the other, so all we can do is pick the first one in the URL array given. If we filtered out 'probably' responses (and considered them as 'no') then Opera wouldn't play any audio at all as everything comes back as 'probably' or 'maybe'.
