### ISSUE TITLE
Sprite falls through platforms (implemented as array of groups)

### ISSUE THREAD

**Issue by CrocoDillon** [photonstorm/phaser#1721]
We are running a contest on our portals over the Easter weekend (so this issue might not be solved in time, but for future reference...), which is a game based on Phaser. You can find the game here http://www.gamesgames.com/ - click the blue “play minigame” button in the header.

The source code of the game can be found here - https://github.com/CrocoDillon/wdg_doodle/blob/master/priv/www/js/init.js

Now if you play the game in Firefox you won't make it past the 3rd “cliff” jump, because you fall through the platform. On other browser it happens too, but in different places and not all the time. Firefox is your best bet to reproduce consistently.

Similar issues - https://github.com/photonstorm/phaser/issues/1424 https://github.com/photonstorm/phaser/issues/1490 https://github.com/photonstorm/phaser/pull/1493

But they don’t seem to help me any further.

I thought it might be related because we’re checking for collision against an array of groups (created from tilemap layers, tilemaps themselves were not usable because collision dissapeared entirely after moving a layer which is needed for endless gameplay behavior), but creating a single group did not fix the issue. More specifically it’s an array of objects from the LayerGroup type, which is defined here https://github.com/CrocoDillon/wdg_doodle/blob/master/priv/www/js/init.js#L411-L507

Really hope you can help us. And for what it’s worth, of course we are using the latest release. The dev branch didn’t seem to have any relevant commits to be worth checking out.

**Comment by rsadwick** [comment]
On Firefox, I consistently fell off the edge but if I jumped and landed near the middle (right next to the spike), it was fine.  The problem only happened near the edges of the platform.

I didn't have time to debug your code but I'd take a look at what **inView** returns  I see you're enabling arcade physics on certain tiles within your **addTile** function.  I'd take a look to make sure that those tiles that the player lands on are enabled properly.

**Comment by CrocoDillon** [comment]
Thanks for your reply @rsadwick. I did enable debug draw and the bodies for all the tiles are there. Even if not that wouldn't explain why this issue is browser specific/semi-random.

The platform tiles that are not physics enable are flowers / water / other visual only tiles.

**Comment by CrocoDillon** [comment]
Changing the way I add tiles to the LayerGroups from per row to per column (essentially swapping these lines - https://github.com/CrocoDillon/wdg_doodle/blob/master/priv/www/js/init.js#L523-L524) seems to fix the issue in FF. However in Chrome sometimes I still fall through the platforms.

**Comment by CrocoDillon** [comment]
Adding `game.physics.arcade.sortDirection = Phaser.Physics.Arcade.SORT_NONE;` seemed to have solved the issue. So I think there is a bug in the sorting. If I have time I can dig deeper.

For what it's worth, I did try Phaser 2.1 and 2.2 and they had the same issue.

**Comment by CrocoDillon** [comment]
Okay I think I found the issue (but I haven't tested this theory).

Our groups consists of sprites with (platforms) and without (props like flowers) body. The [sorting function](https://github.com/photonstorm/phaser/blob/v2.3.0/src/physics/arcade/World.js#L443-L446) doesn't take mixed groups into consideration by always returning -1 if either of the sprites don't have a body.

It would be better to sort non-body sprites to the either end of the array:

    if (!a.body || !b.body)
    {
        return !a.body - !b.body; // ...or something more verbose :)
    }

I would create a PR but I have my doubts about the use of sorting now. The [`collideHandler`](https://github.com/photonstorm/phaser/blob/v2.3.0/src/physics/arcade/World.js#L509) seems to be sorting the groups every time which would seem more expensive than just changing [this `break`](https://github.com/photonstorm/phaser/blob/v2.3.0/src/physics/arcade/World.js#L654) into a `continue`.

**Comment by photonstorm** [comment]
Arcade Physics has never supported mixed-Group collision (i.e. a single Group contain a mixture of physics enabled and non physics enabled objects), so this isn't an entirely surprising outcome I'm afraid.

However it did get me thinking that the Group._hash array should be exposed and made public, and then Arcade Physics itself could add children to it so you would be sure that only children with physics bodies existed in the hash. Then the sort doesn't need to care about invalid body types (although I left that guard in anyway).

Also your use-case made me think it makes more sense to elevate the sort direction property out of the World class and into the Group itself. That way a Group full of platforms could be sorted once upon creation and then wouldn't need to ever be sorted again. Whereas a Group full of baddies would still need to be sorted every single frame, as you'd always need their current coordinates.

So I've made all of the above changes over the last round of commits today, and it's all in the dev branch ready for further testing. As an aside, the reason that function you linked to shouldn't `continue` is because if it did it'll negatively skip all potential children from the wrong end of the array. They're sorted into spacial order, skipped until the colliding Sprite limit is hit, and only then can it break out. I ran a quick profile on it and it's definitely the correct way around (swap the break and continue over for example and you'll see no benefit of the spacial sort at all)

**Comment by CrocoDillon** [comment]
>   Arcade Physics has never supported mixed-Group collision

Might be worth it to add this to the documentation :)

+1 on the sorting once for platforms. I think you can optimize sorting a group of movable objects if you do it only once per frame instead of sorting it for every collision check within that frame. Unless this is already the case, I didn't look into it that much.

**Comment by photonstorm** [comment]
Closing this off as all of the changes are in the dev branch and working nicely.
