### ISSUE TITLE
Sprite damage(amount) function doesn't exist.

### ISSUE THREAD

**Issue by netgfx** [photonstorm/phaser#1739]
Not sure if this function still exists on the sprite component however according to the docs it should be around. If this should not be used anymore what are the equivalents to reducing health on a sprite.

According to the alive property on the docs ->
"This is set automatically by the Health components damage method should the object run out of health. Or you can toggle it via your game code."

**Comment by photonstorm** [comment]
Yes this was an oversight (the Health component was missing from Sprite) but is fixed in dev branch and will be part of 2.3.1 this week.

**Comment by janka102** [comment]
@photonstorm, you said the update would be later that week back in April, but now it's been over a month. Any news on why no stable 2.3.1 update, as I see the dev branch is now on 2.4?

**Comment by photonstorm** [comment]
Because when I wrote this 2.3.1 seemed like a good idea. And then we fixed some things in RenderTexture and States that prevented it from being able to be a point release any more, hence the immediate jump to 2.4. It will be ready as soon as time and testing allows. Hopefully this week, but that depends on some client projects right now.
