### ISSUE TITLE
Phaser Pixelate Filter uniform4fv error.

### ISSUE THREAD

**Issue by TimZie** [photonstorm/phaser#1780]
Ran in to some errors when trying to apply the pixelate filter:
**Error 1**. *Uncaught TypeError: Failed to execute 'uniform4fv' on 'WebGLRenderingContext': No function was found that matched the signature provided* 
**Error 2**. *Uncaught TypeError: Cannot redefine property: size.*

Got it to work (as far as I'm concerned) by:
**Error 1 Fix**: Writing the `uniforms` like this (similar to previous commit, note however, that the previous commit had a comma at the end of the 'pixelSize' row that I've deleted).
```javascript     
this.uniforms = {
        invert: {type: '1f', value: 0},
        dimensions: {type: '4fv', value:new Float32Array([10000, 100, 10, 10])},
        pixelSize: {type: '2f', value:{x:10, y:10}}
};
```
**Error 2 Fix**: Adding `Pixelate` to the `definePropery` like this:
```javascript
Object.defineProperty(Phaser.Filter.Pixelate.prototype, 'size', { ... });
```
instead of:
```javascript
Object.defineProperty(Phaser.Filter.prototype, 'size', { ... });
```

**Comment by photonstorm** [comment]
This is fixed in the dev branch. You shouldn't overwrite the uniforms object really. All it needed was to swap '4fv' to '4f' and it would have worked, however I dug in a little deeper and it appears a mat4 was pointless anyway, so swapped it for a 2f and fixed a few other things in there. Also set the default size to 1.0.
