### ISSUE TITLE
P2 Physics: body.addPolygon displaces sprite

### ISSUE THREAD

**Issue by gaufqwi** [photonstorm/phaser#1801]
When adding physics shapes to a P2 body with addPolygon, the parent sprite is sometimes displaced. This seems to be due to the center of mass of the object moving, as it seemingly does not occur if the new shape has the same center of mass as the old. body.loadPolygon works, but requires the polygon data to come from a JSON file in the cache, making it more difficult to generate programmatically.

[Sample code and images](http://www.html5gamedevs.com/topic/14411-p2-physics-adding-shape-displaces-sprite/)

**Comment by photonstorm** [comment]
This is by design I'm afraid - addPolygon is literally just an interface to the P2 method `fromPolygon`, so everything that this method expects you to handle on your own (such as adjusting the center of mass) you still need to do. However I've updated loadPolygon to make it more flexible, so you can now pass the actual data in directly rather than pull it from the cache, which should help matters out.
