### ISSUE TITLE
Gamepad input thinks that my keyboard is a gamepad

### ISSUE THREAD

**Issue by rbozan** [photonstorm/phaser#1860]
(on Ubuntu 15.04)

http://phaser.io/examples/v2/input/gamepad-debug

Using this, and any other gamepad example, I can see that for some reason my 'pad 1' is my Microsoft keyboard, while my XBOX controller is on Pad 2. This isn't a very big deal, but: if I use any of my axisses it would think that pad 1 actually does that, and Pad 2 is just doing nothing. However every button (including triggers) it would think that Pad 2 does that. Not sure if this is a bug on the debug game or not though..

**Comment by cmutti** [comment]
The example works as intend in my computer. The Xbox controller is treated as Pad 1 and the keyboard isn't doing anything. My keyboard is a Multilaser Tc167.

On elementary OS 0.3 freya.

![selecao_001](https://cloud.githubusercontent.com/assets/11135334/8220138/14990436-1526-11e5-8763-6a9d303e356b.png)

**Comment by photonstorm** [comment]
Unless you can find some code that is causing this I'm going to chalk it up to some browser / hardware / OS combo weirdness. All Phaser does is read from the gamepad API and report back what is attached, so it's the gamepad API that is getting confused here. Hopefully in the months that have passed since you reported this, they've fixed it.
