### ISSUE TITLE
Using getChildAt on undefined id outputs error

### ISSUE THREAD

**Issue by youssefdetovernickr** [photonstorm/phaser#1865]
Uncaught Error: getChildAt: Supplied index 1 does not exist in the child list, or the supplied DisplayObject must be a child of the caller

Meanwhile, reading the docs, getChildAt "returns The child at the given index, if any." However, using "getAt" it actually outputs -1 if it doesn't exist. I'm not sure if this is intentional..

**Comment by photonstorm** [comment]
`getChildAt` is a Pixi level function and either returns the child or throws a runtime error. I personally don't really like throwing errors, especially for something as trivial is a child that doesn't exist, so Group.getAt, which is a Phaser function, returns -1 instead so you can handle it however you wish. So yes, this is very intentional.
