### ISSUE TITLE
Not work pressing three keys at once and one of them SPACE

### ISSUE THREAD

**Issue by VitaZheltyakov** [photonstorm/phaser#1882]
The bug occurs in the processing of pressing three keys at once and one of them SPACE. One of the necessary actions linked to the key not working. In the example http://phaser.io/examples/v2/arcade-physics/asteroids-movement if you press UP, LEFT and SPACE, then the ship will not turn to the left. If you replace SPACE to CONTROL, then the problem disappears.

**Comment by photonstorm** [comment]
From the Phaser.Keyboard documentation:

* _Be aware_ that many keyboards are unable to process certain combinations of keys due to hardware
* limitations known as ghosting. Full details here: http://www.html5gamedevs.com/topic/4876-impossible-to-use-more-than-2-keyboard-input-buttons-at-the-same-time/
