### ISSUE TITLE
Box2D Bodies in a Group

### ISSUE THREAD

**Issue by seejay92** [photonstorm/phaser#1907]
Changing the X/Y of a group creates box2d body at world co-ordinate, instead of sprite's group co-ords. For example - 

```javascript
create() {
        cursors = game.input.keyboard.createCursorKeys()
        game.physics.startSystem(Phaser.Physics.BOX2D);
        game.physics.box2d.setBoundsToWorld()
        group = game.add.physicsGroup(Phaser.Physics.BOX2D)
        group.x = 300;
        group.y = 300;
        rocket = group.create(0,0, 'rocket');
        //rocket.body.offset.x = 300;
        //rocket.body.offset.y = 300;
       // Above doesn't appear to make a change.
       // rocket.body.setRectangle(rocket.width,rocket.height,group.x,group.y,rocket.angle)
       // Above sets bounding box at correct location but falls off with rotation
        }

update() {
        if (cursors.left.isDown){rocket.body.rotateLeft(100)}
        else if (cursors.right.isDown){rocket.body.rotateRight(100);}
        else {rocket.body.setZeroRotation()}
	if (cursors.up.isDown){rocket.body.thrust(100);}
        else if (cursors.down.isDown{rocket.body.reverse(100)}
}

render(){
       game.debug.box2dWorld()
 }
```

Switching the physics engine back to arcade produces the body in the right place, so not sure if maybe just using Box2d wrong!

**Comment by photonstorm** [comment]
Sorry for the time it took to respond to this. Just finished looking at it, and the problem is the plugin works by adjusting the Sprite.x and y values directly - the problem being they are local coordinates, relative to the parent Group, but the Body is always positioned and manipulated in world coordinates. I'm afraid the only way around this is to keep your Groups at 0,0, or don't put Box2D sprites inside of non-world aligned Groups.
