### ISSUE TITLE
Phaser is coupled to 4 physics implementations

### ISSUE THREAD

**Issue by ronami** [photonstorm/phaser#1908]
In it's current state, Phaser has 4 built-in physics implementations that you can use and you're bound to use only them. I'd like to use a different engine, or write my own custom implementation of an existing one, and I can't without having to do some workarounds.

I want to have the option to write a custom physics world, that can then be instantiated by the game engine with supplied configuration, and used by components such as the PhysicsBody or others (as long as you implement the proper methods).

**Comment by photonstorm** [comment]
In this instance the expected course of action is that you should overwrite the Physics Manager with your own custom system. As long as it has the expected entry points it will be perfectly happy with that. As all physics bodies are created through it you can easily replace the enableBody calls to do whatever you need.

**Comment by rblopes** [comment]
Hey, Rich. I have been thinking of some stuff like this for quite a while now. The issue @ronami is bringing here really is a broader stuff and I think some decisions regarding that and how Phaser is structured must be taken into account now for future releases. I bet that refactoring Phaser's physics engines are good place to start…

Now, when he talks about Phaser being bound to 4 physics engines and stuff, what comes to my mind is something like this:

```js
// Pseudo-code, excerpt from Phaser Physics module.
function startSystem (system) {
  if (system === Phaser.Physics.ARCADE) {
    // ... do stuff ...
  }
  else if (system === Phaser.Physics.P2JS) {
    // ... do stuff ...
  }
  else if (system === Phaser.Physics.NINJA) {
    // ... do stuff ...
  }
  else if (system === Phaser.Physics.BOX2D) {
    // ... do stuff ...
  }
}
```

Ok, we know that already by reading the source code… Also, I could pretend the expert and quote some stuff from the fabulous [SOLID principles](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)) here. Yeah, they are relevant, but anyone can see that adding another `if` clause, so that a new, (ficticious) BOX3D engine could be supported from within Phaser is really a design flaw. And this code smell can be seen in other places too (e.g. `Loader`).

Now, let's see that in another way. What must be done so, to add a new, built-in or custom, physics engine to Phaser, one could do something like this:

```js
Phaser.Physics.registerSystem('WhatAWonderfulPhysicsWorld', ThatPhysicsModule);
Phaser.Physics.startSystem('WhatAWonderfulPhysicsWorld');
```

That is, we could leave the necessary parts inside the modules themselves, as these should provide the required APIs to operate with Phaser, including the configuration parsing and the usual collision methods, for example.

Now, I'll leave one last question for your thinking later. Why distribute all default physics engines along with Phaser itself? Well, I think that makes sense regarding the Arcade Physics module, as some parts of it are required by other features of Phaser (but not necessarily obligatory, right?), as well a good starting point to prototype games. Still, I think these should be shipped separately from the Phaser core, and even split from the codebase itself, moving them to their own repositories, so issues regarding them could be tracked there. And, maybe in a near future, those that rely on building systems to compile their games could do something like this (one can dream, right?):

```js
// Again, pseudo-code.
import Phaser from 'vendor/phaser';
import ArcadePhysics from 'vendor/phaser-arcade-physics';
// Of course, the `import`s could be HTML `script` tags too.

// ... boot code ...
Phaser.Physics.registerSystem('ArcadePhysics', ArcadePhysics);
Phaser.Physics.startSystem('ArcadePhysics');

// ... in-game code ...
this.physics.enableBody(object, 'ArcadePhysics');
```

**Comment by clark-stevenson** [comment]
Almost all of my days are spent stressed out with these types of structural question right now :(

**Comment by photonstorm** [comment]
While I agree with most of this, to a degree (I've no intention of splitting up the code base), none of it is relevant to Phaser 2 I'm afraid and is already covered by the plans in place for Phaser 3. I need to keep the issues here as clean and focused as possible, so further discussion can be taken up on the forum if you wish.
