### ISSUE TITLE
a polygon's "closed" value is repeatedly thrown out before draw

### ISSUE THREAD

**Issue by wayfu** [photonstorm/phaser#1960]
This is a combination of two or three pixi level bugs (in both drawPoly and drawShape) that throw away the closed value, and an unnecessary recommendation in the Phaser docs (Graphics.drawPolygon: "If you've got a Phaser.Polygon object then pass polygon.points here."), which will also throw out that value. The recommendation is unnecessary because the drawPoly method can absolutely handle full Phaser.Polygon objects (it will however, as said, strip out the closed information in its current form).

**Comment by wayfu** [comment]
(see also: https://github.com/pixijs/pixi.js/issues/1892#issuecomment-126563824)

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
