### ISSUE TITLE
Tests for typescript typings

### ISSUE THREAD

**Issue by markogresak** [photonstorm/phaser#2008]
Hi!

I wanted to send a PR to DefinitelyTyped to add phaser's typings to tsd. I did not read the part saying there must be tests to assert that typings are compliant with current library's api. I do not have enough experience with phaser since I've just started setting up my first project when I noticed the typings are not on tsd, so I created the PR to add them for easier management. 
Since I'm not sure how test these typings, I would like to ask if someone more experienced is willing to help at my current PR: borisyankov/DefinitelyTyped#5214. 
The current typings in this repo are great, I had very little work to do to make them compliant with DefinitelyTyped conventions, just missing the tests now.

**Comment by photonstorm** [comment]
You might have better luck asking about this on the forum to be honest.

**Comment by clark-stevenson** [comment]
Oh I meant to add to this! 

I do not use DT so I cannot really say anything about it.  

Writing meaningful tests in Phaser would be hard just simply due to the amount of capability it offers.  In Pixi V3, I re-wrote examples in TypeScript, and then put all of them into a flat `pixi-tests.ts` file. Pixi is small enough to be manageable. I feel that, without effort, I can maintain almost all the small functionality of Pixi by maintaining 10-12 test examples.

Phaser has something like 100 examples, and even these do not seem to cover the entire capability of what Phaser can do.  It becomes a question of who wants to write (and Maintain) the commit history of all the examples?  I can only say I have not found the time to do it and until the community grows, it may never be done. 

Actually one thing I will say about DT is that I do not 100% get it.  If `phaser.d.ts` goes to DT, does it mean essentially mean there is now 2 competing definitions? That PRs will occur in 2 places and essentially go off on different paths?

**Comment by markogresak** [comment]
I agree, adding tests to cover all of phaser's capabilities would take tremendous amount of work to get in started and maintain it. I guess that you are right, there would be 2 definitions, the official one in this repo and the other one at DT. The benefit of DT is easier management of typings since you get all of them in one place and don't have to commit them in the repo.

**Comment by photonstorm** [comment]
Thank you for the suggestion. However this will not be implemented in Phaser, so I'm moving this request over to the Lazer feature request list instead. If you wish to submit a PR that adds this feature to Phaser then we will consider merging it.
