### ISSUE TITLE
Lines on WebGL are offsetted when they're under a certain width

### ISSUE THREAD

**Issue by rbozan** [photonstorm/phaser#2105]
http://codepen.io/anon/pen/OyXQPp

As you can see, on WebGL the lines aren't really aligned to the sides when they under a certain width. If you change the "0.8" on the lineStyle to something higher than 2, it seems that it will be normal again.

Canvas also doesn't have this issue.

**Comment by rbozan** [comment]
Still happening on the dev branch, 2.4.4

**Comment by photonstorm** [comment]
The issue is two fold:

First of all the problem is created by the use of scale in the example, not the line width itself. If you just set scale(50) on the Graphics element you'll still see the same result.

The cause is that `PIXI.WebGLGraphics.buildLine` checks to see if the line width is an odd value, and adds 0.5 to it in order to round it to a whole pixel. Usually you don't notice this sub-pixel adjustment, but in your case because the whole thing has been scaled x50 it multiplies the effect dramatically.

I'm not willing to modify Pixi to adjust the way it works, so am chalking this one up to a Pixi anomaly at super-high scale factors.
