### ISSUE TITLE
Random smoothing with webkitImageSmoothingEnabled

### ISSUE THREAD

**Issue by cscott5288** [photonstorm/phaser#2122]
I've had a problem where the game randomly turns smoothing on (it's not just objects I'm tweening). The game will literally be smoothed on browser refresh the 1st time and not smoothed the second (100% random). In the console, I'm getting this warning:

'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.

I manually turned off image smoothing for this property with:
game.context.webkitImageSmoothingEnabled = false;

And I no longer have the random image smoothing. 

I'm guessing webkitImageSmoothingEnabled is something the browser determines is true or false and you can override? What other explanation could there be for it randomly turning on and off, despite the fact that Phaser.game has anti-alias turned off?

BTW my environment is a 2007 imac with Chrome.

**Comment by photonstorm** [comment]
Hmm this shouldn't happen under 2.4.4 any more because Pixi now uses the `Phaser.Canvas.getSmoothingPrefix` function instead, which checks the prefixes in order, starting with none at all, so if the browser reports 'imageSmoothingEnabled' as a valid property then it'll use it from then on. If you still see this with 2.4.4 and can boil this down to a test case then please re-open.
