### ISSUE TITLE
With WebGL, adding child text to button renders text to other buttons

### ISSUE THREAD

**Issue by puzzud** [photonstorm/phaser#2141]
Creating multiple Phaser.Buttons and giving them Phaser.Text children will result in both the buttons and children to be rendered and subsequent labels to be rendered on previously created buttons.

This problem is only reproducible when using WebGL (and not Canvas) as Phaser's renderer.

This bug is seen as a regression between 2.4.3 and 2.4.4 (introduced by 99751a5).  

Example code:
http://phaser.io/sandbox/rscQDbmR
```
function create()
{
    var buttonStyle = { font: "32px Arial", fill: "#ffffff" };
    
    var button1 = game.add.button( 0, 0 );
    var buttonLabel1 = game.make.text( 0, 0, "Button1", buttonStyle );
    button1.addChild( buttonLabel1 );
    
    var button2 = game.add.button( 0, 32 );
    var buttonLabel2 = game.make.text( 64, 256, "Button2", buttonStyle );
    button2.addChild( buttonLabel2 );
    
    var button3 = game.add.button( 0, 64 );
    
    game.add.tween( button2.position ).to( { x: 256 }, 2500, Phaser.Easing.Linear.None, true );
    //game.add.tween( buttonLabel2.position ).to( { y: 128 }, 1500, Phaser.Easing.Linear.None, true );
}
```

**Comment by puzzud** [comment]
99751a5 says something about a new PIXI BaseTexture skipRender member. I don't really understand it or its need here, but unsetting it on buttons does seem to do the job:

button1.texture.baseTexture.skipRender = false;

Maybe there can be a little clarification before this issue is closed?

**Comment by photonstorm** [comment]
It's because the Buttons don't have any textures, so they're given the `__default` texture which the WebGL renderer is told to ignore (because it's breaks sprite batching and is a waste of draw calls).

I guess the reason we didn't spot this in testing is because all the Button examples use a texture for the button.

I think we ought to harden-up the skipRender check, so it's only enabled if the texture is using the default blank image AND has no children. It's not as guaranteed to be accurate (because the children may not render either), but it would catch cases like this.

**Comment by photonstorm** [comment]
This is now fixed in the dev branch. Please pull and have a test (you'll need to build, I only updated the source). Your example code above works fine now though.

**Comment by puzzud** [comment]
Fix works as expected.
