### ISSUE TITLE
[2.4.4] cacheAsBitmap breaks graphics as mask

### ISSUE THREAD

**Issue by jmp909** [photonstorm/phaser#2152]
using a cached graphic as a mask used to work but not as of 2.4.4

``` javascript
var gMask = game.add.graphics(0, 0);
gMask.lineStyle(2, 0xFF0000, 1);
gMask.beginFill(0xFF0000,0.1)
gMask.drawCircle(0,0,mapSize/2,mapSize/2);    
gMask.endFill()

gMask.cacheAsBitmap=true // !!!! breaks mask

renderGroup.add(gMask)
renderSprite.mask=gMask;
```

error
`Uncaught TypeError: Cannot read property 'data' of undefined`
(phaser.js 17578)

seems to be this line
`if(!maskData._webGL[gl.id].data.length)return;`

**Comment by geros** [comment]
Have you found any workaround on this? 
It happens to me when i use  renderer:Phaser.WEBGL while works fine  when i change it to  Phaser.CANVAS

**Comment by jmp909** [comment]
quick fix for WebGL Graphics is to manually set the mask as dirty

```javascript
mask.cacheAsBitmap=true;
mask.dirty=true
```

but ideally would presumably for this to happen in the PIXI source in this function
`Object.defineProperty(PIXI.DisplayObject.prototype, 'mask', {`

https://github.com/photonstorm/phaser/blob/c9c85330ab60547b39ba4c9400c258ed7fb2a317/src/pixi/display/DisplayObject.js#L302

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
