### ISSUE TITLE
Android in portrait mode have less fps than in landscape mode 

### ISSUE THREAD

**Issue by jdnichollsc** [photonstorm/phaser#2181]
Hi guys,

I'm doing some tests using the RESIZE scale mode and I noticed something strange happens in Android. When you have the mobile in Landscape, the performance is very good like in iOS (~60 fps), but in Android when you change to Portrait, the fps is very bad (~8 fps).

It is very strange :/

**Comment by adriangordon1231** [comment]
+1

**Comment by txchen** [comment]
that's quite interesting.
@jdnichollsc how are you using phaser in android, I am curious. Are you using cordova? or cordova + crosswalk?

**Comment by jdnichollsc** [comment]
both, I am creating an integration with Phaser :)

**Comment by pnstickne** [comment]
Does this only occur under 'RESIZE'? What about any mode if there is a scaling applied?

**Comment by jdnichollsc** [comment]
Yes, only in RESIZE scale mode. Using Phaser.ScaleManager.EXACT_FIT works good.

**Comment by jdnichollsc** [comment]
Any news about this error? =)

**Comment by MARSDEN** [comment]
yo Juan ... Dave
its marzy
that u/>/?

On Thu, Oct 29, 2015 at 9:50 PM, Juan David Nicholls Cardona <
notifications@github.com> wrote:

> Hi guys,
>
> I'm doing some tests using the RESIZE scale mode and I noticed something
> strange happens in Android. When you have the mobile in Landscape, the
> performance is very good like in iOS (~60 fps), but in Android when you
> change to Portrait, the fps is very bad (~8 fps).
>
> It is very strange :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/photonstorm/phaser/issues/2181>.
>



-- 
From Marsden Seneca Hayward-Rope
cestlavie.mh@gmail.com
https://www.planitmarz.yolasite.com
marsden@live.ca

**Comment by jdnichollsc** [comment]
@MARSDEN what? I don't understand
See my facebook: https://www.facebook.com/jdnichollsc

**Comment by photonstorm** [comment]
I can't see how it'd make any difference at all about the orientation, unless Android was doing something quirky under the hood.

Perhaps resize is being hammered? Try this: in your States 'resize' function, just log it out each time it's called (it gets sent width / height  parameters, so log those). Perhaps resize is being slammed for some reason. Worth testing anyway.

**Comment by jdnichollsc** [comment]
@txchen see my example :D http://market.ionic.io/plugins/ionphaser

**Comment by jdnichollsc** [comment]
Sorry, my cellphone was a troll with me, @photonstorm ley me try, thanks! :)

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
