### ISSUE TITLE
Large memory leak with game.debug.text in 2.4.4

### ISSUE THREAD

**Issue by kingjerod** [photonstorm/phaser#2208]
I've verified this doesn't happen in 2.4.3. Very simple test case (excluded boilerplate HTML, if you need that let me know):

```javascript
var game = new Phaser.Game(1400, 800, Phaser.AUTO, 'Hi', {create: create, render: render });
function create() {
    game.stage.backgroundColor = '#313131';
}
function render() {
    game.debug.text('Hello!', 5, 20);
}
```

If you watch the browser process, the memory usage in Chrome jumps around by 100's of megabytes (going from 200 -> 600 MB). In FF, it jumps around 100 MB. 

Edit:
With 2.4.3 (OK): http://jsfiddle.net/bfgm8ed0/
With 2.4.4 (leak): http://jsfiddle.net/bfgm8ed0/1/

**Comment by McFarts** [comment]
Holy crap, can confirm here.

![](https://i.gyazo.com/155841120afa6d2e569761ec824d54ac.png)

**Comment by spayton** [comment]
I noticed the same the other day playing around with the rope, so it may not be just to do with game.debug.text

In my case it was to do with being in WebGL mode, and the heap being full of WebGL contexts.  Wasn't sure if it was my rope mods that were breaking it, but as I didn't need it fixed straight away I left it for a rainy day to look at again.

You could fix it to canvas mode and see iff the problem using Phaser2.4.4 goes away.  If it does go away then I would suspect a general WebGL mode problem.

**Comment by photonstorm** [comment]
Interesting. The problem is this line here: https://github.com/photonstorm/phaser/blob/master/src/gameobjects/BitmapData.js#L584

The change that caused this is that BitmapData.clear now calls BitmapData.update, which has the above line in it.

It only happens in WebGL of course, but still, very frustrating. I cannot see a way to fix it either. Even just calling `context.getImageData` is enough to trigger it. So I'll stop BitmapData.clear from calling update and reflect this in the docs.

**Comment by spayton** [comment]
Yup, that's fixed it.

**Comment by photonstorm** [comment]
Well not really, all it did is revert the earlier change, which was a quite important one. But it will have to do for now.

**Comment by kingjerod** [comment]
Dang, you are fast! :beers:
