### ISSUE TITLE
Strange behaviour of QuadTree algorithm

### ISSUE THREAD

**Issue by triadium** [photonstorm/phaser#2225]
![2015-11-22 23 43 03](https://cloud.githubusercontent.com/assets/11703916/11326164/ffcb5486-9172-11e5-87f6-4c0ac6631a58.png)
I looked the example of guadtree and saw the strange behavior of the algorithm at the click position, as shown in the picture. The algorithm has returned all of the objects. Is that correct?

**Comment by photonstorm** [comment]
If the area being checked intersects more than one quad (as it does in the screen shot above) then it brings back all entries, as it's unable to fit inside a single quad. This is just the way the current quadtree implementation works I'm afraid. Technically it could be enhanced so that it determines which quads it intersects with first, and only then tests those - but that sort of goes against the nature of how it's designed.
