### ISSUE TITLE
tilemap.getObjectIndex issue

### ISSUE THREAD

**Issue by yeluoqiuzhi** [photonstorm/phaser#2242]
![image](https://cloud.githubusercontent.com/assets/9261562/11553900/15183b5c-99ce-11e5-9c0c-e2c289d2f30b.png)

Phaser.Tilemap

I found tilemap.objects is an object and it has an array of my objects in tilemap.json file.
I have a look:
```javascript
 getObjectIndex: function (name) {
        return this.getIndex(this.objects, name);
}
```
I think it should be 
```javascript
 getObjectIndex: function (name) {
        //getIndex need an array,but an object here
        return this.getIndex(this.objects.object, name);
}
```

**Comment by cchartr** [comment]
I second the issue raising, but not the solution.
`tilemap.objects` is really a JavaScript object which maps object groups (or object layers, or object arrays) using their names for keys. Therefore in your example, `tilemap.objects` has a member `object` only because that's the name you gave to your object group.
In fact, now that `Tilemap.objects` is an object and not an array, I'd suggest the method `Tilemap.getObjectIndex()` be stripped altogether. Or make it retrieve an object's index from *within* an object group, but that would require two arguments : the object name and the object group name. Anyway in the current state of things, that method is irrelevant.

**Comment by yeluoqiuzhi** [comment]
@cchartr Thank you very much.

**Comment by photonstorm** [comment]
Agreed. Method removed.
