### ISSUE TITLE
iOS scaling issue with responsive iFrame (with example)

### ISSUE THREAD

**Issue by seejay92** [photonstorm/phaser#2247]
Hi all,

Noticed there may be a problem with the scale manager and responsive iFrames, only on iOS devices. 

On PC, Mac and Android the scale manager will fill the parent iframe, and respect the CSS styles applied by the iframes parent, however on iOS the game scale will not obey parent CSS styling and expand past the set limits.

This appears to happen on all scale modes - RESIZE,EXACT_FIT,SHOW_ALL. I've noticed there appears to be some unresponded forum posts on the issue, but they don't appear to describe the issue very clear. I've thrown together a quick and basic example below to show this at work:

http://seejay.co.uk/phaserios/iframe.html

Thanks as always!

**Comment by seejay92** [comment]
UPDATE:

Hi again, just a bit of progress on the issue I raised last week. After doing some surfing on the issue, I found a semi related article at: https://www.magnolia-cms.com/blogs/christopher-zimmermann/detail~@strategies-for-the-iframe-on-the-ipad-problem~.html which raised an issue with ios iframe scrolling.

Following one of their solutions, to use an <object> instead of <iframe>, this seems to have fixed the issue on iOS. I've not fully tested to see if this has broken on other devices, and as I understand you don't have access to some iframe parameters, so I'm not sure how ideal a solution this is.

<iframe> example: http://seejay.co.uk/phaserios/iframe.html
<object> example: http://seejay.co.uk/phaserios/object.html

Is this a problem that lies with the iFrame code on iOS, or is this something that Phaser could change to handle?

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
