### ISSUE TITLE
Upgrading to 2.4.4 slowed down the game

### ISSUE THREAD

**Issue by bymafmaf** [photonstorm/phaser#2249]
Hi,

I've developed my game entirely with version 2.4.3. Yesterday I replaced phaser.js file with 2.4.4 version but then game's fps decreased dramatically. It's like every tween plays in slow motion.

Using phonegap, building for iOS.

**Comment by milkey-mouse** [comment]
That's most likely a PhoneGap problem. Can you test it on a desktop browser? If so, does it still have the performance problem?

**Comment by RogerPaladin** [comment]
http://phaser.io/docs/2.4.4/Phaser.TweenManager.html
Try set 
this.game.tweens.frameBased = true;

**Comment by photonstorm** [comment]
I'm afraid I'm closing this issue. Not because it doesn't happen, but just because it's useless to us because there is no code provided, no indication of what actually happens, no environment details - nothing we could actually debug I'm afraid. Subjective issues like this are best discussed in the forum until the actual issue is located.
