### ISSUE TITLE
Issue with looping sounds in AudioSprite

### ISSUE THREAD

**Issue by NeoHoffa** [photonstorm/phaser#2256]
Adding markers to an AudioSprite, one of them is set to loop, and other one is not.

If the looping sound is played first it loops just fine. But when the second sound plays, the looping sounds stops looping.

```
this.load.audio('sounds', ['sounds.ogg', 'sounds.m4a','sounds.wav']);

var audioSprite = this.game.add.audio('sounds');
audioSprite.allowMultiple = true;
audioSprite.addMarker('soundLoop',  1,  3,  1, true);
audioSprite.addMarker('fire',  5,  2.3,  1, false);

audioSprite.play('soundLoop');   // loops just fine
audioSprite.play('fire');    // plays the sound, but stops looping soundLoop
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
