### ISSUE TITLE
should game.stage.disableVisibilityChange be deprecated?

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#2276]
game.stage.disableVisibilityChange works only sometimes. 

For instance, if you have if you click on the dev console in Chrome, while the game is running, disableVisibilityChange will allow the game to continue running. If you click on another application (notepad for example) outside of the browser, disableVisibilityChange will allow the game to continue running. 

If you click on another tab, however, the game pauses even though the game.onPause event isn't fired (and game.paused isn't set to true). I suggest firing the game.onPause event when switching tabs or deprecating disableVisibilityChange. The reason for deprecating is because it only works some of the time. And I don't think there is a way with the RAF timer to continue running while the game is in a different tab than the active. Perhaps put a note in the docs which says "Still pauses the game when you are in a different tab on the same window thread" and then making sure the onPause event fires when switching to another tab? 

This all based on my experience in OSX 10 in Chrome.

**Comment by photonstorm** [comment]
I'm not deprecating it because it does what it says on the tin. If you swap tab, the game may or may not pause. It's entirely up to the browser if it decides to halt RAF or not. So we cannot use the page visibility API to detect this, because we've already captured that event when the tab swapped (and if you elected to ignore the onPause event then you are at the mercy of the browser). RAF pausing is another event altogether that I'm not sure it's possible to even detect.
