### ISSUE TITLE
Web Audio Sound objects massive memory leak in, at least, Chrome

### ISSUE THREAD

**Issue by AnderbergE** [photonstorm/phaser#2280]
In, at least, Chrome there will be massive memory leaks if you try to stop and disconnect an AudioBufferSourceNode at the same time. Phaser started doing that with this commit: https://github.com/photonstorm/phaser/commit/1990bce48b82b85b487cac0b0f990caede4d8c2d

I have been digging deep into this one and there is a thread in the forums about it:
http://www.html5gamedevs.com/topic/19339-audio-memory-usage-headache/

**Comment by photonstorm** [comment]
Have a go at the dev branch version (you'll need to run grunt to build it), which reverses the stop / disconnect process.

**Comment by photonstorm** [comment]
Don't suppose you know if the recent updates resolved this or not? Would like to close this one off, but am reluctant until I'm sure it's dead.

**Comment by AnderbergE** [comment]
Sorry, I haven't had time to work on the project that this bug appeared on for quite some time.
I'll try to squeeze it in today!

**Comment by AnderbergE** [comment]
I easily get more than 1GB ram with the latest dev. Both in my project and my isolated test case (see below)
On the other hand I get plenty of other errors. Such as:
WebGL: INVALID_VALUE: texImage2D: no image data
255localhost/:1 [.CommandBufferContext]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

So I think I might be doing something else wrong.

Anyway. In the forum I have posted test cases. I've added another one with the dev phaser, does it eat memory for you?
https://dl.dropboxusercontent.com/u/116813451/PhaserSoundTest/index_dev.html

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
