### ISSUE TITLE
sound.volume bug

### ISSUE THREAD

**Issue by VitaZheltyakov** [photonstorm/phaser#2293]
If the browser does not use the Audio API (eg, Crosswalk or CocoonJS), the global change of the sound is not working properly. This code corrects this error:
/**
* @name Phaser.SoundManager#volume
* @property {number} volume - Gets or sets the global volume of the SoundManager, a value between 0 and 1. The value given is clamped to the range 0 to 1.
*/
Object.defineProperty(Phaser.SoundManager.prototype, "volume", {

    get: function () {

        return this._volume;

    },

    set: function (value) {

        if (value < 0)
        {
            value = 0;
        }
        else if (value > 1)
        {
            value = 1;
        }

        if (this._volume !== value)
        {
            this._volume = value;

            if (this.usingWebAudio)
            {
                this.masterGain.gain.value = value;
            }
            else
            {
                //  Loop through the sound cache and change the volume of all html audio tags
                for (var i = 0; i < this._sounds.length; i++)
                {
                    if (this._sounds[i].usingAudioTag)
                    {
                        this._sounds[i].volume = value; // <<<---- Changes here
                    }
                }
            }

            this.onVolumeChange.dispatch(value);

        }

    }

});

**Comment by photonstorm** [comment]
This fundamentally changes what this function does. If you had created a few Sound objects and set different overall volumes on them, this change will now level them all to use the exact same volume (rather than apply it as a multiplier to their current volume).

Exactly what is this change fixing? Might be easier to understand from that angle (feel free to re-open with a test case)
