### ISSUE TITLE
First orientation change is ignored

### ISSUE THREAD

**Issue by RyuMaster** [photonstorm/phaser#2340]
I test it on android. game.scale.isGameLandscape is true, if I start in ladscape mode, all fine. After this, I rotate device, portrait mode enabled visually, but game.scale.isGameLandscape is still true; After this, I get back to landscape mode, game.scale.isGameLandscap still true. I go to portrait again, game.scale.isGameLandscape is  false now.

So, the first check of always fails .This also happens with onChangeOrientation event, first rotation is always failed to register within Phaser.

**Comment by photonstorm** [comment]
Fully working test case needed.

**Comment by RyuMaster** [comment]
```
<script src="phaser.min.js"></script>

<script>

var gWidth = window.innerWidth;
var gHeight = window.innerHeight;  

var game = new Phaser.Game(gHeight, gWidth, Phaser.AUTO, 'phaser-example', { create: create, update: update});
var text;

function create() {



    game.scale.forceOrientation(false, true);
    game.stage.backgroundColor = '#ffffff';
    text = game.add.text(0, 0, "Portrait mode is: " + game.scale.isLandscape);

}


function update() 
{
    text.setText("game.scale.isLandscape: " + game.scale.isLandscape);
}

</script>
```

With this code, if I start application in landscape mode, sometimes I see landscape being false on the start. Besides, if I refresh, weird stuff starts to happen. I can see letters move a little bit on every frame into right direction, or stretch, or sometimes landscape to show proper true. Have no idea whe does this weird behaviour comes from. I am on the android chrome, seems to work find on iPhone Safari.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
