### ISSUE TITLE
2.4.6 issue with bitmaptext missing align param

### ISSUE THREAD

**Issue by iszard** [photonstorm/phaser#2376]
in 2.4.6 phaser there is an error with bitmapText

lines 46318 - 46320

bitmapText: function (x, y, font, text, size, group) {

            if (group === undefined) { group = this.world; }

            return group.add(new Phaser.BitmapText(this.game, x, y, font, text, size));

        },

 

It does not suppoer the 'align' param as documented. From the doc the following should be the correct code.

bitmapText: function (x, y, font, text, size, align, group) {

            if (group === undefined) { group = this.world; }

            return group.add(new Phaser.BitmapText(this.game, x, y, font, text, size, align));

        },

**Comment by photonstorm** [comment]
The alignment argument was added later on to BitmapText, after the GameObjectFactory had been created, by which time it was too late to add it in without changing the API.

We could have added it, but no-one mentioned it before :) I guess because it's easy enough to work around by just creating the BitmapText yourself. I'm not looking to change the API at this stage, and putting `align` after `group` would look weird, so I'm going to leave this one be.
