### ISSUE TITLE
Exiting full screen resizes world to canvas size

### ISSUE THREAD

**Issue by bodhiBit** [photonstorm/phaser#2388]
Whenever I make a game with a world larger than the canvas, there seems to be trouble with going in and out of full screen..

[Codepen example](http://codepen.io/anon/pen/vGgVaV?editors=0010)

**Comment by bodhiBit** [comment]
Okay.. it that the problem is with `Phaser.World.resize()`.. If I use `Phaser:World.setBounds()` instead, there is no problem..

Still.. shouldn't `resize()` work just as well..? or is this an intended side-effect..?

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
