### ISSUE TITLE
Custom body width + sprite reset = body width reset despite setting it

### ISSUE THREAD

**Issue by drhayes** [photonstorm/phaser#2423]
I'm bad with titles. This took me by surprise, though. Bug?

1. Make a sprite with an arcade body.
2. Set width of that body smaller than sprite (e.g. sprite texture width is 64, sprite body width is 4).
3. Set `sprite.scale.x = -1;`.
4. Reset the sprite.

Expected: Sprite body maintains previously set width; sprite body width can be set right after reset and stays that way.

Actual: Despite setting the body width back to what you want, sprite body width gets set to width of sprite texture.

Repro: http://codepen.io/drhayes/pen/MyrLom?editors=0010

**Comment by photonstorm** [comment]
You shouldn't change `body.width` or `body.height` directly like that, this is why they are marked as 'read only' in the docs :) because they're the result of internal calculations, and change depending on various things (like scale).

If you want to change the body size, use `body.setSize` instead. Then all of the relevant properties will be adjusted as well.
