### ISSUE TITLE
Why is separate a private function?

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#2426]
I've always wondered why separate is a private function in arcade physics. seems to me there are tons of applications for a separate function as good as Phaser's outside of using collide. What are the arguments against making it public and documented in the API? Suppose I want to check for overlaps between 2 Phaser.Rectangles directly (using Phaser.Rectangle.intersects) and then separate them? I realize separate is supposed to use physics bodies but I assume it works just as well on normal Phaser.Rectangles. Maybe that's not the best example but I know I've run into scenarios before where I wanted to create a separation directly (not using collide). I think it would be useful if separation accepted other paramaters as well, like how quickly and how far the objects should separation.  

Also curious as to why collide and overlap are different functions - why not make it 1 function with separate as an option?

**Comment by photonstorm** [comment]
`collide` and `overlap` are public facing API methods, which is why they are separate (because they're easier to understand than an argument you may overlook).

I could make `separate` public, but there's little benefit as it only works on Arcade Physics bodies (try it on a Rectangle and see the errors you'll get). What I agree it _should_ have though is the ability to separate but not exchange velocities. And at the end of the day, if you really wanted to call the function, you could anyway. I suspect the edge-cases for that are quite tiny though.

**Comment by ForgeableSum** [comment]
I see. Suppose I want to mark off areas of an image and have an object collide with those areas. My only option, if I want to use separate, is to have sprites and sprite bodies representing each area of that image? That's my predicament. I want to mark off areas of an image for collision but creating separate sprites and bodies for each area would be too taxing on performance. I had hoped I could use Phaser.Rectangles to mark the areas. That solves the actual collision detection part of the problem (with rectange.intersects) but not the separation part.
