### ISSUE TITLE
Sprites disappear from screen when another sprite gets killed

### ISSUE THREAD

**Issue by Kitanga** [photonstorm/phaser#2446]
(using version 2.4.4 "Amandor")
I'm trying to create a game sort of like paratroopers. It is set in space and so naturally the first opponents I could think of were asteroids ('cause everyone hates asteroids).
I was able to create a player who shoots in the pointer's direction. I got the asteroids to spawn randomly and collide with bullets.
But as soon as I decided to have the asteroid break up into smaller asteroids after being hit, the game started acting weird. All asteroids and mini-asteroids would disappear until a new asteroid spawns. Then you shoot down a few more asteroids and it occurs again. The player/gun and its bullets stay on the screen but everything else in the `this.enemies[]` is gone.

When the bullet in the `this.guns['flak'].bullets` group collides with the asteroid in the `this.enemies['asteroids']` this happens:

```
game.physics.arcade.collide(this.guns['flak'].bullets,this.enemies['asteroids'],function(obj1,obj2) {
    obj1.kill();
    obj2.kill(game.rnd.integerInRange(2,5)); // Random number chooses how many mini-asteroids spawn
}
```
Meanwhile in the Asteroid object's kill()...
```
Asteroid.prototype.kill = function(numOfAst) {
    for (var i = 0; i < numOfAst; i++) {
        var miniAst = play.enemies['miniAst'].getFirstExists(false); // Get the first dead mini-asteroid. The play in play.enemies is the state that the game's logic runs in
        miniAst.reset(this.x,this.y); // Place it on the canvas
        miniAst.body.velocity.x = game.rnd.integerInRange(-300,300); // Move it in a random direction horizontally
        miniAst.body.velocity.y = game.rnd.integerInRange(-300,300); // Move it in a random direction vertically
    }
    this.alive = false;
    this.exists = false;
    this.visible = false;

    if (this.events) {
        this.events.onKilled$dispatch(this);
    }

    return this;
};
```
Your help would be much appreciated. 
Thank you!! :D

**Comment by photonstorm** [comment]
Questions like this are best suited to the forum, but even so, a few thoughts:

* Instead of overriding the kill method I would recommend you instead just spawn the new asteroids by listening for the onKilled signal instead, it will keep it cleaner imho.
* Check to see how many times your kill method is being called when 1 bullet hits it, because you've got it as part of a collide check it's possible it runs multiple times.
* If using Chrome, put the command `debugger` into your code, right after the new asteroids are spawned. This will pause the game, open up dev tools and allow you to start testing your objects to see what they're doing.
