### ISSUE TITLE
Tween .onLoop doesn't trigger

### ISSUE THREAD

**Issue by shpowley** [photonstorm/phaser#2457]
I noticed this since Phaser 2.4.6 re-coding a YouTube tutorial Space Invaders clone. As the alien ships fly left and right they never move down. Using Chrome developer tools, I notice Tween .onLoop never triggers as stated in the API docs (http://phaser.io/docs/2.4.7/Phaser.Tween.html#onLoop). In the Space Invaders example, using .onRepeat instead creates the expected behavior.

In the Phaser example pages, a similar Space Invaders example (http://phaser.io/examples/v2/games/invaders#gv) uses .onLoop and you can see the bug here as the aliens never move down. .onLoop never triggers the descend() function.

```
function descend() {
    aliens.y += 10;
}
```

As the Phaser example allows me to switch versions, I noticed .onLoop works in version 2.4.4 and stops working in 2.4.5+.

**Comment by kamenminkov** [comment]
I also noticed that `onRepeat` now acts just like `onLoop` used to. I don't know what's the reason behind this; I'm also curious to find out.

**Comment by ForgeableSum** [comment]
Richard fixed this in 2.4.7:
https://github.com/photonstorm/phaser/releases/tag/v2.4.7

> Tween.update wouldn't dispatch an onLoop signal for Tweens with just one child, such as those created via Tween.to with -1 as the repeat value

**Comment by shpowley** [comment]
In Phaser 2.4.7, with code very similar to the example from http://phaser.io/examples/v2/games/invaders lines 121-124, .onLoop still doesn't seem to work in my local dev environment - with the parameters specified..

Note that the phaser example from http://phaser.io/examples/v2/games/invaders uses 2.4.6 as default and has a problem even loading "phaser.2.4.7.min.js" which makes it hard to verify either way.

I looked at your code sample from issue https://github.com/photonstorm/phaser/issues/2407 and experimented with settings similar to your - it WORKS, sort of. The notable difference being the .tween.to "repeat" parameter. Only with _repeat = **-1**_ (infinite repeat) will onLoop trigger. _With any other finite value for "repeat" (ex. 50 or 1000), onLoop does nothing._

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
