### ISSUE TITLE
ScaleManager: canvas resize to container

### ISSUE THREAD

**Issue by shpowley** [photonstorm/phaser#2458]
Re-coded the Tanks Part 1 official tutorial using Phaser 2.4.7 and tried scaling the game for fun. When creating the game instance using `new Phaser.Game(...)` and specifying a parent parameter, scaling using the following code doesn't seem to do anything:

```
    game.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;
    game.scale.refresh();
```

Specifying null for the parent parameter of `new Phaser.Game(...)` works fine.

Related:
In the Game Scale Phaser example (http://phaser.io/examples/v2/input/game-scale#gv), I noticed the default example doesn't work for whatever version I tried. Line 11 `game.scale.setScreenSize();` replaced with `game.scale.refresh();` gets the code example working for most versions of Phaser ..except 2.4.7. With 2.4.7, the issue I raised above seems to apply. Chrome Dev Tools shows the parent container completely empty.

**Comment by mattstyles** [comment]
Is [this](http://www.html5gamedevs.com/topic/22216-trouble-filling-parent-element-in-dom/#comment-126554) related?

Looks like maybe there is an issue somewhere before [`ScaleManager.getParentBounds](https://github.com/photonstorm/phaser/blob/v2.4.7/src/core/ScaleManager.js#L1415) gets called, `this.boundingParent` is undefined so it uses the `visualBounds` instead.

**Comment by photonstorm** [comment]
Adding this here to remind me to follow-up when it's fixed: http://www.html5gamedevs.com/topic/22216-trouble-filling-parent-element-in-dom/

**Comment by ferrao** [comment]
@photonstorm is this issue the same as or somehow related with #2556?

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
