### ISSUE TITLE
 Code improvement suggestion for angleBetween() method

### ISSUE THREAD

**Issue by Skeptron** [photonstorm/phaser#2463]
As suggested here : http://www.html5gamedevs.com/topic/21698-code-improvement-suggestion-for-anglebetween-method/

I've come across some kind of a bug (maybe intended) and I'd like to suggest a fix. In the arcade engine, the angleBetween() method uses the x / y coordinates of the targeted sprites, and I think it should use the world.x / world.y coordinates instead. In my use-case, I had a character with a child sprite, its gun, that I wanted to point to the player. Because the gun was a child sprite, the angle was not correct and the gun wouldn't target the player.

What do you guys think? Are there use cases where it should be x / y instead of world.x / world.y? Maybe I should have used another method like angleToXY(), but I still kind of feel like angleBetween() should be fixed.

Hope it's helpful!

**Comment by ForgeableSum** [comment]
I know what you're talking about because I've just run into the same problem. However, there is no worldX/worldY property on sprites (although there are on pointers). Sprites are always positioned relative to their parents. If you use Phaser.Math.angleBetween, you run into the same problem when using it between a pointer and sprites that are children of other sprites (and not the game world). And getting the actual world x/y on child sprites (especially child sprites of child sprites) is really a huge pain in the ass. I've had some success with the toGlobal function. Although I don't entirely understand what the function does/ what the params should be etc,  as the docs are pretty vague. 

What I would REALLY love is a method on sprites which allows you to get the absolute world x/y positions. World positions independent of sprite rotation and sprite parents. A position that will always be relative to the world, because right now, that's pretty difficult to get manually. Sprite position could be just like the pointer: there are x/y and world x/y; only the x/y are relative to the parent (not the camera, like with pointers) and the world x/y are always relative to the world. Then getting the angle between pointer could be easily accomplished with Phaser.Math.angleBetween. 

I hope Richard reads this :).

**Comment by Skeptron** [comment]
I don't get your comment. What about http://phaser.io/docs/2.4.4/Phaser.Sprite.html#world ?

Sprites do have a world.x/y property! :)

**Comment by ForgeableSum** [comment]
Holy crap. I thought that was a reference to the game.world. I had no idea such a property existed ... On the one hand, I feel pretty stupid. On the other, my life just got a whole lot easier!

**Comment by pjbaron** [comment]
Bear in mind that that transform only gets updated when the render pass happens (through updateTransform) so it will not reflect any movements you have applied in the current frame.

Date: Tue, 3 May 2016 15:57:07 -0700

**Comment by photonstorm** [comment]
Erm, also how about `worldAlpha`, `worldPosition`, `worldScale` and `worldRotation` which anything that inherits from `PIXI.DisplayObject` has?

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.
