### ISSUE TITLE
AudioSprite: wrong startTime when game.time.time last update is too far from Date.now()

### ISSUE THREAD

**Issue by lucap86** [photonstorm/phaser#2484]
I've a problem with sounds

Seems that it occur if cpu is very busy before sound has to be played
Here it is an example:

![screen shot 2016-05-19 at 11 01 47](https://cloud.githubusercontent.com/assets/15343100/15388489/6fde4cbc-1db2-11e6-8e09-bc098e926d6b.png)

I've added a robot voice at the end of the looped audio in order to make it easy to detect the issue
Focus on the first loop 
it never reach it's end point
Next loops instead correctly play the sound till the end

i think that the problem is the computation of startTime in Phaser.Sound#play 
and the related check (this.currentTime >= this.durationMS) in Phaser.Sound#update

[testSound.zip](https://github.com/photonstorm/phaser/files/272221/testSound.zip)

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
