### ISSUE TITLE
Phaser does not handle loop points in audio

### ISSUE THREAD

**Issue by sleeparrow** [photonstorm/phaser#2531]
Please forgive my lack of understanding about the implementation details.

I'm able to place a "loop point" on songs in my DAW. As an example, I may have an intro in a song that counts four beats on a tamborine. If I place the loop point on the fifth beat, I'm saying that I want the intro (four beats on the tamborine) to be played only once. When the song loops, it should go back to the fifth beat instead of the first.

As far as I can tell, Phaser does not implement this functionality. `Phaser.Sound.prototype.play()` always loops back to the first beat, and `Phaser.Sound.prototype.markers` doesn't seem to load the loop point.

The behavior I would expect is that a loop point is observed automatically, looping back to the fifth beat in the example I gave. I would also expect the loop point to show up in the `markers` list.

It's of note that most music players don't implement this, but it's a great thing to have for games since it enables you to have a few notes at the beginning that otherwise wouldn't loop smoothly. [SFML](https://github.com/SFML/SFML) is an example of a game library that implements this functionality.

Here's a [test track](https://soundcloud.com/sleeparrow/loop_testogg/s-0V5u8) like the one I described in my example. You can download it using the button below the comment box.

Thank you!

**Comment by johnrees** [comment]
maybe this can help to get you started, using `onStop` won't be the _right way_ to approach it but I was getting some strange issues with the other signals

```javascript
var game;

window.onload = function () {
  game = new Phaser.Game();
  game.state.add('play', Play);
  game.state.start('play');
};

function Play() {}
Play.prototype = {
  preload: function() {
    this.load.audio('song', 'loop_test.ogg');
  },

  create: function() {
    this.currentSection = 'first';
    this.song = game.sound.add('song');

    this.song.addMarker('first', 0, 1.888)
    this.song.addMarker('second', 1.889, 4.054)

    this.song.onMarkerComplete.add(this.onMarkerComplete, this);
    this.song.onStop.add(this.onStop, this);

    this.song.play(this.currentSection);
  },

  onMarkerComplete: function(marker) {
    console.log(marker + " section finished");
    this.currentSection = 'second';
  },

  onStop: function() {
    this.song.play(this.currentSection);
  }
};
```

**Comment by tenry92** [comment]
Audio loop points is a general issue in web games, as far as I know. In any case, if you add an onend listener to a sound source, in order to set the position to the loop start point and resume playing, there's usually a small, silent gap in the audio input.

One solution might be to decode the whole audio data, as supported by [AudioContext.decodeAudioData](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/decodeAudioData), and fill the audio input programmatically from that buffer. However this would consume a lot of memory.

Alternatively you can use MOD music (i.e. MOD, S3M, XM, IT) with a web mod player, which usually uses the loop points.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
