### ISSUE TITLE
EXACT_FIT scaling does not work as expected on mobile device

### ISSUE THREAD

**Issue by HDouss** [photonstorm/phaser#2537]
This Issue is about (delete as applicable)
- A bug in the API

I am trying to scale my game like this:

``` javascript
this.scale.scaleMode = Phaser.ScaleManager.EXACT_FIT;
this.scale.pageAlignHorizontally = true;
this.scale.pageAlignVertically = true;
this.scale.forceOrientation(false, true);
this.scale.updateLayout(true);
this.scale.refresh();
```

My understanding of EXACT_FIT is that it stretches the game so it will fill the entire screen and (much probably) does not keep proportions.

So, there is no chance that the scaled height will be larger than the screen height.

When I try my game in the Intel XDK emulators, scaling works as expected in all the devices suggested in the emulator.

But when I try to install the apk on my phone, or I try to debug (with Intel XDK) on my phone the game scales on width coorectly, but keeps its original height which exceeds my screen height (`this.scale.height` has the same value as `this.game.height`).

**Comment by HDouss** [comment]
I figure out the problem happens only if the canvas is appended on a div. If it is appended directly to the body (i.e : 4th arg is empty on `new Phaser.Game(.., .., Phaser.AUTO, '');`), the scaling is working as expected.

**Comment by shanadeshana** [comment]
Thanks for letting me know this, it was making me crazy and I didn't know how to solve it. You saved my life!

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
