### ISSUE TITLE
Resizing browser or changing orientation, can break animations and tweens (example included)

### ISSUE THREAD

**Issue by Ninjadoodle** [photonstorm/phaser#2538]
This Issue is about (delete as applicable)
- A bug in the API

I've tried setting up  frame by frame animations as well as tweens, and I've noticed that resizing the browser window or changing orientation on a device, breaks the animations or tweens.

The animations seems to stop playing at a certain frame and never resume (unless on a timer, in which case they just restart).

I suspect the resizing of a browser / orientation change, momentarily pauses the animations, yet they never seem to finish.

This is an issue on all browsers I've tried, and both iOS and Android.

This doesn't always happen, but of you resize the window for 20 or so seconds, or keep changing orientation, one of the cats eyes will most likely gets stuck mid blink.

Here is a link to a test case ...

https://www.dropbox.com/sh/7p0g53ip5ubqiqt/AAB2sUUeUtsXaf987t1D2OPka?dl=0

Please me know if I can do anything else to help :)

Thank you in advance for any help!

**Comment by Ninjadoodle** [comment]
Hi Richard

Just wondering if you've had time to look into this, as I still haven't managed to solve it?

Thank you!

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
