### ISSUE TITLE
Button overFrame parameter not working properly in 2.4.8

### ISSUE THREAD

**Issue by chrispump** [photonstorm/phaser#2539]
Since version 2.4.8 the overFrame parameter for button spritesheets is not working properly. Parameters for outFrame and downFrame are still working as intended.
You can easily reproduce this behaviour on the Phaser.io button examples:

http://phaser.io/examples/v2/buttons/action-on-click

Here, the 2nd spritesheet frame for the overFrame parameter is being ignored:
`button = game.add.button(game.world.centerX - 95, 400, 'button', actionOnClick, this, 2, 1, 0);`
It's not working for version 2.4.8, but if you switch to 2.4.7 everything is just fine.

**Comment by photonstorm** [comment]
Thanks for spending time reporting this issue. However we've already fixed this in the `dev` branch of Phaser, and it will be part of the next official release. You can track what's already been fixed by looking at the Change Log part of the [dev README](https://github.com/photonstorm/phaser/tree/dev#change-log) file.
