### ISSUE TITLE
useHandCursor not working properly in Phaser 2.4.8

### ISSUE THREAD

**Issue by marcelodeassis** [photonstorm/phaser#2540]
The hard cursor only appears while pressing.

Example:
https://jsfiddle.net/snake/vg3Ljk26/

I've tested in other versions and works fine, only the 2.4.**8** have this issue,

**Comment by MichelAlonso** [comment]
I was going to report this, just to add more info:

This Issue is about:
* A bug in the API

When mouse over the `button` in version 2.4.7 works normally. 
[2.4.7 example](http://examples.phaser.io/_site/view_full.html?d=loader&f=load%20events.js&t=load%20events&phaser_version=v2.4.7&)
[2.4.8 example](http://examples.phaser.io/_site/view_full.html?d=loader&f=load%20events.js&t=load%20events&phaser_version=v2.4.8&)
In 2.4.8 detects only if you click outside button(inside canvas), hold and move over the button, and also after this don't dispatch `mouseOut` if you release inside button.

The same occur with `sprite` with `event.onInputOver`(inputEnabled is enabled).

After some research looks like something related with `Phaser.Pointer` parameter in `inputHandler._pointerOverHandler`.

**Comment by photonstorm** [comment]
Thanks for spending time reporting this issue. However we've already fixed this in the `dev` branch of Phaser, and it will be part of the next official release. You can track what's already been fixed by looking at the Change Log part of the [dev README](https://github.com/photonstorm/phaser/tree/dev#change-log) file.
