### ISSUE TITLE
Phaser keyCode might not work on all browsers.

### ISSUE THREAD

**Issue by SVasilev** [photonstorm/phaser#2542]
This Issue is about

* A possible bug in the implementation

Hello, I looked at the implementation of Phaser.Keyboard to see how you get the keyCode:
https://github.com/photonstorm/phaser/blob/v2.4.8/src/input/Keyboard.js#L370

In this code the _event_ object is comming from the DOM. Then I looked at the MDN spec:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

It seems that keyCode is deprecated so the suggested solution as you see is:
```
window.addEventListener("keydown", function (event) {
  if (event.defaultPrevented) {
    return; // Should do nothing if the default action has been cancelled
  }

  var handled = false;
  if (event.key !== undefined) {
    // Handle the event with KeyboardEvent.key and set handled true.
  } else if (event.keyIdentifier !== undefined) {
    // Handle the event with KeyboardEvent.keyIdentifier and set handled true.
  } else if (event.keyCode !== undefined) {
    // Handle the event with KeyboardEvent.keyCode and set handled true.
  }

  if (handled) {
    // Suppress "double action" if event handled
    event.preventDefault();
  }
}, true);
```

Wouldn't be nice to have that in Phaser as well to avoid future incompatibilities with different browsers and platforms?

**Comment by photonstorm** [comment]
Thanks for submitting this issue. We have fixed this, and the fix has been pushed to the `dev` branch.

**Comment by photonstorm** [comment]
Actually I'm going to remove this change from Phaser. It's not as simple as adding that conditional in. `keyCode` returns a numeric code. `key` (and `keyIdentifier`) return strings. And the strings are in-consistent across browser. For example IE9 returns `Up` where-as Chrome returns `ArrowUp`. This would mess with the `Phaser.KEY` consts in a large way.

I appreciate it's deprecated, but I also suspect it's one of those things that will hang around for ages yet, due to how common using keyCode is, and how much it would break if support was dropped. We can address this differently in Lazer, but I'll revert my change for now.

**Comment by SVasilev** [comment]
Hello,
Happy to get you interested. There are some ways to convert the keyIdentifier to keyCode but it is useless because right now I think that only Chrome cares about that property. So Phaser should not deal with it anyway. The key property is not adopted from all browsers too.
So I think that the best solution for now would be
```
var key = event.keyCode || event.which;
```
As said in http://stackoverflow.com/questions/15108670/cross-browser-cross-os-way-to-get-keycode-character-pressed-onkeydown-event
