### ISSUE TITLE
isOver not working on 2.4.8

### ISSUE THREAD

**Issue by fzuleta** [photonstorm/phaser#2547]
Hi!

This Issue is about isOver always false on Button, on 2.4.7 works fine, 

`if (this.mBody.onInputUp && isOver == true) {`

isOver is always reported false in 2.4.8

cheers and thank you!

**Comment by photonstorm** [comment]
Thanks for spending time reporting this issue. However we've already fixed this in the `dev` branch of Phaser, and it will be part of the next official release. You can track what's already been fixed by looking at the Change Log part of the [dev README](https://github.com/photonstorm/phaser/tree/dev#change-log) file.
