### ISSUE TITLE
canvas size is wrong in fullscreen mode

### ISSUE THREAD

**Issue by ferrao** [photonstorm/phaser#2556]
I have a simple 2 column layout:

```
<div class="container">
        <div class="sidebar"></div>
        <div id="phaser-div" class="main"></div>
</div>
```

The `container` div has it's display css property set to `flex`, `sidebar` is fixed to 200px, the `phaser-div` uses up all remaining space using the `flex-grow` css property. 

This setup works just like i want using the `SHOW_ALL` scale mode. `fullScreenScaleMode` is also set to `SHOW_ALL`

When entering full screen mode by calling `requestFullscreen()` on the container element, the canvas size is adjusted, but instead of taking up the available space in `phaser-div`, it takes up all the space available in the `container` element, causing the game to be cropped by 200px

In essence, i want the _whole container to go fullscreen_ and not only the phaser element.

**Comment by photonstorm** [comment]
This is now fixed in the dev branch in a couple of different ways.

First this commit: https://github.com/photonstorm/phaser/commit/79e135087f2ddb12322e6ed8dd30bf12599f7953 it will now check to see if Phaser was responsible for putting it full screen or not, and adjust accordingly. Secondly, you can specify the `ScaleManager.fullScreenTarget` if full-screen mode is set from within Phaser, to scale that element instead of the Phaser canvas.
