### ISSUE TITLE
Argument of type 'typeof InputField' is not assignable to parameter of type 'Plugin'.

### ISSUE THREAD

**Issue by smks** [photonstorm/phaser#2566]
This Issue is about trying to use a plugin with Phaser.

```
constructor() {

        this.game = new Game(
            960,
            540,
            Phaser.CANVAS,
            this.gameId,
            {
                create: this.create
            },
            true,
            true
        );

        this.game.add.plugin(Fabrique.Plugins.InputField);
    }
```

src\typescript\game.ts(38,30): error TS2345: Argument of type 'typeof InputField' is not assignable to parameter of type 'Plugin'.

`plugin(plugin: Phaser.Plugin, ...parameter: any[]): Phaser.Plugin;`
- An error in the TypeScript defs

Thanks!

**Comment by photonstorm** [comment]
Hmmm, but `Fabrique.Plugins.InputField` should extend `Phaser.Plugin`, then it'd work fine, surely?

**Comment by smks** [comment]
Yes indeed it does. I still get the error though.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
