### ISSUE TITLE
Children of Removed Display Objects Still Fire Touch Events

### ISSUE THREAD

**Issue by fillmoreb** [photonstorm/phaser#2586]
This Issue is about (delete as applicable)
- A bug in the API

When a display object is removed from the world, it's children are still firing their touch events, even though they are no longer in the display list.  The following code can be used to reproduce the problem:

`
    var parent = null;
    var child = null;

```
var game = new Phaser.Game(800, 600, Phaser.AUTO, '', {create: create});

function create() {
    parent = game.make.sprite(0,0);
    child = game.make.graphics(0,0);

    parent.addChild(child);

    child.beginFill(0xFF0000);
    child.drawRect(0,0,50,50);

    game.world.add(parent);

    child.inputEnabled = true;

    child.events.onInputDown.add(function(){
        alert("Hi!");
        game.world.remove(parent);
    });
}
```

`

Click on the red square, an alert will pop up saying it's been clicked on, then it will remove it's parent from the world.  Then click on the spot the red square was previously occupying (I had to click twice on Chrome), and the alert still opened despite the fact that all items were removed from the world.

I was able to reproduce this error both in Chrome and Safari, OSX El Capitan.

**Comment by photonstorm** [comment]
Children in Pixi have absolutely no concept of the `root`, they know only about the immediate parent, and that's it. Without that information it's impossible to know if a child is still on the display list or not. 

It's also perfectly valid to have a 'hit area' style sprite that _isn't on the display list at all_, and still be capable of processing input events. So I don't agree this is a bug, as what happens is correct. However it's definitely a feature request of a kind, because children should know if they are on the display list or not. And if they did, then there could be an input related option that told them to ignore events if they're unparented (although it would be off by default, as it's actually an extremely useful feature).

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
