### ISSUE TITLE
Suggestion - sprite angle follow tween path?

### ISSUE THREAD

**Issue by shibekin69** [photonstorm/phaser#2590]
Hi Rich,

Sorry if this seems bothersome, but is there anyway to add the feature where a sprite follows the angle of a tween path (if one is using a bezier curve)?

And well, I noticed something too when using the bezier interpolation on a tween. This is the code snippet that I'm using (x and y values just dummies):

```
this.testTween = this.game.add.tween(obj).to( { x: [1,2,3,4,4,3,2,1], y:  [1,2,3,4,4,3,2,1] }, 1000, Phaser.Easing.Sine.InOut, true, 0, true).interpolation(function(v, k){
            return Phaser.Math.bezierInterpolation(v, k);
});
```

I noticed that if I try to stop the tween using the assigned variable:

`this.testTween.stop()`

It won't stop.

But it works if I use this to stop it:

`this.game.tweens._tweens[0].stop()`

If I remove the bezier curve [.interpolation] function, I can stop it using:

`this.testTween.stop()`

I'm using Phaser 2.4.8 btw.

**Comment by hilts-vaughan** [comment]
You can generate the tween data using phaser at the time slices, why not compute the angle between these points and index them during the tween to update accordingly? You can probably wrap this in your own special type of tween

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
