### ISSUE TITLE
Sprite animations issue after "loadTexture" method is used

### ISSUE THREAD

**Issue by plissken2013es** [photonstorm/phaser#2598]
This Issue is about 
- A bug in the API
- A problem with my own code

I'm not sure if this is an API bug or a problem in my code. 
What's happening is that I preload two spritesheets, one containing 4 frames and another one containing 5. 
Then, I create a sprite based on my first spritesheet (4 frames) and add two animations to it.
If I play mi first animation (4 frames) everything's ok. Then, I try to load a new texture for my sprite via loadTexture and then play its corresponding animation, and that's where something weird occurs: my animation lacks of its last frame (the fifth).
It seems that I can't load a texture with a different number of frames than the very first one (that I used to create my sprite) has.
The problem gets worse with textures with less frames
I know that it's optimal to use an atlas, but... can't we use this approach? Is it a known limitation?

Sample code is here:
https://app.box.com/s/2da3mgt6xuzzb915cdzxa2gl4v3pv2ek

**Comment by photonstorm** [comment]
As you've identified when a new texture is loaded, none of the existing animation frames are removed or modified. You could possibly try calling `sprite.animations.loadFrameData(img.frameData, frame)` (where img is taken from `Cache.getImage`) but this is unfortunately still really just trying to work around a system that was never meant to handle texture swapping mid-animation like this.

**Comment by plissken2013es** [comment]
Thanks for clearing this out, Richard.

**Comment by photonstorm** [comment]
I'd be curious to know how you would like the Animation system to handle frames split over multiple textures. I.e. how would you like the API to change so you can specify this? I'm thinking maybe something like giving the texture key before the frame name? Or blocking them into objects.. i.e.: `animations.add('shoot', { texture1: [0,1,2,3], texture2: [0,1,2,3,4,5,6] )`

Because I'm well aware Phaser doesn't support this now, and I want it to.

**Comment by plissken2013es** [comment]
Regarding to your first comment, I've tried this:
`sprite.animations.loadFrameData(fame.cache.getFrameData("texture_key");`
And then I tried to play the new animations, but it doesn't work: some weird visual effect occurs.

Maybe the API only needs to take account on the size and number of frames that the new texture has. For example:
`function preload() {`
 `game.load.spritesheet("key1", null, 27, 63, 4);`
 `game.load.spritesheet("key2", null, 31, 69, 5);`
 `}`
`function create() {`
 `mySprite= game.add.sprite(0, 0, "key1");`
 `mySprite.animations.add("anim1", null, 6, true);`
 `mySprite.animations.add("anim2", null, 12, false);`
 `mySprite.play("key1");`

Later in the code:
`mySprite.loadTexture("key2", 0, true);`
`mySprite.play("anim2");`
The "loadTexture" method stops the current animation before loading the new texture and before showing the frame number 0, in this case. It should reset the "frameTotal" and "_frames" properties of anim1 and anim2 to 5 and [0, 1, 2, 3, 4, 5] because I set its optional "frames" Array property to null when I defined them at the "preload()" method, and this means that I want to use all available frames.

Nevertheless, you propose a new interesting approach to this matter: it'll be great if we could link any animation to a any key spritesheet by passing an object parameter instead of one array parameter containing frame numbers or names. So, finally, the "animations.add" method could be this way:
`add(name, frames, frameRate, loop, useNumericIndex) `
where the frames parameter continues to be optional (null, by default) but could be an array or an object.
If an array is given, it behaves as usual: the API takes an array of numbers/strings that correspond to the frames to add to the animation and in which order. e.g. [1, 2, 3] or ['run0', 'run1', run2]). If null then all frames will be used.
But, if an object is given in this form:
`mySprite.animations.add('shoot', { texture1: [0,1,2,3], texture2: ["gun0", "gun1", "gun2", "gun3", "gun4", "gun5", "gun6"], texture3: null })`
The API now interprets that we want this animation to have three different "flavors": one that uses texture1 -which is an spritesheet-  and its frames from 0 to 3, another one that uses texture2 -an atlas- and its frames named gun0 ... gun6, and finally texture3, an spritesheet from which we use all available frames.
Obviously, we'll need a method to switch between "texture modes" later in our game.

It seems like a non-trivial improvement for the API, but it provides a new useful way to handle sprites.

What do you think?

**Comment by photonstorm** [comment]
I believe if you set the animation up to span multiple textures then it should swap between them automatically for you. I like the idea of mixing atlas + sprite sheets like above, that makes sense (although I suspect very rare)

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
