### ISSUE TITLE
Sound.onMarkerComplete signal is broken

### ISSUE THREAD

**Issue by WVI** [photonstorm/phaser#2600]
It's already been noticed, but here's the issue thread, for insurance.

```
game.bgm = game.add.audio('southSide');
game.bgm.addMarker('start', 0, 11.748, 0.7);
game.bgm.addMarker('loop', 11.748, 110.769, 0.7, true);
game.bgm.play('start', 0, 0.7, false);
game.bgm.onMarkerComplete.add(function() { // This will only fire once, and the sound will NOT loop after heading into the loop section under any circumstances, whether loop is set to true or false on the marker or play function itself
      if (game.bgm.volume != 0.0) {
           console.log('yes');
           game.bgm.play('loop', 0, 0.7, true);
     }
}, this);
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
