### ISSUE TITLE
game.physics.p2.useElapsedTime doesn't matter

### ISSUE THREAD

**Issue by noobshit** [photonstorm/phaser#2602]
http://www.html5gamedevs.com/topic/23554-gamephysicsp2useelapsedtime-true/

If game.physics.p2.useElapsedTime == true then use  game.time.physicsElapsed == 1/60
If game.physics.p2.useElapsedTime == false then use game.physics.p2.frameRate == 1/60

I did hotfix for myself with 

```
        if (this.useElapsedTime)
        { 
            let lastUpdate = this.lastUpdate || Date.now();
            let now = Date.now();
            let dt = (now - lastUpdate) * 60/1000 * 1/60; 
            this.lastUpdate = now;

            this.world.step(dt);
        }
```

But game.time.physicsElapsed is also used in LifeSpan and tweens.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
