### ISSUE TITLE
Sound.pause, sound.resume causes weird behavior

### ISSUE THREAD

**Issue by ulitiy** [photonstorm/phaser#2603]
- A bug in the API

```
audioJSON = {
      spritemap: {
        'one': {start: 0, end: 6.5, loop: true},
        'two': {start: 7, end: 9, loop: false}
      }
    }
audioSprite = this.load.audiosprite('sfx', ['audio/fx_bundle.mp3'], null, audioJSON);
sound = audioSprite.sounds['one'];   // loops just fine
sound.play('one');
sound.pause();
sound.resume();
```

loops first but also loops the whole file so building infinite cacophony.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
