### ISSUE TITLE
Camera with lerp does not center on followed sprite

### ISSUE THREAD

**Issue by adambadawy** [photonstorm/phaser#2605]
This can be observed in the following example by moving the character around. When the camera is catching up from above or left of the character, it doesn't stop at the center of the sprite.

I wrote this issue in a hurry. Please let me know if I can provide any other information.

```javascript
var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', { preload: preload, create: create, update: update, render: render });

function preload() {
    game.load.image('background','assets/tests/debug-grid-1920x1920.png');
    game.load.image('player','assets/sprites/phaser-dude.png');
}

var player;
var cursors;
var debugLine;
var debugLine2;

function create() {
    game.add.tileSprite(0, 0, 1920, 1920, 'background');
    game.world.setBounds(0, 0, 1920, 1920);
    game.physics.startSystem(Phaser.Physics.P2JS);
    player = game.add.sprite(game.world.centerX, game.world.centerY, 'player');
    game.physics.p2.enable(player);
    player.body.fixedRotation = true;
    cursors = game.input.keyboard.createCursorKeys();

    game.camera.follow(player, Phaser.Camera.FOLLOW_LOCKON, 0.1, 0.1);
    debugLine = new Phaser.Line(0, 0, 0, game.camera.view.height);
    debugLine2 = new Phaser.Line(0, 0, game.camera.view.width, 0);
}

function update() {
    player.body.setZeroVelocity();

    if (cursors.up.isDown) {
        player.body.moveUp(300)
    }
    else if (cursors.down.isDown) {
        player.body.moveDown(300);
    }
    if (cursors.left.isDown) {
        player.body.velocity.x = -300;
    }
    else if (cursors.right.isDown) {
        player.body.moveRight(300);
    }
    
    debugLine.centerOn(game.camera.view.centerX, game.camera.view.centerY);
    debugLine2.centerOn(game.camera.view.centerX, game.camera.view.centerY);
}

function render() {
    game.debug.text("Arrows to move.", 32, 32);
    
    game.debug.geom(debugLine, '#ff0000');
    game.debug.geom(debugLine2, '#ff0000');
}
```

**Comment by kevinAlbs** [comment]
I was able to reproduce this, and I think a quick fix to your issue is to add to your create() method:
`game.camera.roundPx = false;`

The key issue seems to be that the camera position increment may have no effect if the increment is too small and gets rounded off when roundPx is true. Specifically: https://github.com/photonstorm/phaser/blob/v2.6.2/src/core/Camera.js#L624-L635 may be incrementing `this.view.x` by small values which always get rounded to the same integer during `this.view.floor()`.

I'm not sure if this is "technically" a bug because maybe this is what should happen if roundPx is true, but it is definitely unexpected. Is there a reason that roundPx is true by default? And if roundPx is true, could we store the exact unrounded position in `view` and rather round `this.displayObject.position`? I'd be happy to take a stab at this if this sounds like a possible solution.

**Comment by photonstorm** [comment]
Thanks @kevinAlbs - you're right. Just adding: `game.camera.roundPx = false;` to the above example fixes it just fine. I'm happy with that as a solution really, the property is there to be changed on a case-by-case basis, and this is such a case.
