### ISSUE TITLE
alignTo() and alignIn() don't work well with Sprites who have parents

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2606]
Let's say I have a Sprite at `(200, 200)` with `50px` `width` and `height`. I create another Sprite and add it as a child to the first sprite, then use `child.alignIn(parent, Phaser.TOP_CENTER)`. This theoretically should set the child's `x` to `25` and `y` to `0`, but it instead sets it to `225` and `200`.

Because it's a child, when rendered, it gains the `(200, 200)` from its parent in addition and its visible `x` and `y` is `425` and `400`. The end result is the child completely out of the parent and definitely not in the top center of it.

The `alignIn()` and `alignTo()` methods could have an addition argument that checks whether the Sprite should be positioned relative to the world or to its parent. Or perhaps `alignInParent()` and `alignToParent()` could be introduced.

**Comment by hdodov** [comment]
I've come up with the code below for this problem. It seems to be working perfectly. I tested it with various combinations of child and parent anchors, scales and positions. The parent's scale is set to 1 because its `width`, `left` and `top` are affected by it and would cause the child to be positioned inaccurately. However, the scale is then turned back. I've not yet seen a problem with that.
```
Phaser.Sprite.prototype.alignInParent = function(position, offsetX, offsetY){
	if(this.parent.name == "__world")return;

	var s = this.parent.scale;
	this.parent.scale.setTo(1);
	this.alignIn(this.parent, position, offsetX, offsetY);

	this.left -= this.parent.left + (this.parent.width*this.parent.anchor.x);
	this.top -= this.parent.top + (this.parent.height*this.parent.anchor.y);

	this.parent.scale = s;
};
```
This could be a possible implementation, or just an idea of it.

**Comment by jbrisebois** [comment]
@hdodov solution's work great. Thanks!

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
