### ISSUE TITLE
addChild() convenience suggestion

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2608]
Phaser provides us with the `addChild()` and `addChildAt()` methods for `Phaser.Sprite`. This adds them to an array of Sprites, called `children` in the parent Sprite. However, working with indexes can be tricky and a bit difficult. If you need to attach a lot of child Sprites to another Sprite and then manipulate them, you need to know at which index they're located.

My suggestion is to add an additional argument to `addChild()` and get the following:

```
var myParent = game.add.sprite(0, 0, 'image'),
    myChild = game.add.sprite(0, 0, 'image2');

myParent.addChild(myChild, 'myChlidName');
myParent.children.myChildName.alpha = 0.5; // or something else
```

If the second argument is not given, the function could work like it does now - assign an incrementing number as the key. For example:

```
var myParent = game.add.sprite(0, 0, 'image'),
    myFirstChild = game.add.sprite(0, 0, 'image2'),
    mySecondChild = game.add.sprite(0, 0, 'image2'),
    myThirdChild = game.add.sprite(0, 0, 'image2');

myParent.addChild(myFirstChild);
myParent.addChild(mySecondChild, 'myChlidName');
myParent.addChild(myThirdChild);

myParent.children.myChildName // references mySecondChild
myParent.children[0] // references myFirstChild
myParent.children[1] // references myThirdChild
```

Currently, I'm using this way to provide easier access to the child:

```
var myParent = game.add.sprite(0, 0, 'image'),
    myChild = game.add.sprite(0, 0, 'image2');

myParent.addChild(myChild);
myParent.ref_myChild = myChild;
myParent.ref_myChild.alpha = 0.5;
```

And I find this pretty annoying, especially when I have lots of child Sprites.

Implementing this would require the `children` property of `Phaser.Sprite` to be an Object, instead of an Array, I think. However, if it causes no significant difficulties for the engine, things my become a lot easier, in my opinion.

**Comment by hilts-vaughan** [comment]
You can extend Sprite and them over ride the addChild method to accept this
parameter and search the children for you.

**Comment by hdodov** [comment]
Yep, I know. But it would be nice if people can have it without writing it themselves. An engine's job is to make things as easier as it can.

**Comment by hilts-vaughan** [comment]
I don't disagree but you said your current approach was frustrating -- so you can always wrap things to make them easier. :(

**Comment by samme** [comment]
You can just do

```javascript
sprite.aChild = sprite.addChild(…);
// or even
sprite.children.aChild = sprite.addChild(…);
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
