### ISSUE TITLE
Get

### ISSUE THREAD

**Issue by Neogene** [photonstorm/phaser#2610]
Hi i found a bug in 2.6 (in 2.5 there isn't)

* A bug in the API

collideSpriteVsGroup: function (sprite, group, collideCallback, processCallback, callbackContext, overlapOnly) {

       //etc
            var bounds; ------> THIS VARIABILE IS undefined <-------

            for (var i = 0; i < group.hash.length; i++)
            {
                //etc, here bounds is not initialized

                //  Inject the Body bounds data into the bounds object
                bounds = object1.body.getBounds(bounds); ---> CHECK with bounds which is undefined <----

**Comment by photonstorm** [comment]
Thanks for spending time reporting this issue. However we've already fixed this in the `dev` branch of Phaser, and it will be part of the next official release. You can track what's already been fixed by looking at the Change Log part of the [dev README](https://github.com/photonstorm/phaser/tree/dev#change-log) file.
