### ISSUE TITLE
kinematic and gravitation

### ISSUE THREAD

**Issue by valentin93** [photonstorm/phaser#2611]
Hello. 
Avoiding moving sprite to deviate from its trajectory when colliding
I set kinematic = true.

But then gravity stops working.

How to avoid the impact from other objects in the collision, but at the same time keep all the physical properties?

**Comment by hdodov** [comment]
Uhm.
I believe the Sprite behaves the way you want by default. When you enable physics for it, gravity affects it. It's affected by collision only when you deliberately want it to by using `game.physics.arcade.collide`. If you want to only check if a Sprite collides, but you don't want the engine to separate it from the colliding object (having impact), you just use `game.physics.arcade.overlap`. Have a look at the examples that Phaser provides.

Hope that was helpful! :)

**Comment by photonstorm** [comment]
To be using a kinematic body you must be using P2, not Arcade Physics. As soon as a body is kinematic it will definitely ignore gravity (it wouldn't be kinematic otherwise!) - to avoid collision from other objects you need to set-up collision Groups, and assign your objects to them in the order you need.
