### ISSUE TITLE
Arcade physics: Circle body goes through square body

### ISSUE THREAD

**Issue by spixy** [photonstorm/phaser#2625]
Hi, when I used default (square) body, everything works fine, but if I add `playerSprite.body.setCircle(25)`, that body **sometimes** goes through other square body.
`playerSprite` is moving from left to right (and possibly from up to down if I jumped).

However `game.physics.arcade.collide(playerSprite, groupWithSquareSprites, collisionHandler)` works fine even for circle.

(using Phaser v2.6.1)

```
game.physics.arcade.enable(playerSprite);

playerSprite.body.checkCollision.up = false;
playerSprite.body.checkCollision.down = true;
playerSprite.body.checkCollision.left = false;
playerSprite.body.checkCollision.right = true;

playerSprite.body.allowRotation = false;

playerSprite.body.setCircle(25); // without this its working
```

```
game.physics.arcade.enable(otherSquareSprite);

otherSquareSprite.body.allowGravity = false;
otherSquareSprite.body.allowRotation = false;
otherSquareSprite.body.immovable = true;
otherSquareSprite.body.moves = false;

otherSquareSprite.body.checkCollision.up = true;
otherSquareSprite.body.checkCollision.down = false;
otherSquareSprite.body.checkCollision.left = true;
otherSquareSprite.body.checkCollision.right = false;

groupWithSquareSprites.add(otherSquareSprite);
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
