### ISSUE TITLE
Slow motion is choppy

### ISSUE THREAD

**Issue by noobshit** [photonstorm/phaser#2631]
http://phaser.io/examples/v2/time/slow-down-time
**NOW** When you set high slowMotion balls will wait X frames to move Y pixels.
**EXPECTED** move ball Y/X pixels every frame.

init commit = phaser 2.6.1
Later commits I fixed problem by changing phaser.js. I changed game.updateLogic() and game.update().

https://github.com/noobshit/updateFixed

I think above change in updateLogic would fix issue with physics https://github.com/photonstorm/phaser/issues/2602

Sorry for using phaser.js but I don't know how make phaser src work with index.html. :(

**Comment by hexus** [comment]
For my [Arcade Slopes demo](http://hexus.github.io/phaser-arcade-slopes) I discovered a workaround for this. Still doesn't seem to do what it says on the tin, so I'd personally like to see this improved too. That way you just tweak `time.slowMotion` for instant smooth bullet time. :)

```
this.time.slowMotion = features.slowMotion;
this.time.desiredFps = 60 + (features.slowMotion > 1 ? features.slowMotion * 20 : 0);
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
