### ISSUE TITLE
[2.7.0] TilemapLayer.resize() and TilemapLayer.resizeWorld() not working

### ISSUE THREAD

**Issue by noidexe** [photonstorm/phaser#2646]
I have counts that detects a window resize and does <code>this.layer.resize(this.game.width, this.game.height);</code> and <code>this.layer.resizeWorld();</code> so that the tilemap layer covers the whole window on different aspect ratios. 

Here is a comparison of what happens on 2.6 versus 2.7. 
![Imgur](http://i.imgur.com/hHfaH5N.jpg)

It doesn't seem to scale the layer but the tileset.

**Comment by noidexe** [comment]
And here's how it looks on 2.7.0 without the calls to layer.resize and layer.resizeWorld(note that the lava near the bottom is made of sprites and the dark background is a tilesprite). 

![Imgur](http://i.imgur.com/R8jb3a7.png)

**Comment by noidexe** [comment]
I've tested again with the latest dev and I noticed that the tilemap layer scales up to the width and height originally defined when calling new Phaser.Game(...)

That is, if I call game.scale.setGameSize(newwidth, newheight) while the game is running and then do layer.resize(this.game.width, this.game.height) it won't work if the new game.width and/or game.height is larger than when phaser was initialized. This wasn't the case with 2.6.0. 

I've managed to work around the problem by initializing phaser with the same value for height than I use for width and then adjusting it to the real dimensions of the window. That way it works with ratios up to 1:1

**Comment by hexus** [comment]
I actually fixed this as part of a pull request (#2691) because I was facing the same issue.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
