### ISSUE TITLE
Phaser.Physics.Arcade.Body alignIn() and alignTo()

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2658]
Having those two methods for the Body will be useful. For example, I currently have a 125x125 Sprite that must collide with only its center 20x20 pixels. What I'm currently doing is this:

```
sprite.body.width = 20;
sprite.body.height = 20;
sprite.body.offset.x = (sprite.width - sprite.body.width)/2;
sprite.body.offset.y = (sprite.height - sprite.body.height)/2;
```

Having the `alignIn()` and `alignTo()` not only in the Sprite, but in the Body itself will allow me to do that:

```
sprite.body.width = 20;
sprite.body.height = 20;
sprite.body.alignIn(Phaser.CENTER);
```

It's not that big of a deal, I know. Those things can easily be calculated. Having the methods will make things easier, though.

**Comment by samme** [comment]
I did this a few times too and eventually wrote:

```javascript
Phaser.Physics.Arcade.Body.prototype.resize = function(width, height) {
  var offsetX, offsetY;
  if (height == null) {
    height = width;
  }
  offsetX = 0.5 * (this.sprite.width  - width)  / this._sx;
  offsetY = 0.5 * (this.sprite.height - height) / this._sy;
  width  /= this._sx;
  height /= this._sy;
  return this.setSize(width, height, offsetX, offsetY);
};
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
