### ISSUE TITLE
Why Physics is getting slower when FPS drops?

### ISSUE THREAD

**Issue by ulitiy** [photonstorm/phaser#2659]
- A bug in the API
  or
- A problem with my own code

Hey!
I have 150 particles in the scene. It works fine on the desktop but it's slow on the mobile device (15 FPS). But as I understand that shouldn't break the timing of physics, physics should depend on time, not on update steps. So particles should fly with exactly same speed on any device (but on 15 FPS it will be twitchy). Why doesn't it work that way? You can open particlestorm/hsv-colors example on a slow mobile device to see that particles are getting destroyed and don't even leave the center of the screen.

**Comment by GGAlanSmithee** [comment]
probably related to #2635

**Comment by Dillybob92** [comment]
@ulitiy Try setting `game.forceSingleUpdate` to false and re-test it, still happening?

**Comment by ulitiy** [comment]
Yes, still happening, and it seems that elements live longer than their lifespan.

**Comment by noobshit** [comment]
https://github.com/photonstorm/phaser/issues/2602 here is explanation

**Comment by ForgeableSum** [comment]
I've noticed this too. I wonder if it's intentional.

**Comment by samme** [comment]
You need `game.forceSingleUpdate = false`.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
