### ISSUE TITLE
When the pointer is out of the game it's considered isDown=false

### ISSUE THREAD

**Issue by ulitiy** [photonstorm/phaser#2660]
- A bug in the API

Probably we can use onMouseMove `event.which` or something to determine the button state. I think the button state itself is more important than if it's left the canvas or if mousedown/up event happened.

**Comment by photonstorm** [comment]
In order to do this we'd need to capture `mousemove` events on the `window` itself. And if the game is in an iframe, or embedded a layer or two down, to all parents as well. This is not something I want to do, it feels far too invasive. If you need to do it, then capture window level movement events yourself and process them as needed.

Unless you can think of a cleaner solution.

**Comment by ulitiy** [comment]
@photonstorm Well you don't have to capture mousemove on window, the canvas itself is enough. With each mousemove event it passes `event.which` with button down if any.

```
    $(this.game.canvas).mousemove((event)=>this.mouseDown = (event.which === 1));
    $(this.game.canvas).mouseleave((event)=>this.mouseDown = false);
...
    if (this.input.activePointer.isDown || this.mouseDown)
```

**Comment by photonstorm** [comment]
This was done for a specific reason. Digging through the code I can see this in `Mouse.onMouseOutGlobal`:

```
        //  If we get a mouseout event from the window then basically
        //  something serious has gone down, usually along the lines of
        //  the browser opening a context-menu or similar.
        //  On OS X Chrome especially this is bad news, as it blocks
        //  us then getting a mouseup event, so we need to force that through.
        //
        //  No matter what, we must cancel the left and right buttons

        this.input.mousePointer.stop(event);
        this.input.mousePointer.leftButton.stop(event);
        this.input.mousePointer.rightButton.stop(event);
```

Following that back, `onMouseOutGlobal` is bound to `window` in `Mouse.start`:

```
            window.addEventListener('mouseup', this._onMouseUpGlobal, true);
            window.addEventListener('mouseout', this._onMouseOutGlobal, true);
            canvas.addEventListener('mouseover', this._onMouseOver, true);
            canvas.addEventListener('mouseout', this._onMouseOut, true);
```

Yet putting a trace in, `onMouseOutGlobal` is clearly being called when the mouse leaves the canvas, not the window. So the bigger issue I can see here, is why on earth that is happening.

**Comment by namark** [comment]
I'm not very well versed in DOM, with all its events, but this was bugging me too, and, after some testing, it seems to me that any mouse out event eventually bubbles up to window, a parent of everything, I guess. However I couldn't find any straight forward way to deal with that... an `if(event.relatedTarget == null)` check works for me, but doesn't feel particularly robust...

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
