### ISSUE TITLE
Conflict with ScaleManager.USER_SCALE and visibility change

### ISSUE THREAD

**Issue by Scraft** [photonstorm/phaser#2663]
I am using ScaleManager.USER_SCALE to perform the following constraints:
- Ensure canvas size matches window size
- Scale the game up/down, proportionally, to maximise the window size
- Centre the game

During normal play this is working exactly as intended, however when the game loses focus, everything on screen is offset (typically up and left). I have made a cut down example of just a single sprite on screen and confirmed the issue still occurs there (attached).

[bootstrap.zip](https://github.com/photonstorm/phaser/files/379762/bootstrap.zip)

I have noted that if I set disableVisibilityChange to true, the issue goes away, however I do not want to do this, as I use the visibility change pause/resume callback to show/hide the games pause menu.

Here is a screen shot when the game is in focus:
![Image of focus](https://camo.githubusercontent.com/8891ec50cc1288d3e7287ef15b658bafba927195/687474703a2f2f67616d65736465762e636f6d2f74656d702f666f6375732d7363616c652d6275672f73637265656e73686f74732f5363616c65427567496e466f6375732e706e67)

Here is a screenshot when the game doesn't have focus:
![Image of focus](https://camo.githubusercontent.com/83cca2fde3e355efa4f7b64ed46e2e86fdd785fa/687474703a2f2f67616d65736465762e636f6d2f74656d702f666f6375732d7363616c652d6275672f73637265656e73686f74732f5363616c654275674f75744f66466f6375732e706e67)

Please note, when switching to another application, it takes a second or two for the focus change to kick in (on Chrome at least).

**Comment by AleBles** [comment]
This is not behaviour I've encountered before, and you're images are not working anymore, is it possible for you to also share your ScaleManager code?

Also what kind of behaviour are you seeing on other browsers?

**Comment by Scraft** [comment]
My appologies; I seem to have zipped up the wrong file - the zip file should have contained everything required to replicate this issue. Tonight I will get the right files zipped up and get them attached. In terms of browers, I mostly use Google Chrome; but I will also confirm tonight if this issue exists on IE too.

**Comment by Scraft** [comment]
Okay, here is an example of it going wrong (tested in Chrome and Internet Explorer):

http://gamesdev.com/temp/focus-scale-bug/example/

The full source code is here:

http://gamesdev.com/temp/focus-scale-bug/src/focus-scale-bug.zip

And the infocus screenshot:

![In Focus](http://gamesdev.com/temp/focus-scale-bug/screenshots/ScaleBugInFocus.png)

And out of focus screenshot (you have to wait for a second or two sometimes):

![Out Of Focus](http://gamesdev.com/temp/focus-scale-bug/screenshots/ScaleBugOutOfFocus.png)

**Comment by AleBles** [comment]
So the main thing I see here is that you resize the game in the setResizeCallback.[ setResizeCallback is called always after the game resized](http://phaser.io/docs/2.6.1/Phaser.ScaleManager.html#setResizeCallback), so effictively you are looping this piece of code every x ms.

Now this is all nice and it appears to work correct when the game is in focus, but appearantly there is something in the browser going on that will misplace the game when it goes out of focus. From what I can see is that your resize is still called when out of focus, and to me it appears that Phaser is unable to correctly calculate the width.

For me the easiest fix is instead of using Phaser's built in mechanics the way you do (which is wrong due to the infinite loop you're causing) is to use the browser's built in events for resizing.

effectively replacing:
```javascript 
this.game.scale.setResizeCallback(function () {
    thisPtr.resizeGame();
}, null);
```
with:
```javascript
window.addEventListener('resize', function () {
    thisPtr.resizeGame();
});
```

**Comment by Scraft** [comment]
Thanks, this makes quite an improvement, and explains why my previous workaround seemed to do the trick:
`if (!force) {
    if (this.lastWindowSize != null) {
        if (this.lastWindowSize.x == window.innerWidth && this.lastWindowSize.y == window.innerHeight) {
            return;
        }
    }
}`
One thing I do note; even with your suggested fix, when I hit F12 in Chrome (to bring up the developer tools, which for me appear docked at the bottom of the screen), I end up with the game off the left edge of the screen **until** I click on the game screen, at which point it fixes itself up. It isn't a major problem; I presume it will happen in my previously linked to example case (when your suggested fix is made). If this issue is worth looking into I am happy for this to be kept open; I am also happy for this to be closed if you are happy with the current state of affairs.

**Comment by hilts-vaughan** [comment]
The game is technically paused at that point -- that's probably why. Try
dissing pausing when focus is lost and see if it fixes itself (the dev
tools thing)

**Comment by Scraft** [comment]
It doesn't appear to be paused (indeed I wouldn't expect it to be, and it doesn't appear to be on any page I try, including this GitHub comment page). Assuming we are talking about the same thing.

**Comment by Scraft** [comment]
Notably; the problem doesn't happen when the following is set:

```javascript
this.game.stage.disableVisibilityChange = true;
```

Which is something I noted from the start.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
