### ISSUE TITLE
getBounds + getLocalBounds discussion

### ISSUE THREAD

**Issue by photonstorm** [photonstorm/phaser#2667]
I want this open as a proper issue here, so we can discuss it properly, without it being attached to a commit note.

Here is the discussion so far between @fmflame and @namark:

https://github.com/photonstorm/phaser/commit/483a3b6836358bc5c9df48d8ff2d52e8cd9609db#commitcomment-18407087

@namark yes getLocalBounds should not account for parent transformations and I believe this is how it works right now. If you look at what happens in this.getBounds(this.parent); with this.parent, you will notice that the parent gets a temporary blank matrix (PIXI.identityMatrix) and then we are updating the transform of its children. This is not seen here cause I think we are commenting on an outdated commit - there are more fixes in the next ones - so check them out to see what I am talking about. Plus I just posted an additional changes today. Everything should be working perfectly for DisplayObject/DisplayObjectContainer. And for Sprite, Strip and Graphics - it should work the same as before with the latest fix - I do think it is not working as it should and that there are issues with them but they are from before and I don't have the time to fix them at this point in time.
Anyway, if you are having issues it is very possible that with the new fixes old calculations you did would be invalidated and you should rewrite since they weren't correct in the first place. But what you are asking - does work as you say. There is difference in how the code gets bounds and updates transforms. I have provided examples and I tripple checked with similar libraries of how getting bounds should work so I doubt there is a mistake at this point.
this.getBounds(this) -> should return the untransformed bounds of the DisplayObject for e.g if you have a graphic (0, 0, 200, 100) with scale = 2, it would return (0, 0, 200, 100). If you want to get the bounds of the object with it's transforms then you would call this.getBounds(this.parent) and the result would be (0, 0, 400, 200), which is the local bounds of the DisplayObject - meaning it's the bounds it has in it's local coordinate, which is in his parent's coordinate, including it's own (not parent's) transforms. 
So I do believe what I did is the correct way of how this should work. Please check if you have the latest fixes pulled @photonstorm already merged them all and it's possible you'd have to updated your logic to work with the changes. If you are having further questions or doubts if things should work the way I changed them - please provide me with some examples and logic/reasoning behind them of what you'd expect. You can also check the examples I've provided in the PR description - IncorrectDisplayObjectDimensionsDemoFixed_v2.6.1 is updated with the latest changes and fixes for this.
https://github.com/photonstorm/phaser/commit/483a3b6836358bc5c9df48d8ff2d52e8cd9609db#commitcomment-18412303

@fmflame I am on the latest dev branch, and this is the relevant change for getLocalBounds method, I believe.

What I meant is that this "this.getBounds(this) -> should return the untransformed bounds" is exactly what getLocalBounds used to do, and I don't see anything inherently wrong with that. So what if other libraries do it differently? Logically I see no reason why, say, the object's position in its parent, should in anyway affect its "local" bounds.

But even if you are willing to introduce this change, the way things are now, since you effectively reverted the method for some objects in a later commit, there is a major inconsistency. Just create an Image object and observer the local bounds(meaning what getLocalBounds returns). No matter how you transform it (position/scale/rotate) the local bound remain the same. Do the same with, say, BitmapText, and local bounds will change with the transform. If nothing else this would be a nightmare to document. This is not how things used to be, and for me, frankly, it is easier to adjust a single line of code in my fork, instead of restructuring my entire project... just thought to point this out...

**Comment by fmflame** [comment]
Ok I understand what you are saying and you have a point. But it is not that what I did wasn't right. For me the bigger issue was that in getLocalBounds you weren't getting the transforms of the object. And later on you get width of the object and what it used to return was scale * getLocalBounds() and then what about rotation ? So if I am getting you right what you kind of imply is that we should roll back the changes so that your code starts working the way it did before the changes (and possibly before 2.6.1 I guess cause it included a flawed change for this there as well). This is definitely not the right approach and I completely agree that for Sprite, Strip and Graphics it will work inconsistent and this point cause I actually changed nothing for them - but this inconsistency comes from the fact that their getLocalBounds and probably, getBounds and getting width or height are also bugged in my opinion and don't work correctly the way they should for these components. I just cant' afford the time to take a look at fix them as well. Even writing this takes too much from my precious time. I was planning to take a look at them as soon as I have some spare time and fix them as well, which would make things be and work consistent and correctly. But you see I am just a man and if you see this inconsistency right now, you could help fix it and the Phaser team as well. It's my preference that I would rather have something working correctly rather then everything to be broken. And by the way if you do need localBounds working correctly for those components, I think putting them in a Group would solve your issues with them for now cause, their getBounds should be working just fine and you could manager the group instead of them if you have a case of needing to use getLocalBounds or if you'd like to get the width and height taking into consideration the rotation. 

So I believe what we should do at this point is find the proper fix for Sprite, Strip and Graphics getLocalBounds(), width and height. And all problems will be solved.

**Comment by fmflame** [comment]
Just to let you know I updated the text I wrote in the previous comment, please make sure you read the last version of it! Thanks

**Comment by namark** [comment]
Noo, I didn't mean to revert anything... just make the getLocalBounds return `this.getLocalBounds(this);`... and everything should work the way it was before... at least for me it does... I'll make a pull request...
It's just a matter of how you define local bounds, and I think there is no right or wrong here, in terms of logic. Nothing was broken. It was just different. You understand local coordinate system to be the parent's coordinate system, while Phaser considered the object's own coordinate system(where it has no transform) to be local. I see no practical reason for changing this behavior and breaking existing code, since now you can use getBounds to get what you wanted.

**Comment by photonstorm** [comment]
I think part of the problem is the ambiguity of the term 'local'. It can literally mean multiple things. Local to the parent, or local to the stage space (which is how Pixi used to define it).

**Comment by photonstorm** [comment]
Thinking about it, I guess this is why most frameworks have just `getBounds` and then you can use `localToGlobal` and similar methods to transform them.

**Comment by namark** [comment]
#2668 It's really tiny.

And yes the term is ambiguous, but it was what it was for all this time, why change it? The new super `getBounds` method, covers everything now, thanks to @fmflame, so the getLocalBounds change really accomplishes nothing but breaking existing code.

**Comment by fmflame** [comment]
No, I definitely do not agree with you. And your PR will break the proper working of the components and the retrieved dimensions.

I will ask you this question - if you create an image and it has 200 width and 100 height and scale 2, what would you expect getting width or height to return? shouldn't it be 400 and 200? With your PR, you're making them return 200, 100 which would be incorrect. And what if you add rotation to that. My code will return the proper exact size taking into account the rotation, while your code will still return 200, 100. I know what you are trying to do is patching it so your code doesn't break with the Phaser update. And breaking the correctly working code isn't the right way to do this.

@photonstorm I do know PIXI at least in this build you have of it used to return this.getBounds(this) like @namark  says, but I do belive local should mean local not inside the component or the component to itself, it just doesn't make sense. In most cases you wouldn't position or adjust another component to yours depending on it's local size, so this is generally useless in most cases. But I do understand the reasoning behind if you'd wanted to keep the getLocalBounds() return this.getBounds(this) to preserve how it was working until now. I am comming from other languages and frameworks and with my experience I did the right thing updating this the way I did and I think sometimes people should understand a change is necessary when it makes sense. But anyway if you decide that you want to preserve how getLocalBounds() work, then yes change the line from this.getBounds(this.parent) to this.getBounds(this), but then go to width and height and change them to not get their values from getLocalBounds(), but from this.getBounds(this.parent) instead. Still I am not supporting this decision but if you wanna do it, then add this to his PR so you don't break the width and height.

**Comment by fmflame** [comment]
Actually on the other hand, it does not matter to me how you'd want it to be. Just let me know what getLocalBounds you'd like to return and I will make the changes. I googled a bit so there are different implementations for this. So both options are ok in my opinion. I even think that maybe it will be better to leave getLocalBounds() as @namark said to work as before for consistency. Just say the word @photonstorm .

**Comment by fmflame** [comment]
Oh and one more thing. We still have to think of how to fix PIXI Sprite, Sprite, Strip and Graphics getBounds(), width and height, cause they currently do not account for rotation. I will take a look at it when I have the time. For now @photonstorm  just let me know if you'd like me to revert getLocalBounds() to return the this.getBounds(this) or keep it as is. Thanks.

**Comment by namark** [comment]
@fmflame About the width and height accessors... thanks for pointing out!
In my understanding they just represent the dimensions of the object as a rectangle, not its bounds. Accounting for rotation makes little sense here, and for few cases where it would be useful, you can use getBounds. They accounted for scale, since that was the only way to set the width and the height, as I understand. 
Also, while in your case they will return the right rotated value, setting a value will be broken and inconsistent with what you get. An obvious example would be an object rotated by 90 degrees. Change it's `scale.x` as much as you want, the width of the bounds will not change, only the height would. So, from outside perspective, you can keep setting the width property without it ever changing, since it only modifies `scale.x`, while your rotated object would perform confusing shenanigans. 
That can be fixed of course, but is it worth it? Where would you really need the width and the height of an object to account for the rotation? Any common use cases? And once again you are breaking existing behavior. 

Some things are just different in Phaser from what you would expect, coming from, say, Starling framework, but in my experience many of those are more practical/useful, even if not "text book" correct :)

And yes I'm closing my pull request, in shame...

**Comment by photonstorm** [comment]
I think it would be best if `getLocalBounds` worked as it did in Phaser 2.6.0 and before, and `getBounds` is the new, more flexible and accurate one, as currently merged in dev.

`width` and `height` shouldn't be based on the bounds (either local or global), this is correct. You should consider them as being the texture dimensions, but taking local scale into account.

**Comment by fmflame** [comment]
I created a new PR with the changes we discussed: #2671
But still since I am not happy with it, here are my thoughts on this:


I dislike having to make this change, I would rather fix the remaining components to work with the new approach. 

So although I understand it's PIXI compatible and that there are different approaches to what getting local/global bounds or width/height would return. But to me getting the width of the object which would take into account the scaling but not the rotation is just broken. I come from flash/flex/starling and those guys are just smarter in my opinion and this solution to me is just a step back for Phaser. I believe the approach PIXI has to this isn't the better one and if you reconsider about it, I would be happy to help transition to the more advanced approach meaning:
- getLocalBounds() to return the local bounds of the object plus all transformations to it;
- if you wanted to get the local untransformed bounds for some reason you could to this.getBounds(this);
- getting width and height would return the this.getLocalBounds();

The biggest difference these two approaches have is that getting width and height with the better approach would work consistent and would return the real width and height based on all transformations on the object. While on the other hand the old PIXI's approach will calculate only the scaling and will leave out the rotation and for me it just doesn't make sense you would calculate one transformation and would leave out others. If we transition to the better approach positioning of DisplayObjects that are scaled/rotated would be straightforward using just width and height as usual and they would be perfectly aligned, while with the old PIXI's approach you would have to know you need to use getBounds() so you are returned the correct width and height dimensions - for me this is an inconvenience.

Again, If you people decide to transition to this new approach count me in, I would help if you need me to. Thanks for the discussion.

**Comment by photonstorm** [comment]
The biggest problem `width` and `height` have is that Pixi uses it as a means to _set_ the scale on the object as well. Adjusting the width of an object adjusts its scale.x value accordingly. Right or wrong, this is such a common convention now, that to break it would cause untold grief.

The other thing it does (on Sprites at least) is to just read the texture width and return that, with the scale applied to it. This is a computationally really cheap operation, just the sum of two numbers. Because of this the getters for width/height are used a lot both internally, and outside. Dropping a bounds call into those getters would be extremely detrimental, unless it was aggressively caching its bounds (which it could do, but doesn't right now).

It's not the sort of change I can make in a point release, it would need to wait for a major version, because it fundamentally alters things.

**Comment by fmflame** [comment]
@photonstorm I do understand the implications and you are absolutely right with all of your arguments. I would love to see that in a major version someday. It's good to know just that the idea for this is on the table :) Thank you. I think we can wrap up this topic.

If you would allow I would also use this moment to ask about 2, I cannot say new features, but two small to medium alterations:
1) When extending right now I am limited with 3 base properties in DisplayObject and they are - position, scale and pivot and anchor in Sprite. They are declared as public properties. What I need them to be - is defined with getters and setters which would set a protected properties of _position, _scale, _pivot and _anchor. The reasoning for this is for me to be able to extend and override them if I wanted to. Because it turns out I do in some cases and I just can't do it, because I am essentially overriding with getter and setter and when we are missing the internal _scale and I point with the getter and setter to another child component's scale for example, when I set it's scale and then the getter gets it, both the child component and the component I am overriding will point to the same scale value - the one from the child component. Which is not what I want, I want the scale of the Group to be left unchanged taking it's value from the internal _scale value - which at this point does not exist.

And even more than that. I also think that it will be best if position, scale and pivot are not a Point.
They could just as easily be scaleX, scaleY, positionX, positionY, pivotX, pivotY, anchorX and anchorY - separate number properties with getters and setters. This way If I wanted to override what happens to the internal components when we change any of those values I could do that. This would provide me a maximum freedom. Right now how do you do that? I create separate properites/methods to go around this limitation. We should not be limited - viva la freedom! :)

2) I would love to see a component in Phaser which I can extend creating new components, but something different than Group, which is what I use now. The issue here is that this component does a lot more stuff for managing children and if for example I wanted to create a ToggleButton with a dynamic text label for example (which I am doing now), I extend Group to get some Phaser goodies. But as you can imagine I don't need all of that functions for managing lots of children so I end up with a base class which is way too bloated. It would be nice if that functionality for managing children could move up into another component that extends group and keep Group as a base component whatever it is you want to make.

Ok so along with the big topic we discussed today, these are the other two major things  I am having issues with when working with Phaser. And I think it's not that difficult to make these changes happen and they will have great value to us coders. So I'm guessing separating Group into a base class and a children managing class would not break anything, people would possible only have to replace the class they are extending from? But for the scale, position, pivot and anchor I'm guessing you would consider only for a major version.

I really wanted to put these improvement ideas on the table as well. It's not a problem for me to help with this work if needed, but would really love to have these changes for the sake of freedom and extensibility purposes.

I could also post these as an issue Feature Request if you think that will be best for now. Please let me know what you think. Thank you!

**Comment by photonstorm** [comment]
What I've got on the roadmap is a Transform object, which every class will then have. It will contain all of the transform and bounds related functions, scaleX, positionY, and so on. We can then remove all of those from the core display objects. This will serve three purposes, first it will clean up the classes a lot, secondly it will remove the need for things like Observable Points, and finally it will allow devs to easily replace the Transform component with their own.

Right now I want to focus on getting 2.7.0 released, with the new batching and tilemap stuff in. Then we're swapping to Phaser 3.0.0 development, which can include fundamental changes to the structure and base classes.

**Comment by fmflame** [comment]
Awesome! Sounds even better than what I had in mind and described above :) Can't wait.

**Comment by photonstorm** [comment]
Going to close this off, as the updates are merged now. Please keep an eye on the repo though, as when I introduce the Transform class, it'd be great to get your feedback on it.

**Comment by fmflame** [comment]
Ok Great! No problem :) If I miss it somehow, you can always write me though - it would definitely be interesting for me to check out :)

**Comment by photonstorm** [comment]
I've noticed a very strange issue, which I'm sure it a result of these changes: For the first frame of a Sprites existence, it appears at 0x0 and flashes up there briefly, then moves into its right place. For simple objects this doesn't matter too much, despite the visual glitch, but for physics objects it often makes them embed into each other.

I need to debug this further, to remove both issues, before I can release 2.6.2 - but figured I'd add a comment here in case anyone could shed some light on it quicker than it takes me to wind through it all.

**Comment by photonstorm** [comment]
Ok the physics issue is unrelated, but I'm still definitely seeing strange flashes of Sprites in incorrect positions for 1 frame. Debugging further now ...

**Comment by fmflame** [comment]
Hmm well, in order to calculate proper bounds, sometimes, like with getLocalBounds(), the transform is reset for a parent and then reapplied, but it's weird cause it worked with the same idea even before changing the code a bit. I am building a 2D no physics game right now and I am not seeing any flashes with my build - which includes only the changes I created as PRs here. If you want I could give you my phaser.js file for you to test out and be certain this is not caused by something else ?

**Comment by photonstorm** [comment]
It's fine, it's my issue to figure out. I'm trying to create a test case that demonstrates it consistently, but if you look at [this example](http://phaser.io/examples/v2/text/bitmaptext-max-width), for me under 2.6.2, very often I see a large scaled version of the text character appear in the top-left of the game, before it appears in the correct place in the line.

In another project I've got a sprite that appears on mouse-over, which is scaled and rotated, but has a quickly flash of 'unscaled / positioned / unrotated' in the middle of the game. Both are canvas only, so it's not a WebGL thing, and neither happen with 2.6.1.

I think it might be event related. The bitmap text example displays based on a timer, and the rotated one based on a mouse event. It's as if they're created out of sync with the game loop, and appear strangely for a frame.

**Comment by fmflame** [comment]
That seems to be tough to chatch... I am currently traveling, but if I happen to find time to check it out (with this helpful guidelines you've provided) and do some debugging I will and will let you know if I find something. Otherwise good luck figuring this one out!

**Comment by namark** [comment]
I'm on a41f62a37a5ea1802ba9a51bbdd034e7e9392661, using bitmap fonts a lot, modifying their text based on keyboard events, and didn't notice anything like that, so far. I'll update my fork tomorrow and see if that makes a difference.

**Comment by photonstorm** [comment]
I'm starting to think this might just be a Canary glitch. It's such a pain in the ass to debug! More investigation tomorrow.
