### ISSUE TITLE
[TypeScript] compile error on TypeScript version 2

### ISSUE THREAD

**Issue by wingyplus** [photonstorm/phaser#2674]
This Issue is about (delete as applicable)
- An error in the TypeScript defs

In example

``` typescript
/// <reference path="./phaser.comments.d.ts" />

class MyGame extends Phaser.Game {
}
```

Expect:

No errors

Actual:

When I compile with TypeScript version 2. it throws an errors

``` bash
$ tsc --version
Version 2.1.0-dev.20160731
$ tsc ./phaser-test.ts
p2.d.ts(255,44): error TS2690: A class must be declared after its base class.
p2.d.ts(268,42): error TS2690: A class must be declared after its base class.
p2.d.ts(598,34): error TS2690: A class must be declared after its base class.
p2.d.ts(607,33): error TS2690: A class must be declared after its base class.
p2.d.ts(615,33): error TS2690: A class must be declared after its base class.
p2.d.ts(634,38): error TS2690: A class must be declared after its base class.
phaser.comments.d.ts(2495,26): error TS2690: A class must be declared after its base class.
phaser.comments.d.ts(2519,26): error TS2690: A class must be declared after its base class.
phaser.comments.d.ts(6912,29): error TS2690: A class must be declared after its base class.
phaser.comments.d.ts(15430,28): error TS2690: A class must be declared after its base class.
pixi.comments.d.ts(1784,31): error TS2690: A class must be declared after its base class.
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
