### ISSUE TITLE
Flickering when drawing Groups to RenderTextures

### ISSUE THREAD

**Issue by hexus** [photonstorm/phaser#2677]
This issue is about Pixi, as far as I can tell. I've been able to reproduce it as far back as 2.4.8 (it likely exists in many earlier releases too).

In a game I'm developing, I'm rendering a group of objects to a texture as an occlusion map for a lighting engine.

However, since I've added particles to the mix I've noticed some inconsistent results, specifically a flickering of the texture. This throws off my shadow mapping.

I have reproduced the issue in a little Phaser Sandbox example:

http://phaser.io/sandbox/fGDghJLL/play

![phaser-render-texture-issue](https://cloud.githubusercontent.com/assets/2626789/17298415/e324c62c-5801-11e6-8223-8f6fb0c85108.gif)

And the effect this has in my game engine:

![phaser-render-texture-issue-2](https://cloud.githubusercontent.com/assets/2626789/17298585/7467acb2-5802-11e6-9b68-5ce16832c6ed.gif)

I have a suspicion that this is caused by the bounds of the group changing regularly as the particles travel.

Another issue highlighted here is the texture being rendered upside down, which I've had to cater for in shaders later on in my rendering pipeline. A minor inconvenience, but if they were consistently the right way up I could clean up my shaders a little.

**Comment by hexus** [comment]
After having a little read of this:
http://webglfundamentals.org/webgl/lessons/webgl-2d-matrices.html

And seeing this demo (resize your browser to see the effect):
http://webglfundamentals.org/webgl/webgl-canvas-clientwidth-clientheight.html

I am more sure that this issue is caused by the bounds of the group and how it's rendered.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
