### ISSUE TITLE
cacheAsBitmap cuts off

### ISSUE THREAD

**Issue by kamilsobieszuk** [photonstorm/phaser#2679]
http://phaser.io/sandbox/PleptNUq

Phaser cuts off text (and other groups of objects) depending on their x and y position.

In example you can see that text on 0x0 is fine, 25x25 is cut in half and 40x40 is completely invisible.

In version 2.5.0 everything worked fine. It might be related to different x and y that are returned by getLocalBounds in newest version.

**Comment by photonstorm** [comment]
Thanks for spending time reporting this issue. However we've already fixed this in the `dev` branch of Phaser, and it will be part of the next official release. You can track what's already been fixed by looking at the Change Log part of the [dev README](https://github.com/photonstorm/phaser/tree/dev#change-log) file.
