### ISSUE TITLE
Ellipses don't always "sense" onInputDown event

### ISSUE THREAD

**Issue by Siri0n** [photonstorm/phaser#2680]
Example: http://phaser.io/sandbox/wPzGvzJM (ES6, works in latest Chrome)
Expected behavior: when clicking on white circle, message appears in console.
Real behavior: it works only sometimes, sometimes message doesn't appear in console.

On simpler examples it works fine, but in that particular project it isn't. I'll try to narrow down a situation when that bug occurs.

P.S. Sorry for my English.

**Comment by Siri0n** [comment]
More sophisticated example:
http://phaser.io/sandbox/iWxszjfC/play
I've found that it's trouble with drawEllipse method, not with a whole Graphics object.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
