### ISSUE TITLE
The trouble with right mouse button in Maxthon browser

### ISSUE THREAD

**Issue by zonex5** [photonstorm/phaser#2701]
Right mouse button does not work in the browser Maxthon and Nitro. The following code displays in any case 'left mouse':

```
game.input.onDown.add(function (p) {
     if (game.input.activePointer.leftButton.isDown) {
          console.log('left button')
      }
     if (game.input.activePointer.rightButton.isDown) {
           console.log('right button')
      }
}, this);
```

In other browsers everything works correctly.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
