### ISSUE TITLE
World x/y does not work (example included)

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#2703]
* A bug in the API

http://phaser.io/sandbox/edit/qGrKzXHd

In this example, I have 3 sprites: SpriteA, B and C. 

C is child of B and B of A. If you try and make an "x" appear on top of sprite C by adding it to the game world as a sprite at the world x/y of C, the x appears very from the sprite. The only time "x" appears on top of the sprite (using world x/y) is if the child sprite is a direct descendant of the game world (i.e. it is like sprite A and is not the child of another sprite). 

Is this a bug in Phaser? Either way, how can I can get absolute world x/y?

**Comment by photonstorm** [comment]
Like I said in the forum post, you can never get the world position until the display list has been updated. And to get the position, use `worldPosition`, like this:

```
function create() {

    var spriteA = game.add.sprite(100, 100, 'phaser');
    var spriteB = game.add.sprite(30, -15, 'phaser');
    var spriteC = game.add.sprite(30, 30, 'phaser');
    
    spriteA.anchor.setTo(.5);
    spriteB.anchor.setTo(.5);
    spriteC.anchor.setTo(.5); 
    
    spriteA.addChild(spriteB);
    spriteB.addChild(spriteC);
    
    spriteA.angle = 30; 
    spriteB.angle = 90;
    spriteC.angle = 10; 

    game.stage.updateTransform();
    
    var x = game.add.sprite(spriteC.worldPosition.x,spriteC.worldPosition.y,'x');
    x.anchor.setTo(.5);

}
```

**Comment by ForgeableSum** [comment]
I didn't see a response to the forum post. You're talking about this one?

http://www.html5gamedevs.com/topic/24535-how-to-calculate-absolute-world-xy-without-using-world-xy-property/?page=2

I tried this method. If the camera is not at 0,0, you need to add the camera coordinates. then the camera coordinates will throw everything off based on where the camera is positioned (my camera moves a lot). Sometimes it will be okay but it all depends on where and how much the camera is moving. Also tried all these before getting the coordinates:

    game.stage.updateTransform();
    game.world.updateTransform();
    gameObjects.updateTransform(); (Phaser.Group all my game objects belong to)
    msprite.parent.updateTransform();
    msprite.parent.parent.updateTransform();
    msprite.updateTransform();
    game.camera.update();

No dice.

**Comment by ForgeableSum** [comment]
Actually, I've gotten it to the point where it works 99% of the time, but every so often, when I add the camera x/y, and the camera is moved very far from the sprite, the coords will show up near where the camera is, very far from the sprite.

**Comment by photonstorm** [comment]
The camera position is irrelevant to the `worldPosition` property:

http://phaser.io/sandbox/edit/xSRRSTQS

This is your example, expanded a little, and I see nothing wrong with the placement of anything. It's all relative, to each other, within the world, and looks fine.

**Comment by ForgeableSum** [comment]
I've just discovered that it only happens if you rapidly move the camera a large distance. Example:
http://phaser.io/sandbox/edit/YfZgjVWA

I've also discovered if you put a slight delay (e.g. 10 milli with setTimout), worldTransform will show the correct results (so long as you add the camera x/y). Why is this? Is this the best workaround? 

Another difference between my example and yours is that I have need to constantly re-calculate the coordinates after the game has restarted (as parents are moving and rotating). Hence why I need to add camera.y/camera.y. 
  

Thanks!

**Comment by photonstorm** [comment]
No you can't do it with `setInterval` like that - that is adjusting the camera _out of sync_ with the game loop, so sometimes it'll happen before the display list updates, and sometimes it won't, so the results will be erratic. The only difference it makes is that it guarantees a render loop has taken place, so the full transform has happened, all the sprites updated, the camera taken into account, etc.

If you do anything out of bounds - i.e. from a callback or a timer, including trying to calculate the position of an adjusted object, it'll sometimes be correct, sometimes not. The `worldPosition` property is literally the position of the sprite within the world - not on the screen. It doesn't matter how much, or how far, your camera moves, or where the camera even is, it's still just the position of the sprite in the world. Depending on _when_ you read it, depends on if it takes an adjusted camera position into account or not though. Hence the whole issue with the loop and performing calculations out of sync.

**Comment by photonstorm** [comment]
To summarise:

1. If you adjust the camera position, and then immediately do an `updateTransform`, it won't make any difference to the results - because the camera is only factored in during the game loop, not the transform loop.

2. If you parent a sprite with another sprite, and want to position it based on its world position, then you do need to update the full stage transform first. Not just the parent, or the group, but the whole stage, because it iterates down. If you need to factor in the camera position to the position as well, and the camera _hasn't_ been changed via code since the last game loop, then it'll work. If the camera has been moved, it won't be factored into the position.

3. You can use the `postRender` function if you need to position something _after_ the camera, and all the transforms, have happened. You cannot adjust the camera in this function and expect it to influence positions though, but you can read world positions and they'll be accurate, with the correct camera offsets etc, providing you haven't gone and changed the camera again since the game loop took place.

4. Callbacks and Timer events, and anything out of sync with the main game loop, are never guaranteed to be able to read the current position values accurately. Sometimes they'll be right, sometimes not. It all depends on when they occur with regard to the point the game loop is in at that moment in time.

**Comment by ForgeableSum** [comment]
I knew it wasn't a permanent solution. In my game, the camera can jump because if you click on the mini map, the camera jumps instantly to that location. The camera is also constantly moving when a sprite is being followed as well.

I'm sure there is some kind of trick I can use as it's an issue of timing. How does one update the "full stage transform"?

I'm glad we got to the bottom of it even if the solution isn't clear yet.
