### ISSUE TITLE
2.7.0 multi-texturing more calls than 2.6.1?

### ISSUE THREAD

**Issue by Cristy94** [photonstorm/phaser#2706]
I have tried switching to the 2.7.0 dev branch hoping for improved performance, but it made it worse (from 40 GPU calls to over 100, it's passing the same uniform before each draw call)

This is how the GPU calls looked in 2.6.1:

![capture2](https://cloud.githubusercontent.com/assets/1384885/17809270/06a1ebb4-661e-11e6-9389-33c57d5028c6.PNG)

And this is how to looks in 2.7.0 (the same with or without using setTexturePriority):

![capture](https://cloud.githubusercontent.com/assets/1384885/17809292/24cdb726-661e-11e6-86ca-d20fa4883e04.PNG)

**Comment by photonstorm** [comment]
Thanks for opening this issue. As much as we'd love to help you, we need a fully working code sample to do so. Please provide one and then we'll re-open this issue and look at resolving it for you if possible.

If it's easier you can use the [Phaser Sandbox](http://phaser.io/sandbox/) to create a code sample (as this is now running the latest build of Phaser). Enter your code, click the 'save icon' in any of the editor tabs, and paste the URL here.

**Comment by Cristy94** [comment]
See those two links:
https://fiddle.jshell.net/k5xwvtg1/10/show/light/  - v2.6.1 - **24** GPU calls (not necessarily draw)
https://fiddle.jshell.net/k5xwvtg1/11/show/light/  - v2.7.0 -  **39** GPU calls

I think what is "special" about this example is that the sprites are in a group that has an offset.

**Comment by photonstorm** [comment]
The two links above don't match the GPU call screen shots above for me, which I guess were taken from your actual game, rather than the linked examples?

I can't see anything wrong in the two linked examples, because there is only one texture being used, so nothing for multi-texturing to take advantage of. In that instance I'm seeing a couple more GL calls to set things up, but the overall amount of draw calls is identical, because there's nothing for it to do.

Multi-texturing comes into its own when there are, quite simply, multiple textures being used.

I've moved all the texturing stuff out of the dev branch for now, until 2.6.2 is released. Then I'll merge it back in and revisit this.

**Comment by Cristy94** [comment]
Yes, the links above are a simplified version of what happens in my game. A couple more GL calls to set things up add up, and in the case the GPU call log looked twice as big with the new version (performance wise the game still stayed at 60FPS so I don't know if it was better or worse). I was wondering if it's normal for the same uniforms with the same values to be sent before each draw call?

**Comment by Cristy94** [comment]
And for example, on Safari or Chrome on iOS the FPS drops to 28fps (if no setTexturePriority is used) and if I try to use setTexturePriority some larger spritesheets (1024x1024) display as a solid pink color instead of their actual textures.

With the 2.6.1 the game stays at 50+ FPS

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/phaser-v2-6-2-es6-port/12507/3
