### ISSUE TITLE
Feature Request - common onUpdate method for all animations of a Sprite

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2710]
Currently, to have a function fired upon each animation update, you need to do this:

```
var spr = game.add.sprite(0, 0, "something");
var anim = spr.animations.add("run", [0, 1, 2, 3], 6);
anim.enableUpdate = true;
anim.onUpdate.add(someFunc, this);
```

However, things get silly when you have 10 animations and they all need to fire the same `onUpdate` function. A lot of redundant code suddenly appears.
My suggestion is to have an `onUpdate` event on the Animation Manager itself and make this possible:

```
var spr = game.add.sprite(0, 0, "something");
spr.animations.add("run", [0, 1, 2, 3], 6);
spr.animations.add("stand", [4, 5, 6, 7], 6);
...
spr.animations.enableUpdate = true;
spr.animations.onUpdate.add(someFunc, this);
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
