### ISSUE TITLE
Phaser.Text destroy crop bug

### ISSUE THREAD

**Issue by Extersky** [photonstorm/phaser#2716]
This issue is about a bug in the API.

When a Phaser.Text object is deleted using .destroy(), a subsequently created Phaser.text object will effectively become invisible when cropping is applied using the crop function. 

Examples:
https://jsfiddle.net/5xjLb7fm/
A text object created and cropped after destroying a text (text2) causes the created text (text3) to not be visible. Another text created after this will be visible. The text created before the text to be destroyed remains visible.

https://jsfiddle.net/4zwm779e/
After creating, destroying and recreating equal amount of text objects, none of the recreated texts become visible. I noticed that when more texts were created after the deletion, the last items will be visible. For example, after creating and deleting 2 texts and then creating 4 texts, the last two texts will be visible.

During the updateCrop call of the hidden texts the frame and size will both have width 1 and height 1.

This can be reproduced with at least 2.6.1 and 2.7.0 beta 3.

**Comment by photonstorm** [comment]
Definitely a bug. And a very weird one. Almost certainly to do with the Canvas Pooling that Text objects use. Will investigate.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
