### ISSUE TITLE
Feature Request - zero duration tween

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2719]
It feels really strange when you set the duration of something to 0 milliseconds and it suddenly defaults to 1 second. I don't understand that thing with tweens and it becomes uncomfortable sometimes.

If I want to animate something, but in some cases I want it to happen instantly (when initializing it or respawning it for example), I have to deliberately check whether I want it to happen at once and just change it's value, or use a tween.

It's logical to have a default value of 1000 milliseconds when the input is a negative number (since you can't do something for negative time because real world physics and stuff). But why that behavior with 0 milliseconds input?

In my opinion it's going to be a lot more comfortable and logical if this:
`game.add.tween(prop).to({x:10}, 0, Phaser.Easing.Cubic.InOut, true);`
simply does this:
`prop.x = 10;`
and then calls the `onComplete()` functions, etc.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
