### ISSUE TITLE
Add examples for extending Phaser.Weapon

### ISSUE THREAD

**Issue by the-kid89** [photonstorm/phaser#2727]
When I have KILL_DISTANCE set the bullets just never die.

```
Weapon.MeleeAttack = function (game) {
    Phaser.Group.call(this, game, game.world, 'Single Attack', false, true, Phaser.Physics.ARCADE);
    this.bulletKillType = Phaser.Weapon.KILL_DISTANCE;
    this.bulletKillDistance = 32;
    this.nextFire = 0;
    this.bulletSpeed = 600;
    this.fireRate = 100;
    for (var i = 0; i < 64; i++) {
        this.add(new Attack(game, 'weapon'), true);
    }
    return this;
};
```

**Comment by JTronLabs** [comment]
[Works fine for me](http://jsfiddle.net/hnLthack/11/)

**Comment by JTronLabs** [comment]
Did you discover the issue?

**Comment by the-kid89** [comment]
I still have not been able to get this to work with an extended class based on the documentation in http://phaser.io/tutorials/coding-tips-007.

**Comment by samme** [comment]
Don't use http://phaser.io/tutorials/coding-tips-007 . It's unrelated to Phaser.Weapon, which was added later. Use http://phaser.io/docs/2.6.2/Phaser.Weapon.html .

**Comment by the-kid89** [comment]
How new is Phaser.Weapon?

**Comment by samme** [comment]
It was added around Phaser v2.5. If you write your own Weapon class (like <http://phaser.io/tutorials/coding-tips-007>) you have to check and kill bullets yourself. If you use Phaser.Weapon instead then you can use `Phaser.Weapon.KILL_DISTANCE`.

**Comment by the-kid89** [comment]
I was able to get it working after you pointed out to me that it coding-tips-007 was creating the the weapon outside of the Phaser.Weapon class. It may be worth adding more examples to the Phaser.Weapon object as there really doesn't seem to be many.

I now just need to extend and I will be done.

**Comment by JTronLabs** [comment]
Feel free to add examples or update the coding tips. Glad you solved the problem, thanks @samme  Want to close the issue?

**Comment by the-kid89** [comment]
Is it okay if we leave the issue open for now. So when I get everything worked out and submit a pull request I can reference this ticket. Maybe change the title though.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.

**Comment by crossx4real** [comment]
works for me, you may have to do a hard reload in browser or clear you mem cache in order for it to work. works for me.
