### ISSUE TITLE
Arcade Physics Body setSize and setCircle seem buggy.

### ISSUE THREAD

**Issue by ColaColin** [photonstorm/phaser#2750]
* A bug in the API

Specifically I cant figure out a relationship between the sprite width/height and the values passed to setCircle/setSize that makes sense. 

See the create code and the results here: http://phaser.io/sandbox/JhEcJatZ/play

**Comment by photonstorm** [comment]
This has already been addressed by adding some further clarity to the documentation, which can be seen in the dev branch, but the most important part is:

```
    * If you've scaled a Sprite by altering its `width`, `height`, or `scale` and you want to
    * position the Body relative to the Sprite's dimensions (which will differ from its texture's
    * dimensions), you should divide these arguments by the Sprite's current scale:
    *
    * `setSize(32 / sprite.scale.x, 32 / sprite.scale.y)`
    *
```

Setting the width and height of a Sprite simply adjusts its scale values, so that it visually appears at that size, but it's still based on the underlying texture dimensions. A Sprite with a texture 32x32 that has width/height set to 128x128 is still only 32x32 in size, it just now has a scale x/y value of 4.

**Comment by ColaColin** [comment]
I am starting to realize how this works. Thanks
