### ISSUE TITLE
Sprite filters have screen-aligned coordinates in shaders

### ISSUE THREAD

**Issue by hexus** [photonstorm/phaser#2751]
As far as I'm aware, this is a bug in the API and possibly a Pixi issue. Either that, or I'm not using filters correctly.

Hasn't been fixed in dev, and the closest related issue I could find was #2320, fixed by #2326, but it's only somewhat related.

---

Rendering sprites with filters applied demonstrates that the coordinates within the shader are scaled to the screen from 0.0 to 1.0, instead of scaled to the sprite texture.

This is demonstrable in this example:

http://phaser.io/examples/v2/filters/basic

Changing `if (vTextureCoord.x < 0.1) {` to `if (vTextureCoord.x < 0.5) {` demonstrates that the filter spans half of the screen width (400px) despite the sprite being 512x512.

Using `sprite.filterArea`, `filter.setResolution` or any other workaround I've tried seem unable to have any impact on this.

Are filters meant to work this way? I need the shader coordinates to always align with the sprite, no matter where it is in the game world. It seems intuitive to me that applying a filter to sprite would have this effect.

---

**Edit:**

I have managed to hack around this for now, in my own use case, by passing in a position uniform:

``` javascript
sprite.x - game.camera.x / sprite.width
sprite.y - game.camera.y / sprite.height
```

Then, subtracting this from the UV:

``` glsl
vec2 uv = gl_FragCoord.xy / resolution.xy - position.xy;
```

Then, ignoring anything below 0.0 or above 1.0 in the shader, because for some reason if the sprite goes off camera the shader still draws at its full size in the corner but the coordinates remain correct:

``` glsl
if (uv.x < 0.0 || uv.y < 0.0 || uv.x > 1.0 || uv.y > 1.0)
    discard;
```

Apologies that there isn't a full demo of this yet, I'll eventually put one together using the Phaser sandbox.

**Comment by hexus** [comment]
I've noticed this thread on the forums:

http://www.html5gamedevs.com/topic/14917-phaser-filter-uv-coordinate-mappings/

The last three posts grab my attention. The poster is asking the same question as me, but apparently the fragment shaders are meant to output in screen space?

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.

**Comment by hexus** [comment]
EffectsLayers are going to be amazing 😍
