### ISSUE TITLE
No way to set `withCredentials` when loading resources

### ISSUE THREAD

**Issue by noseglid** [photonstorm/phaser#2753]
I am loading a few resources which will look different depending on which user requests the resources. The users are identified via a cookie which is set for the active domain. In order for the browser to append cookies, [`withCredentials` must be set to true on the XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials).

I don't see any way to set this through the Loader. Did I miss something, or is this something we can include?

**Comment by Cristy94** [comment]
Wouldn't it be easier to append some URL params to the request? Like `site.com/yourResources?user=data_from_cookie` ?

**Comment by noseglid** [comment]
There are multiple reasons why I wouldn't want to do that:

  * The cookie (which is the credentials to my site) will be a GET parameter. Risky when using copy&paste. Also likely to end up in serverside logs (e.g. apache logs)
  * I would have to manually append this, rather than having the browser do it for me automatically.
  * I would need separate parsing of the authentication on the backend side depending on which Loader I'm using (Phaser, or another resource fetcher/setter in my application).

**Comment by Cristy94** [comment]
Yeah, but cookies are in no eay safer against a hacker.Also, using CORS with credentials is not enabled by default on Safari on iOS so the users would have to manually enable that. (Settings > Safari > Accept Cookies and set 'Always') 
  On Tue, Sep 13, 2016 at 19:33, Alexander Olsson<notifications@github.com> wrote:   
There are multiple reasons why I wouldn't want to do that:
   
   - The cookie (which is the credentials to my site) will be a GET parameter. Risky when using copy&paste. Also likely to end up in serverside logs (e.g. apache logs)
   - I would have to manually append this, rather than having the browser do it for me automatically.
   - I would need separate parsing of the authentication on the backend side depending on which Loader I'm using (Phaser, or another resource fetcher/setter in my application).

**Comment by stoneman1** [comment]
Not very hard to implement to the loader. 

Do we want to add this? Should it be for the whole loader or specific file? If for file then we need to make a check for withCredentials property on the file object. If for whole loader we probably should add property withCredentials.

https://github.com/photonstorm/phaser/blob/master/src/loader/Loader.js#L2336 
There is the xhrLoad function which should be edited to check those things.

**Comment by noseglid** [comment]
@stoneman1 I'm not super familiar with the Phaser codebase yet so I haven't attempted to make the changes but here are my thoughts about its design:

Optimally, it should be possible to set on a per-resource basis. I think *most* resource should have it set to false (the default value). Since it's credentials I think a defensive strategy is most sound. Only on occasion should it be set to true.

This means that an argument needs to be added for all different loading methods (`json`, `spritesheet`, `image`, etc.). Preferably an `options` object which may be extended in the future if more similar needs arise.

If that is too much work, I'm content with a simpler solution where `withCredentials` can be set globally on the loader object. Not as flexible, but get the job done. One apparent drawback is that it may be very common to keep assets (images etc) on a CDN, where you would most likely not want to send credentials.

**Comment by stoneman1** [comment]
So every load function needs a new parameter. Lets say that you want to load a image then you would use load.image(key, url, overwrite, {withCredentials: true}) and then you just check that property from the file in the xhrLoad function. Not too much of work really. Just waiting for other people to comment if this is something we want and how we want to do it :)

**Comment by noseglid** [comment]
SGTM 👍

**Comment by photonstorm** [comment]
Before we discuss how this can be done (I can think of a few ways), sprite sheets and all images in Phaser are loaded via Image tags, not XHR, so `withCredentials` will make no difference to them at all. It'll only impact the resource files (json/xml), which _are_ loaded via xhr.

@noseglid does that matter for your use-case? If not, then I've a way to implement this without needing new arguments for all methods. If it doesn't work for tag loaders (Image, Audio) then I'm not sure it's worth adding?

**Comment by noseglid** [comment]
I only need it when loading stuff via XHR. It is probably a good thing it
can't be done for images etc. as they are likely to be on a CDN and one
should definitely not send credentials there.

For my specific use-case it is only the `loadJSON` method which matter

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
