### ISSUE TITLE
Javascript event queue slows/ceases to function while Phaser is running

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#2755]
* A bug in the API

The issue that made me aware of this:
http://stackoverflow.com/questions/39461135/socket-io-client-does-not-emit-based-on-available-memory-cpu-in-tab

setInterval and setTimeout literally slow to a crawl when the game dips below 50 FPS i.e. when Phaser is using a lot of memory/cpu of the tab. Is this intentional? It causes socket.io to cease to work (as socket.io depends on the event queue as do many other js applications).  This seems to be  major issue to me because what is javascript without the event queue? Mind you, this isn't when the tab is at a halt because of a lack of cpu/memory, this is when the tab is under a moderate load ( a by-product of that is a drop in FPS).

**Comment by ForgeableSum** [comment]
New evidence has come to light.

It seems the event queue works just fine under normal circumstances (regardless of the memory/cpu load Phaser is taking up), except when I execute this function at the beginning of my game:

function createFogOfWar() {

    var bmd = game.make.bitmapData(game.camera.width, game.camera.height);

    bmd.fill(0, 0, 0);

    var img = game.add.image(0, 0, bmd);
    img.alpha = fogOfWarAlpha;
    fogOfWar.img = img;
    fogOfWar.addChild(img);
    fogOfWar.bmd = bmd;

    img.fixedToCamera = true;

}


Yup, that one function (and not the function which updates the fog of war) causes the event queue to break when the tab is under moderate cpu/memory stress. It doesn't seem to be a memory/cpu issue as the event queue works just fine when the game is under an extremely heavy load (i.e. down to 20 FPS). 

This bmd isn't even that big (it's the camera size, which is the window size). So I can't imagine what is happening here.

**Comment by photonstorm** [comment]
Input events, timers and RAF are _blocking_ events. If you do something expensive in them, they literally freeze the single thread that JS runs in. _You_ (personally) may not consider that function expensive, but at the time it's being called, the browser does.

Lots of essential info here: https://medium.com/@paul_irish/requestanimationframe-scheduling-for-nerds-9c57f7438ef4#.mlxcyxv5l

**Comment by ForgeableSum** [comment]
But how is creating a bmd related to any of that?
(hope that questions doesn't sound like " .... but why male models??" to you).

**Comment by photonstorm** [comment]
Because it's a relatively expensive operation, especially for a window sized canvas. Think about what it does internally: Search the Canvas Pool for a free canvas, retrieve one (if it can, generate one if it can't: expensive), resize that canvas, clear out it pixel values, fills it, updates it, then goes into the part about creating a new Image, assigning it a texture etc.

It's not a huge amount _on a Phaser level_, but add onto that all of the memory management, GPU updates, and whatever else the browser does internally, and it takes up precious milliseconds. Call that at a point where the main thread is already blocked (i.e. from an event handler), and it just adds to the delay, before anything else can continue.

That article explains how the whole process flow is like driving down a one-way street. Stick a load of traffic on it, make one of those cars go slow, and everything behind it has to wait until it has cleared. What's more, you have _no control_ over what the browser will do internally to mitigate this (i.e. throttling setTimeout perhaps). All you can do is ensure you only release fast cars onto the road.

**Comment by ForgeableSum** [comment]
Thanks, Richard, for the explanation. It makes so much more sense now :). 

I think I will have a go at creating a web worker to run socket.io and communicate with the server. That way, nothing going on with the main thread will tie up network communications. If that fails, I will need to focus on making the cars faster, as you say.

**Comment by photonstorm** [comment]
I would suggest you try and create a bunch of bmd's up front (and the Images that use them), and have them ready in advance. Then you can unleash them as needed. I don't know how many you need, but caching just a few at the start would surely help removing creating them from what sounds like a hotspot bit of code.
