### ISSUE TITLE
Firefox debug console open causes sprites to be scaled incorrectly

### ISSUE THREAD

**Issue by clccmh** [photonstorm/phaser#2756]
In the screen-shot bellow, the green line is the sprite bounds for my sprite when the debug console in not open.
![screenshot from 2016-09-13 20-45-55](https://cloud.githubusercontent.com/assets/5368387/18497366/38b46350-79f3-11e6-84e4-5b9de7ed32aa.png)

This screen-shot is the same sprite, with the debug console open.
![screenshot from 2016-09-13 20-46-35](https://cloud.githubusercontent.com/assets/5368387/18497368/3dc22fb2-79f3-11e6-893c-dd52249007da.png)

As you can see, when the debug console is open, the sprite scales incredibly small. 
*This is not an issue on sprites that have an image, only invisible sprites.*

### This is the code that is creating my sprite:
```
    finishLine = game.add.sprite(256, 512);
    finishLine.scale.x = 10;
    finishLine.scale.y = .1;
    finishLine.enableBody = true;
    game.physics.enable(finishLine, Phaser.Physics.ARCADE);
    finishLine.body.immovable = true;
```

**Comment by photonstorm** [comment]
The above code (in isolation) would not be impacted by the dev tools being open. The only thing that could cause it would be if your game is set to automatically change scale / size based on available window space. If that's true, then I would expect different scaling, because you've got less vertical space available in the window.

There is more to this issue than the fact the sprite is visible, or not, I'm afraid. Needs an isolated test case to prove it out please.
