### ISSUE TITLE
onInputOver fails while using Touch on the 2nd time

### ISSUE THREAD

**Issue by jamesfdickinson** [photonstorm/phaser#2764]
onInputOver fails while using Touch on the 2nd time and after.

The isOver flag is left on when releasing a touch on an input object because it never calls the _pointerOutHandler.  So when the touch is moved over the same object it was released on earlier the _pointerOverHandler ignored it because the isOver flag is still "true".

When releasing a touch on an input object does not call the "onInputOut" event which is correct.  This change is not asking to trigger an "onInputOut" but just call the _pointerOutHandler when the touch is released to clear the "isOver" flag.  The _pointerOutHandler has a parameter "silent" which work perfect for this situation.

To reproduce use either a device or chrome dev tool emulating mobile.  

http://jsbin.com/hawajeqijo/edit?console,output
1. Touch anywhere other than on the input element and drag over the input object.  
2. Release your touch event on the the input object
3. Repeat and notice the over event will not trigger until an "out" event is made.

Suggested code change in phaser.js

From

```
stopPointer: function (event) {

        if (this.pointer1.active && this.pointer1.identifier === event.identifier)
        {
            return this.pointer1.stop(event);
        }

        if (this.pointer2.active && this.pointer2.identifier === event.identifier)
        {
            return this.pointer2.stop(event);
        }

        for (var i = 2; i < this.pointers.length; i++)
        {
            var pointer = this.pointers[i];

            if (pointer.active && pointer.identifier === event.identifier)
            {
                return pointer.stop(event);
            }
        }

        return null;

    }

```

To

```

stopPointer: function (event) {

        if (this.pointer1.active && this.pointer1.identifier === event.identifier)
        {
            if (this.pointer1.targetObject) {
                this.pointer1.targetObject._pointerOutHandler(this.pointer1, true);
            }
            return this.pointer1.stop(event);
        }

        if (this.pointer2.active && this.pointer2.identifier === event.identifier)
        {
            if (this.pointer1.targetObject) {
                this.pointer1.targetObject._pointerOutHandler(this.pointer2, true);
            }
            return this.pointer2.stop(event);
        }

        for (var i = 2; i < this.pointers.length; i++)
        {
            var pointer = this.pointers[i];

            if (pointer.active && pointer.identifier === event.identifier)
            {
                if (pointer.targetObject) {
                    pointer.targetObject._pointerOutHandler(pointer, true);
                }
                return pointer.stop(event);
            }
        }

        return null;

    }

```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
