### ISSUE TITLE
Error「Uncaught ReferenceError: begin is not defined」when using phaser custom build

### ISSUE THREAD

**Issue by fenixwu** [photonstorm/phaser#2765]
An error occurs when using custom build.

Even I use "grunt full" to build full version of Phaser, it happen, too.

I found it is because line:14805 "var removed = this.children.splice(begin, range);"

Variable "begin" is not defined before.

I edit "begin" to "beginIndex", and run it successfully.

**Comment by photonstorm** [comment]
Thanks for spending time reporting this issue. However we've already fixed this in the `dev` branch of Phaser, and it will be part of the next official release. You can track what's already been fixed by looking at the Change Log part of the [dev README](https://github.com/photonstorm/phaser/tree/dev#change-log) file.
