### ISSUE TITLE
Feature Request - HTML element parenting

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2772]
Sometimes, you need an input field in your game. For example, I have an email and password input fields so that players can enter my game. I have made background sprites for them in Phaser where they should be going. However, it's currently impossible to make the HTML elements behave like children to these ingame sprites. I am using the following method and it works perfectly. The only annoying thing is that I need to call it constantly in the `update()` method. Here it is:

```
function placeHTMLelem(e, g){
    e = document.getElementById(e);

    if(g.worldAlpha > 0 && (g.visible && g.parent.visible)){
        setTransform(e, "scale(" + (g.worldScale.x*game.scale.scaleFactorInversed.x) + ")", "left top");
        e.style.left = (g.world.x - g.offsetX - game.camera.x)*game.scale.scaleFactorInversed.x + game.canvas.offsetLeft + 'px';
        e.style.top = (g.world.y - g.offsetY - game.camera.y)*game.scale.scaleFactorInversed.y + game.canvas.offsetTop + 'px';
        e.style.width = g.texture.width + "px";
        e.style.height = g.texture.height + "px";
        e.style.opacity = g.worldAlpha;
        e.style.display = 'block';
    } else {
        e.style.display = 'none';
    }
}

// Easily applies transform for all browsers.
function setTransform(elem, value, origin){
    elem.style.webkitTransform = value;
    elem.style.MozTransform = value;
    elem.style.msTransform = value;
    elem.style.OTransform = value;
    elem.style.transform = value;

    elem.style.webkitTransformOrigin = origin;
    elem.style.MozTransformOrigin = origin;
    elem.style.msTransformOrigin = origin;
    elem.style.transformOrigin = origin;
}
```

Haven't yet seen a scenario in which this doesn't work. Different game sizes, sprite scales, alphas, everything. It would be great, however, if this is implemented in Phaser and I could just do something like this:
`gameSprite.addChildHTML("elem-id");`

Thanks!

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
