### ISSUE TITLE
Looped audiosprite sprites do not loop correctly after a pause and resume (plays extra copy of the audiosprite from the beginning in addition to the loop)

### ISSUE THREAD

**Issue by rroylance** [photonstorm/phaser#2773]
This Issue is about (delete as applicable)
- A bug in the API

When using looped audiosprite sprites pause and resume the audiosprite seemingly gets confused and will start playing the entire audiosprite in addition to looping (causing overlapping sounds, typically music in our case).

[Codepen.io demo here, this demo will always use the most recent build on the dev branch (within a few minutes typically)](https://codepen.io/rroylance/pen/jrwWqP?editors=0010)

Example sequence *in the codepen; which calls this.game.sound.pauseAll() and this.game.sound.resumeAll() in onPause and onResume respectively;
- Audiosprite contains 1 music track set to loop *so no real reason to use an audiosprite anyway, but for the purposes of this demo it does
- Wait for music to start playing
- Then click out of the window pausing Phaser (and pausing all audio)
- Then click in the window resuming Phaser (and resuming all audio)
- Wait for the track to finish and you should here it start to play again but also have a copy playing over top with a slight offset

or the more realistic example of;
- Audiosprite contains 2 music tracks set to loop
- Play music track 2, which is second in the audiosprite
- Then click out of the window pausing Phaser (and pausing all audio)
- Then click in the window resuming Phaser (and resuming all audio)
- Wait for the track you played to finish and you should here track 2 start playing again but with track 1 playing on top of it

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
