### ISSUE TITLE
Camera smooth bounds

### ISSUE THREAD

**Issue by tenry92** [photonstorm/phaser#2774]
I am working on a platformer with "camera controls" placed all over the map. I'm gonna achieve something I know from games like _Donkey Kong Country 2_.

Example: In the beginning of my level, there's a limit above and under the camera, the camera will only move horizontally. Some point later in that level, there's another "camera control", which shall raise the camera - i.e. rise the bottom limit a few pixels - and raise the top limit, as there's some interesting stuff going on there.

Now, when I enter the second area, I update the camera bounds, and the camera immediately jumps to a new location, ensuring being inside the bounds. However, I wish the camera to move smoothly a little bit up, using the _lerp_ property.

I suggest a new property in the _Camera_ class called **smoothBounds**, disabled by default. The internal _updateTarget_ method should take this boolean into account, when interpolating between current and target position.

**Comment by hilts-vaughan** [comment]
This already exists but I don't remember the function .. :(

I'll look it up when I'm home if nobody else does.

**Comment by hilts-vaughan** [comment]
http://phaser.io/examples/v2/camera/smooth-follow

**Comment by tenry92** [comment]
Thank you, but this is _not_ exactly, what I'm looking for. I'm already using this for the general smooth follow in my platformer. But as soon, as I update my camera bounds - to adjust the focus on a specific area in the level - and the camera is not fully within these bounds, it immedieately jumps to a new location in order to be within these bounds instead of moving smoothly inside the bounds.

If you check the internal _checkBounds()_ method, which is called per frame: it immediately sets the x and y value. I need to interpolate between the current value and the value from _checkBounds_.

**Comment by ramorris3** [comment]
@tenry92 I just pushed a change that adds `smoothBounds` like you described.  Once it merges, you should test it out and let me know if it does what you're looking for.

keep in mind that the interpolation happens at a rate of `Camera.lerp`, so if you're going to use `Camera.smoothBounds` you'll need to also set `Camera.lerp`

**Comment by tenry92** [comment]
Thank you for your effort. I took a look into your changes and left a review. I'll check it out and test it later, and inform you if it works as expected.

**Comment by ramorris3** [comment]
I updated the commit to account for your comments.  Hopefully that works... test out the most recent change and let me know when you get the chance.

**Comment by tenry92** [comment]
Seems okay, looking at the changes. I hope to find time in the next days to test it on my platform in order to give you feedback, thanks :)

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
