### ISSUE TITLE
Group.inputEnableChildren not working, need to individual enable the children

### ISSUE THREAD

**Issue by JTronLabs** [photonstorm/phaser#2780]
This Issue is about (delete as applicable)

* A bug in the API

http://phaser.io/sandbox/edit/amknPIQj

So you need to set inputEnable on the children for it to work, which [contradicts this example](http://phaser.io/examples/v2/input/group-input-events)

**Comment by alperakgun** [comment]
Interesting, I was also just working on the same issue where Emitters (which are also groups) won't enable input on children despite inputEnableChildren.  Might be related to the  **child.input** part in the file "  phaser/src/core/Group.js .  Apparently when group.create is called, it works but when group.add is called otherwise.  (I'm sorry I've confused your ticket),

```
    if (this.inputEnableChildren && (!child.input || child.inputEnabled))
    {
        child.inputEnabled = true;
}
```

**Comment by photonstorm** [comment]
The problem is that you used `addChild` instead of `add`. The first is a Pixi method, that circumvents all of the things that Group does. The second will work fine with the input enable flag set. I appreciate this is confusing, but it is what it is in v2. Don't use Pixi methods if you want Group functionality.

**Comment by alperakgun** [comment]
Also _g.inputEnableChildren = true;_   must be before the .add() is called.

**Comment by JTronLabs** [comment]
Wow. Thanks Rich! Good catch, and good to know. Thank you for the heads up @alperakgun
