### ISSUE TITLE
bug about sprite.animations.destroy()

### ISSUE THREAD

**Issue by bomakoto** [photonstorm/phaser#2787]
Hello, I think there is a little bug for Sprite.animations.destroy();
the method destroy() will set this._frameData=null;

Source code: https://github.com/photonstorm/phaser/blob/master/src/animation/AnimationManager.js

So if you remove all the animations of a sprite by that method, 
then we cannot add animations to this sprite by sprite.animations.add()
because the method add will call the method getFrameIndexes of this._frameData, and we get an error.

However, if we remove an animation using sprite.animations.getAnimation('someName').destroy();
we can add animations to the sprite.

In other words, we are forced to avoid using the sprite.animations.destroy() otherwise we cannot add animations to this sprite later. This can be a bug source and it is hard to find the reason that we cannot add animations to the sprite anymore.

( I spend almost one hour finding the bug.)

I think a fix can be like this:

in sprite.animations.add:

before:
`this._frameData.getFrameIndexes(frames, useNumericIndex, this._outputFrames);`
after:
`if(this._frameData===null){
    this._frameData= new Phaser.FrameData()... // whatever, I don't know which class can create a new      frameData.
   }`

another way:, in sprite.animations.destroy():

before:
`this._frameData = null;`

after:
`this._frameData.clear(); // pseudocode, the clear() will clear all data in frameData.`

Thanks! 

Bocheng.

**Comment by bomakoto** [comment]
Example code:

var sprite=game.add.sprite(game);
sprite.animations.add('some animations name' , [0,1,2,3],10,false);

sprite.animations.destroy(); 
sprite.animations.add('some name', [0,1,2,3], 10, false);

you will get an error.

**Comment by rroylance** [comment]
By calling destroy on the AnimationManager you are destroying the AnimationManager, which also destroys all the animations. This seems intended, you call destroy on something you no longer need to use, so the AnimationManager not being usable after calling destroy on it makes sense. The comment for the function could be interpreted as saying it just destroys all the animations, I'll give you that.

There should however be a function to remove all animations that the manager is managing though...

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
