### ISSUE TITLE
phaser can't play mp3 file use webaudio mode in crosswalk

### ISSUE THREAD

**Issue by LibiChai** [photonstorm/phaser#2790]
we try a lot of  audio file (wav mp3 ogg ), only mp3 file can't play use webaduio mode  in crosswalk.

thank you

**Comment by photonstorm** [comment]
mp3 works fine in normal browsers, so this is surely a crosswalk issue. Have you tried asking them about it?

**Comment by hilts-vaughan** [comment]
This is a Crosswalk issue -- ran into it myself./

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
