### ISSUE TITLE
Phaser 2.6.2 - Typescript definition issue with functions getTileX, getTileXY & getTileY from TilemapLayer

### ISSUE THREAD

**Issue by Edistra** [photonstorm/phaser#2796]
These 3 methods are simply missing from the definition file.

``` js
class TilemapLayer extends Phaser.Sprite {
   ...
   getTileX(x: number): number;
   getTileXY(x: number, y: number, point: Phaser.Point): Phaser.Point;
   getTileY(y: number): number;
}
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
