### ISSUE TITLE
Feature Request - P2 loadPolygon offset

### ISSUE THREAD

**Issue by Azumi0** [photonstorm/phaser#2797]
Hi, i recently encoutered a issue when my sprite had an anchor set to diffrent values than 0.5. The P2 physics body ignored the anhchor.

```
    arm = game.add.sprite(game.world.centerX - 80, 177, 'arm');
    game.physics.p2.enable(arm);
    arm.anchor.setTo(0.5, 0.9);
    arm.body.clearShapes();
    arm.body.loadPolygon('physicsData', 'arm');
```

I found that other methods than "loadPolygon", like "addShape" supported offset, so I expanded the "loadPolygon" with same offset support. I would greatly appreciate if you could include this in the next release of Phaser. Thank you so much for your awesome job!

```
loadPolygon: function (key, object, offsetX, offsetY) {
    if (offsetX === undefined) { offsetX = 0; }
    if (offsetY === undefined) { offsetY = 0; }

    if (key === null)
    {
        var data = object;
    }
    else
    {
        var data = this.game.cache.getPhysicsData(key, object);
    }

    //  We've multiple Convex shapes, they should be CCW automatically
    var cm = p2.vec2.create();

    for (var i = 0; i < data.length; i++)
    {
        var vertices = [];

        for (var s = 0; s < data[i].shape.length; s += 2)
        {
            vertices.push([ this.world.pxmi(data[i].shape[s]), this.world.pxmi(data[i].shape[s + 1]) ]);
        }

        var c = new p2.Convex({ vertices: vertices });

        // Move all vertices so its center of mass is in the local center of the convex
        for (var j = 0; j !== c.vertices.length; j++)
        {
            var v = c.vertices[j];
            p2.vec2.sub(v, v, c.centerOfMass);
        }

        p2.vec2.scale(cm, c.centerOfMass, 1);

        cm[0] -= this.world.pxmi(this.sprite.width / 2);
        cm[1] -= this.world.pxmi(this.sprite.height / 2);
        cm[0] += this.world.pxmi(offsetX);
        cm[1] += this.world.pxmi(offsetY);

        c.updateTriangles();
        c.updateCenterOfMass();
        c.updateBoundingRadius();

        this.data.addShape(c, cm);
    }

    this.data.aabbNeedsUpdate = true;
    this.shapeChanged();

    return true;

}
```

**Comment by photonstorm** [comment]
Could you please submit this as a Pull Request?

**Comment by Azumi0** [comment]
Of course. This is my first time using GitHub in that manner, so I hope I did it correctly.
https://github.com/photonstorm/phaser/pull/2799

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
