### ISSUE TITLE
Feature Request - Sprite preUpdate and postUpdate events or empty methods

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2800]
I wanted to do something simple. Before a Sprite is updated, I store its current `x/y`. After the engine physics have been applied, I draw a line on a Graphics object from the stored `x/y` to the current `x/y`.

I tried using `sprite.preUpdate()` + `sprite.postUpdate()` and `sprite.body.preUpdate()` + `sprite.body.postUpdate()`. They are internal and as far as I can see, Phaser does important stuff in them, so it didn't work.

If I use the empty `update()` method provided by Phaser and put the drawing of my line there, it still doesn't work since the line is being drawn _during_ the `update()`, not _after_ it and it ends up drawing from a certain `x/y` to the same `x/y`.

My suggestion is to add `onPreUpdate` and `onPostUpdate` events, so that something like this would be possible:

```
sprite.events.onPreUpdate.add(storePositionMethod, this);
sprite.events.onPostUpdate.add(drawLineMethod, this);
```

However, I imagine that would bash performance in the throat, so perhaps empty `preUpdate()` and `postUpdate()` methods like the `update()` one would be enough.

Thanks!

**Comment by samme** [comment]
We can't add empty `preUpdate` and `postUpdate` methods because those would pre-empt the default ones.

You can override these and call the default methods manually:

```javascript

sprite.preUpdate = function() {
  var result = Phaser.Sprite.preUpdate.call(this, arguments);
  // do stuff…
  return result;
};

sprite.postUpdate = function() {
  var result = Phaser.Sprite.postUpdate.call(this, arguments);
  // do stuff…
  return result;
};
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
