### ISSUE TITLE
Phaser atlas cache dimension bug?

### ISSUE THREAD

**Issue by lino10** [photonstorm/phaser#2802]
Hi, I'm having weird problem with the atlas loader.

I have temporary images which are 100x150, those images are put in one spritesheet and loaded using the atlas loader(game.load.atlas).

Today I received new images to replace the temporary images which are 100x135, those are also put into one spritesheet and loaded using atlas loader.

At first I thought it's just replacing the atlas image and data. But apparently the draw in game becomes a mess, phaser draws the image with old size(100x150), so the images are overlapping.
I've tried the hard refresh(ctrl+f5) but it's still not working.  Then I tried to clear browser cache, and the result is fine.

So is this intended mechanism or a bug? Do I must always clear browser cache if the image in spritesheet changed dimension? Can I prevent the phaser not to cache the atlas dimension? Because I can't ask the players to clear browser cache everytime.

I have other images(like button) which are not in the spritesheet. The temporary images and new images have different dimension too, they're loaded using manual load(game.load.image), and they don't have problem like the atlas load.

Phaser v2.6.2
Firefox 49.0.1

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
