### ISSUE TITLE
Feature Request - P2 physics overlap method

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2804]
Currently it's impossible (or perhaps possible, but really hard) to check whether two P2 bodies overlap.

For example, I have a couple of Sprites that form a race circuit, which are in a collision group. Then, I have a car, which is in another collision group. They don't collide, but I still need to know when the car leaves the track so I can apply some penalties or something.

`game.physics.p2.overlap()` would be a really cool thing to have. It would be even better if you can check a P2 body against a whole collision group - similar to how the Arcade physics `overlap()` can work with a single Sprite against a group of Sprites.

Thanks!

**Comment by Swissnetizen** [comment]
I think this will help you http://www.html5gamedevs.com/topic/5567-trigger-with-p2/

**Comment by Swissnetizen** [comment]
Maybe we could add a `isSensor` parameter to `body.addRectangle`.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
