### ISSUE TITLE
Adding support for Letterbox integer scale.

### ISSUE THREAD

**Issue by koolkap** [photonstorm/phaser#2805]
Unlike: 

https://www.scirra.com/tutorials/73/supporting-multiple-screen-sizes#h2a4

We have letterBox function in latest phaser, Something like this **scaleSpritePropotional(sprite,width,height,mode)**

Extending with the mode 
like:

Phaser.LETTERBOX = true;
Phaser.LETTERBOXINTEGER = true:

```
function scaleSpritePropotional(sprite,width,height){
     width = Math.round(width);
        height = Math.round(height);
           if(Phaser.LETTERBOX){
           sprite.scale.x = 1;
            sprite.scale.y = 1;
        if ((sprite.width <= 0) || (sprite.height <= 0) || (width <= 0) || (height <= 0))
        {
            return sprite;
        }

        var scaleX1 = width;
        var scaleY1 = (sprite.height * width) / sprite.width;

        var scaleX2 = (sprite.width * height) / sprite.height;
        var scaleY2 = height;

        var scaleOnWidth = (scaleX2 > width);

        if (scaleOnWidth)
        {
            scaleOnWidth = letterBox;
        }
        else
        {
            scaleOnWidth = !letterBox;
        }

        if (scaleOnWidth)
        {
            sprite.width = Math.floor(scaleX1);
            sprite.height = Math.floor(scaleY1);
        }
        else
        {
            sprite.width = Math.floor(scaleX2);
            sprite.height = Math.floor(scaleY2);
        }

         }else if(Phaser.LETTERBOXINTEGER){
                 sprite.width /= 2;
                 sprite.height / =2; //To maintain the same aspect ratio of the image.
         }
         //  Enable at some point?
         sprite.x = Math.floor((width - sprite.width) / 2);
         sprite.y = Math.floor((height - sprite.height) / 2);

}
```

The logic is inspired from the construct 2 Drop down for the multiple screen size keeping the asset aspect ratio same for multiple screen.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
