### ISSUE TITLE
Tilemap vs sprite collisions arcade physique phaser 2.6.2

### ISSUE THREAD

**Issue by Xesenix** [photonstorm/phaser#2809]
- An error on the web site

I am trying to implement collisions between sprite and tile in arcade physique engine in phaser version 2.6.2
To learn how to use phaser for this task i am using this example:  http://phaser.io/examples/v2/tilemaps/map-collide
It doesn't seam to work because sprite character falls thru tile floor and doesn't collide with anything but world bound. Also it would be good to highlight importance off using body velocity so noobs like me wont think that they can use body position instead.

**Comment by kebabskal** [comment]
+1
I cant make Sprite > TileMap collisions work either.

**Comment by Xesenix** [comment]
im making something like this so it works:
in create:
```
game.physics.startSystem(Phaser.Physics.ARCADE);
game.physics.arcade.gravity.y = 1000;
var csv = '';
game.cache.addTilemap('cave', null, csv, Phaser.Tilemap.CSV);
var tilemap = this.game.add.tilemap('cave', this.tileSize, this.tileSize, layer);
var groundLayer = this.tilemap.createBlankLayer('ground', tileColumns, tileRows, tileSize, tileSize, layer);
	groundLayer.scale.set(1);
	groundLayer.renderSettings.enableScrollDelta = true;
	groundLayer.resizeWorld();
	groundLayer.debug = false;

var charactersLayer = game.add.spriteBatch();

var unit = game.add.sprite(...)
game.physics.enable(unit);
unit.body.collideWorldBounds = true;
charactersLayer.add(unit)
```
in update:
```
game.physics.arcade.collide(groundLayer, charactersLayer);
```
and ARCADE physics works only if you use velocity for moving objects (at least easiest way to make it work is to use velocity and acceleration)

**Comment by kebabskal** [comment]
My problem was that I passed tilemap.layers[0] to the collide function.
That is actually not the same as the result of tilemap.createBlankLayer().
A bit counter intuitive.

**Comment by andrewlphilpott** [comment]
Man, I can't get this working by following their tutorial (or any other tutorial I've found) either. I've been trying to get collision working for like 2 hours now.

**Comment by hilts-vaughan** [comment]
Andrew,

You should upload some code so others can see what's going on.

**Comment by andrewlphilpott** [comment]
@hilts-vaughan I'm actually using the exact same code (aside from some variable names) as in [this example](https://github.com/photonstorm/phaser-examples/blob/master/examples/tilemaps/map%20collide.js) right now just to make sure I'm not insane. This is the result I'm getting: http://d.pr/i/ZJB7.

The only thing that differs from that example is my JSON, so could that maybe be the issue?

**Comment by Xesenix** [comment]
yes scaling is totally useless i lost few weeks trying to fix it but end i got to conclusion that i would need rewriting most of engine so it would work and i resigned from scaling

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
