### ISSUE TITLE
Feature Request: "Official" plugin for Spine-TS

### ISSUE THREAD

**Issue by shibekin69** [photonstorm/phaser#2811]
Hi,

LINK TO RUNTIME: https://github.com/EsotericSoftware/spine-runtimes/tree/master/spine-ts

As what the title says :). Can we kindly request for some sort of "official" plugin integration/support for Spine-TS? Esoteric's updated their JS runtime with a TypeScript version deprecating all other JS versions, but that's as far as they're willing to go to put up a JS version. Orange-games have made some headway onto creating a plugin, but at the moment, it's stuck with the old version of the runtime (2.x?), so none of the new features are supported. It works well enough, with some bugs here and there.

The plugin works well enough in today's mobile phones, providing good performance. I can't say how it performs when all of the features used, but if the game is played in a desktop environment, there shouldn't be any problems with regards to speed.

**Comment by ianjohnspain** [comment]
Yes this is something that would be really good.

**Comment by codism** [comment]
Also really keen to see this working, it would be great.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
