### ISSUE TITLE
Phaser.Particles.Arcade.Emitter.setAlpha and setScale crashes when rate parameter is positive

### ISSUE THREAD

**Issue by brianbunch** [photonstorm/phaser#2812]
This Issue is about (delete as applicable)
- A bug in the API

Whenever the rate parameter to Phaser.Particles.Arcade.Emitter.setAlpha or Phaser.Particles.Arcade.Emitter.setScale is positive, Phaser crashes due to what seems to be invalid tween data.

I have attached a minimal example:
[crash.html.zip](https://github.com/photonstorm/phaser/files/545687/crash.html.zip)

**Comment by samme** [comment]
It's not a positive duration but a duration below ~15ms (which is less than 1 frame).

Error checking could be better but for now avoid very small durations. If you want 10s use `10000`.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
