### ISSUE TITLE
SoundManager does not always respect muting - "part 2"

### ISSUE THREAD

**Issue by SBCGames** [photonstorm/phaser#2817]
- A bug in the API
  
  This is related to previously closed issue (https://github.com/photonstorm/phaser/issues/2382), thus "part 2"...

Currently muteOnPause is checked in gamePaused() and gameResumed() methods, which are called by Stage visibility hadler.

I have client that displays overlay with menu over game. If disableVisibilityChange is set to true or overlay does not steal focus, then game runs under it (unfortunately both is possible). For this, client's framework sends his own onPause() and onResume() events when it shows or hides overlay. Inside handlers of these events I set paused to true or false. Overlay has menu with sound on/off button on it, which sends events onMute() / onUnmute(). If game is paused with call to paused = true/false in onPause()/onResume(), then setting game.sound.mute = true/false inside event handlers for onMute()/onUnmute() events does not have effect.

Reason is, that in paused property of Phaser.Game, setMute and unsetMute are called without muteOnPuase check. Adding checks resovles issue.

``` javascript
Object.defineProperty(Phaser.Game.prototype, "paused", {

    get: function () {
        return this._paused;
    },

    set: function (value) {

        if (value === true)
        {
            if (this._paused === false)
            {
                this._paused = true;
                if (this.sound.muteOnPause) {            // added check
                    this.sound.setMute();
                }
                this.time.gamePaused();
                this.onPause.dispatch(this);
            }
            this._codePaused = true;
        }
        else
        {
            if (this._paused)
            {
                this._paused = false;
                this.input.reset();
                if (this.sound.muteOnPause) {            // added check
                    this.sound.unsetMute();
                }
                this.time.gameResumed();
                this.onResume.dispatch(this);
            }
            this._codePaused = false;
        }

    }

});
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
