### ISSUE TITLE
Changes to improve tweened camera movement broke some preRender usage

### ISSUE THREAD

**Issue by danzel** [photonstorm/phaser#2825]
In 68c29470cf07591222d2267006c16158d480728f / #2482 the `stage.updateTransform()` call was moved from `*Renderer.render` and in to `Stage.postUpdate`.

In my game I am updating the position of my Sprites in a `preRender` method (I don't need to update them every update, just every time we are going to render a frame). But this no longer works.

Previously `updateTransform` would happen after `preRender`, now it happens before, so any transform changes made inside `preRender` won't be applied.

Was this an intended behaviour change? I'm unsure what use `preRender` has now.
Thanks!

**Comment by samme** [comment]
I think this was probably intended. Maybe the docs should now say positioning in `preRender` isn't straightforward.

You may be able to position them by manipulating `worldPosition` or by calling `updateTransform` yourself on parts of the display tree.

Are you using `game.lockRender`? You can just test that in `update` or `postUpdate` to do conditional updates.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
