### ISSUE TITLE
scaleMode RESIZE with resolution > 1 results in incorrectly sized canvas

### ISSUE THREAD

**Issue by danzel** [photonstorm/phaser#2826]
If you set `resolution: 2` when constructing your Phaser.Game object it creates a canvas twice as big as desired and resizes it to the correct size using CSS (good).

If you also set `game.scale.scaleMode = Phaser.ScaleManager.RESIZE;`, then the CSS style to resize the game back down is not applied, so the canvas ends up being twice as big as it should be.

Example (right click + inspect the canvas to see how big it is):
https://codepen.io/anon/pen/yaAkEw

I think maybe `ScaleManager.updateDimensions` should call `resetCanvas` (that's the cludge I've done locally anyway), but I'm not too sure.

Thanks!

**Comment by ForgeableSum** [comment]
Shit. That's interesting. I wonder if this has anything to do with this:
http://www.html5gamedevs.com/topic/25403-why-does-lower-resolution-not-improve-performance/

Could it be that lower resolution doesn't give you better performance because the canvas size is double what it needs to be?

**Comment by danzel** [comment]
Don't think so, in that case the canvas would be smaller than it should be.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
