### ISSUE TITLE
Feature Request - Phaser.Math.reach()

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2831]
A method that combines `Phaser.Math.maxAdd()` and `Phaser.Math.minSub()`. I've got something like this at the moment:
```
function reach(value, goal, step) {
    var diff, sign;

    diff = goal - value;
    sign = Math.sign(diff);
    diff = Math.abs(diff);

    return (diff > step)
        ? value + (step * sign)
        : value + (diff * sign);
}
```
I call it `reach()` because you give it a value, goal and step value. If the value is greater than the goal, it gets reduced by an amount equal to the step, if it's lower than the goal, it's increased.

It's useful for calculating the power output of an engine, for example. When you are holding the throttle, the power must go upwards, if you hold the reverse button, it needs to drop below zero. With this function, you just specify the current power and desired power (goal) and everything works.

Thanks!

**Comment by hdodov** [comment]
The solution proposed by @ItsMeAlves wouldn't work as expected. If the value is 5, the goal is 10 and the step is 100, `reach()` would return 105, instead of 10. That's why in my example implementation I used the `difference` variable.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
