### ISSUE TITLE
Feature Request - Phaser.SoundManager.destroyAll()

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2834]
Phaser's SoundManager has the ability to stop all sounds with `stopAll()`, but it doesn't have the ability to destroy them. `stopAll()` can be useful for when you pause the game, for example, but `destroyAll()` would be useful for when you abandon the game and go to a menu state.

This is the code I used to implement `destroyAll()` myself. It's based on the code for `stopAll()`:
````
Phaser.SoundManager.prototype.destroyAll = function () {
    for (var i = 0; i < this._sounds.length; i++)
    {
        if (this._sounds[i])
        {
            this._sounds[i].destroy();
        }
    }
    this._sounds = [];
};
````

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
