### ISSUE TITLE
getBounds() returns the wrong values after kill() and revive()

### ISSUE THREAD

**Issue by vikramarka** [photonstorm/phaser#2838]
Hi there,

It seems that getBounds() of Sprite returns old values after kill() and revive(). I have some objects coming from bottom and as soon as they overlap with the player I am killing them using kill() But once the same object revived, the getBounds() returns the old values even if we set the x and y values explicitly.

Thanks

**Comment by vikramarka** [comment]
The x and y values of the sprite are correct, only the x and y values in the bounds rectangle are the old ones.

**Comment by vikramarka** [comment]
So, overlap() method is returning true, even if the sprite is a different place.

**Comment by samme** [comment]
Try

    sprite.updateTransform().getBounds()

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
