### ISSUE TITLE
How to implements proper classic simple game pause?

### ISSUE THREAD

**Issue by devnewton** [photonstorm/phaser#2839]
I wanted to implements a classic game pause:

- game can be paused/resumed by the _Pause_ keyboard button.
- game can be paused/resumed by the _Start_ gamepad button.
- game can be paused/resumed by clicking on a visible on screen button.
- when paused, a pause message is displayed above everything.
- when paused, a clickable _Resume_ button is displayed above everything.
- when paused, everything in the game is stopped (sprites, animations, musics, sounds...).

Here is what prevent to implement this in Phaser 2.6.2:

- there is no _PAUSE_ in Phaser.KeyCode.
- Gamepad callbacks disabled when game is paused cf https://github.com/photonstorm/phaser/issues/2179
- everything is stopped, there is no way to keep some object alive, so it's not possible to have a clickable Phaser.Button for resume.

Is there other way to implements this?

**Comment by jorio** [comment]
I needed an animated pause screen with gamepad support, which rules out `game.paused`, so here's my workaround:
- pause all timers
- pause all tweens
- pause physics
- replace input bindings with pause screen-specific bindings

Do the reverse to unpause. You may also want to pause all animations and particle emitters. You should be careful not to alter the state of the game in your objects' update routine when the game is "paused." Hope this helps.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
