### ISSUE TITLE
Camera shake causes problems with render textures

### ISSUE THREAD

**Issue by ForgeableSum** [photonstorm/phaser#2841]
I absolutely love the camera shake. However, since its tied in directly with the renderer, if the camera is shaking, it will mess up render textures that are rendering stuff (e.g. with the renderXY method). I end up with black outlines around the render texture. I am 100% positive this is due to the camera shake. 

I have tried calling game.camera.reset, but no luck. If I do a camera shake at any time before rendering to a render texture, i end up with weird black outlines on the render textures.

**Comment by jorio** [comment]
I encountered a similar issue that may be related to yours: when filters are active on an image, camera shake won't affect all objects on the screen ([forum post](http://www.html5gamedevs.com/topic/26135-camera-shake-artifact-when-shaders-are-applied/), [jsfiddle](https://jsfiddle.net/9yok8p0x/1/)). To work around this, I ended up rolling my own shake routine that manipulates the camera's x/y coordinates.

**Comment by ForgeableSum** [comment]
Wow, I encountered your issue 20 days later:
https://github.com/photonstorm/phaser/issues/2889

I may end up making my own shake effect, as the built-in one just causes so many problems that no one seems to be able to address. It's really unfortunately, because i had my own shake functions and they worked fine ... but they weren't as convenient as a built-in one. When the built-in one was added, I deleted all mine. So much for that. No I'm going to have to dig up that old code.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
