### ISSUE TITLE
Feature Request- Yoyo tweens with an array of properties

### ISSUE THREAD

**Issue by dwyermt** [photonstorm/phaser#2846]
```
this.game.add.tween(this.letterSprite).to(
      {
        x: [100,200],
        y: [100,200]
      },
      1000,
      Phaser.Easing.Quadratic.InOut,
      true, 0, -1, true
    );
```

Yoyoing a tween with an array of properties results in it returning to its original position without the yoyo.

**Comment by hilts-vaughan** [comment]
Isn't this a feature request? What were you expecting?

**Comment by dwyermt** [comment]
I was expecting the tween to yoyo regardless of there being 1 or 2 different positions the sprite tweens to.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
