### ISSUE TITLE
Feature Request - Phaser.Text.matchWidth()

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2847]
When making a game that requires user input, that input might be longer than expected. Let's say you are making a leader board and want to put a player's name on it. If the player has a name of 80 characters, that will look hella ugly and might even break the UI if `alignTo()` is being used.

My suggestion is to have a function like this:
```
Phaser.Text.prototype.matchWidth = function (width, suffix) {
	var t = this.text;
	suffix = suffix || "";

	while (this.width > width && t.length > 0) {
		t = t.slice(0, -1);
		this.setText(t + suffix);
	}
};
```

This reduces the text's width while it's longer than the given width. For example, if there is an object like this:
```
var text = game.add.text(0, 0, "Loremipsumdolorsitametloremipsum");
```
And then:
```
text.matchWidth(65, "...");
```
The text will be something like
```
Loremips...
```

**Comment by chrispwns** [comment]
I'll go ahead and start on this since it sounds interesting. :)

**Comment by hilts-vaughan** [comment]
Is a character limit really the way to do this? It's probably better to actually measure the text and clip it since the font-size etc will actually matter, rather than the # of characters.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
