### ISSUE TITLE
Dragging failing randomly on Chrome mobile

### ISSUE THREAD

**Issue by romanrandom** [photonstorm/phaser#2857]
This Issue is about

* An unexpected behaviour

When using Chrome and Chrome Canary for desktop in *device emulation mode*, dragging randomly stops working on any object. The same is true with Chrome on mobile.

When it stops working on desktop, simply disabling the *device emulation mode* fixes the issue.

Maybe this is a Chrome issue.

I would include some code but I don't know which part could be useful since everything works well normally and no error is thrown when it fails.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
