### ISSUE TITLE
Bug - Group.sort .SORT_DESCENDING flips the order of the items back and forth when using 'z' for sorting

### ISSUE THREAD

**Issue by prof-kerfuffle** [photonstorm/phaser#2859]
This Issue is about (delete as applicable)

* A bug in the API

When you sort a group repeatedly by 'z', and use .SORT_DESCENDING, the order flips back and forth. The issue seems to be caused by the updateZ () call at the end of Group.sort function, since it sets the z value of the group items based on their order, which causes the items to be rearranged repeatedly. Simply removing the updateZ () call at the end seems to fix it, though it may cause other issues that I'm not aware of.
`
The updateZ call referred to:

	Phaser.Group.prototype.sort = function (key, order) {
		if (this.children.length < 2){
			//  Nothing to swap
			return;
		}
		if (key === undefined) { key = 'z'; }
		if (order === undefined) { order = Phaser.Group.SORT_ASCENDING; }
		this._sortProperty = key;
		if (order === Phaser.Group.SORT_ASCENDING){
			this.children.sort(this.ascendingSortHandler.bind(this));
		}
		else{
			this.children.sort(this.descendingSortHandler.bind(this));
		}	
		this.updateZ(); // REMOVING THIS CALL SEEMS TO FIX IT
	};
`
Test code:

	var game = new Phaser.Game(400, 200, Phaser.AUTO, '', { preload: preload, create: create, update: update });
	var group;

	function preload(){
		game.load.image('phaser', 'phaser-dude.png');
	}
	function create(){
		var s1 = game.add.sprite(0, 0, 'phaser');
		s1.z = 0;
		var s2 = game.add.sprite(0, 10, 'phaser');
		s2.z = 1;
		group = game.add.group();
		group.add(s1);
		group.add(s2);
	}
	function update(){
		group.sort('z', Phaser.Group.SORT_DESCENDING);
	}
`
Phaser sandbox example:
https://phaser.io/sandbox/edit/bmFSUMXE

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
