### ISSUE TITLE
[Official] -- Jitterness from Phaser's Sprite / Background

### ISSUE THREAD

**Issue by Dillybob92** [photonstorm/phaser#2885]
I setup an example [jsfiddle](http://jsfiddle.net/vnzzfnmg/6/) to illustrate this with proper assets.

When your character **is moving and the camera starts to pan**, you will notice the background has a small "jitterness". This can be disabled by setting `game.camera.roundPx` to true.

However, if that is disabled and you move the character. Your character starts to jitter. Some things I've found in this adventure:

- This only happens when moving with `body.velocity.x`, under both `P2` and `Arcade` physics. 

- If you move the character with `body.x` or just `x` it's absolutely fine.

- If you remove the *tilemap texture* you can literally see the jitterness happen behold your eyes when moving. [Example here](http://jsfiddle.net/vnzzfnmg/8/) -- Make sure you move far enough for the camera to pan.

- I've also tried `game.renderer.renderSession.roundPixels = false;` with no prevail. 

- This happens under CANVAS and WEBGL render modes

@photonstorm and @englercj  Please take a look.. I've tried everything my brain will let me. Also posted on [Stack O](http://stackoverflow.com/questions/40811148/how-to-remove-jitterness-from-phasers-sprite-background). Thanks in advance!

**Comment by englercj** [comment]
Potentially related issues: #2883, #1377

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.

**Comment by samme** [comment]
<http://jsfiddle.net/vnzzfnmg/10/>
