### ISSUE TITLE
Phaser Community Edition Tags?

### ISSUE THREAD

**Issue by fkrauthan** [photonstorm/phaser#2892]
Hey,

I just looked thru the github tags and can not see any tags for the two phaser 2 community edition releases? It would be very helpful to exactly get back to a certain version including the community edition. Are there any plans to publish them in the future with proper tagging here? Or is there another source that references which revision was exactly published for which version?

Thanks,
Florian

**Comment by photonstorm** [comment]
I don't have any plan to tag them on this repo, no. I just think it would be too confusing, as you'd pull down all three versions in the tagged release, plus the tags would get confused when we start tagging v3 releases. You can get back to an exact version via npm easily enough. I think the best course of action will be to move Phaser CE to its own repo when v3 is ready for release, but in the meantime it needs all the visibility it can get, so it's staying here for now.

**Comment by fkrauthan** [comment]
Hmm I see. I feel like that we still should tag it (it is easy to just move files around within that tag so only the CE content is in that tag). And with adding a suffix e.g. 2.8.0-ce it should be clear that that is the CE version/tag. In addition I just looked at the NPM package and the package should probably be published without the grunt files and the docs as this just makes the package bigger then it needs to be.

**Comment by photonstorm** [comment]
Tags point to specific commits, i.e. the state of the repo at that moment in time. How would you tag a sub-folder of the repo? I've seen it done using the folder SHA-1 keys, but it was a bit of a hack to say the least. If there's an easy way, I'm happy to do it.

It's important the npm package includes all the grunt files, otherwise you're unable to do a custom build of Phaser, which I know loads of devs do. The docs are vital too, lots of people prefer the look of the local doc browser over the site based one, and it's not unusual to have to work offline too, where again they are essential (i.e. while commuting). The Phase npm package has always included these, so it's nothing new, and removing them would be unexpected, although not an impossibility either.

**Comment by fkrauthan** [comment]
Yeah you would pretty much create a new branch, delete all the v2/v3 code and then use git mv to move the content of v2-ce to the top. And then you just create a tag of that. I know its not perfect. Anyways was just a suggestion. I agree with you I think the best would be to split off community (and it feels a bit like that should be done before v3 is finished).

**Comment by photonstorm** [comment]
Will keep an eye on things. It depends on activity. If lots of people get involved and it starts becoming an issue, then I'll move it to its own repo. At it stands only a couple are involved so far.

**Comment by fkrauthan** [comment]
Sounds good. Btw I am really pleasant surprised with your response time. Shows your dedication for this project which is always good if I base my project on top of your work 👍
