### ISSUE TITLE
Text Object Stretches On Android/XDK (While using Clipping Mask)

### ISSUE THREAD

**Issue by shibekin69** [photonstorm/phaser#2907]
Hi,

I'm using Phaser 2.6.2. I've got a dialog history box that uses a clipping mask and dragging capabilities. There's no problem with desktop browsers or NW.js. But the problem only shows up when the game's deployed on Android using Intel's XDK. Simply put, I append text to the dialog history text box, and I should be able to see this no problem. But in Android + Intel XDK, when the text box gets to a certain size or height, the text box starts stretching as if you're distorting the text box height! The longer the text, the more stretched it gets, and it soon becomes a black box.

**Comment by shibekin69** [comment]
From my observations, it's got some weird thing/interpretation going on with the text object's height property. Like a disconnect or something. When I append more text by using textVar.setText(textVar.text + '\n\n' + 'more text here') to the height increases which is expected. But if it goes up a certain height value (which I don't know), it starts to stretch. This can be worked around by putting a limit to the height value, but unfortunately in my case, I rely on the height property my touch-drag functionality, so by setting the height, it breaks the feature.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
