### ISSUE TITLE
Poor WebGL performance on high resolutions

### ISSUE THREAD

**Issue by bladeSk** [photonstorm/phaser#2908]
When rendering a game on a high resolution, such as 2560x1440, the performance is poor even in the simplest scenes. This only affects the WebGL renderer. Canvas works better, but it's not a viable workaround for us, as it has other performance limitations. I'm experiencing this issue on all combinations of Windows, OSX, Chrome and Firefox.

See: https://jsfiddle.net/ddwy6jLz/
For comparison - Three.js runs smoothly even on high resolutions: https://jsfiddle.net/28sudnx1/

Tested with Phaser 2.6.2, older versions also affected.

I've tried debugging the rendering process, but it seems fine, very few draw calls, the shaders don't use any expensive operations, no CPU intensive calculations either. I have absolutely no idea what might be causing this :/

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
