### ISSUE TITLE
Tween speeds differ significantly between Chrome on Windows / MacOS

### ISSUE THREAD

**Issue by AntonFagerberg** [photonstorm/phaser#2916]
I developed a game which heavily uses tweens to move characters around.

Example in code: https://github.com/AntonFagerberg/hotel/blob/master/src/game.js#L295

This GIF shows the intended character movement speed:
https://raw.githubusercontent.com/AntonFagerberg/hotel/master/gif/hotel_final2.gif

This works in Chrome (54.0.2840.98 and 55.0.2883.87) and Safari (10.0.1) on my Mac. It also works on Safari for iOS (latest version at time of writing).

However, on my friends Windows machine running Chrome (54.0.2840.99 and 55.0.2883.87) the speed is significantly slower: https://dl.dropboxusercontent.com/u/1937996/HotelGameplay.mp4

(I think animation speed is fine but movement speed is much slower)

You can try the game here: http://www.antonfagerberg.com/hotel/
Full code is here: https://github.com/AntonFagerberg/hotel (Ludum Dare entry so it's kinda messy)

API-version: 2.6.2

This Issue is about
* A bug in the API

Update, tested on three machines with Windows and Chrome and two of them are getting incorrect speed so this is tricky...

**Comment by st0n3vn** [comment]
Hello, I am experiencing the same issue on a specific PC on Chrome and Firefox (it's fine on Edge). Here is a link to Phaser forum where I've described it: http://www.html5gamedevs.com/topic/26690-tweens-running-slow-an-a-specific-pc-on-chrome/#comment-154159

**Comment by st0n3vn** [comment]
Just a quick update: are you by any chance testing this on a high refresh rate monitor? I updated my post (the one linked in my previous reply) as I've found that my issue was only experinced on a 120hz monitor. Tweens were ok as I tuned that down to 60hz.

**Comment by AntonFagerberg** [comment]
Yes I think that's the culprit! Nice catch :)

I can't verify it enitrely but it seems highly likely.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
