### ISSUE TITLE
Artefacts on sprite animations & tweens

### ISSUE THREAD

**Issue by AntonFagerberg** [photonstorm/phaser#2917]
I'm experiencing artefacts on my sprite animations when my characters are moving sideways using tweens.

In this image, I've tried to highlight the artefact which is a thin white line behind the ghost: http://imgur.com/a/EFdLr

It happens on several different sprites and I've checked thoroughly that there isn't anything wrong with the images themselves.

Moving GIF: https://raw.githubusercontent.com/AntonFagerberg/hotel/master/gif/hotel_final2.gif (you can see it clearly when the ghost is jumping on the second floor)
You can run the game here: http://www.antonfagerberg.com/hotel/

Animations loaded: https://github.com/AntonFagerberg/hotel/blob/master/src/game.js#L636
Sprite added: https://github.com/AntonFagerberg/hotel/blob/master/src/game.js#L176
Animation play: https://github.com/AntonFagerberg/hotel/blob/master/src/game.js#L186

The sprite: https://github.com/AntonFagerberg/hotel/blob/master/img/guest1_walk.png

Source code: https://github.com/AntonFagerberg/hotel

API-version: 2.6.2

This Issue is about
* A bug in the API

**Comment by photonstorm** [comment]
Hi - The code and assets look fine, although I only checked the ghost animation. This is almost certainly caused by pixel interpolation on textures, under WebGL. If you force the game to CANVAS (instead of AUTO) I'm confident it will remove the problem.

It's caused by WebGL interpolating pixels when reading a frame from the sprite sheet, and under certain circumstances it's pulling in an extra vertical strip of pixels from the frame to the left of the one being displayed (in this case, but it's not limited to that, it can do it from any adjacent frame).

Texture Atlas software such as Texture Packer have built-in features to avoid this, called Border and Shape padding, where it adds in an extra few pixels of blank space around frames, so the GPU can't grab frames from adjacent cells by mistake. I'd strongly recommend using it, if you need to keep using WebGL and can't switch to canvas.

**Comment by AntonFagerberg** [comment]
Alright, thanks! I tried canvas and at least that seems to work. 😃
I'll consider Texture Packer in future projects.

**Comment by AntonFagerberg** [comment]
Short followup, it seems to be incorrect on iOS still. Does Safari on iOS always use WebGL or something?
