### ISSUE TITLE
game.time.slowMotion should lerp

### ISSUE THREAD

**Issue by nickaversano** [photonstorm/phaser#2923]
Love what you're doing with this framework. Noticed that `slowMotion` makes the game feel like it's lagging (see [here](http://phaser.io/examples/v2/time/slow-down-time)). Would be cool if the positions of game objects lerped between the previous and current when `slowMotion` is used so you still get a nice 60fps feel.

**Comment by samme** [comment]
When using `slowMotion` you should increase `desiredFps` such that

    60 === game.time.desiredFps / game.time.slowMotion

**Comment by nickaversano** [comment]
Seems like a non-obvious api. Perhaps this should be in the documentation for game.time.slowMotion ?

**Comment by samme** [comment]
I have hunch the lag (#2631) was a bug introduced by some other change in the game loop, and this is a non-obvious workaround. :)

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
