### ISSUE TITLE
Camera scale bug for box2d and tilemap layer

### ISSUE THREAD

**Issue by mortsini** [photonstorm/phaser#2931]
If the camera is zoomed - game.camera.scale.x = game.camera.scale.y = 2;
It will cause a mismatch between box2d rendering view as well as TileMap layer scrolling.

For box2d debug view, I changed phaser.js: 
in 
    box2dWorld: function () {
...
        this.context.translate(-this.game.camera.view.x, -this.game.camera.view.y, 0);
+ this.context.scale(this.game.camera.scale.x, this.game.camera.scale.y); // fix
        this.game.physics.box2d.renderDebugDraw(this.context);
...

To fix tilemap layer scrolling, 
every time the camera's scale is changed, the layer's scrollFactorX and scrollFactorY must be updated to be divided by the camera's scale.x and scale.y

**Comment by hexus** [comment]
This seems to work for me:

```
layer.scaleFactorX = 1 / camera.scale.x;
layer.scaleFactorY = 1 / camera.scale.y;
```

`fixedToCamera` layers don't cater for this properly. They really seem to hate scaling of any kind.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
