### ISSUE TITLE
can not update value in  phaser object from method that is called from dom event

### ISSUE THREAD

**Issue by ihabZhaika** [photonstorm/phaser#2932]
Hi,
the issue is when try to update an variable in the phaser object class , not from [create(),preload(),update() etc..) , no thing get happens , as if no modification is done
this post has the same problem with code , so it may help.
[Forum post](http://www.html5gamedevs.com/topic/22849-phaser-and-angular-access-thisgame-from-the-dom/
)
More Description :
i am using a textbox to get input for the game , when the user enters a text i call a method that set the value to variable in the class that inherits from Phaser.State , but the value not get updated

phaser version :  Kore Springs 2.6.2
web framework : angular 2

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
