### ISSUE TITLE
cursor icon not changed if cursor not moving

### ISSUE THREAD

**Issue by shirofaii** [photonstorm/phaser#2933]
cursor state not changed if mouse not moving, but sprite change its position, scale, rotation etc

Steps to reproduce
* Open page: https://phaser.io/examples/v2/input/pixel-perfect-click-detection
* move mouse to the bear and stop it, wait until rotating bear slide under cusor
* cursor doesn't changed to hand until player move mouse

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
