### ISSUE TITLE
 Phaser.Physics.P2.Body anchor problem

### ISSUE THREAD

**Issue by ihabZhaika** [photonstorm/phaser#2935]
Hi,
in the [documentation](http://phaser.io/docs/2.6.2/Phaser.Physics.P2.Body.html) of the P2 written
> Note: When a game object is given a P2 body it has its anchor x/y set to 0.5, so it becomes centered.

which causes a lot of problems , because when the sprite[lets say a 32*32]  is added on x,y , the square of the tile is on x+16,y+16 because of the note above
now when i set the anchor to (0,0) the texture get updated , but the collision bounders still the same as if the anchor is (0.5,0.5)
Tried to use body.offset , but as above only the texture get updated , so did not work
Tried to use     sprite.body.setRectangle(sprite.width,sprite.height,16,16,0); ,but the collision stop to work

So what to do in this case ?

**Comment by ihabZhaika** [comment]
Update:
found solution 
`    sprite.body.setRectangle(sprite.width,sprite.height,sprite.width/2,sprite.height/2,0);
`
then apply the collision groups

but is the above scenario is bug or not ?

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
