### ISSUE TITLE
Issue with Bitmap fonts and accented characters

### ISSUE THREAD

**Issue by jansensan** [photonstorm/phaser#2940]
Issue: A bug in the rendering of accented characters of a Bitmap font
Phaser version: 2.6.2
Demo: https://github.com/jansensan/test-phaser-bitmap-font

There is an issue with certain punctuation characters and accented characters when using Bitmap font:

![image](https://github.com/jansensan/test-phaser-bitmap-font/blob/master/src/assets/issue-screenshot.png?raw=true)

As demonstrated from the image above, many characters are not rendered properly:
- Punctuation: ×÷±–…“”‘’
- Accented A's: àáâäåãāæ ÀÁÂÄÅÃĀÆ
- Accented E's: èéêëėęē ÈÉÊËĖĘĒ
- Accented I's: ìíîï ÌÍÎÏ
- Accented O's: òóôöøõōœ ÒÓÔÖØÕŌŒ
- Accented U's: ùúûüū ÙÚÛÜŪ
- Accented Y's and C's: ÿŸ çÇ

While it is not a guarantee against human error, I have spent a lot of time to ensure this issue does not stem from my code.

- Ensured the font data XML is set to UTF-8
- Wrapped offending characters in `<!CDATA[[]]>`
- Tested the mapping of each characters

This leads me to believe the issue is with the rendering of the characters in the library. However, is it because:

- Accented characters are simply not supported?
- There is a specific way to declare accented characters to display them in Bitmap font?
- An actual omission in the library surrounding those characters?
- Magic?

Thanks for any help you can provide.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
