### ISSUE TITLE
property columnWidth of game.debug.bodyInfo seems to be buggy

### ISSUE THREAD

**Issue by Spoink8** [photonstorm/phaser#2948]
Hi huys, 

Before all, thank for the amazing work done with the framework. Great job ! 

So let's start : 

I have tried to resize the bodyInfo with this 3 props : 

game.debug.font = '20px Courier';   WORKING !

game.debug.lineHeight = 25; WORKING ! 

game.debug.columnWidth = 50; NOT WORKING ! //This prop seems buggy, always fixed to 0 ?! 

I work on phaser 2.6.2 with cordova. But the bug appear too on firefox and chrome browsers.

Here a sample of code demonstrate my point (i hope is a bug and not a reflection of my missing skills)

[html.zip](https://github.com/photonstorm/phaser/files/691535/html.zip)

I hope you a very happy news years. 

Best regards !

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
