### ISSUE TITLE
IPad Pro Keyboard not recognized

### ISSUE THREAD

**Issue by ipante** [photonstorm/phaser#2953]
Keyboard events are not fired with the iPad Pro Keyboard.

**Comment by photonstorm** [comment]
Strange.. does it not fire normal window keyboard events? All Phaser does is listen for:

```
        window.addEventListener('keydown', this._onKeyDown, false);
        window.addEventListener('keyup', this._onKeyUp, false);
        window.addEventListener('keypress', this._onKeyPress, false);
```

If those don't come in, no event will happen within Phaser either.

I suggest you edit the input/Keyboard class and start adding in some debugging flags, to see what happens when, if at all.

**Comment by ipante** [comment]
Yeah, it's weird. I've tried a simple keydown event on Codepen with an addEventListener attached to the Body. Il works perfectly.

I'll throw some flags in Phaser classes to identify the issue.

**Comment by photonstorm** [comment]
Attach it to the window, like Phaser does, to see if it makes a difference.

**Comment by photonstorm** [comment]
Also Phaser won't start the Keyboard handler if the `Phaser.Keyboard` object is missing, so double check that isn't excluded somehow.

**Comment by ipante** [comment]
It also works [attaching it to the window](http://codepen.io/isaacpante/pen/ygYXJK?editors=0010).
But, for example, I can't get [this Phaser code](https://phaser.io/examples/v2/input/keyboard-justpressed) to work.

**Comment by photonstorm** [comment]
I wouldn't worry about it at that level yet. You need to determine if even the likes of `Keyboard.processKeyDown` is called first.

**Comment by ipante** [comment]
Ok. I'll check.

Question: is there some preventDefault mechanism included in the Phaser.Keyboard? I'm wondering if the events could be overwritten by some iOS shortcuts. Anyway, it could make sense for the cursors, but it looks strange for a simple letter.

**Comment by photonstorm** [comment]
They don't capture by default, you have to enable it with `Keyboard.addKeyCapture` - that doesn't stop iOS from preventing it getting the message in the first place though, just the event bubbling out again.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
