### ISSUE TITLE
Phaser 2.6.2 mobile safari, Phaser.ScaleManager.SHOW_ALL cause resize (video demo)

### ISSUE THREAD

**Issue by supermrji** [photonstorm/phaser#2955]
Phaser 2.6.2
I make a html tag overlay for finger scroll top to hide iphone safari's navgation.

### [Video demo](http://imgur.com/a/N2SBL)
in the video, when I scroll up and hide the navgation, `Phaser.ScaleManager.SHOW_ALL` cause a resize event , so canvas resize and cause navgation show again .

if I use `Phaser.ScaleManager.NO_SCALE` , it will be OK .
but canvas or camera both are wrong size.

How can I prevent `resize event` after navgation hide ?

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
