### ISSUE TITLE
[Feature Request] Allow Emitter Subclassing by returning particle

### ISSUE THREAD

**Issue by Secretmapper** [photonstorm/phaser#2972]
Phaser emitter class `emitParticle` returns false when there is no emitted particle, and true when there is an emitter particle.

It would be great if it returns the actual particle emitted when it can emit a particle, so that it's possible to further edit it's properties.

This use case arose when I subclassed the Emitter Class wanting to allow the emitter to explode in a 'circular' fashion. If emit Particle returned the particle instance it would enable something similar to:

```
  emitParticle () {
    const speed = 5
    const particle = super.emitParticle()

    [xv, yv] = normalize(1 * rand(), 1 * rand())
    
    particle.body.velocity.x = xv * rand() * (speed)
    particle.body.velocity.y = xy * rand() * (speed)
}
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
