### ISSUE TITLE
Impossible to unpause a game using a gamepad

### ISSUE THREAD

**Issue by WVI** [photonstorm/phaser#2973]
This Issue is about (delete as applicable)
* A bug in the API (always say which version you're using!)

I feel like this would take too long to set up in the sandbox, and I think the issue is self-explanatory: If you're controlling a game using the gamepad, and you use Phaser's game.paused bool to pause the game, you can't unpause it with controller input because Phaser's pause also stops polling all gamepad input. This applies up to the latest official version of Phaser 2, 2.6.2.

**Comment by hayesmaker** [comment]
+1

**Comment by iansmathew** [comment]
+1

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
