### ISSUE TITLE
setPreloadSprite Doesn't Work With Cache

### ISSUE THREAD

**Issue by splttingatms** [photonstorm/phaser#2974]
This Issue is about: A bug in the API
Phaser v2.5.0 setPreloadSprite - http://phaser.io/docs/2.5.0/Phaser.Loader.html#setPreloadSprite

Issue:
The setPreloadSprite function does not render the sprite if all the assets are loaded from cache.

Expected: 
Expected the function to render the sprite full width/height once all the assets are loaded, regardless of whether the assets came from cache or explicit load.

Example:
<https://jsfiddle.net/zpq8mftj/2/>
Run once to see the progress bar, load again and the bar does not appear. You can also check the "disable cache" setting under Network tab in Chrome Developer Tools to force behavior.

**Comment by samme** [comment]
v2.6.2 <https://jsfiddle.net/ymqo7u54/2/>

A workaround is simply to remove the crop in `create()`.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
