### ISSUE TITLE
Feature Request - relativeRescale()

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2976]
Just a method that scales an object relative to a point. It would be useful for zooming things in and out. I'm sure there's a magic math formula for this, but here is my current implementation:

```
function relativeRescale(sprite, scale, point) {
    var dx = point.x - sprite.x,
        dy = point.y - sprite.y,
        rx = dx / sprite.width,
        ry = dy / sprite.height;

    sprite.scale.setTo(scale);
    sprite.x -= ((sprite.width * rx) - dx);
    sprite.y -= ((sprite.height * ry) - dy);
}
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
