### ISSUE TITLE
Arcade's `overlap` modifies bodies

### ISSUE THREAD

**Issue by belen-albeza** [photonstorm/phaser#2977]
This Issue is about (delete as applicable)

* A bug in the API (2.6.2)

I'm finding that Acade's `overlap` modifies the bodies by setting the `touching` flags. However, the documentation states that:

> Unlike collide the objects are NOT automatically separated or have any physics applied, they merely test for overlap results.

Either this is a bug, or the documentation should clarify this.

**Comment by hexus** [comment]
I believe these flags are set for the developer's use in the collision/overlap callback, so they can tell which sides of the body are overlapping.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
