### ISSUE TITLE
overlapX and overlapY is never 0 after collision

### ISSUE THREAD

**Issue by noseglid** [photonstorm/phaser#2980]
This Issue is about

* A bug in the API (Phaser v2.6.2 | Pixi.js | WebGL | WebAudio     http://phaser.io ♥♥♥)

The issue can be [seen in the sandbox](http://phaser.io/sandbox/PPXmYQAF/play).

The top-left sprite should move 200 pixels to the right 500ms after the collision, but it's velocity is instantly reset. I have tracked the issue to the `overlapX` and `overlapY` being set after a collision.
The `collided` variable in [Body.js of arcade physics](https://github.com/photonstorm/phaser/blob/master/v2/src/physics/arcade/Body.js#L649) will then be true, casing the [stopMovement() method to be called](https://github.com/photonstorm/phaser/blob/master/v2/src/physics/arcade/Body.js#L673), effectively stopping all motion.

Am I using this incorrectly? If I manually set `overlapX/Y` to 0 after a collision, the subsequent `moveTo` functions work as expected.

**Comment by samme** [comment]
> The top-left sprite should move 200 pixels to the right 500ms after the collision, but it's velocity is instantly reset.

Did you set `body.stopVelocityOnCollide = true;`?

**Comment by noseglid** [comment]
> Did you set body.stopVelocityOnCollide = false?

Setting this makes it somewhat work. The second `moveTo` runs, but it no longer stops on collide (obviously) which I would like it to do.

**Comment by samme** [comment]
https://github.com/photonstorm/phaser-ce/issues/23

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.

**Comment by samme** [comment]
It was fixed in photonstorm/phaser-ce#23 ♥♥♥
