### ISSUE TITLE
Gamepad bug on disconnect, the game crashes

### ISSUE THREAD

**Issue by JUL1** [photonstorm/phaser#2982]
I tried using the gamepad callbacks to handle it but it didn't work

The issue :

https://i.imgjar.co/jar/44cBFjQsq0KcnLuTgFv2qQ.png

It happens when gamepad(s) is deconnected, it crashes the game entirely (freeze)

The fix I used :

https://i.imgjar.co/jar/GN3N4R3mqEqLLKPxgO-TNw.png

---------------------------------------------------------------------

Btw, rich, can you update the commandothug link ?

https://phaser.io/news/2015/09/commando-thug

It's hosted there now:

http://jul1.github.io/

Thx a bunch

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
