### ISSUE TITLE
Bug - P2 body angle is incorrect after `game.physics.p2.enable()`

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2985]
If I enable debugging on the body, the sprite is shown to be in the correct angle. However, this isn't actually the case. I've made my game in such a way that if the car _doesn't_ drive over a body, its tires leave marks, as shown here:
![bug2](https://cloud.githubusercontent.com/assets/5570098/22852660/746c0840-f049-11e6-892b-6ad962b6cb3b.png)
If I just enable the physics body, the body is rotated incorrectly (even though debug shows it as correct). If I cache the sprite angle, set it to `0`, enable the body and reset the angle, things are working fine. (to clarify, that specific sprite's angle `a` is `-90`, meaning that it's a 300x100 rectangle)

I think the problem might be in this method, which is called when the body is initialized:
```
setRectangleFromSprite: function (sprite) {

    if (sprite === undefined) { sprite = this.sprite; }

    this.clearShapes();

    return this.addRectangle(sprite.width, sprite.height, 0, 0, sprite.rotation);

}
```
It calls `addRectangle()` while providing `sprite.rotation`.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
