### ISSUE TITLE
Many WebGL errors running "Multiple-Shaders" example

### ISSUE THREAD

**Issue by zmertens** [photonstorm/phaser#2992]
After loading the "Multiple-Shaders" example found [on the Phaser website](http://phaser.io/examples/v2/filters/multiple-shaders) there are a plethora of WebGL errors starting with:
`WebGL: INVALID_VALUE: vertexAttribPointer: index out of range` . 

 - It doesn't appear that there are any attributes being used in the 2 shader programs.
 - This was tested on Google Chrome, *Version 56.0.2924.87 (64-bit)*
 - Longer list of errors:
```js
Phaser v2.6.2 | Pixi.js | WebGL | WebAudio     http://phaser.io ♥♥♥
256phaser.js:21233WebGL: INVALID_VALUE: vertexAttribPointer: index out of range
b.WebGLFilterManager.applyFilterPass @ phaser.js:21233
b.WebGLFilterManager.popFilter @ phaser.js:21102
b.Sprite._renderWebGL @ phaser.js:15122
b.DisplayObjectContainer._renderWebGL @ phaser.js:14605
b.DisplayObjectContainer._renderWebGL @ phaser.js:14605
b.WebGLRenderer.renderDisplayObject @ phaser.js:17694
b.WebGLRenderer.render @ phaser.js:17673
updateRender @ phaser.js:35426
update @ phaser.js:35316
updateRAF @ phaser.js:61331
window.requestAnimationFrame.forceSetTimeOut._onLoop @ phaser.js:61295
```

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
