### ISSUE TITLE
Full Screen Api - Chrome 56 | Android 4.4.2

### ISSUE THREAD

**Issue by SoproniOli713** [photonstorm/phaser#2999]
Currently using phaser 2.6.2

but when also tried to open the 
[Full Screen Example on Mobile Error](http://phaser.io/examples/v2/display/fullscreen)

Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.
Phaser.ScaleManager: requestFullscreen failed or device does not support the Fullscreen API

http://stackoverflow.com/questions/42755141/phaser-full-screen-api-not-supported

**Comment by ri0t** [comment]
This is also interesting in regard to electron, where its API offers BrowserWindow.setFullScreen - which i can call at any convenience. I am currently using that, but i have to abuse game.scale.setScale(BrowserWindow.getSize[0], BrowserWindow.getSize[1]) (private method!) to get phaser to render at the new size, which then circumvents the fullscreenScaleMode :(

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
