### ISSUE TITLE
Render works wrong.

### ISSUE THREAD

**Issue by yacand** [photonstorm/phaser#3008]
This Issue is about (delete as applicable)
* A bug in the API (v2.6.2 "Kore Springs" - Built: Fri Aug 26 2016 01:02:57)

When you use "*.addChild" or "*.visible = true" Phaser rendering display object to x=0, y=0 (first frame object blink top left screen) then object is showing in right position.
Help me do quickly fix in "phaser.js" if this possible.

**Comment by halilcakarr** [comment]
i believe you should download v2.6.2. I'm using the same build and i dont have any problem with ".addChild" or ".visible = true".

**Comment by yacand** [comment]
DisplayObject is blinking very quckly. See video top left - 4 spades blink there and then set right position (image card has right x,y before command addChild).
Same situiation with blue frame on card. First step blue frame show in old coordinates and then in right. Coordinates set before visible = true.

![2017-04-14_15-31-03](https://cloud.githubusercontent.com/assets/24897612/25043344/ee0b31bc-2127-11e7-8e75-a12b308d714a.png)
![2017-04-14_15-30-31](https://cloud.githubusercontent.com/assets/24897612/25043345/ee0b8b62-2127-11e7-84f8-9fd99fd1eed6.png)

[bug_video.zip](https://github.com/photonstorm/phaser/files/922040/bug_video.zip)

**Comment by yacand** [comment]
I can change code in phaser.js but perfomance is bad. Maybe do you know other way?

PIXI.DisplayObjectContainer.prototype.updateTransform = function () {

    if (!this.visible)
    {
        return;
    }

    this.displayObjectUpdateTransform();

    if (this._cacheAsBitmap)
    {
        return;
    }

    for (var i = 0; i < this.children.length; i++)
    {
        this.children[i].updateTransform();
        **this.children[i].updateTransform();**
    }
};

**Comment by yacand** [comment]
I researched more.
This happends only for when change from DisplayObject.visible = false to DisplayObject.visible = true.

**Comment by halilcakarr** [comment]
I see the problem know. But sorry i have no idea why this is happining. Maybe go and open a topic on www.html5gamedevs.com people's are using there more effective.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
