### ISSUE TITLE
tilemap layer render bug

### ISSUE THREAD

**Issue by pocketoy** [photonstorm/phaser#3010]
[bandicam 2017-04-20 15-43-59-392.zip](https://github.com/photonstorm/phaser/files/940857/bandicam.2017-04-20.15-43-59-392.zip)

```
         game.camera.bounds = null;
         this.zoomgrp = game.add.group();
         this.map = game.add.tilemap();
         this.layer = this.map.create('minemap', 100, 100, 16, 16);
         this.zoomgrp.add(this.layer);

         ....

         this.zoomgrp.scale.set(2);

```
and drag mouse (move camera position)
please view video.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
