### ISSUE TITLE
P2: Body does not consider parent transformation if sprite is a added as child to another sprite

### ISSUE THREAD

**Issue by linenolte** [photonstorm/phaser#3011]
For P2 physics engine the body which is used for collision detection does not consider the parent transformation if it is added as parent to another sprite.
See the following example: Sprite1 is a child of sprite2. If the bounds for collision detection are rendered the bounds for the pentagon are outside of the sprite. If I remove  the line sprite2.addChild(sprite1);
the bounds are rendered correctly. 
In my current impl of the game I do a rough collision detection by my own (just check the bounding box) without using P2 collision detection because of this problem.
 
thanks for your help

Holger

![grafik](https://cloud.githubusercontent.com/assets/27810720/25227851/657fdd32-25ca-11e7-83f1-b5e75daab181.png)

`<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>Phaser Hello World</title>
        <script type = "text/javascript" src="./phaser-ce-2.7.6/build/phaser.min.js"></script>

    </head>
    <body>
        <div id="gameContainer" class="game-container"></div>
        <script type="text/javascript">

            var game = new Phaser.Game(800, 600, Phaser.AUTO, 'phaser-example', {preload: preload, create: create});

            function preload() {
                game.load.image('circle', 'test/images/images.png', 225, 225);
                game.load.image('fuenfeck', 'test/images/fuenfeck.png');
            }

            function create() {

                game.stage.backgroundColor = '#ffffff';

                game.physics.startSystem(Phaser.Physics.P2JS);
                game.physics.p2.gravity.y = 1000;

                sprite1 = game.add.sprite(50, 400, 'fuenfeck');
                sprite1.scale.x = 0.5;
                sprite1.scale.y = 0.5;
                game.physics.p2.enable(sprite1, true);
                sprite1.body.clearShapes();
                sprite1.body.addPolygon({}, 0, 15, 10, 45, 40, 45, 50, 20, 25, 0);
                sprite1.body.data.gravityScale = 0;

                sprite2 = game.add.sprite(100, 200, 'circle');
                sprite2.scale.x = 0.5;
                sprite2.scale.y = 0.5;
                game.physics.p2.enable(sprite2, true);
                sprite2.body.setCircle(45);
                sprite2.body.data.gravityScale = 0;
                sprite2.addChild(sprite1);

            }

        </script>
    </body>
</html>`

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
