### ISSUE TITLE
[Question] Regarding Spine Support down the road

### ISSUE THREAD

**Issue by shibekin69** [photonstorm/phaser#3041]
Hi,

I read in one of the email subscription letters about supporting bone-animation packages like Spine and Creature. I'd just like to say that you guys might want to try to implement the latest Spine at the earliest possible time to see if it's possible or not - to weed out bugs caused by Phaser, or Spine-TS, or both, because it seems there are issues in the community phaser-spine plugin that can't be fixed with Phaser 2.x at the moment. 

The problem with Spine is that the devs didn't bother with a Phaser-specific implementation and just laid out a generic Typescript/JS Spine-TS. Unlike Creature, where the dev provides Phaser-specific support. But the problem with Creature is that quite frankly, the UI is a pain.

May I ask about the chances of the latest (or near latest) Spine and its features being supported in Phaser 3?

**Comment by photonstorm** [comment]
Thanks for opening this issue (a while ago now!) - I'm going to close it just because I want to keep this please tidy and focused on current live issues, rather than feature requests, but just to say that we fully understand how important Spine support is and we will definitely start exploring it. For updates please check out our weekly dev logs, when we work on it you'll see it mentioned in those.

**Comment by shibekin69** [comment]
Thanks for responding Rich! Looking forward to it. Based on my experience with using Spine on Phaser 2.x, I think you may want to look into the ability of treating Spine as a Phaser.Group object or a Phaser.Sprite object. In some use cases, being able to transform the Spine object as a whole when treated as a Group is useful, rather than only transforming the root bone when the Spine object is treated as a Sprite object.
