### ISSUE TITLE
Phaser 3 Example Crashes

### ISSUE THREAD

**Issue by magig** [photonstorm/phaser#3046]
Hi, I went to try out this Phaser 3 [example](http://labs.phaser.io/view.html?src=src\physics\matterjs\simple%20body.js) but got black screen - here's the console output from updated osX Chrome:

[console.txt](https://github.com/photonstorm/phaser/files/1292979/console.txt)

**Comment by photonstorm** [comment]
Matter.js isn't included in the build up on the examples repo because no work has been done on its API yet. You could comment it back in and build it yourself if you like (you can find the part you need in the `src/physics/index.js` file - then just build it) but I left it out of the Beta because it's massive! (adds 330KB)

**Comment by magig** [comment]
OK thanks!

**Comment by photonstorm** [comment]
Shout if you get stuck building it, I can shove a pre-built version on labs for you, but it's probably best to wait until the Matter.js API has been done tbh.
