### ISSUE TITLE
[Phaser 3] Click events not detecting sprite after calling setDisplayOrigin(0)

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3066]
I'm using Phaser 3 beta 5.

When I call `setDisplayOrigin(0)` on a Sprite, it doesn't react to input events anymore. More specifically, even if I click on the sprite, `event.gameObject` (from the click callback) will not refer to the sprite I clicked on. It does **not** happen when manually setting the displayOrigin by typing `sprite.displayOriginX = 0, sprite.displayOriginY = 0`. 

I first encountered the bug in Google Chrome 61.0.3163.100.  I managed to reproduce the bug with Firefox 56 as well in one of the examples, more specifically [this one](http://labs.phaser.io/edit.html?src=src\input\mouse\click%20sprite.js). It is enough to add one single line to `create()`, as follow:

```
var sprite = this.add.sprite(400, 300, 'eye').setInteractive();
sprite.setDisplayOrigin(0);     // this is the new line
```

Following this modification the sprite doesn't react to clicks anymore.

**Comment by photonstorm** [comment]
`displayOriginX / Y` are read only properties. Setting them directly won't actually change the origin values, which is why it appears to work (because it didn't actually change anything).

Calling `setDisplayOrigin` with zero will actually set the origin values to be Infinity, breaking input in the process (because I can't calculate where the sprite actually is). So the error is in that method really, as it should never let you set x or y to zero (or rather, if it does, it should not then calculate the origin based on it).
