### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by Twilrom** [photonstorm/phaser#3099]
Is there any official stance on which browsers Phaser 3 plans to support?
There are polyfills for at least IE 8, which seems pointless since that doesn't even support the `<canvas>` tag.
Would be good to have an official decision for the cut-off. Both for development and support issues. Is the intention to support any browser that has `<canvas>` support?

**Comment by Twilrom** [comment]
I meant a more complete list. What about Firefox? Chrome? Opera? Opera Mini's incomplete canvas support? Is there no decision as of yet?

**Comment by photonstorm** [comment]
It should be exactly the same as V2. We've never specified explicit versions of self-updating browsers like FF or Chrome in the past and has never caused an issue. Only for set-in-stone versions like IE9 or OS versions like iOS7+ etc did it really matter.

Because it's ES5 through-out there should be very few areas where it won't be compatible. When you get into API territory like Web Audio it's harder though. It would be easier to just list out a range of API / browser features we expect to be in place, rather than saying "FFx will work!" and then finding that actually, on Linux, with a certain GPU for example, it actually doesn't.

**Comment by Twilrom** [comment]
Alright. Thanks
