### ISSUE TITLE
Original tileid property for tiles (Feature request)

### ISSUE THREAD

**Issue by nkholski** [photonstorm/phaser#3150]
Proposed: a property to tiles holding the original tile id.

Why: It would be useful for resetting tiles to their original tile ids after manipulating a tilemap. Also, I've been experimenting a bit with animated tiles, and this original tile id could be used to identify which animation to apply while the tile id changes during the animation.

ping @mikewesthad

**Comment by mikewesthad** [comment]
Thanks for pinging me. Let me think about this more when I get a chance. 

Re: animation. My first thought is that tile animation - which would be great to have - would be better implemented as something similar to the existing animation systems in v3. E.g. having an `Animation` class that is responsible for updating a tile's index, rather than a `Tile` needing to have any "memory" of its past id.

**Comment by mikewesthad** [comment]
Circling back to this issue - I don't think it makes sense for a `Tile` instance to have an memory of it's past ID(s). Tile animation would be great territory for a plugin, or a potential PR that uses an `Animation` class.

That said, you could implement something like this with the existing API's `tile.properties`.

```js
// At setup:
layer.forEachTile(tile => {
  tile.properties.originalIndex = tile.index;
});
```

Or, if you are using Tiled, you can set up your animations using the editor there. When you load up your tilemap, you can access the animation data via `tile.getTileData()`. The structure of the tile data will look something like this:

```js
{
    "animation":[
        {
            "duration":100,
            "tileid":33
        }, 
        {
            "duration":100,
            "tileid":65
        }, 
        {
            "duration":100,
            "tileid":129
        }
}
```

Then you can use that however you want.
