### ISSUE TITLE
addColor Function missing

### ISSUE THREAD

**Issue by sftsk** [photonstorm/phaser#3223]
* A bug in the API (always say which version you're using!) v3.0

This function existed in 2.x but does not seem to be around anymore:
https://github.com/photonstorm/phaser/blob/7f196a01e7dba59a30601ff5a5bb53c818d1c967/src/gameobjects/Text.js#L498

Any other way to highlight some specific words?

**Comment by photonstorm** [comment]
We removed a lot of things like this and will look at adding them back via extensions to the game objects, rather than bloating them out like we did in v2 every time we had a good idea (and some not so good ideas!) - we will be allowing for devs to vote on which features they want us to work on next, so please take part in that when we announce it in the newsletter.

**Comment by sftsk** [comment]
Alright, cheers :)
