### ISSUE TITLE
Feature: Containers

### ISSUE THREAD

**Issue by vpmedia** [photonstorm/phaser#3294]
Hello!

I'm opening this to track the development status of the Container (Layer) feature.
I need this to be able to port my existing application, for multi screen layouts and gui components pure flat display list makes refactoring more difficult.
Ideally I could switch my app dependency between Phaser 2 and Phaser 3, this is the one major thing what I've found so far which makes porting a bit more time consuming.

https://github.com/photonstorm/phaser3-wip/tree/master/wip/container
https://phaser.io/phaser3/devlog/73 (Layers mentioned here)
http://www.html5gamedevs.com/topic/36051-does-phaser-3-need-containers/
https://groups.google.com/forum/#!topic/phaser3-dev/lBzGlTu3gQg
https://groups.google.com/forum/#!topic/phaser3-dev/CoKnWK56bk8

Thank you!

**Comment by photonstorm** [comment]
I'm afraid I'm going to close this issue. Not because we're not adding Containers, they are in R&D at the moment. But because I want GitHub issues to be used for actual code / implementation issues with the API - in order for this to be useful (i.e. to allow you to track development) we would have to remember to keep updating it, or referencing the issue number in our commits, and frankly this is just too much work for us. I'd rather you Watch the repo and monitor from there, or keep track in the Dev Logs for a more casual observation of progress.

**Comment by vpmedia** [comment]
I completely understand, thanks!

**Comment by xxzzrr6000000** [comment]
Close

**Comment by xxzzrr6000000** [comment]
Hllow world
