### ISSUE TITLE
displayOriginX and Y are not updated after texture change

### ISSUE THREAD

**Issue by Jerenaux** [photonstorm/phaser#3321]
With Phaser 3.1.2, see [this fiddle](https://jsfiddle.net/jtcuuuub/1/). I'm drawing two blocks on top of each other; same sprite, same position. Both have their origin set at 0.5 (I know it's default but it's to make it explicit). Only difference: the first one has its texture provided as an argument to the factory, while the second one has its texture set by `setTexture()`.

They should appear on top of each other, but they don't, the second one seems to be displayed with a origin of (0,0). Actually, as can be seen from the `console.log()` statements, the problem is that the second block has wrong `displayOriginX and Y` values, that were not updated after calling `setTexture()`.

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).
