### ISSUE TITLE
Config 'transparent' does nothing

### ISSUE THREAD

**Issue by kirillbunin** [photonstorm/phaser#3332]
Setting `transparent `in config to false, true, 0, or 1 does nothing. I would expect the background to be transparent instead of black when applied.

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).
