### ISSUE TITLE
Tree shaking for webpack projects

### ISSUE THREAD

**Issue by Luchanso** [photonstorm/phaser#3351]
Hey, @photonstorm can you adopt this project in future for tree shaking?
https://webpack.js.org/guides/tree-shaking/ 

It will reduce finally bundle

**Comment by photonstorm** [comment]
It won't reduce anything for the Phaser build files, because we explicitly define exactly what will be exported. If you `import Phaser` then you are given everything we set as being part of the core API. You can alternatively create your own entry point that exports exactly what you need and nothing more. Tree shaking is brilliant for your games, but less useful for a library where we need full control over what is included or not in the build.

If you want to create your own bundle then look at the differences between `src/phaser.js` and `src/phaser-arcade-physics.js` as those are our 2 current entry points. The first is basically "everything including the kitchen sink", the second is a more streamlined package. But you can take it even further, choosing exactly what you want in your bundle.
