### ISSUE TITLE
What is Phaser's philosophy on testing, automated or otherwise?

### ISSUE THREAD

**Issue by allanbreyes** [photonstorm/phaser#3361]
This issue is about **Testing** (discussion/question). I submitted my first PR to the project (#3360), but I was a bit surprised that there weren't any unit tests. This isn't a _request_ for automated testing; I wanted to ask what Phaser's philosophy on testing is. Concretely:

1. Is automated + CI testing on the roadmap?
2. Lacking automated tests, how can contributors test to make sure that a change/addition/deletion doesn't break something? e.g. is there a particular `phaser3-examples` thing to manually test?

FWIW, as a newcomer, I was hesitant about submitting the PR because I wasn't sure what side-effects it may have. I see the challenges in WebGL/canvas-based testing... I wish I had a concrete suggestion, but I have no idea how to do integration tests w/ graphics, animations, etc. nor if there exists any open source tooling for it. Thanks! :heart: this project so far!

**Comment by hexus** [comment]
To make a small contribution to this discussion, I know the team plan to add example links to the docblocks of relevant code. That will at least be one way to confirm the robustness of some changes.

**Comment by bradharms** [comment]
I seem to recall seeing unit tests on the Gantt Chart but it's not there now.

**Comment by Antriel** [comment]
I have no idea about future plans regarding testing, but the examples repo has a basic chrome-puppeteer based testing that could be improved to act as proper regression tester. One issue it has is that it takes quite some time to run (an hour or so).

**Comment by allanbreyes** [comment]
@Antriel I think your on to something. Even if we used `chrome-puppeteer` to screenshot some rendered examples as artifacts, it's a really fast way to see if any regressions were introduced. Heck, maybe it's just one canary that draws and moves a couple sprites. The screenshot can then be diffed to see if something totally broke rendering, messed up positioning, etc.

**Comment by hexus** [comment]
I wonder how easy it would be to run the tests in parallel. One hour sounds like a bit of a wait!

**Comment by Antriel** [comment]
@allanbreyes screenshot support is already implemented, along with basic console error checks, but to be able to diff the results, they would need to be deterministic, i.e. running in special phaser mode that would run exactly x frames with exact timestep (and avoiding other non-deterministic things like Math.random)

@hexus It already does that. The one hour comes from running over 1000 examples, letting each run for 5 seconds to settle.
I was testing that around, on my laptop with i7 7700 (4 threads with HT) and 16GB ram, I got best speed with 4 instances. Chrome spawns a LOT of processes, and likes to eat ram. It could be probably improved by making phaser run in some kind of setImmediate loop instead of RAF (less memory swapping and other overhead), and by not actually rendering before it's 'screenshot' time (which could be made directly from phaser API instead of relying on puppeteer's one). Further improvement might be running specific non-visual examples in nodejs without chrome, in headless mode. All this would take some work though.
