### ISSUE TITLE
Unexpected behaviour of LoaderPlugin#progress event

### ISSUE THREAD

**Issue by vinerz** [photonstorm/phaser#3384]
* A bug in the API (3.2.1)

I am relying on `LoaderPlugin#progress` event in order to create a progress bar indicator on the Preload state of my game. However, the event value does not reflect the real progress state as it should be.

As I can see at Phaser's source code, the event uses `this.list.size` to calculate loaded assets, but it does not take into account the still remaining `inflight` requests.

The result is that the progress bar displays 100% loaded even before the latest assets in the queue are finished loading. If the asset is big enough (such as an audio file), the 100% stays there for multiple seconds on slow mobile networks before dispatching the `complete` event.

**Comment by rblopes** [comment]
Something to do with `maxParallelDownloads`. If you set it to 1, the progress will only report 100% in the very last file. Otherwise, will trigger 100% as many times the value of `maxParallelDownloads` is set.

## Screenshots
<details>
<summary>With default <code>maxParallelDownloads</code> (4)</summary>

![spectacle ti6190](https://user-images.githubusercontent.com/61425/37343431-513ff126-26a6-11e8-9f01-60fb3fb44aa6.png)
</details>
<details>
<summary>With <code>maxParallelDownloads</code> set to 1</summary>

![spectacle pe6190](https://user-images.githubusercontent.com/61425/37343491-79ac3912-26a6-11e8-87c5-d1c515587918.png)
</details>

## Sample code
<details>
<summary>Sample code (<a href="https://jsfiddle.net/rblopes/u1zvuun6/">live</a>)</summary>

```js


const images = ['advanced_wars_tank', 'asuna_by_vali233', 'atari800xl', 'bikkuriman', 'bsquadron2', 'cakewalk', 'chain', 'diamond', 'ghost', 'helix', 'mouse_jim_sachs', 'palm-tree-left', 'parsec', 'phaser', 'phaser2', 'platform', 'red_ball', 'rgblaser', 'shinyball', 'shmup-ship', 'splat', 'thrust_ship', 'tinycar', 'yellow_ball']; 

new Phaser.Game({
  width: 400,
  height: 300,
  scene: [{
    key: 'default',
    loader: {
      baseURL: 'https://labs.phaser.io/',
      path: 'assets/sprites/',
      crossOrigin: true,
      //maxParallelDownloads: 1
    },
    preload() {
      images.reduce((o, k) => o.image(k), this.load)
        .on('load', ({key}) => console.log(`Loaded '${key}'...`))
        .on('progress', k => console.log(k));
    },
    create() {
      //for (const texture of this.textures.getTextureKeys()) {
      //  const x = Phaser.Math.RND.integerInRange(50, 350);
      //  const y = Phaser.Math.RND.integerInRange(50, 250);
      //  this.add.image(x, y, texture);
      //}
    }
  }]
});
```
</details>

**Comment by samme** [comment]
I think the issues implies the correct formula would be

```javascript
this.progress = 1 - ((this.list.size + this.inflight.size) / this.totalToLoad);
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
