### ISSUE TITLE
Firefox, WEBGL, map uncorrectly displayed

### ISSUE THREAD

**Issue by Zykino** [photonstorm/phaser#3407]
This Issue is about
* A bug in the API ( Phaser v3.2.1 (WebGL | Web Audio) )

Saw on Firefox 59.0 (64bits)
In WEBGL the map does not look good (I do not see anything with my tiles and map)
https://codepen.io/anon/pen/mxrWqq
If we switch it to CANVAS instead of WEBGL (or AUTO) the map is shown correctly.

If your Issue contains _any_ form of hostility it will be instantly closed.
**Be nice. We do this for free.** And we love it :heart:

**Comment by photonstorm** [comment]
The error was caused because you were doing `load.spritesheet` and passing that as the tileset, instead of `load.image`. It worked in canvas because it didn't use the tile size for the UV data. However, we've updated the WebGL renderer for static layers to support this, so you can now actually pass in an image or a spritesheet, and it'll just treat the sheet as a plain image. This is now fixed in master.
