### ISSUE TITLE
.setOffset(x, y) not working on static group physics bodies

### ISSUE THREAD

**Issue by DouglasLapsley** [photonstorm/phaser#3465]
Version: 3.3.0

Creating a static group as follows and then offsetting the body of the gameObject created within it returns an error.

```
this.platformGroup = this.physics.add.staticGroup();
let plat = this.platformGroup.create(200, 100, 'sprites', 'platform');
plat.body.setSize(300, 20).setOffset(0,20);
```
.setSize() works fine.  .setOffset() fails with the following error:

`ERROR TypeError: plat.body.setSize(...).setOffset is not a function`

Thanks!

**Comment by josephjaniga** [comment]
@photonstorm What's the expected behavior? I'd love to get a pull request in on this one.  I've a local branch providing StaticBody with the setOffset method working now and eliminated the above error.

But as it stands, that alone isn't enough to actually implement the body offset.  If `StaticBody`(ies) are expected to have offset functionality, I can put that in.

Thanks

**Comment by josephjaniga** [comment]
Took a crack at this, hoping to talk it over see if this makes sense.

**Comment by DouglasLapsley** [comment]
Nice one, thanks.  I look forward to hearing what the Phaser Gurus say :)

**Comment by photonstorm** [comment]
PR merged, thanks both. Discussion can be tracked on #3541
