### ISSUE TITLE
matter.add.gameObject(this) causes a collision event

### ISSUE THREAD

**Issue by alexandernst** [photonstorm/phaser#3485]
If I do `this.scene.matter.add.gameObject(this);` in the constructor of a class that inherits from `Matter.Image` (probably happens with any `Matter.` type), I get a collision event of the image itself collisioning with the body that is being added.

Is that an expected behaviour?

**Comment by photonstorm** [comment]
I don't really get what you're trying to do. Show some code please.

**Comment by alexandernst** [comment]
I have this in my `Main` class (entrypoint).

        this.matter.world.on('collisionstart', (event) => {
            event.pairs.forEach(pair => {
                let {bodyA, bodyB} = pair;
                let objs = [bodyA, bodyB];
                objs.forEach(obj => {
                    let go = obj.gameObject;
                    if(go) {
                        let [_obj] = objs.filter(x => obj.id !== x.id);
                        //console.log("emitting collision", _obj);
                        go.emit("collision", _obj);
                    }
                });
            });
        });

I use this so I can subscribe to the collision events on a per-object basis instead of having to keep my collision logic in one place.

I have this in my `Player` object.

        this.on("collision", this.collision);
        this.scene.matter.add.gameObject(this); // <--- bug?

If I leave the second line uncommented, I get a collision event right after creating the player object. I think that this happens because the image is colliding with it's own physics body.

If I comment the second line, I don't get that initial collision event.

**Comment by hexus** [comment]
An image can't collide with it's own physics body, so it must be colliding some other physics body in the Matter world.

**Comment by alexandernst** [comment]
That is the only thing in the entire scene (aside from a tile map). Can it collide with a tile map?

**Comment by hexus** [comment]
After discussing, it turns out alex was extending MatterImage and then calling `this.scene.matter.add.gameObject(this);`.

I've suggested to extend `Image` instead, and wrap the custom class up as a MatterObject using `this.matter.add.gameObject(image);` from the scene. Hopefully that sounds about right.

**Comment by harriscory730** [comment]
Yea I am ready 6015516712


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Chris Andrew <notifications@github.com> Date: 3/31/18  12:23 PM  (GMT-06:00) To: photonstorm/phaser <phaser@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [photonstorm/phaser] matter.add.gameObject(this) causes a
  collision event (#3485) 
If you've prepared the layer's tile bodies with this.matter.world.convertTilemapLayer(layer);, yes.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/photonstorm/phaser","title":"photonstorm/phaser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/photonstorm/phaser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hexus in #3485: If you've prepared the layer's tile bodies with `this.matter.world.convertTilemapLayer(layer);`, yes."}],"action":{"name":"View Issue","url":"https://github.com/photonstorm/phaser/issues/3485#issuecomment-377709160"}}}

**Comment by hexus** [comment]
@alexandernst, feel free to close this if it's no longer an issue.

**Comment by alexandernst** [comment]
@hexus I'm not quote convinced this should be closed. There are several problems with the example I gave you, and we just made a workaround. The layer itself had a body, as well as the Image class (which is shouldn't, right?).

**Comment by hexus** [comment]
I may have been wrong about the layer having a body, but extending `MatterImage` in the way you were wasn't quite right.

I think it would be better to provide a simplified reproduction of the issues you're facing, then we can address them properly here.

**Comment by photonstorm** [comment]
I need a fully working code sample to even understand what's going on here now. Codepen / jsbin please.

**Comment by hexus** [comment]
This should probably be closed. It's just incorrect usage of `matter.add.gameObject()`.

**Comment by alexandernst** [comment]
Yes, I'll provide a code example, I just haven't had time to do it this week. As late as monday evening I'll be able to upload a .zip containing minimal code required to repro the bug.

**Comment by alexandernst** [comment]
I just made a minimal repro test code for this bug, and then I went ahead and tested it with 3.4.0 and 3.5 beta.
With 3.4.0 it breaks very badly, but with 3.5-beta everything works as expected, so I think we can close this :) 👍
