### ISSUE TITLE
Funny jsdoc causes issues in d.ts generation

### ISSUE THREAD

**Issue by erd0s** [photonstorm/phaser#3493]
**This repo is for Phaser 3 related issues only**

Official support for Phaser 2 has now ended. We urge you to visit the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) for continued development of v2.

This Issue is about (delete as applicable)

* An error in the documentation
* An error in the TypeScript defs

--------
In `Config.js` there's some jsdoc definitions that look like `* @property {HTMLCanvasElement} [?canvas=null] - [description]`, which end up as `"?canvas": HTMLCanvasElement;` in the d.ts file.
* https://github.com/photonstorm/phaser/blob/master/src/boot/Config.js#L61
* https://github.com/photonstorm/phaser3-docs/blob/master/typescript/phaser.d.ts (erm i can't link to the line because the file is big! But it's line 320)

I think we can just get rid of the ? to fix this since the []'s already indicate that it's optional.

**Comment by erd0s** [comment]
OK! I made a PR https://github.com/photonstorm/phaser/pull/3494

**Comment by photonstorm** [comment]
For anyone else coming to this issue: There are lots of cases of this (not just in Config.js), some are valid, some are not. The rules are:

1) If you see a ? at the start of a _data-type_ (not the name) it means it is nullable. These should only be set for class properties. For configuration objects the ? is not required.

2) If you see a ? at the start of a property / parameter _name_ then it's a mistake and should be removed.

Closing this issue because the relevant PR is now merged.
