### ISSUE TITLE
Improved/Updated Documentation

### ISSUE THREAD

**Issue by iway1** [photonstorm/phaser#3601]
Currently, there is no documentation for Phaser 3 specifically, and the old documentation for Phaser 2.6 is lacking. Specifically, the descriptions of properties/methods don't do a good job of explaining exactly why and how you would use them. Many of the the descriptions are of properties are of the form "A reference to {some phaser interface}." I've created new documentation for a majority of the properties/methods for the Game object, based on the documentation for 2.6. In the new documentation, for each member I describe why you would use it and how you would use it, as well as short code examples showing a use case for that property/method. Is it possible for me to contribute with this documentation, and is there any chance of an updated effort towards documenting Phaser 3 in an attempt to make learning Phaser easier? Thank you.

**Comment by iamchristopher** [comment]
There is plenty of documentation available. Refer to [the repo](https://github.com/photonstorm/phaser3-docs) for details and to contribute.

**Comment by photonstorm** [comment]
Documentation needs to be provided via PRs to the main repo. If it's extensive, i.e. adds lots of text into the source, then we'll need to extract it out into single files and reference via a jsdoc `@tutorial` tag to avoid making the code unmaintainable.

Please understand that Phaser 2 wasn't born with documentation, it took many _years_ to build it up and tweak it. Phaser 3 is barely 2 months old and being refined daily.

As it stands there are 6,922 elements in v3 that need documenting (it was a thousand more than this a month ago). Even at a super-fast rate of 1 minute per element (which is highly unrealistic when averaged out), that's still nearly 40 days worth of work, assuming 3hrs per day dedicated to documenting, and no days off.

So yes, if people want to help, we'll gladly accept it via PRs, because it's one hell of a mammoth task.
