### ISSUE TITLE
WebAudioSoundManager fix causes document.body is undefined error 

### ISSUE THREAD

**Issue by squilibob** [photonstorm/phaser#3649]
The WebAudioSoundManager fix that attaches events on the document.body to fix Chrome v66+ not playing audio until a user gesture is received is causing an error on an older version of Firefox. There is no error using Chromium (latest build) but on Firefox 52 document.body is undefined. If I add a check to phaser.js then the game runs fine including sound

`        if (!document.body) {
                _this.unlocked = true;
        } else {
`

**Comment by photonstorm** [comment]
I'm not sure what's more alarming. The fact we have to fix this for Chrome at all, or the fact that Firefox has no concept of `document.body`.

**Comment by Antriel** [comment]
Maybe it's undefined because the game is instantiated before body loads? i.e. script is called in <head>?

**Comment by photonstorm** [comment]
Nope, it can't be that because Phaser waits for a DOM Load event before starting any systems, including Web Audio.

MDN implies FF has supported body since version 2, but it was bugged until version 60?! Which seems batshit crazy to me, but there we go: https://developer.mozilla.org/en-US/docs/Web/API/Document/body
