### ISSUE TITLE
graphics.clear() not working properly in CANVAS mode (drawn strokes remain)

### ISSUE THREAD

**Issue by Antriel** [photonstorm/phaser#3655]
Version 3.7.1
This code will draw a nice filled triangle as the drawn lines will keep getting rendered.
```js
var i = 0;
function update() {
    graphics.clear();
    graphics.moveTo(0, 0);
    graphics.lineTo(100 + i, i++);
    graphics.strokePath();
}
```

**Comment by Antriel** [comment]
Oh, then it's me not using the API properly, that's ok then.
The separate canvas idea is pretty nice, but as you said, unrelated.

**Comment by raisen** [comment]
Hi @Antriel , were you able to figure out a solution for this problem? I have a similar problem which I posted on #3965 . I think your bug is more related to mine than #3886. 

If you look at both my examples, it works as expected in WebGL so I'll stick with WebGL for now until I figure out a solution for canvas.

**Comment by Antriel** [comment]
Yes, the solution is exactly what rich said. See my answer: https://github.com/photonstorm/phaser/issues/3965#issuecomment-415135124

**Comment by Antriel** [comment]
For future reference, the solution to my original code is:
```
var i = 0;
function update() {
    graphics.clear();
    graphics.beginPath(); //add this
    graphics.moveTo(0, 0);
    graphics.lineTo(100 + i, i++);
    graphics.strokePath();
}
```
