### ISSUE TITLE
Scene Transitions causes the rendering order of scenes to be swapped in v3.7.1

### ISSUE THREAD

**Issue by Hsaka** [photonstorm/phaser#3656]
The first time a scene transition happens, everything is normal. On a subsequent transition, the rendering of the scenes appears to be switched.

Compare https://labs.phaser.io/view.html?src=src\scenes\transition%20test%201.js&v=3.6.0 with https://labs.phaser.io/view.html?src=src\scenes\transition%20test%201.js&v=3.7.1

Steps to reproduce: On v3.7.1 of the example above, notice on the first run, the planet appears behind the girl as the transition happens. Click through until the first scene appears again. Now the planet appears above the girl as the transition happens. The same happens with the other transition example https://labs.phaser.io/view.html?src=src\scenes\transition%20test%202.js where the PacMan scene appears above, then below the first scene.

**Comment by photonstorm** [comment]
Finally had a look at this, and the Scenes swap position because they use `moveAbove` and `moveBelow` in the transition configs, which moves them around the Scene list. I'm happy this is doing what it's meant to do.

The question is if they should only move for the duration of the transition and then move back again after it completes? Although that feels a bit strange to me. It could be a new config option perhaps.
