### ISSUE TITLE
setScrollFactor not behaving as documented

### ISSUE THREAD

**Issue by GGAlanSmithee** [photonstorm/phaser#3662]
According to the [documentation](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.Text.html#setScrollFactor), `setScrollFactor` should make the object move in sync with the camera if set to a value of 1, and not move at all if set to a value of 0. The actual behavior is the other way around though.

reproduction:

https://jsfiddle.net/29oc1849/5/

**Comment by samme** [comment]
> A value of 1 means it will move exactly in sync with a camera. A value of 0 means it will not move at all, even if the camera moves.

I think that's correct, but _in sync_ may be giving the wrong impression. It means in equal proportion.

**Comment by GGAlanSmithee** [comment]
@samme , yeah the wording was a bit off, but you agree that the implementation and documentation does not match?

**Comment by samme** [comment]
No, I think they match.

1 means a camera scroll of +1px (on the game world) shifts the rendering -1px (on the game canvas). 

0 means a camera scroll of 1px (on the game world) shifts the rendering 0px (on the game canvas).

**Comment by GGAlanSmithee** [comment]
Hmm, if that's the case, I think the documentation could state this more clearly in other words. I can still not interpret it any other way.

**Comment by photonstorm** [comment]
This is working as intended and the jsfiddle demonstrates it. The scroll factor value is the relationship between the camera movement and the object. So a value of 1 means 1:1, i.e. the camera moves 1px, the object will move 1px. A value of 0 means the object never moves. A Value of 2 means for every 1px the camera moves, the object will move 2px, and so on. This is why a value of 1 keeps the object in-sync with the camera, because however much it moves, the object retains its place in the game world.

**Comment by GGAlanSmithee** [comment]
@photonstorm thanks for the additional explanation, 

I guess my only concern after @samme's previous explanation was the language in the documentation, but I guess it's a PEBCAK :)
