### ISSUE TITLE
Bug: unable add custom file loader after game booted

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#3671]
(Phaser 3.8.0) LoaderPlugin [installs file loaders](https://github.com/photonstorm/phaser/blob/master/src/loader/LoaderPlugin.js#L104) in constructor. After this operation, any custom file loader could not be added into loader by [FileTypesManager.register(...)](https://github.com/photonstorm/phaser/blob/master/src/loader/FileTypesManager.js#L41). 
Thus custom file loader only could be added in game configuration like phaser example does.

**Comment by photonstorm** [comment]
A custom file loader can be added either via the game config, or via a plugin loaded from the Loader / local code / installed via a Scene. The only limitation is that the Loader that loads the plugin containing the custom file type cannot then have it added to itself, which is a fair enough limitation imho.

**Comment by rexrainbow** [comment]
Sorry I had not provide sample code, here it is-

[Load custom file loader plugin in game config](https://codepen.io/rexrainbow/pen/zjMopV), message shown on console. The plugin and loader are all work.
[Load custom file loader plugin by this.load.plugin](https://codepen.io/rexrainbow/pen/rvdEjq), message shown on console. The plugin loaded success, but custom file loader did not add to loader.

**Comment by photonstorm** [comment]
Yes, this is exactly what I would expect. The Loader instance that loads the plugin with a file type cannot use it, because the Loader has already been created. To work with this you need to structure things differently. Either use the game config, or if you can't, use a Boot scene that is responsible for loading any assets your Preloader needs. Then move to the Preloader Scene, and because it'll be a new instance of the Loader, you'll be able to access new file types from it.

**Comment by rexrainbow** [comment]
Thank you for explaining it, I will wtite down this constrain into my note.

**Comment by rexrainbow** [comment]
@photonstorm 

Phaser 3.9.0, custom file loader could install into [current scene](https://github.com/photonstorm/phaser/blob/master/src/plugins/PluginManager.js#L796).
But only **scene plugin** has scene parameter in constructor, should I turn the plugin type from global to scene if I try to use this feature? Is there any sample code for this new feature?
