### ISSUE TITLE
Resizing doesn't change render area on mobile

### ISSUE THREAD

**Issue by TicknorN** [photonstorm/phaser#3674]
On mobile, a full-page game does not render correctly after changing the orientation of the phone.
I tested this in Chrome for Android, and Chrome for PC using the "mobile" inspector (device toolbar enabled).

Code/How to reproduce:
https://codepen.io/TicknorN/full/BxvBWW
Visit that page (full page mode) in mobile or in Chrome Mobile Inspector in portrait mode (use a set resolution and not "responsive mode"), then refresh the page. If you switch to landscape mode on either, the render area does not correctly resize, even when Chrome is switched back to normal PC view.

This issue is experienced via both the WebGL & Canvas render methods.

**Comment by photonstorm** [comment]
Looking at your code I can't see anywhere where the camera bounds are updated after the resize (see this example for one way to do it): http://labs.phaser.io/view.html?src=src\game%20config\game%20resize.js

**Comment by TicknorN** [comment]
Oh you're right; that fixed it.

I'm sorry; I thought I had already looked through the camera documentation and ruled it out.

Any idea why this only happens on mobile?

**Comment by photonstorm** [comment]
It'd happen on desktop too, but maybe you don't notice it because the initial camera bounds were large enough that after resizing they're still displaying anything. I.e. if you load with a really tiny browser window, then resize it bigger, I would expect it to still appear cut-off (without the camera bounds fix obviously) even on desktop.
