### ISSUE TITLE
Stream audio content (i.e. game music)

### ISSUE THREAD

**Issue by oktayacikalin** [photonstorm/phaser#3681]
While working on my game (https://www.gemhunters.de) I tried to port my old music assets. I ended up converting the mod and xm files to ogg.

When the game tries to load a 3-6 MB ogg file, the loader blocks the user for quite some time.

To avoid this I'm now creating a new Audio() object myself and add the necessary blur and focus event actions to it.

It would be great If you could add a proper loader for streaming audio files.

For now I hacked my codebase a bit. The music is having the type audioStream in the pack file and I've written a helper to extract the URL for creating the Audio object.

**Comment by photonstorm** [comment]
The problem is that the Phaser Sound Manager assumes you're using either Web Audio or legacy Audio, and will then pick either one or the other based on browser support (and your game config settings, you can override the choice from that.) - so if it detects web audio it uses it for everything. The Sound Manager is an instance of either one or the other, but what this will require is support for both running at the same time. Or a way to stream from an Audio tag via Web Audio, which is likely possible, but I've never looked into it.

**Comment by oktayacikalin** [comment]
Just to give you some feeling:
For example on my smartphone my game now starts in about 1-2 secs and not the 10-15 from before.

**Comment by photonstorm** [comment]
Glad you got it working. Doesn’t change the fact it’s still a significant API update to get the feature request in.

**Comment by photonstorm** [comment]
Thank you for opening this feature request (all those months ago!). As the development of Phaser 4 has now started I am tidying-up the repo and closing off old issues that won't be directly fixed or implemented in Phaser 3 by me. I would still consider community PRs that address this issue, however, and have left the GitHub tags intact so others can track them if they wish to get involved. However, I'm afraid this is no longer a feature that will be added to v3.

**Comment by samme** [comment]
- [Audio tag loader](https://phaser.discourse.group/t/audio-tag-loader-phaser-3/12846)
- [Stream audio in Phaser v3.60](https://phaser.discourse.group/t/stream-audio-in-phaser-v3-60/13658)
