### ISSUE TITLE
Can't scale texture inside tileSprite

### ISSUE THREAD

**Issue by Legomite** [photonstorm/phaser#3702]
I'm using a small texture, but I want it to be much larger than it actually is when it's being used inside a tileSprite. I believe it was possible in Phaser 2 using tileScale, but it's not working in this version.

**Comment by wildman1985** [comment]
))lLp0

On May 25, 2018 8:26 PM, "Legomite" <notifications@github.com> wrote:

I'm using a small texture, but I want it to be much larger than it actually
is when it's being used inside a tileSprite. I believe it was possible in
Phaser 2 using tileScale, but it's not working in this version.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/photonstorm/phaser/issues/3702>, or mute the thread

**Comment by photonstorm** [comment]
It’s not a feature in v3. There are no immediate plans to add it, but I’ll leave it open as a feature request for now.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
