### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#3719]
I'm using Drag & Drop, and as I saw drop zone is being detected based on pointer x and y positions. I'm right? And if yes, is it expected behavior for drop ?
So I've a case when my sprite must be scaled and during dragging my mouse is going out of sprite, so when i'm trying to put it in visually there, where i want, my pointer isn't there, so dropzone isn't that one, which i want.
I've done some testes and sow, if there is a `gameObject.setOrigin(0.5)` line in drag function,  my sprite saves its relative position based on active pointer. So i think that expected behavior of drag must be this way. If I'm right, it mean that transforms doesn't work properly and origin point doesn't update on scale change.
Please, check it @photonstorm . Thanks for attention

```
var config = {
    type: Phaser.WEBGL,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);

function preload ()
{
    this.load.atlas('cards', 'assets/atlas/cards.png', 'assets/atlas/cards.json');
}

function create ()
{
    var image = this.add.image(400, 300, 'cards', 'clubsKing');

    //  Make interactive
    image.setInteractive();
    image.setScale(image.y / config.height)
    //  Make draggable
    this.input.setDraggable(image);

    this.input.on('dragstart', function (pointer, gameObject) {

        this.children.bringToTop(gameObject);

    }, this);

    this.input.on('drag', function (pointe, gameObject, dragX, dragY) {
        gameObject.setScale(gameObject.y / config.height)
        gameObject.x = dragX;
        gameObject.y = dragY;
        // gameObject.setOrigin(0.5) // uncomment this line to see expected behavior
    });
}
```

**Comment by photonstorm** [comment]
It happens because when the drag event _starts_ it sets the `input.dragX/Y` values to be the difference between the position of the pointer and game objects position. Those values are then used throughout the drag event as an offset for the pointer position. But you're changing the offset immediately by adjusting the scale. so the offset is no longer correct, and the more you scale it, the more incorrect it becomes.

This is quite an edge case but worth supporting I guess, it'll mean it'll have to recalculate the offset every frame which is a pain (right now it does it just once at the start) but probably worth doing all the same. Will have a think about it, as I'm redoing the input system for 3.10 anyway.

**Comment by photonstorm** [comment]
I've changed my mind about this one, it won't be supported natively because it's trivial to support in your drag callback:

```
        gameObject.x = pointer.x;
        gameObject.y = pointer.y;
```

Use that instead of the `dragX` and `dragY` values and it'll work fine.
