### ISSUE TITLE
Bug: multi-drag in a single game object

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#3757]
In this [phaser 3 example](https://labs.phaser.io/view.html?src=src\input\multitouch\multi%20drag.js), each game object could be dragged by a touch pointer, it works fine.
How about multi-drag in a single game object? This game object could be dragged by these touch pointers, too. But the behavior might be incorrect, like `dragX`, `dragY` .

In `InputPlugin.js`,
1. set [`input.dragX` based on a touch pointer](https://github.com/photonstorm/phaser/blob/master/src/input/InputPlugin.js#L874)
    ```javascript
    input.dragX = pointer.x - gameObject.x;
    ```
2. set [variable `dragX` based on previous pointer](https://github.com/photonstorm/phaser/blob/master/src/input/InputPlugin.js#L962)
    ```javascript
    var dragX = pointer.x - gameObject.input.dragX;
    ```

In *multi-drag in a single game object* case, pointer in step 1 and step 2 might not be the same.

**Comment by photonstorm** [comment]
It feels highly strange that you would want to start dragging an item with finger 1, then carry on dragging it with finger 2 without having let go with finger 1 first. Or to drag a single item with 2+ fingers. I literally cannot think of a reason why that needs to be supported.

**Comment by rexrainbow** [comment]
Agree. Single dragging per object is enough, imo. So it is better to add some conditions to avoid dragging by multiple pointers. PR added.

**Comment by photonstorm** [comment]
Thanks for opening this issue, and for submitting a PR to fix it. We have merged your PR into the `master` branch and attributed the work to you in the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). If you need to tweak the code for whatever reason please submit a new PR.

**Comment by joelmalone** [comment]
Hey there!  I have a use case for multi-drag on a single object.

(Excellent work btw, I love the project!)

In an app I'm working on, the user drags "paper cutouts" (physics sprites) around the screen.  I use spring constraints to perform the actual drag, which gives a sense of weight to the sprites and feels more genuine, as if you were dragging them across a tabletop by hand.  It is natural for the user to use two fingers at once to drag a single object so they get better control over how the sprite rolls as they drag it.

I've forked the code to re-enable multi-drag on a single object (reverting #3767), which works well, but the `dragend` event doesn't fire for the second (and subsequent) drags.  This is due to the single-drag architecture in `src/input/InputPlugin.js`.  Needs more work.

My question is, do you think it would be worthwhile for me to submit a PR to support multi-drag?  Do other people need it?

As it would be a behavioural (and potentially breaking) change, I would make it configurable per-object.

So the proposed PR would do the following:

* Add a new opt-in option to enable multi-drag per-object (e.g. `stickerSprite.setInteractive({ draggable: true, multiDrag: true })`
* Modify `src/input/InputPlugin.js` to respect this setting when managing drag states.
