### ISSUE TITLE
graphics.Arc 0-360 deg not closed properly

### ISSUE THREAD

**Issue by jjalonso** [photonstorm/phaser#3798]
const graphics = this.add.graphics();
    graphics.lineStyle(50, 0xf44277);
    graphics.arc(0, 0, 200, Phaser.Math.DegToRad(0), Phaser.Math.DegToRad(360));
    graphics.strokePath();

When using a big border the arc is not closed properly on the right side

<img width="463" alt="screen shot 2018-06-29 at 09 48 04" src="https://user-images.githubusercontent.com/389467/42083382-9f99cfd2-7b82-11e8-8074-1d881a193d52.png">

**Comment by photonstorm** [comment]
Yes, not really surprising given how it builds the arc up. Can be fixed by using an end angle > 360. In this specific case, 361 is enough to close the gap completely, but it will depend entirely on the stroke thickness. The end angle is clamped in the renderer, so I'll see about removing that, then you can overshoot it in code to close off un-sightly holes (as this can't be done automatically)

**Comment by jjalonso** [comment]
Thanks!

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
