### ISSUE TITLE
camera ignore

### ISSUE THREAD

**Issue by mishelen** [photonstorm/phaser#3889]
Hello)

In my opinion, the description of the method `ignore` is somewhat inaccurate. As docs describes it takes game object or arrays of it.

> \* Given a Game Object, or an array of Game Objects, it will update all of their camera filter settings
    * so that they are ignored by this Camera. This means they will not be rendered by this Camera.

But it not true. As it only work with non-grouping GameObjects like Text or Sprite.

For example, I had to make such a wobble that would completely ignore everything:

```js
this.cameras.main.ignore(
  this.list // Group, extends (?) GameObject
    .getChildren() // Containers, each extends GameObject
    .map(i => i.list) // finally gameobjects like Text, Image
    .reduce((acc, item) => acc.concat(item), [])
);
```
Yes, I noticed that the renderer of the container handles the property `cameraFilter`, but in my case it does **not work** for me:

```js
this.cameras.main.ignore(this.list.getChildren()); // ignore  containers
```

So, why I can't to just do 

```js
this.cameras.main.ignore(this.list);
```
So my questions is why group is not handle cameraFilter? As I can see Group only belongs to Gameobjects namespace, but not extends GameObject. And why I cant ignore Containers?

Well, of course, the counter question, if there is an `ignore`, then how can I make the camera render only objects passed to it.

**Comment by mishelen** [comment]
Here is another observation. `ignore` apparently does **not** work with `graphics` GameObject.

Use case the same, I just added graphics inside each container of one group (same code snippet above).

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. All Game Objects, either inside Containers or not, can be ignored by Cameras now.

You can see two examples for this in the labs in the cameras folder, "ignore gameobjects" and "ignore gameobjects in containers" are the example names.

The exception is Groups, because they're not Game Objects. They're just pools. Objects are not exclusively bound to a Group. One object can appear in many different Groups, so it's impossible for the Camera to be able to ignore a single Group while still respecting the other Groups.
