### ISSUE TITLE
DynamicLayer - wrong bounds with scrollFactor

### ISSUE THREAD

**Issue by Zax37** [photonstorm/phaser#3893]
Test steps:

1. Open and run this example:
http://labs.phaser.io/edit.html?src=src/game%20objects/tilemap/tests/visual%20culling%20check.js

2. Look at the small red, pink and yellow tiles. Move camera right. They disappear.

Any ideas why the bounds are not computed correctly? As I test that on different Phaser versions, it seems to be fine in 3.6, but broken in 3.7.1 and above.

**Comment by photonstorm** [comment]
The issue is the tile culling (rather than the scrollFactor) because it was assumed that the LayerData `baseTileWidth` and `baseTileHeight` properties were authoritative, but it appears we need to use those for the Tilemap itself, not any of the layers, to get a true bounds. I've updated the Cull function to use this and the test works fine now.

Just pinging @mikewesthad - can you see anything wrong with the current approach in https://github.com/photonstorm/phaser/blob/master/src/tilemaps/components/CullTiles.js ? It passes whatever I throw at it, but there's so many weird edge-cases in tilemaps who knows.

**Comment by Zax37** [comment]
This did not fully fix the issue. Open same example, add this line:
```
layer3.setScrollFactor(0.5);
```
Same thing happens.

**Comment by Zax37** [comment]
Seems to work fine in v3.12.0-beta2 :)
