### ISSUE TITLE
v3.12.0-beta2 Hit area for Image GO is broken if you replace the textureId

### ISSUE THREAD

**Issue by hackhat** [photonstorm/phaser#3921]
I just create a simple image and the hit area is double the size. I set the texture and the new width/height:

        planet.setTexture(textureId256);
        planet.displayWidth = 55;
        planet.displayHeight = 55;

        // wait a bit
        planet.setTexture(textureId128);
        planet.displayWidth = 55;
        planet.displayHeight = 55;

Steps to reproduce:

 - Add image with texture of size 256x256 and set interractive and add pointerdown event
 - After a bit of time replace the texture with one that is 128x128
 - Click on the right of the new image and you point down on the image to the right it will be hit, it should not be.

![image](https://user-images.githubusercontent.com/11173732/44005923-eb791f68-9ead-11e8-84c0-7b7b6de2aba4.png)

I even added the following, but this will not hit anything at all, not sure if is another bug, or I don't know how to use it.

`

          const shape = new Phaser.Geom.Circle(planet.x, planet.y, planet.radius);
          planet.setInteractive(shape, Phaser.Geom.Circle.Contains);
`

**Comment by photonstorm** [comment]
If you replace the texture with something of a different size then it's up to you to resize the hit area as well. The hit area isn't bound to the texture in any way. All that happens if you _don't_ provide a hit area shape when you make something interactive is that it will generate a rectangle based on the _current_ texture frame size - but once that rectangle is created it won't ever modify itself again.

**Comment by hackhat** [comment]
Ah ok, thanks. Again, I think we can improve the docs on that area.
