### ISSUE TITLE
scene.run start paused scene instead of resume

### ISSUE THREAD

**Issue by alexeymolchan** [photonstorm/phaser#3931]
Phaser 3.11

Docs says that - If the given Scene is paused, it will resume it.

So basics scenario, i have 2 scenes Main menu (mm) and Modal window (mw), i pause mm and run mw then i run mm from mw and stop mw, but mm didn't resume instead it started again.

i checked code of the Scene Manager and actually in this block
```
else if (scene.sys.isBooted && !scene.sys.isActive())
    {
        //  Paused?
        scene.sys.resume(data);
    }
``` 
```scene.sys.isBooted``` is always undefined when i call scene.run()

**Comment by NokFrt** [comment]
This bug still exists in 3.16.2. ScenePlugin's run() creates a new scene even if the scene has already existed and is only paused.

`
// SceneA
this.scene.input.on("pointerdown", () => {
this.scene.pause();
this.scene.scene.run("sceneB");
});

// SceneB
this.scene.input.on("pointerdown", () => {
this.scene.pause();
this.scene.scene.run("sceneA"); // SceneA is paused. run() should just resume it, but sceneA.create() is called instead.
`

**Comment by photonstorm** [comment]
It's _not_ paused at the time you call it. `this.scene.pause` queues the operation, so it's paused on the next update. `this.scene.scene.run` bypasses the queue entirely, running the Scene immediately, because it's hitting the SceneManager and not the ScenePlugin.

**Comment by NokFrt** [comment]
I'm sure it's paused. I maybe gave wrong example which is not so clear.

I have two scenes. SceneA and SceneB. ScenaA is paused but visible (I'm sure it's paused). SceneB is running and it's above SceneA. In sceneB (which works as an overlay above sceneA)  after the player click on a button, I do this:

// I can check that the sceneA is paused (so I'm really sure it's paused at the time I'm trying to run it again)
// let sceneA = this.scene.get("sceneA");
// let isSceneAPaused = sceneA.sys.isPaused    // isSceneAPaused is true

this.scene.run("sceneA");   // This doesn't work correctly. It creates a new sceneA instead of resuming it. But this.scene.resume("sceneA") works.
this.scene.sleep("sceneB");

**Comment by gbishop** [comment]
I see the behavior as well. One scene is paused. From the other scene I use "run" which should resume it but instead it starts a new instance.

**Comment by samme** [comment]
Example: https://codepen.io/samme/pen/PooNjMZ

**Comment by gbishop** [comment]
Yes. I see create being called after every run.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by gbishop** [comment]
I have verified that it works as expected now. Thanks!
