### ISSUE TITLE
body.gameObject is null in 'collisionstart' event handler when using TexturePacker and PhysicsEditor

### ISSUE THREAD

**Issue by rscott442** [photonstorm/phaser#3985]
## Version

* Phaser Version: Phaser v3.11 (WebGL | Web Audio)

* Operating system: Windows 10 Pro (64-bit) Version 1803

* Browser: Chrome 68.0.3440.106 (Official Build)(64-bit)

## Description

After the ship hits the ball, open the console and see "Uncaught TypeError: Cannot read property 'setTint' of null"
game.js:43

Single Stepping through with Chrome Developers tools, you can see the bodyA.gameObject is null.

The setTint call works (and gameObject is valid) when I load the two images directly like this.load.image('ship', 'images/ship.png');

Do I need to modify this code in some way so I can use TexturePacker and PhysicsEditor?

Do you know if Phaser or Matter.js is responsible for defining the gameObject? I am still learning how everything fits together with body and gameObject.

## Example Test Code

Link to my site for testing...

http://www.robertsgames.com/phaser3test/

## Additional Information

[phaser3test.zip](https://github.com/photonstorm/phaser/files/2325646/phaser3test.zip)

**Comment by mikewesthad** [comment]
@rscott442, I was deep in this issue not too long ago so figured I'd chime in. This is actually the expected behavior with compound bodies, which are matter bodies that are actually composed of multiple, separate bodies linked together. When it comes to matter collisions with compound bodies (looks like both your ship and ball are both compound bodies), it's only the root/top-level body that has the `gameObject` property you are looking for. In your case, you can get to the root body from `bodyA` via `bodyA.parent`, but a more general function that gets the root of deeply nested bodies would be:

```js
function getRootBody(body) {
  while (body.parent !== body) body = body.parent;
  return body;
}
``` 

So you could do:

```js
this.matter.world.on('collisionstart', function (event, bodyA, bodyB) {
  const rootBodyA = getRootBody(bodyA);
  const rootBodyB = getRootBody(bodyB);
  rootBodyA.gameObject.setTint(0xff0000);
  rootBodyB.gameObject.setTint(0x00ff00);
});
```

You can see that kind of approach in context in [this demo](https://labs.phaser.io/edit.html?src=src\game%20objects\tilemap\collision\matter%20detect%20collision%20with%20tile.js) from Phaser Labs. Note: I wouldn't rely the `bodyA` & `bodyB` parameters in the event handler like in your sample code - I would loop over `event.pairs`. There may be multiple colliding bodies on a given tick of the physics engine, and `bodyA`/`bodyB` will only be the first colliding pair from the tick.

If you get deeper into trying to detect matter collisions between game objects, then you might find this [phaser-matter-collision-plugin](https://github.com/mikewesthad/phaser-matter-collision-plugin) useful. It wraps up things to make detecting collisions between game objects a bit easier.

**Comment by rscott442** [comment]
@mikewesthad - Thanks Mike! I will start trying your suggestions.
