### ISSUE TITLE
Problem with fillRoundedRect and generateTexture function. 

### ISSUE THREAD

**Issue by Yaroshuk** [photonstorm/phaser#4004]
## Version

* Phaser Version: 3.11

* Operating system: Windows 10

* Browser: Chrome 68.0.3440.106

## Description

It's problem with generateTexture function. I use this for generaеe my textures, it's ok when I draw rounded rect in my Graphics object, but it's wrong (the image is distorted) when I generated texture and use it on my Sprite object. 

## Example Test Code

```
class Player extends Phaser.GameObjects.Sprite {
    constructor(scene, x, y) {
        super(scene, x, y, 'logo2');
    }
}
class Test extends Phaser.Scene {
    constructor() {
        super({ket: 'Test'})

        this.graf;
        this.text;
    }

    preload() {
        this.graf = new Phaser.GameObjects.Graphics(this, {x: 10, y: 10});
        this.graf.fillStyle(0x1cba76);
        this.graf.lineStyle(2, 0xffffff);
        this.graf.fillRoundedRect(0, 15, 50, 50);
        this.graf.generateTexture('logo2', 50, 65);
        this.children.add(this.graf)
    }

    create() {
        let play = new Player(this, 100, 50);
        this.children.add(play)
    }
}
```

## Additional Information

[Photo](https://photos.app.goo.gl/SdpFFu8r7TzXxhYv7)

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).
