### ISSUE TITLE
Performance: Replace internal scene shutdown event for game object destroy

### ISSUE THREAD

**Issue by goldfire** [photonstorm/phaser#4028]
When debugging a memory leak issue, we discovered that the `shutdown` event wasn't being turned off on GameObjects (https://github.com/photonstorm/phaser/pull/4024#event-1841241172). Fixing this caused a performance issue when several dozen entities were destroyed in a single frame.

Unless I'm missing something, it seems like it would be much more efficient to just loop through the scene's list and destroy the game objects when the scene is shutdown rather than attaching a `shutdown` listener to each object. For example, our main scene has 4-5k game objects, and even though most of them are inactive, this still causes thousands of idle events to be setup

**Comment by photonstorm** [comment]
I did some tests this morning.

I created a Scene with 5k Sprites in. The distinction is important as Sprites live in the Display List and Update List, where-as Images only live in the Display List. On click, I swap to another Scene with 5k Sprites in. Clicking that Scene swaps back to the first Scene again. I tested swapping back and forth several times in a single profile.

Under 3.12 the first change took nearly 200ms, 90ms of which was the `emit` event, the rest was the removal of the objects from the two lists.

![image](https://user-images.githubusercontent.com/164476/45475851-6d516280-b735-11e8-8f62-340bd69f6548.png)

Interestingly, subsequence Scene swaps took half the time (around 98ms), which I guess we can attribute to internal optimizations.

I then swapped to 3.13 with my changes in. The changes stop Game Object's listening for the `shutdown` event. Instead, the Display and Update Lists purge their children directly (and also skip removing themselves from the two lists if it was a Scene that invoked the destroy). Swapping from A to B now took 113ms for the first swap, which is almost half the time previously:

![image](https://user-images.githubusercontent.com/164476/45476109-08e2d300-b736-11e8-84f1-1cc40a2d77d2.png)

Subsequent swaps were ~60ms. Although a bit of an edge case it's clearly better off removing them directly rather than through events, so I'm happy to keep this change in.
