### ISSUE TITLE
Matter.js bugs in Phaser vs. not in Phaser

### ISSUE THREAD

**Issue by wemyss** [photonstorm/phaser#4041]
## Version

* Phaser Version: 3.12.0

* Operating system: macOS High Sierra - 10.13.4

* Browser: Chrome v69 / Firefox 63

## Description

When trying to get matter physics to work with generated curved shapes in Phaser there are a few strange things that happen. Namely a sliding/rolling object gets caught on each segment of the collision shape for the curve (sorry, not sure what it's actually called... 😕). 

The other issue (which you can see clearly from the demo) is there is an extra line drawn in the debug physics outline (I say the debug mode as it doesn't seem to impact the world at all).

I may be using the Phaser API incorrectly but I went through the source code for Phaser and I feel like I'm using the appropriate methods/classes/etc.

## Example Test Code

Phaser code sample: https://codepen.io/wemyss/pen/RYJvdm - you can use arrow keys to move around. You can see clearly that it "catches" on each segment

Matter.js equivalent: https://codepen.io/wemyss/pen/bxQGQd?editors=1010 - the `my_points` is copied directly from the other example through the chrome dev console using `copy()`

## Additional Information

Thanks for making phaser awesome! 💯

**Comment by photonstorm** [comment]
Two issues here. First of all, the extra line in the debug. This line is the convex hull being drawn. In Phaser 3.14 you can now turn this off, or give it another color, so it's more obvious what it is.

The second issue with the circle being 'caught' on the edges is because of your `update` function. Comment out line 90 (`this.player.setVelocityX(0)`) and it doesn't happen at all, working exactly the same as your Matter demo.

**Comment by wemyss** [comment]
Thank you! I was doing something silly 😸
