### ISSUE TITLE
Audio doesn't work in safari?

### ISSUE THREAD

**Issue by increpare** [photonstorm/phaser#4217]
## Version

* Phaser Version:
whatever version is used here:
https://labs.phaser.io/view.html?src=src\audio\HTML5%20Audio\AudioSprite.js

* Operating system:
macos 10.14.1 (18B75)

* Browser:
safari 12.0.1

## Description

On the cat astro phi demo page clicking buttons produces no audio on safari on osx, but works fine on chrome 70.0.3538.110.

## Example Test Code

https://labs.phaser.io/view.html?src=src\audio\HTML5%20Audio\AudioSprite.js

## Additional Information

This is probably due to how safari handles audiocontexts now ( https://hackernoon.com/unlocking-web-audio-the-smarter-way-8858218c0e09 ), and how chrome will very, very soon ( https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/5Y1BqbGauEs/rRocaytKBgAJ ) .

**Comment by samme** [comment]
> [Log]      Phaser v3.16.0 Beta 3 (WebGL | HTML5 Audio)  https://phaser.io (dev.js, line 6326)
[Warning] NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. (dev.js, line 149835)
play
playCatchPromise — HTML5AudioSound.js:384
pickAndPlayAudioTag — HTML5AudioSound.js:287
play — HTML5AudioSound.js:129
playAudioSprite — BaseSoundManager.js:300
(anonymous function) — AudioSprite.js:65
emit — index.js:183
processDownEvents — InputPlugin.js:800
update — InputPlugin.js:555
[…]

**Comment by SoimanAndrei** [comment]
Hey guys!
Any progress? :)

**Comment by photonstorm** [comment]
This works fine with 3.16 RC3 in Safari on Mac OS using either Web Audio or the Audio Tag.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by guilala** [comment]
What commit contains the fix? Is the fix also merged to Phaser CE?
