### ISSUE TITLE
Moving coloured rectangles highly affects on FPS and causes error messages in console

### ISSUE THREAD

**Issue by IonRod** [photonstorm/phaser#4306]
## Version

* Phaser Version: 3.14.0, 3.15.1
* Operating system: MacOS Mojave 10.14.2
* Browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)  / Safari Version 12.0.2 (14606.3.4)

## Description

The problem is that in Chrome this starts working extremely slow after 10-30 seconds after start and in Safari it's starts to show lot of errors and prevents app from debug: 
![image](https://user-images.githubusercontent.com/886012/51554969-932b0880-1e87-11e9-8f3d-091418bb1b10.png)

## Example Test Code
https://pastebin.com/VaAW9hXs

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).
