### ISSUE TITLE
this.frame.source is null on setText after Phaser.Scene.restart()

### ISSUE THREAD

**Issue by paulbonneau** [photonstorm/phaser#4323]
## Version

* Phaser Version: 3.15.1

* Operating system: Mac osx Sierra 10.13.6

* Browser: Firefox Quantum 64.0.2 (64 bits)

## Description

Using setText after scene restart trigger the following error 

```
this.source is null
this.frame.source is null
```

## Example Test Code

Here is a pen demonstrating the problem (hitting a polygon with the ball will trigger a scene restart then the error):
[https://codepen.io/paulbonneau/pen/OrKgvR](url)

## Additional Information
Thanks a lot for all the effort you put in Phaser :)

**Comment by photonstorm** [comment]
Adding comment as remind myself to build minimal test case from code provided (as it's too large to be used effectively to isolate this issue)

**Comment by samme** [comment]
Make sure you're not referencing/using an old (destroyed) text object.

**Comment by photonstorm** [comment]
The problem is that the event `addScore` is still emitted even after you restart the Scene, after which the Text object has been destroyed. You should clear all custom events when a Scene shuts down to avoid repeat invocation. You can fix your demo by adding:

`this.sys.events.once('shutdown', this.shutdown, this);` to the create function, and:

```
    shutdown: function ()
    {
        this.events.off('addScore');
    },
```

Also, bailout of the update loop if you restart the Scene.
