### ISSUE TITLE
Error when destroying a zone which is being dragged on mobile

### ISSUE THREAD

**Issue by reyalpsirc** [photonstorm/phaser#4337]
## Version

* Phaser Version: 3.15.1 & 3.16.0-rc3

* Operating system: at least Android 8.1 and iOS 12.1

* Browser:
    * Mobile browsers and Webviews

## Description

When using a draggable zone with one finger and clicking a button that destroys it with another finger, the library crashes with an error about `Cannot read property 'dragState' of undefined`

## Example Test Code

[ https://codepen.io/reyalpsirc/pen/yZgNrY?editors=0010
]( https://codepen.io/reyalpsirc/pen/yZgNrY?editors=0010
)
Please note that the example above does not show the real error on the alert due to CORS but it demonstrates the crash anyway

**Comment by reyalpsirc** [comment]
@photonstorm I just updated the codepen to test with **3.16.0-rc3** and the same problem happens

**Comment by reyalpsirc** [comment]
@samme Just updated it to 3.16.1 and the problem persists

**Comment by photonstorm** [comment]
I've fixed an almost identical problem today (#4228) - could you please see if it fixes this issue as well?

**Comment by reyalpsirc** [comment]
@photonstorm I just built the master branch and the problem seems to still be there. Is there any way I can update the codepen with the current data on the master branch?

**Comment by photonstorm** [comment]
I appreciate how old this issue is, but I'm going to close it as I've tested it against 3.55 and 3.60 on real devices and it works just fine now (to be honest, it may have done for a while). Test version here if anyone else wants to try it:

https://labs.phaser.io/view.html?src=src/bugs/4337%20drag%20destroy.js&v=dev

Drag yellow circle with one finger then tap red square with another to destroy during drag.
