### ISSUE TITLE
Spine plugin documentation, state of spine plugin

### ISSUE THREAD

**Issue by sergey-pimenov** [photonstorm/phaser#4349]
Hi! Thank you very much for making Spine plugin.
Spine plugin works great, but I can't understand how dynamically change animations, use animation mixes etc. Maybe these features are not available yet? It would be great to understand the current state of the plugin.

**Comment by yandeu** [comment]
This is already possible. Take a look at my example.
https://github.com/yandeu/phaser3-spine-example

**Comment by photonstorm** [comment]
This is definitely all possible (thanks @yandeu for the cool example!) but I'm going to label this issue as TODO because the jsdocs need finishing for the plugin.

**Comment by al-arz** [comment]
@photonstorm any ETA on spine plugin docs?

**Comment by photonstorm** [comment]
Nope, I don't give ETAs for anymore. Spine will be part of the 3.18 release, so whenever that is ready, it will have the docs in. Having said that, to use the plugin fully you only really need the Spine Runtime docs, not the Phaser ones, and those have been available since the start from the Esoteric site.

**Comment by photonstorm** [comment]
This was released with 3.19 and I fixed a few major issues with 3.20 which is now in the master branch, so am closing this issue off. Thanks!
