### ISSUE TITLE
Phaser not correctly restoring state after using 'ESC' to exit fullscreen.

### ISSUE THREAD

**Issue by khutchins** [photonstorm/phaser#4357]
## Version

* Phaser Version: 3.16.2

* Operating system: Windows 10

* Browser: Chrome 72.0.3626.96, Firebox 65.0 (doesn't seem browser-specific)

## Description

When exiting fullscreen mode using 'ESC', I expect that the Phaser game window will be restored to its previous size. Instead, it appears to be keeping its fullscreen size but in windowed mode.

## Example Test Code

https://codepen.io/anon/pen/XOqMVP

To reproduce:
1. Launch code pen.
2. Click on Phaser window to gain focus.
3. Press 'F' to trigger Phaser to toggle fullscreen.
4. Exit fullscreen using ESC (not the natural Phaser path)
5. Phaser window will not be the same size as it was before entering fullscreen.

**Comment by photonstorm** [comment]
Ahhh nuts, yes, you're right.

**Comment by codypotter** [comment]
Perhaps this could be fixed by changing the canvas to default size when the exit full screen event is captured.
`document.addEventListener('fullscreenchange', exitHandler);
document.addEventListener('webkitfullscreenchange', exitHandler);
document.addEventListener('mozfullscreenchange', exitHandler);
document.addEventListener('MSFullscreenChange', exitHandler);`

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by khutchins** [comment]
I'm no longer running into the issue with the version I built from head. Thanks.
