### ISSUE TITLE
Fullscreen exiting immediately

### ISSUE THREAD

**Issue by reinildo** [photonstorm/phaser#4386]
Hi. Thanks for the great work.
I've forked a codepen from Samme, it is an example to go full screen with phaser.
If you apdate phaser version to 3.16.2 it stops working. Up to 3.16.1 it works fine.
here are the links to test:
https://codepen.io/reinildo/pen/omOaaB?editors=0110
https://codepen.io/reinildo/pen/qgwJQq?editors=0111

Thanks

**Comment by photonstorm** [comment]
3.16 contains built-in support for fullscreen, and this direct approach is conflicting with it. If you wish to carry on doing it your way, rather than using the Scale Manager, that is fine, but you need to stop the Scale Manager from handling the change request. The easiest way to do this is to replace the `ScaleManager.onFullScreenChange` function (just set it to a blank function).

Alternatively, if you don't need the Scale Manager at all, you can just call `this.scale.stopListeners()` to unbind it from the fullscreen handlers.
