### ISSUE TITLE
Phaser 3.16.2 - setVelocityY increments velocity considerably

### ISSUE THREAD

**Issue by jbgomez21** [photonstorm/phaser#4398]
## Version

* Phaser Version: 3.16.2

* Operating system: Windows

* Browser: all

## Description
When I change setVelocityY from 959 to 960, velocity is incremented considerably

https://embed.plnkr.co/kHaX8x3qFJbBzEm9qxCK/

**Comment by hexus** [comment]
The issue seems to be that the box is colliding with the world bounds. It's actually being centred on the very top left and being pushed out by the collision. It's positioned this way because a sprite's origin is its centre by default.

You can prove this by commenting world bounds collision.

```js
//this.ball.setCollideWorldBounds(true);
```

If you inset the sprite into the world (by half it's height/width), you should no longer face such an issue.

```js
preload() {
    this.load.spritesheet("ball", "assets/sprites/ball.png", {
        frameWidth: 22,
        frameHeight: 22
    });
}

create() {
    this.ball = this.physics.add.sprite(11, 11, 'ball', 0);
    this.ball.setCollideWorldBounds(true);
    this.ball.setVelocityY(959);  
    //this.ball.setVelocityY(960);  
}
```

**Comment by photonstorm** [comment]
^ what he said :)

**Comment by jbgomez21** [comment]
@hexus Thank you very much!

Greetings!
