### ISSUE TITLE
Drag performance issues due to recent commit (31c0b4f2f)

### ISSUE THREAD

**Issue by aliblong** [photonstorm/phaser#4500]
## Version

* Phaser Version: 3.17.0 (master)

* Operating system: Windows 10

* Browser: Chrome

## Description

Found performance issues with drag, and traced it back to commit 31c0b4f2f.

## Example Test Code

The [multiple draggables example in the official Phaser examples repo](https://github.com/photonstorm/phaser3-examples/blob/master/public/src/input/dragging/multiple%20draggables.js) illustrates the problem well.

## Additional Information

[Drag behavior on master](https://i.imgur.com/cxHQ5R8.gifv) (N.B., the dragging at the very end of the gif is withOUT the pointer held down, meaning `dragend` isn't fired properly or something)
[After reverting 31c0b4f2f](https://i.imgur.com/LQ5XaLR.gifv)

**Comment by rexrainbow** [comment]
This issue might come from `pointer up` event.
[Here](https://codepen.io/rexrainbow/pen/ZNJpyK) is a testing.

1. Pointer down
2. Move/drag fast
3. Pointer up quickly

You might see `pointerup` (or `pointerdown`) string might log twice, sometimes.
I guess that it is because [updateInputPlugins](https://github.com/photonstorm/phaser/blob/master/src/input/InputManager.js#L982) was called twice when `mouse-move` and `mouse-up`/`mouse-down`  at the same tick.

Phaser 3.16.2 works fine in this testing.
( Setting -> Javascript -> Change phaser version from
`https://cdnjs.cloudflare.com/ajax/libs/phaser/3.17.0/phaser.min.js` to
`https://cdnjs.cloudflare.com/ajax/libs/phaser/3.16.2/phaser.min.js` )

**Comment by bchee** [comment]
This is already being worked on by Richard. Please see #4538 - you can follow progress on the bug there.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
