### ISSUE TITLE
SceneManager stop() not accepting and passing through optional data

### ISSUE THREAD

**Issue by GetsukenStudios** [photonstorm/phaser#4510]
## Version

* Phaser Version: 3.16.2

* Operating system: 

* Browser: 

## Description

When I needed to pass extra data to my `shutdown` event handler in a scene, I realized after some debugging that the method `Phaser.Scenes.SceneManager#stop` is missing the parameter for the optional `data` to pass when stopping a scene and it also doesn't pass `data` to `Phaser.Scenes.Systems#shutdown`.

## Example Test Code

```    
    stop: function (key)
    {
        var scene = this.getScene(key);

        if (scene && !scene.sys.isTransitioning())
        {
            scene.sys.shutdown();
        }

        return this;
    }
````

## Additional Information

My simple fix:
```
    stop: function (key, data)
    {
        var scene = this.getScene(key);

        if (scene && !scene.sys.isTransitioning())
        {
            scene.sys.shutdown(data);
        }

        return this;
    }
```

**Comment by photonstorm** [comment]
It's not missing it, it's simply not meant to be there and isn't part of the API.

**Comment by GetsukenStudios** [comment]
I see, thanks. 

I'm curious, why does it pass `data` in `Phaser.Scenes.Systems#shutdown` when emitting the `SHUTDOWN` event then? Because that's why I assumed that `Phaser.Scenes.SceneManager#stop` is supposed to pass the data when it calls `scene.sys.shutdown()`. 
```
shutdown: function (data)
    {
        this.events.off(Events.TRANSITION_INIT);
        this.events.off(Events.TRANSITION_START);
        this.events.off(Events.TRANSITION_COMPLETE);
        this.events.off(Events.TRANSITION_OUT);

        this.settings.status = CONST.SHUTDOWN;

        this.settings.active = false;
        this.settings.visible = false;

        this.events.emit(Events.SHUTDOWN, this, data);
    }
```

**Comment by Olliebrown** [comment]
I'm examining the API just to make sure this simple solution makes sense in the larger context of the Scene subsystem.  Looking at the current lifecycle of a scene, an optional `data` already pops up in some places:

### Scene.Systems.settings.data
- This comes from an object passed to SceneManager's `add()`, `start()`, or `run()` functions
- It is passed into `Scene.init()` by SceneManager's `bootScene()` method (or `bootQueue()`)
- It is passed into `Scene.create()` by the SceneManager
- It is also just generally accessible within the scene as `this.settings.data`

### Scene.SceneManager.sleep/.wake and .pause/.resume
- These functions all accept an optional 'data' parameter
- This is transient data sent along with the corresponding event, unrelated to settings.data

### What to do with SceneManager.stop()?
The simple solution proposed above treats it more like the transient event data not strongly associated with the scene object. However, the partner event to stop() is the whole 'add/start/run' ecosystem and the data that is passed to those events is *not* transient but set to the Scene.settings object.  

I'm thinking, because of the duality of this particular event (stop), it would be appropriate to pass along any data that is provided as a parameter (just like wake() and resume()) but, if none is provided, pass along settings.data just in case someone was expecting it to behave like add/start/run.  In theory, settings.data will be the same object that was passed to one of those.

Strictly speaking this is redundant as you could always just access Scene.settings.data inside any reasonable scene.stop event listener as `this.settings.data` so passing it in doesn't enable anything that couldn't have been done before, but I'm thinking it might help anyone that doesn't know about settings.data!  FWIW, I didn't know about it until I researched this issue.

**Comment by photonstorm** [comment]
I think it's safe (and the most common use-case) to treat it as transient data, and if not given, don't send anything across.

**Comment by photonstorm** [comment]
Thank you for submitting this feature request. We have implemented this and the feature has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
