### ISSUE TITLE
Scene activePointer `justMoved` appears to not reset until pointer click happens

### ISSUE THREAD

**Issue by giniwren** [photonstorm/phaser#4518]
## Version
* Phaser Version: 3.16.2
* Operating system: OSX
* Browser: Checked in Firefox 66.0.4 and Chrome 74.0.3729.131

## Description
When using `scene.input.activePointer.justMoved`, it appears that the variable is set but then not reset to false again until activePointer is clicked (either left or right click), regardless of any mouse movements/stillness to follow.

## Example Test Code
https://codepen.io/giniwren/pen/KLVozb

## Additional Information
It seemed like the property did update correctly in the past (used an example from the `labs.phaser.io` site using Phaser v3.15.1).

If it would be of help, I can triage further and create a pull request for a potential solution. Thanks for your time and let me know if I can provide any more details.

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).
