### ISSUE TITLE
[3.17] Arcade Physics tied to framerate, physics timescale has no effect, world collission issues

### ISSUE THREAD

**Issue by ampled** [photonstorm/phaser#4529]
## Version

* Phaser Version: 3.17

* Operating system: Windows 10

* Browser: Chrome and Edge

## Description

I'm having a set of different issues with Arcade Physics when upgrading from 3.16 to 3.17.
I discussed some of these with @Antriel on discord and we agreed I should submit a github issue with a minimal repro. I'm not sure the repro covers all the issues I'm having, but it certainly demonstrates that there's some issues.

1) Setting worldFPS either via setWorldFPS or providing an fps value in the physics config affects game logic. This didn't happen in 3.16. In 3.17, setting the world FPS lower makes everything happen faster. This is demonstrated in the minimal repro.

2) Physics "happen faster" when I'm running my game in chrome on a screen with a higher refresh rate. I've tested my game on my stationary computer with a 144hz refresh rate and a laptop with a "regular" 60hz refresh rate. I've also confirmed these framerates by checking the `game.loop.actualFps` value. This is super problematic since you can't cap web browser framerates. This can be tested with any Phaser game on a 144hz monitor by switching between Chrome and Edge, since Edge's framerate seems to be capped at around 70 fps.

3) Setting the arcade physics world FPS to a high value (120+ in my case) makes the physics buggy. At stand still, a game object with gravity applied standing firm on a colission-enabled tilemap layer sends multiple different tiles to the colliders process callback, when at default worldFPS (or even at high worldFPS in 3.16) the process callback only receives the one and same tile over and over. It seems that the high worldFps completely breaks "consistent" frame to frame GameObject/Tilemap-Layer colission.

4) Setting the physics timescale doesn't seem to have any effect anymore

All of these things worked fine in 3.16. If needed I will provide more code examples, but generally most existing examples can be "broken" by setting the fps value in the physics config. 

## Example Test Code

https://stackblitz.com/edit/phaser3-typescript - 3.17
https://stackblitz.com/edit/phaser3-arcade-physics-world-fps-316 - same repro in 3.16

**Comment by ampled** [comment]
The 3.16 repro suddenly had some issues, I'm just posting these gifs demonstrating the issues in they repros go down.

# 3.16
![FUeVUMgKNp](https://user-images.githubusercontent.com/6841690/58540712-3d31ed00-81fa-11e9-8e47-a0c5793f3ecf.gif)
![5e6wUyyyBW](https://user-images.githubusercontent.com/6841690/58541054-ee388780-81fa-11e9-9a04-afcaea0a7fe7.gif)

# 3.17

![8uFThQPJ9s](https://user-images.githubusercontent.com/6841690/58540705-35724880-81fa-11e9-8713-ded0af5e1c67.gif)
(notice how timescale changing doesn't affect anything)

![TUqHnUlfkS](https://user-images.githubusercontent.com/6841690/58541024-da8d2100-81fa-11e9-94f9-2604efa0bf4e.gif)
Tilemap collission issues on high worldFPS

**Comment by peteroravec** [comment]
Same issue here...

**Comment by ampled** [comment]
I've double verified that Arcade Physics are tied to framerate by running the 3.17 repro in a Chrome browser and moving the browser between a 144hz monitor and a 60hz monitor on the same computer.

**Comment by samme** [comment]
In v3.17.0 Phaser always makes at least 1 physics step per game update (animation frame). That will make physics run "too fast" for any physics rate smaller than the animation rate. But any physics rate at least as large as the animation rate runs at the correct speed.

**Comment by photonstorm** [comment]
This is one of those non-trivial issues. I could revert it to how 3.16 worked, but it was changed for a good reason (i.e. you'd frequently get Bodies that were flag cleared but not updated), so it needs more carefully thinking about rather than simply putting it back how it was.

**Comment by ampled** [comment]
I'm sure the update fixed some issues, though I'm not sure what flag cleared means.

Some questions:
- Any good pointers on how to help solve this?
- Are any of the problems listed in the issue description solvable by writing code in our own projects? Could messing with TILE_BIAS fix the tilemap collission issue?
- Is there a defined goal on how Arcade Physics should work? (eg separate physics from framerate)
- The timescale feature was very cool, but broken in 3.17. Should it be kept in the framework if it conflicts with any solution to these issues?

Could the old arcade physics be opt-in in the next release while these issues are being worked on? It's the only thing keeping me from upgrading my project to 3.17 right now and I'd love to get the controller input fixes.

**Comment by Antriel** [comment]
If anyone cares about my opinion:

- Running physics update every frame regardless of whether it actually should is a very dirty hack (essentially game breaking, as illustrated). If not running the update causes issues, those issues should be fixed instead.
- Ideally physics should be entirely decoupled from rendering, with optional render interpolation being used. Optional, because with low enough physics timestep (120 Hz and more), it stops being needed.
- @ampled one option you could have is to simply choose much smaller physics timestep, e.g. 144 Hz or 200 Hz. It will modify your physics behavior obviously, which you will need to tweak, but if you can afford running so much physics, it will fix your problems (because you will always need to run at least 1 update unless the player has over 200 FPS).

**Comment by photonstorm** [comment]
Arcade Physics, by its very nature, _cannot_ be decoupled from rendering. In all other physics systems, the sprite position is based on the body. If the body doesn't move (because no physics step took place that frame), then the sprite doesn't move.

AP literally works the other way around. The body position is based on the sprite position and, more importantly, the body delta is based on the current and previous sprite position. The body position is then modified based on velocity, collision, etc and fed back into the sprite at the end of the process. 

There is _nothing_ stopping the sprite from being moved of its own accord outside of physics (tweens, input, paths, etc) and this happens frequently. If a sprite was attached to a pointer move event, for example, it's absolutely possible for it to be in a completely different position to its body if the physics step is running at a lower rate than the frame rate. The bigger the difference between the two, the larger the gap between the visual and where the body actually is. This doesn't matter terribly, the bigger issue is the larger the difference, the larger the delta the body uses. It's a fundamental design flaw in the Flixel physics system but it's been that way since day 1 and the whole API is based around this reversed state of authority.

In an ideal world, if a sprite is enabled for physics, then _nothing_ should change its position other than the body moving, at which point it doesn't matter if you step at 10fps or 200fps. Honestly, I long for that day, but it isn't happening yet. In the meantime, I'll address the step-every-frame issue.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
