### ISSUE TITLE
3.17.0 tween config set paused is true, run play/resume is not action

### ISSUE THREAD

**Issue by YehChin** [photonstorm/phaser#4570]
Such as title

3.16.2 - is OK
https://labs.phaser.io/view.html?src=src\tweens\pause%20and%20resume.js&v=3.16.2

3.17.0 - is not action
https://labs.phaser.io/view.html?src=src\tweens\pause%20and%20resume.js&v=3.17.0

english is bad, forgive me.

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md). See #4525

**Comment by thanh-taro** [comment]
I think it is happen again on v3.18.1.
You can try to reproduce in the example: https://labs.phaser.io/edit.html?src=src\tweens\pause%20and%20resume.js
