### ISSUE TITLE
It's impossible to start a tween if it has paused: true in its configuration object

### ISSUE THREAD

**Issue by NokFrt** [photonstorm/phaser#4595]
## Version

* Phaser Version: 3.17

* Operating system: Win10

* Browser: Chrome

## Description
It's impossible to start a tween if it has paused: true in its configuration object. Tween.play() does not start the tween.

## Example Test Code

https://labs.phaser.io/view.html?src=src\tweens\paused%20tween.js&v=3.17.0

**Comment by samme** [comment]
#4525

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).

https://labs.phaser.io/view.html?src=src\tweens\paused%20tween.js&v=dev

**Comment by photonstorm** [comment]
Re-closing, as for some reason it still appears in search results even when filtering out closed issues!
