### ISSUE TITLE
Texture key already in use but has not been defined yet

### ISSUE THREAD

**Issue by Edwin-Pratt** [photonstorm/phaser#4597]
## Version

* Phaser Version: 3.17.0

* Operating system: Windows 10 v1903

* Browser:

## Description

I am creating a game with Phaser, and I am currently working with the game over scene.
I am loading an image as the background for the button, however, every time I run the code, I get an error like the following:

```text
phaser.min.js:1 Texture key is already in use: game-over-button
```

This button is not defined any where else in my game and even though this error appears, the button still gets displayed.

## Example Test Code

```javascript
// game-over.js

const gameOver = new Phaser.Scene('gameOver')

gameOver.preload = function() {
    this.load.image('game-over-background', './images/game-over-background.png')
    
    // === This is where the error occurs ===
    this.load.image('game-over-button', './images/game-over-button.png')
    // ======
}

gameOver.create = function() {
    this.add.image(320, 240, 'game-over-background')
    this.add.image(240, 160, 'game-over-button') // Text will go on to of the button
}
```

## Additional Information

It would be nice if the error could be a little more verbose, like explaining in which scene the texture is defined.

**Comment by photonstorm** [comment]
The error means the texture key has already been loaded somewhere else in your game. Phaser doesn't keep track of _which_ Scene loads what files, because it's a bit pointless (after all, it's your code, you should know which Scene is loading which files). This is why it can't tell you _where_ it's happening, only that it is. View the network panel in dev tools, look for the file being loaded elsewhere, breakpoint it, or just do a full file-search for the path in your code.
