### ISSUE TITLE
DOMElements Wrapper does not resize automatically

### ISSUE THREAD

**Issue by adrianolobo** [photonstorm/phaser#4601]
## Version
* Phaser Version: 3.17

* Operating system: Linux Mint 19 Cinnamon

* Browser: Chrome 74

## Description

When the game resizes using `scale.resize(width, height)` and  `cameras.resize(width, height)` the element that wraps all `DOMElements` does not resizes automatically.

## Example Test Code

```
var config = {
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 150,
    height: 600,
    backgroundColor: '#2d2d2d',
    dom: {
        createContainer: true
    },
    scene: {
        create: create
    }
};

var game = new Phaser.Game(config);

function create ()
{
    var style = {
        'background-color': 'lime',
        'width': '220px',
        'height': '100px',
        'font': '48px Arial',
        'font-weight': 'bold'
    };

    var element = this.add.dom(150, 300, 'div', style, 'Phaser 3');

    setTimeout(() => {
        this.cameras.resize(300, 600);
        this.scale.resize(300, 600);
    }, 2000);
}

```

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).
