### ISSUE TITLE
JustDown event not triggered after switching scene

### ISSUE THREAD

**Issue by tranchikhang** [photonstorm/phaser#4635]
## Version

* Phaser Version: 3.18.1 
* Operating system: Windows 10
* Browser: Chrome

## Description

I have 2 screens: `MainScene` and `UIScene`.
In MainScene, if key `A` is pressed, switch to UIScene. In UIScene, if key `B` is pressed, switch to MainScene.
The problem occurs after switching from UIScene back to MainScene, if I press `A`, the JustDown event is not triggered the first time. If I press `A` again, the event will be triggered.

## Example Test Code

```javascript
class MainScene extends Phaser.Scene {
    constructor() {
        super('MainScene');
    }
    preload() {
        this.buttonA = this.input.keyboard.addKey('A')
    }
    create() {}
    update() {
        if (Phaser.Input.Keyboard.JustDown(this.buttonA)) {
            console.log('buttonA is pressed')
            this.scene.pause('MainScene');
            this.scene.run('UIScene');
        }
    }
}

class UIScene extends Phaser.Scene {
    constructor() {
        super('UIScene');
    }
    preload() {
        this.buttonB = this.input.keyboard.addKey('B')
    }
    create() {}
    update() {
        if (Phaser.Input.Keyboard.JustDown(this.buttonB)) {
            console.log('buttonB is pressed')
            this.scene.pause('UIScene');
            this.scene.resume('MainScene');
        }
    }
}
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    scene: [MainScene, UIScene]
};

var game = new Phaser.Game(config);
```

## Additional Information

I had a quick look at the source code, and I think the problem is: when I press key `A` to change the scene, the method `Phaser.Input.Keyboard.Key#onUp` will not run. So key A will be 'stuck' as `onDown` state.

**Comment by tranchikhang** [comment]
A temporary solution is adding
```javascript
this.buttonA.isDown = false;
```
before changing the scene. This will "release" the key from `onDown` state.

**Comment by photonstorm** [comment]
The issue is that the Keyboard Plugin is only reset when a Scene is shut down, not just paused. When a Scene is simply paused it literally freezes everything in its current state, including key values, events, etc. It will not then respond to the key up event when it occurs in the other Scene.

If a Scene is shut down (i.e. you start a new Scene) then `KeyboardPlugin.resetKeys` is called automatically and handles this transition for you, resetting key states so they don't become frozen 'down'. Because you're not actually stopping the Scene, just pausing it, it's up to you to reset the keys yourself (by calling this method directly, which is why it's exposed publically), either at the time you pause or when you resume. It's up to you when you call it and is game specific really.

The other option, of course, is to bind the Scene change event to the keyup event, instead of keydown. Having it respond in the update loop like the sample code is quite unusual and honestly, not really that safe, probably much better to use the event system for this kind of big Scene change.
