### ISSUE TITLE
Current Dist does not contain fixes contained in current code?

### ISSUE THREAD

**Issue by Shadetheartist** [photonstorm/phaser#4645]
I ran into an issue with tilemap debug rendering that i figured i could build a PR for myself, as the fix was very simple. (just a method name goof)

However when i checked the source code (src/tilemaps/components/RenderDebug.js) the fix was already implemented. But in the dist folder the phaser.js file did not include the same fix. 

Just wondering why that would be? Is the dist folder not intended to reflect the current state of the code?

**Comment by photonstorm** [comment]
The dist folder contains the build files for the most current release version (which is 3.18.1). Look at the Change Log to see what has been fixed / changed in the master branch since that release, to know what's in the src folder. When 3.19 is released dist will be updated with the new build files and the repo will be prepared ready for 3.20 development.

**Comment by Shadetheartist** [comment]
Oh ok, thanks for the explanation :)

**Comment by photonstorm** [comment]
No worries. You can make your own build using the provided npm scripts in the meantime if you like, but 3.19 will be out very soon.
