### ISSUE TITLE
How phaser loader really work ?

### ISSUE THREAD

**Issue by ramazord** [photonstorm/phaser#4677]
Hi, i'm trying to serve my `.json` file in static folder using next js and react, but when i'm trying to use fetch as get request to static folder, it works on localhost but not in file protocol `file://`. i got CORS error on file protocol.

this is my request using axios

```
  const request = axios.get(path);
  request.catch(e => {
    throw Promise.reject(new Error(`Request error : ${e}`));
  });
  request.then(response => {
    const { dispatch } = store;
    dispatch(setCourse(response.data));
  });
  return request;
```

okay but that's not the question, the question is, when i'm using phaser and load json from static folder it works on both protocol, http and file protocol, how the phaser loader really work ?

this is my loader and storing it to redux

```
import Phaser from 'phaser';
import { store } from '../../redux/store';
import { setCourse } from '../../redux/actions/course';

export default class Boot extends Phaser.Scene {
  constructor() {
    super({ key: 'Boot', active: true });
  }

  preload() {
    this.load.json('topicData', './static/contents/topic.json');
  }

  create() {
    const data = this.cache.json.get('topicData');
    store.dispatch(setCourse(data));
  }
}
```

Thank you.

**Comment by photonstorm** [comment]
The Phaser Loader uses XHR to pull in the file from the given URL, unless you actually provide a JSON object instead of a URL, then it just uses that directly. XHR will work over either file or http, but your server has to be properly configured or you'll potentially get CORs errors, as it tries to access resources from outside of its allowed domain. Please continue this conversation on either the Phaser Forum or Discord, as I like to keep GitHub issues for API problems rather than general support, thanks.
