### ISSUE TITLE
Chrome Mobile Display Cuts Off

### ISSUE THREAD

**Issue by ChocolateCheese9** [photonstorm/phaser#4686]
## Version

* Phaser Version: 3.18.1

* Operating system: IOS 12.4

* Browser: Chrome

## Description

When I use scale mode Phaser.Scale.Fit on Chrome Mobile, Instead of stretching and keeping aspect ratio, it crops a bit off of the bottom. It’s a mobile only bug, and I’ve only tested on iPhone 6.

## Example Test Code

scale: {
        mode: Phaser.Scale.FIT,
        autoCenter: Phaser.Scale.CENTER_BOTH
    },

## Additional Information

![845CDA59-58D9-482D-9199-F8B0E26C9A9F](https://user-images.githubusercontent.com/31376905/62333178-4b5ced80-b477-11e9-86f8-cf0ea925114e.png)
![709F0ABB-A05C-4AF0-85F6-A5052B115A70](https://user-images.githubusercontent.com/31376905/62333179-4b5ced80-b477-11e9-8100-5db55d7cefe4.png)

**Comment by photonstorm** [comment]
Thank you for spending the time opening this issue originally. I'm sorry, but I am closing off really old issues that we were unable to attend to at the time. It's very likely this has since been resolved via either updates to Phaser or the mobile os / browser in question. Happy to re-open if it can be demonstrated as still broken on modern devices via a test case.
