### ISSUE TITLE
scale.zoom mode doesn't zoom as I expect

### ISSUE THREAD

**Issue by BinaryMoon** [photonstorm/phaser#4697]
Hi - I asked about this on Discord a while ago and Rich said it should be an easy fix and added a mention to this ticket - https://github.com/photonstorm/phaser/issues/4633

This is a follow up ticket to hopefully get it fixed.

I should add that I didn't know if this was a bug or a feature. From my perspective an existing feature didn't work as I expected so I am reporting it as a bug, but it could be a feature since it seems I misunderstood how it should work.

## The problem

I am making a full screen pixel art game, and I want to be able to scale the pixels so they are displayed larger. However when I set the scale:zoom amount the game does not scale up.

I expected setting the zoom value as follows would make each pixel 4 pixels in size:

```
game_config {
	scale: {
		zoom: 4
	}
}
```

**Comment by photonstorm** [comment]
@BinaryMoon hey Ben, sorry but I have to confess I don't recall what this issue was any longer 😬 Setting the `zoom` value will create a canvas still at the original dimensions, but with a display width/height of the zoom factor:

```js
    scale: {
        mode: Phaser.Scale.NONE,
        parent: 'phaser-example',
        width: 160,
        height: 144,
        zoom: 4
    },
```

Would create a canvas with the follow properties:

![image](https://user-images.githubusercontent.com/164476/94128643-4c5a9680-fe52-11ea-8d6e-9916050028b4.png)

Were you expecting it to create a canvas of size 640x576 (in this case)?

**Comment by BinaryMoon** [comment]
Hey Rich - This is going back a bit :)

If I recall correctly I didn't expect the canvas to change size at all, I expected the content to zoom in so that each pixel was drawn at 4x4 pixels.

I often make the canvas full screen but I don't want to make a game that is 1000+ pixels wide, so I want to zoom into the canvas and get nice crisp pixel art.

Thanks

**Comment by photonstorm** [comment]
I think this is what happens now, right? The canvas is still only 160x144 in size, so that's the total number of pixels being rendered, it's just scaling up x4 with CSS, to give a visual display of 640x576:

http://labs.phaser.io/100.html?src=src/scalemanager/zoom%20with%20no%20scale.js

If you right-click the canvas on this demo and 'copy image', the image you get is only 160x144 in size.

**Comment by BinaryMoon** [comment]
Not really. I don't want the canvas to be larger. If I set it to 100px wide then I want it to stay 100px wide, but the pixels to be 4 times the size.

Thinking about it now though I guess I might be able to set the canvas to a quarter of the size I want and then use the zoom to enlarge to the desired size. It's been a while since I've worked on this so I'd have to test to see if it works the way I wanted.

I think the problem I had is that I set a size, and then a zoom, and then the size is not what I had set it to be.

**Comment by BinaryMoon** [comment]
All that said. It might be an edge case, especially if nobody else has mentioned it. It's just that the setting did not work in the way I expected it to.

**Comment by photonstorm** [comment]
Fair enough, but to me, it's working exactly as I intended it to. It was never meant to zoom the pixels (that is what camera zooming is for), it was meant to up-scale a canvas without changing the pixel dimensions of it. Afraid I'm going to have to close this one off as it's doing what I intended.
