### ISSUE TITLE
Unavailable to use RenderTexture as source for TileSprite

### ISSUE THREAD

**Issue by pavel-shirobok** [photonstorm/phaser#4719]
## Version 
* Phaser Version: 3.19
* Operating system: Windows 8.1

## Description
Texture created with RenderTexture can't be used as source for TileSprite. Only transparent tileSprite, with no errors or warnings

## Example Test Code
https://codepen.io/pavel-shirobok/pen/abomqgP?editors=0010

**Comment by photonstorm** [comment]
Thank you for opening this issue. This is a limitation in the way TileSprites work. However, in 3.20 they will now throw a console warning if you try to create one from the incorrect texture type.

**Comment by pavel-shirobok** [comment]
@photonstorm Thanks for explanation and update. Is there a chance to make it work sometimes in future?

**Comment by photonstorm** [comment]
Not really I'm afraid. You could get around it by using `RenderTexture.snapshot()` and the image you get back from that could be added to the Texture Manager. Then it's just a normal image, so is safe to use for a TileSprite. This is a massive assumption for Phaser itself to make though, so it won't do it automatically.

**Comment by pavel-shirobok** [comment]
@photonstorm Is it kind of webgl's or phaser's limitation? Is there chance to get it work with some PR? And if it's phaser, so can you let me reference for getting start point where to see it? Thanks a lot at all! :)

**Comment by photonstorm** [comment]
TileSprites use a canvas object internally which they create a fill pattern from. You can't `drawImage` a WebGL Texture to a canvas, which is why you can't use a Render Texture (or anything else specifically WebGL, like a Shader). So, instead, you need to snapshot the GL Texture, which is an _async_ process!, save that to the Texture Manager, then apply this to the TileSprite so it can rebuild its internal canvas fill pattern. Which is fine if you do it locally in your own code, but too much of a change to do internally.

**Comment by pavel-shirobok** [comment]
@photonstorm thanks a lot for explanations!

**Comment by rexrainbow** [comment]
RenderTexture can draw on canvas when [render type is CANVAS](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/rendertexture/RenderTexture.js#L285). Perhaps we could add a  parameter of render texture, to force drawing on canvas with canvas render, in webgl mode.

**Comment by rexrainbow** [comment]
Render-texture can draw game object on canvas, if 
1. Canvas render is also available in webgl mode, and
2. Force render-texture runs in canvas mode.

But point 1. is a big change of p3 engine...

**Comment by photonstorm** [comment]
Yes, the problem is a mixture of concerns: If you force a Render Texture to use canvas, then you could draw it to a TileSprite, but you _can't_ then draw GL based items to that Render Texture! (such as cameras, shaders, other RTs, etc) - so you make one thing work, but it breaks something else in the process.

**Comment by pavel-shirobok** [comment]
Im not a profession in phaser and webgl, so sorry for maybe stupid words. But maybe it can be solved by extending/new pipeline? I mean I can use RenderTexture for adding it's glTexture to camera's pipeline for example, and have no problem to show it or combine with other units. So perhaps it's limitation of TintTexturePipeline?

**Comment by photonstorm** [comment]
It's not really anything to do with the pipeline. It's purely because TileSprites use a canvas fill pattern to generate their base texture. If they used something else, like a frame buffer, then it could work, but they don't and it's a huge change to implement.

**Comment by pavel-shirobok** [comment]
@photonstorm @rexrainbow Hi, guys, I know I can be annoying, but what about this [codepen](https://codepen.io/pavel-shirobok/pen/BaBXmWG?editors=0010)?

**Comment by photonstorm** [comment]
If that solution works for you, there is no reason not to use it. It doesn't support `tileScaleX/Y` by the looks of it, but if you don't need that, then it hardly matters.
