### ISSUE TITLE
Tilemap.convertLayerToStatic throws error when used multiple times

### ISSUE THREAD

**Issue by Vegita2** [photonstorm/phaser#4737]
## Version

* Phaser Version: v3.17.0

* Operating system: Linux Mint 19.1

* Browser: Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

## Description

When using `Tilemap.convertLayerToStatic` multiple times the function throws an error.
```
Uncaught TypeError: Cannot read property 'tilemapLayer' of undefined
    at Tilemap.convertLayerToStatic (VM591 3.17.0.js:100799)
    at Scene.create (eval at <anonymous> (frame.html:45), <anonymous>:35:6)
    ...
```

## Example Test Code

```
var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    backgroundColor: '#ffffff',
    parent: 'phaser-example',
    pixelArt: true,
    scene: {
        preload: preload,
        create: create
    }
};

var game = new Phaser.Game(config);
var controls;

function preload ()
{
    this.load.image('walls_1x2', 'assets/tilemaps/tiles/walls_1x2.png');
}

function create ()
{
    var map = this.make.tilemap({ width: 200, height: 200, tileWidth: 32, tileHeight: 32 });

    var tiles = map.addTilesetImage('walls_1x2', null, 32, 64);

    var layer = map.createBlankDynamicLayer('layer1', tiles);
    layer.randomize(0, 0, map.width, map.height, [ -1, -1, -1, 0]);

    var layer2 = map.createBlankDynamicLayer('layer2', tiles);
    layer2.randomize(0, 0, map.width, map.height, [ -1, -1, -1, 0, 1]);

    map.convertLayerToStatic(layer)
    map.convertLayerToStatic(layer2)
}


```

**Comment by Olliebrown** [comment]
When you call `convertLayerToStatic()` the layer passed in will be destroyed.  Inside of the `destroy()` function, there is a call to `tilemap.removelayer()` which removes the layer from the array of layers inside the tilemap.  The created static layer is NOT added into the tilemap in its place.  The end result is that there is one fewer layers in the array of layers in the tilemap.

All of the layers in this array that come after the removed layer will now have an INCORRECT layerIndex.  Each layer has a property `layerIndex` that is set when it is added to the tilemap and is equal to its index in that array.  It is NOT updated when a layer is removed and that causes the problem you are seeing.  I will see about submitting a PR to fix this but below are a few workarounds you can do.

--------

Fix the layerIndex manually after calling convertLayerToStatic:
```javascript
map.convertLayerToStatic(layer) // Remove layer at index 0
layer2.layerIndex = 0 // This layer now needs to be one less
map.convertLayerToStatic(layer2)
```

Convert the layers in opposite order so that the last layer gets deleted first:
```javascript
map.convertLayerToStatic(layer2)
map.convertLayerToStatic(layer)
```

Both the above changes avoid the bug for me.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
