### ISSUE TITLE
Can not load Tiled 1.2 map with Collection of Images

### ISSUE THREAD

**Issue by dranitski** [photonstorm/phaser#4780]
## Version

* Phaser Version: Phaser v3.19.0-FB (WebGL | Web Audio)

* Operating system: Arch Linux, but the problem is not OS-specific

* Browser: Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)

## Description

Hello! I am having a problem while trying to load Tiled map where tiles are not based on Tileset Image but are represented by **collection of Images** (read [here in Tiled docs](https://doc.mapeditor.org/en/stable/manual/editing-tilesets/))

Here is the difference:
Tiled JSON Map based on Tileset Image:
![111](https://user-images.githubusercontent.com/27373393/66068307-0710cb00-e556-11e9-9732-9c00ea6df642.png)

Tiled JSON Map represented by collection of Images:
![112](https://user-images.githubusercontent.com/27373393/66068328-11cb6000-e556-11e9-8a19-f6d68bd22d41.png)

Here is my code https://bitbucket.org/dmitrydranitski/phaser3-tiled-collectionofimages/src/master/
You can reproduce the issue by cloning it, running npm install and npm start.

I have an error
![113](https://user-images.githubusercontent.com/27373393/66068347-1abc3180-e556-11e9-90a1-6a8831090286.png)

As I can see in source code Phaser3 parser knows of such scenario and even creates an ImageCollection [ParseTilesets.js#L136](https://github.com/photonstorm/phaser/blob/master/src/tilemaps/parsers/tiled/ParseTilesets.js#L136)

But then the parser falls to getting data from empty (in that case) mapData.tiles array: [AssignTileProperties.js#L48](https://github.com/photonstorm/phaser/blob/master/src/tilemaps/parsers/tiled/AssignTileProperties.js#L48)

**Am I doing something wrong, is that a bug or such tilemaps are not supported?**
For me uniting all my images into a single file (for example with TexturePacker) is not an option because tons of maps and tilesets are made by the moment and changing them all will be a total pain. 

I will try to dig into Phaser3 sources deeper tomorrow to understand why parser behaves like that and what it tries to do in [AssignTileProperties.js#L48](https://github.com/photonstorm/phaser/blob/master/src/tilemaps/parsers/tiled/AssignTileProperties.js#L48)

## Example Test Code

Here is my code https://bitbucket.org/dmitrydranitski/phaser3-tiled-collectionofimages/src/master/
You can reproduce the issue by cloning it, running npm install and npm start.

**Comment by Olliebrown** [comment]
Examining the code for Tilemap loading (something I've been working on a lot lately) it looks to me like support for Image Collection type tilesets is incomplete. Yes, it does attempt to parse them and include them in the map data but that's as far as it goes.  It does not include image collection tiles in the global tilemap and that's why the line you point out results in an undefined error.

One thing I run into with your example map json were unusual tile IDs.  There seems to be an assumption in the JSON parsing code in phaser that the IDs for individual tiles will be sequential and start at 0.  Yours do not (they are 290, 416 and 441 but they should be just 0, 1, and 2) and are one less than the IDs listed in the imagecollection's 'tiles' array.  I'm no expert on Tiled but I can see from Phaser's parser that the actual IDs of tiles are largely ignored (except when reading out tileProperties and tileData).  Instead, it seems there is an assumption that they are globally sequential in the same order as the tilesets appear in the tileset array.  Perhaps this is not a safe assumption and that would be a much BIGGER problem to solve if this is the case.

Ultimately, fixing this and completing support for image collections looks like a very deep rabbit hole and will take some time.  I was able to get it to at least parse our data (with some fairly significant changes) but nowhere close to actually drawing the map.  I may still work on this but first, I would need to understand where your map data came from and confirm that it is a possible output from tiled.  Can you maybe share the TMX file that gave you this json?

**Comment by jakewright** [comment]
It'd be great to have support for a collection of images. I've run into the same issue, though my tile IDs _are_ sequential and start at 0, as expected.

**Comment by gogoprog** [comment]
I implemented a quick solution in #4964

**Comment by photonstorm** [comment]
Closing this issue off, as I merged the 'tileset from image collection' PR some time ago, and today fixed the non-consecutive tile IDs bug as well.

**Comment by neu5** [comment]
I have the same problem. I created minimal repo containing TMX files:
https://github.com/neu5/phaser-tiled-isometric
@Olliebrown do you think you could look at this?

**Comment by douglasg14b** [comment]
Is this still a problem?

```ts
    preload ()
    {
        this.load.image("tiles","src/assets/cityTiles_sheet.png");
        this.load.tilemapTiledJSON({ key: 'map', url: 'src/assets/BaseGameMap.json'});
    }

    create ()
    {
        const map = this.make.tilemap({ key: 'map' })
        const tileset = map.addTilesetImage('City_Tiles', 'tiles')
    }
```


When using  a collection of images in `src/assets/BaseGameMap.json'` results in a map with layers that are each names as the path to the tile. But the original layer `City_Tiles` is gone after loading.

I just get a `No data found for Tileset: City_Tiles` warning.

![image](https://user-images.githubusercontent.com/1400380/229411496-6113f264-1763-4928-801b-5f0063c56a54.png)

![image](https://user-images.githubusercontent.com/1400380/229411515-7b5b3cce-b839-48f1-bc7b-7f7d2c5b5ca8.png)
