### ISSUE TITLE
Matterjs difference between poly shape and gameObject verts shape

### ISSUE THREAD

**Issue by ClemDelp** [photonstorm/phaser#4931]
## Version
Phaser Version: 3.21.0
Operating system: macOS Catalina
Browser: chrome 79.0.3945.88

## Description
I'm adding a polygon then a matter.gameObject shape to apply correct physic interaction body with exactly the same points (string path) but the render is different and so the physic is not applied correctly.

Illustrated with the following image, you can see in pink the "gameObject shape verts" (display by debug: true config) and in purple the polygon placed by game.add.polygon:

![image](https://user-images.githubusercontent.com/4126690/71523366-f360d080-28c8-11ea-9ff5-15a6c325486d.png)

## Example Test Code

```
var poly = this.add.polygon(
    CONFIG.game.width / 2,
    CONFIG.game.height / 2,
    groundPath,
    0x0000ff,
    0.2
  );

this.matter.add.gameObject(poly, {
    isStatic: true,
    ignoreGravity: true,
    shape: {
      type: 'fromVerts',
      verts: groundPath,
      flagInternal: true
    }
});
```

## Additional Information

Exactly the same result if I try to use matter.add.fromVertices instead:

```
var verts = this.matter.verts.fromPath(groundPath);
this.matter.add.fromVertices(
    CONFIG.game.width / 2, // The X coordinate of the center of the Body.
    CONFIG.game.height / 2, // The Y coordinate of the center of the Body.
    verts, // [description]
    {
      ignoreGravity: true,
      isStatic: true
    }, // [description]
    true, // Flag internal edges (coincident part edges)
    0.01, // Whether Matter.js will discard collinear edges (to improve performance).
    10 // During decomposition discard parts that have an area less than this.
)
```

groundPath format is ```883 2 883 3 882 3 882 4 881 4 881 5 880 5 879 5 879 6 878 6 878 7 877 7 877 8 876 8 876 9 877 9 877 10 876 10 875 10 875 9 874 9 873 9 87.....```

An other strange point is the fact that the location in the space between gameObject and the poly are different.

**Comment by photonstorm** [comment]
This is to be expected as the two objects are very different. A Polygon Game Object has an origin (which you can adjust) that defaults to 0.5, where-as Matter body positions are based on the center of mass, not their dimensional center point, and the center of mass changes based on the vertices.

Also, a Matter body needs convex polygons and will pass your path data through poly-decomp in order to achieve that. It will also clockwise sort the vertices and remove co-linear points. A Phaser Polygon has no such requirement, as it's not used for physics, so you can specify the vertices in any order. They're just a bunch of linear points that map to the perimeter of the polygon.

As such, the two objects are going to be vastly different depending on how complex the path data is and there's really nothing that can be done about it I'm afraid.

**Comment by photonstorm** [comment]
Thinking about it a little more, you could try to use the Matter body vertices, once the body has been created, for the Polygon Game Object, rather than the raw path data. Then it would have to build the polys out of the decomposed data, so they would match up. You would have to create one Polygon object per Matter Path, though, as the decomposition will have broken the data down into a series of polygons, not just one single one.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/polygon-render-is-wrong/4965/2
