### ISSUE TITLE
Ability to set gameObject rerender needs

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#4980]
Hi, I'm making games for mobile devices and using full HD assets. And as I saw phaser performance drops with full HD assets. For example, I've full HD background image, just removing that image from the scene increases fps by 5 in my game. So I thought about the ability to say which texture might be rendered on every frame and which can stay as it was. I've set that background with an image tag in behind my canvas div and as a result, I've fixed my fps by that 5 fps. 
On another side I've game objects that are in one container and aren't being changed during the game, just container is being moved.
As we know the game with phaser is being rendered from back to front, so if I've container with multiple game objects in it, that container's every component will be re-rendered on every frame. The ability to set the container not re-renderable by its components will fix the problem. And a lot of performance problems can be fixed by this. 
Unfortunately, I haven't read how rendering happens in phaser and can't say is it possible or not, but I think it costs to try.

**Comment by photonstorm** [comment]
It's not possible, sorry. The canvas is cleared every frame. So every frame it starts blank, then it works its way through, rendering each item in turn. It has no knowledge of which items have been updated since the last frame. In order to do that, every Game Object would need some kind of 'dirty' flag, which is set by _any_ component that modifies it in some way during that frame. So changing its position flags it as dirty. Or changing scale, or alpha, or tint, or animation frame, or literally anything that has changed how or where it appears on the canvas. To add this flag is a massive change across pretty much the whole Game Object API.

Once you have the flag, however, you could start to implement the ability for the renderer to skip the whole clean + draw process if nothing has changed that frame. You could probably also implement some kind of dirty rectangles system, so only the areas of the canvas that contain dirty items are cleared and redrawn. Both of these are non-trivial. Even Pixi 5 doesn't offer them.

And none of that would avoid a Container re-rendering its children. To do that, the Container would need to render its children to its own texture / fbo, not to the canvas. Depending on the size of the children, this could be huge, so it's not something that could be enabled by default. If you've a truly static container, it makes a lot more sense to use a Render Texture instead.

The frame rate is tightly linked to the GPU fillrate. Every pixel you draw costs time. It doesn't matter if that's done via a thousand small sprites or a couple of massive images, the fillrate is fundamentally the same. Once you're filling too many pixels for the device, performance suffers. There's no way to automagically cure this, it just comes down to testing and careful use of assets. Once you accept the fact that "this is the fillrate my GPU can handle", you can work back from there. Of course, there are other factors that influence performance, but fillrate is one of those hard and fast limits that can't be changed and needs to be worked around.
