### ISSUE TITLE
video.play(), and video.setPaused(false) methods

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5000]
[`video.play()`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/video/Video.js#L434) can play video and attach events.
[`video.setPaused(false)`](https://github.com/photonstorm/phaser/blob/master/src/gameobjects/video/Video.js#L1441) can resume (play) video without attaching any event.

Ideally, uses `video.play()` to start playing at 1st time, then uses `video.setPaused(false)` to resume playing on the other times. I use a boolean variable to distinguish these different states.
```javascript
var played = false;
var PlayVideo = function() {
    if (!played) {
        played = true;
        video.play();
    } else {
        video.setPaused(false);
    }
}
```

How about add a private variable like `video.played` in Video class for this logic? Therefore user can use `video.play()` for all cases.

**Comment by photonstorm** [comment]
Thanks for the suggestion, but honestly, I'm happy with having this split across 2 methods. Especially as you'd need to add a parameter to `video.play()` in order to pause the video, but it already has lots of parameters, so I think it would get a bit messy. I feel that tracking the state in your own variable isn't too much to ask?

**Comment by rexrainbow** [comment]
There has a workaround, so it is ok. Issue closed.
