### ISSUE TITLE
Difficulty positioning a rect polygon from PhysicsEditor JSON

### ISSUE THREAD

**Issue by Jazcash** [photonstorm/phaser#5007]
## Version

* Phaser Version: 3.22.0

* Operating system: Windows 10

* Browser: Chrome

## Description

I've drawn a collision polygon for my matter sprite using PhysicsEditor like so:

![image](https://user-images.githubusercontent.com/1434248/74611407-79dca600-50f3-11ea-93e1-ff6153a4d69a.png)

The generated JSON:

```
"ground-layer": {
		"type": "fromPhysicsEditor",
		"label": "ground-layer",
		"isStatic": true,
		"density": 0.10000000149011612,
		"restitution": 0,
		"friction": 0.10000000149011612,
		"frictionAir": 0.009999999776482582,
		"frictionStatic": 0.5,
		"collisionFilter": {
			"group": 0,
			"category": 1,
			"mask": 255
		},
		"fixtures": [
			{
				"label": "",
				"isSensor": false,
				"vertices": [
					[ { "x":0, "y":54 }, { "x":0, "y":244 }, { "x":2048, "y":244 }, { "x":2048, "y":54 } ]
				]
			}
		]
	}
```

But my game is rendering in the center like this:

![image](https://user-images.githubusercontent.com/1434248/74611438-bb6d5100-50f3-11ea-97a2-0c19b9e93b34.png)

If I change the polygon to not be a perfect rect, e.g.

```
"vertices": [
    [ { "x":0, "y":54 }, { "x":0, "y":245 }, { "x":2048, "y":244 }, { "x":2048, "y":54 } ]
]
```

Then it renders exactly how it looks in PhysicsEditor:

![image](https://user-images.githubusercontent.com/1434248/74611471-0dae7200-50f4-11ea-9f90-9d6033bc06bd.png)

**Comment by hexus** [comment]
This seems like it might be a center of mass problem, which is how Matter centers its physics bodies. It's difficult to know this for certain without seeing anything other than your JSON, but try following @CodeAndWeb's tutorial on using PhysicsEditor with Phaser 3. It explains this very well:

https://www.codeandweb.com/physicseditor/tutorials/how-to-create-physics-shapes-for-phaser-3-and-matterjs

Indeed, because this issue seems to be simply with difficulty using Phaser, PhysicsEditor and Matter, I'd suggest directing questions like these to community channels before opening a bug report, as noted in the bug report template you will have seen when posting this issue:

> This repo should not be used for technical support. If you're struggling to use Phaser then post your question to the [forum](https://phaser.discourse.group/), [Slack](https://phaser.io/community/slack) or [Discord](https://phaser.io/community/discord) channels. GitHub Issues are for bugs and feature requests only.

If you can provide a code example, even when using the method mentioned in the tutorial above, please feel free to open another issue, but it _must_ contain a code example, once again as mentioned in the bug report template:

>All issues must have source code demonstrating the problem. We automatically close issues after 30 days if no code is provided.
> 
> The code can be pasted directly below this comment, or you can link to codepen, jsbin, or similar. The code will ideally be runnable instantly. The more work involved in turning your code into a reproducible test case, the longer it will take the fix the issue.

Cheers!
