### ISSUE TITLE
make.image leaves textureless quad in the scene

### ISSUE THREAD

**Issue by JimZeeKing** [photonstorm/phaser#5010]
## Version

* Phaser Version: 3.22

* Operating system: Win 10

## Description
Using this.make.image leaves a textureless quad in the scene (same with this.make.sprite)

## Test code

```
var config = {
    parent: "gameContainer",
    type: Phaser.AUTO,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    scene: {
        preload: preload,
        create: create,
        update: update
    },
    backgroundColor: 0xffffff
};

var game = new Phaser.Game(config);

function preload() {
    this.load.image("Hello", "../assets/images/hello.png");
}

function create() {
    //this creates a visible quad on scene
    this.make.image(game.renderer.width / 2, game.renderer.height / 2, 'Hello');
    // this.add.image(game.renderer.width / 2, game.renderer.height / 2, 'Hello');
}
```

**Comment by samme** [comment]
Do you see ![green rectangle with diagonal slash](http://labs.phaser.io/assets/sprites/default.png)?

**Comment by JimZeeKing** [comment]
Yes

**Comment by photonstorm** [comment]
The `make.image` parameters are incorrect. There are only two parameters, a configuration object and a boolean called `addToScene`. As you're passing a valid size as the boolean, it will equate to `true`, so a broken image is added to the scene (because the first parameter is an invalid config object)

Check the docs / examples for further details.
