### ISSUE TITLE
Timelines do not guarantee sequential tween callback order

### ISSUE THREAD

**Issue by snowbillr** [photonstorm/phaser#5144]
## Version

* Phaser Version: Phaser v3.22.0-FB

* Operating system: macOS 10.14.5

* Browser: Not browser specific

## Description

Expected behavior: For multiple tweens in a timeline, each tween's onStart and onComplete callbacks should be called in-order as the timeline executes.

Actual behavior: sometimes a subsequent tween's onStart callback is called prior to the previous tween's onComplete callback.

## Example Test Code

https://codepen.io/snowbillr/pen/vYNaEJd?editors=1111

Take a look at the console log in that codepen. Here's an example run:

```
"start 1"
"complete 1"
"start 2"
"start 3"
"complete 2"
"start 4"
"complete 3"
"complete 4"
```

and here's what output is expected:

```
"start 1"
"complete 1"
"start 2"
"complete 2"
"start 3"
"complete 3"
"start 4"
"complete 4"
```

## Additional Information

None.

**Comment by khaledbnmohamed** [comment]
Bro You are a lifesaver !! I completely lost my enthusiasm for learning this framework. I was hopelessly searching for an open issue that solves the mystery so THANK YOU.

**Comment by snowbillr** [comment]
That's always a satisfying feeling to see someone having the same issue as you 😂 

There's been no work towards a resolution for this in Phaser as far as I know, but if it's helpful, here's how I got around it.

I built a [`CallbackQueue`](https://github.com/snowbillr/scooch-dungeon/blob/master/src/lib/callback-queue.ts) that I add my callbacks to in their expected execution order when I'm constructing my timeline. Then, in my timeline and each of the tweens' `onStart` and `onComplete` callbacks, I call `callbackQueue.runNext()`. That way, even if there are tween callbacks that happen out of order, my callback queue will still run them in the order I'm expecting.

You can see it being used here: https://github.com/snowbillr/scooch-dungeon/blob/master/src/dungeon/movement-planner.ts#L21

I don't know if this results in millisecond differences for when the callbacks should actually be running for tween's completing and starting, but there hasn't been any problem in my game with this solution, so I'm continuing to use it.

**Comment by khaledbnmohamed** [comment]
> That's always a satisfying feeling to see someone having the same issue as you 
> 
> There's been no work towards a resolution for this in Phaser as far as I know, but if it's helpful, here's how I got around it.
> 
> I built a [`CallbackQueue`](https://github.com/snowbillr/scooch-dungeon/blob/master/src/lib/callback-queue.ts) that I add my callbacks to in their expected execution order when I'm constructing my timeline. Then, in my timeline and each of the tweens' `onStart` and `onComplete` callbacks, I call `callbackQueue.runNext()`. That way, even if there are tween callbacks that happen out of order, my callback queue will still run them in the order I'm expecting.
> 
> You can see it being used here: https://github.com/snowbillr/scooch-dungeon/blob/master/src/dungeon/movement-planner.ts#L21
> 
> I don't know if this results in millisecond differences for when the callbacks should actually be running for tween's completing and starting, but there hasn't been any problem in my game with this solution, so I'm continuing to use it.

Seems like a promising implementation but kinda hard to grasp especially while having my first steps using phaser. Thank you again for your help

**Comment by photonstorm** [comment]
I know _why_ this happens, but it's a non-trivial fix. The issue is time slippage. When the Timeline is created, the tweens all have precise starting offsets (0, 200, 400, 600 in your case) which are pre-calculated. These are the equivalent of 'startDelay'.

What happens with Timelines is that all of the tweens are running in parallel, together. They are _not_ started when the previous one completes, they're started when `Timeline.play` is called. However, the subsequent tweens in the array are given `offset` values, to stop them from updating until they should do. Because updates are linked to the browser time, which rarely updates perfectly, the first tween may end after 228ms, not 200, so it has gained an extra 28ms. However, tween 2 is going to start as well (at 228ms), which is 28ms _late_. By the time that completes, tween 3 has already begun, because 400ms have passed, and so on. Because the tweens are so tight together with no delays, they will overlap in terms of start and end times.

If you put `this.tweens.createTimeline({ useFrames: true });` you'll see it works perfectly, in the exact sequence expected, because it's no longer relying on time values and is instead using render frames.

The reason this is hard to fix is that Timelines aren't sequential - you can have overlapping tweens (indeed, it's what they're best for imho), so it isn't a simple case of waiting for one tween to end before making the next. I'll have a think about this further, but I'm not sure of an 'elegant' fix tbh.

**Comment by snowbillr** [comment]
That makes a lot of sense! Thanks for the explanation.

My initial use case for the timeline was to run tweens sequentially. I tried to do this first without timelines by creating the next tween in the `onComplete` callback of the previous tween. The problem with that approach was that there was a delay in between the tweens - they weren't continuous since there was a frame after the previous tween ended and the new one started. So I switched to using timelines instead.

Do you have a recommendation for running sequential tweens, with no frame delay in between their endings and beginnings, without using a timeline?

**Comment by photonstorm** [comment]
Just to say that Timelines have been removed from Phaser 3.60 and replaced with the new Tween Chain system, which enables perfectly sequenced playback. Although this is a breaking change, I feel it was worth making for the benefits it brings (such as fixing issues like this!)
