### ISSUE TITLE
Add setInteractive bounds on graphics to documentation

### ISSUE THREAD

**Issue by marcus13345** [photonstorm/phaser#5245]
If documentation related issues shouldn't be here, let me know, ill close and move this elsewhere.

The syntax solution in #4194 should be documented somewhere. Possibly in [Input:InputConfiguration](https://photonstorm.github.io/phaser3-docs/Phaser.Types.Input.html#.InputConfiguration) as Graphics links out to it. 

Having shape be documented as an `any` type with no real explanation of what data it wants, is extremely unhelpful.

As well, the idea of the callback function being used to determine whether a a given point is within a geometry, while extremely modular, is not explained very well. My first idea was to simple pass an array of coordinates, as its similar to the way [this example](https://phaser.io/examples/v3/view/input/game-object/change-sprite-hitarea-size) works.

**Comment by samme** [comment]
In Phaser terms [geometric shape](https://photonstorm.github.io/phaser3-docs/Phaser.GameObjects.GameObject.html#setInteractive "setInteractive()") usually means one of the [Geom](https://photonstorm.github.io/phaser3-docs/Phaser.Geom.html) classes.

I think the `any` type is necessary because you could use any data source and then handle it in your own callback.

**Comment by marcus13345** [comment]
@samme I was going to try and add a little nuance to what I meant to say, but after taking a looking at the referenced PR, I think that hits the nail on the head.
