### ISSUE TITLE
Lights don't turn on and have low FPS when there are several (approx 10) sprites on screen

### ISSUE THREAD

**Issue by jacola** [photonstorm/phaser#5265]
## Version
* Phaser Version:
Phaser v3.50.0-beta.1 (WebGL | Web Audio)  https://phaser.io

* Operating system:
macOS 10.15.5 & iOS 13.6

* Browser:
Chrome Version 84.0.4147.105 (Official Build) (64-bit) & mobile Safari 

## Example Test Code

I create several lights based on my Tiled map's object layer.
```
const light = this.lights.addLight(obj.x + 16, obj.y + 16, radius); 
light.setIntensity(intensity);
```

<img width="1206" alt="Screen Shot 2020-08-12 at 22 04 33" src="https://user-images.githubusercontent.com/941214/90018816-77e15180-dce8-11ea-9da0-1840730cfe07.png">

They don't turn on unless I flag them as dirty.
```
      this.lights.forEachLight((light) => {
      const dist = getDistance(
        curPlayer.sprite.x,
        curPlayer.sprite.y,
        light.x,
        light.y
      );
      // Game is running at 800x450, so this distance is hard coded...
      if (dist < 600) {
        light.dirty = true;
      }
    });
```

<img width="1206" alt="Screen Shot 2020-08-12 at 22 04 52" src="https://user-images.githubusercontent.com/941214/90018875-92b3c600-dce8-11ea-8f78-e5ccf67f1804.png">

## Additional Information
The FPS on iOS & macOS becomes unusable with lighting enabled and there are multiple sprites on the screen, while Android and Linux only see small fluctuations in FPS.
![IMG_2966](https://user-images.githubusercontent.com/941214/90018774-68620880-dce8-11ea-8890-3b74429d4b21.PNG)

**Comment by photonstorm** [comment]
As discussed on Discord, the Lights shader is computationally expensive. If you don't need 10 _real_ lights, turn this number down to the smallest you can possibly have it! Also, remember that on Tilemaps there was a batching bug which caused performance to go through the floor, this is now fixed in the master branch. If you don't need the lights to change the sprites re: normal maps, use the new Point Light Game Object instead.
