### ISSUE TITLE
Unexpected behaviour of ArcadeBodyCollision if monitor frequency exceeds game FPS

### ISSUE THREAD

**Issue by R33D3M33R** [photonstorm/phaser#5283]
## Version
* Phaser Version: v3.24.1
* Operating system: Linux
* Browser: any hardware accelerated browser

## Description

Dear developer(s),

I have been trying to create a simple arcade game in which a player scores if the opposing player fails to block it with the paddle. I detect collisions with the world bounds by using **body.blocked** (sample code below). 

I have discovered that the game doesn't work properly in hardware accelerated browsers (Chromium/Opera) if monitor frequency (120 Hz) exceeds game FPS (60 FPS), as the body.blocked event fires multiple times on every boundary hit. As soon as this.physics.world.setFPS(120) is used, the problem disappears. In Firefox, everything works perfectly regardless of FPS.

IMHO, this is unexpected behaviour, but it also might be an user error as I'm a complete beginner with this framework.

Best regards,
Andrej

## Example Test Code

```javascript
var gameScene = new Phaser.Class({
    Extends: Phaser.Scene,
    create: function () {
        ballVelocity = 300;
        ball = this.add.circle(400, 300, 10, '0xffffff');
        this.physics.add.existing(ball);
        ball.body.setCollideWorldBounds(true);
        ball.body.setBounce(1, 1);
        ball.body.position.setTo(150, 150);
        ball.body.velocity.setTo(300, 300);
    },

    update: function () {
        // boundary hit
        if (ball.body.blocked.up) {
            console.log('up')
        } else if (ball.body.blocked.down) {
            console.log('down')
        } else if (ball.body.blocked.left) {
            console.log('left')
        } else if (ball.body.blocked.right) {
            console.log('right')
        }
    },
});

window.onload = function () {
    game = new Phaser.Game({
        type: Phaser.AUTO,
        width: 800,
        height: 600,
        physics: {
            default: 'arcade',
            arcade: {
                gravity: false,
                debug: true
            }
        },
        scene: [gameScene]
    });
};

```

**Comment by samme** [comment]
I think that's expected, because `update()` would be running twice as often as the physics step.

I can think of a few solutions (choose one):

- Move the contents of `update()` into a [WORLD_STEP](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.Events.html#event:WORLD_STEP) event handler
- Set [physics.world.fixedStep](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.World.html#fixedStep) = true
- [physics.world.setFPS](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.World.html#setFPS) 120
- [physics.world.setFPS](https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Arcade.World.html#setFPS) 120 if [game.loop.actualFps](https://photonstorm.github.io/phaser3-docs/Phaser.Core.TimeStep.html#actualFps) is near 120 after a few seconds (see <https://codepen.io/samme/pen/KbdXad>)

**Comment by R33D3M33R** [comment]
Hello, thanks for your input. 

This was clearly my mistake thinking update and physics step are automatically in sync. I will definitely use the WORLD_STEP event handler from now on. 

Best regards,
Andrej

**Comment by samme** [comment]
No mistake, really. 🙂 The example are written that way, because it's the simplest, but as you noted, it's not really consistent with a fixed-step physics delta.

For a lot of games I think authors may prefer `this.physics.world.fixedStep = false`.
