### ISSUE TITLE
Change game size in resize event not working

### ISSUE THREAD

**Issue by iforcode** [photonstorm/phaser#5290]
* Phaser Version:
3.24.0

## Description
I try to handler resize browser by `scale.on('resize')` event and i will change size of game like

`create ()`
`{`
`    this.scale.on('resize', this.resize, this)`
`}`
`resize(gameSize, baseSize, displaySize, resolution) {`
`   this.scale.setGameSize(window.innerWidth, window.innerHeight)`
`}`

But i get error when i resize browser

`VM15 phaser.min.js:1 Uncaught RangeError: Maximum call stack size exceeded`
`    at initialize.onResize (VM15 phaser.min.js:1)`
`    at initialize.o.emit`
`   ...`

## Example Test Code
https://jsfiddle.net/3gsaj7ot/

**Comment by photonstorm** [comment]
There's no need to call `setGameSize` as it has already been updated to the new size by this point, plus it's causing the error, because invoking it launches the resize event, which invokes it again, etc. The only thing you're likely to need to do in your resize handle is to change the camera sizes `this.cameras.resize()`, and any other custom logic your game needs.
