### ISSUE TITLE
GameObject x and y readonly modifier missing in the documentation

### ISSUE THREAD

**Issue by monteiz** [photonstorm/phaser#5365]
## Version

* Phaser Version: 3.24.1

This issue is about the documentation. In the **GameObject** class (and subclasses) the `x` and `y` members should me marked as `readonly`.

I was naively using the members to set the position of my **GameObject**(s), but I had some silent misbehaviour. I am now using `setX` and `setY` instead, and everything works properly.

Maybe it is documented somewhere else, but having these two members marked as `readonly` would certainly save some headache 😉

**Comment by photonstorm** [comment]
But they're absolutely not read-only! You can change them as often as you like and I do it in nearly every example on the site. There's literally no difference between changing the `x` property or using `setPosition`, one just updates the other. The only time you would get issues is if you're got a physics object, because then you should move the object using forces, not by changing its position. Aside from this, they're definitely safe to use.

**Comment by monteiz** [comment]
I gave myself a thumbs-down for this.
