### ISSUE TITLE
[3.50-beta11] Mesh+RenderTexture

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5415]
## Version

* Phaser Version: 3.50-beta11

* Operating system: win10

* Browser: Chrome, firefox

## Description

I try to create a mesh game object, the texture is from another render-texture. 
This combination works fine in 3.50-beta10. But in 3.50-beta11, the image of mesh is flipX and flipY. 

[Test code](https://codepen.io/rexrainbow/pen/PoGwNxV):
- Left image is the source render-texture, 
- Right image is the mesh, which looks similar with left image, but flipX and flipY.

BTW, Mesh with normal texture loaded from url works fine in 3.50-beta11.

**Comment by photonstorm** [comment]
This needs adjusting for in the Mesh UV coordinates really, like in this example: http://labs.phaser.io/view.html?src=src\3.50\game%20objects\render%20texture\scene%20to%20render%20texture%20quad.js

**Comment by rexrainbow** [comment]
Could you point out which line is for *adjusting for in the Mesh UV coordinates*?
I found that I did not use  this line: [`mesh.hideCCW = false`](https://github.com/photonstorm/phaser3-examples/blob/master/public/src/3.50/game%20objects/render%20texture/scene%20to%20render%20texture%20quad.js#L159). But I can not confirm it.

**Comment by rexrainbow** [comment]
Do you mean this line: [`mesh.modelRotation.set(2.604, 0.427, 0)`](https://github.com/photonstorm/phaser3-examples/blob/master/public/src/3.50/game%20objects/render%20texture/scene%20to%20render%20texture%20quad.js#L160)?

**Comment by photonstorm** [comment]
What I meant was it should really be dealt with by the UV coordinates. Textures from WebGL are often y flipped, where-as textures from image files are not, but this ought to be accounted for in the mesh UV coordinates, rather than any trickery elsewhere. You can, of course (as in the example above) just rotate the mesh around instead, so it renders correctly anyway. But not if using a 3d model. I'll close this as I've merged your PR with flipY in.
