### ISSUE TITLE
Video API in WeChatBrowser(x5 engine) can't render？ 

### ISSUE THREAD

**Issue by luvsta** [photonstorm/phaser#5418]
## Version

* Phaser Version: 3.23.0 - 3.24.1

* Operating system:iOS 12-14

* Browser:WeChat Browser ( x5 engine )

## Description

When I use Video API in Wechat Browser, the console remind me "TypeError: null is not an object (evaluating 'this.frame.realWidth')"
When I check 'Phaser.scene.cache.video' ,it shows that Map Struct's size is 0.
On the contrary, it’s available in PC Chrome and Mobile Phone Browser, the video rendered successfully and the Map Struct's size is 1.
See additional information for details.

## Example Test Code

load : this.load.video('key','url',true,false)

scene: this.add.video(0,0,'key');

## Additional Information

PC console:
![pc console](https://user-images.githubusercontent.com/38464468/100565554-e03b5980-32fe-11eb-96c1-9a5f5be1c181.jpg)
ios console:
![iOS抛出异常](https://user-images.githubusercontent.com/38464468/100565606-f812dd80-32fe-11eb-82b0-1deb1d03c5ee.PNG)

**Comment by photonstorm** [comment]
Are you sure this is a video format that WeChat is capable of playing? have you tested the video outside of Phaser? (like in a simple HTML video component)

**Comment by jcyuan** [comment]
> Are you sure this is a video format that WeChat is capable of playing? have you tested the video outside of Phaser? (like in a simple HTML video component)

i'm familiar with this platform, it's not a fault of Phaser, because Phaser loads video with `<video>` tag in `VideoFile` loader type, but this tag is just not available on this platform. to create a video on this platform, there is its private API: `wx.createVideo(...);`

@luvsta if you wanna do this, you have to customize your own loader filetypes (https://github.com/photonstorm/phaser/blob/master/src/loader/filetypes/VideoFile.js FYI), and register it into the file manager:

```
FileTypesManager.register('wxVideo', ...... {  this.addFile(new YourOwnFileType(...));  });
```

**Comment by photonstorm** [comment]
Useful info, thanks!

**Comment by luvsta** [comment]
@jcyuan thx bro,I realized that the WeChat browser was blocking the load event，and i fixed that using 'wx-js-sdk' ,wrapping code behavior as user behavior.

**Comment by luvsta** [comment]
@photonstorm Yes, I found out later that it was a browser limitation
