### ISSUE TITLE
strokeRoundedRect() draws wrong lines on mobile

### ISSUE THREAD

**Issue by fkoch-tgm** [photonstorm/phaser#5429]
## Version

* Phaser Version: 3.50 Beta Build 11

* Operating system: Android 9

* Browser: Firefox 83.1.0 (Mobile)

## Description

When you call the strokeRoundedRect()-Method in the smartphone-browser with a line-thickness >2, the beginnings of the arcs in the corners draw lines to (0,0):

![screenshot](https://user-images.githubusercontent.com/45557700/101144410-91e8cc00-3618-11eb-9d26-883987a53953.jpg)

## Example Test Code
The code is an adapted version of the example from phaser.io: https://phaser.io/examples/v3/view/game-objects/graphics/stroke-rounded-rectangle

```javascript
var config = {
    width: 800,
    height: 600,
    type: Phaser.AUTO,
    parent: 'phaser-example',
    scene: {
        create: create
    }
};

var game = new Phaser.Game(config);

var graphics;

function create ()
{
    graphics = this.add.graphics();

    graphics.lineStyle(1, 0xff00ff, 1);

    graphics.strokeRoundedRect(32, 32, 300, 200);

    graphics.lineStyle(6, 0xffff00, 1);

    graphics.strokeRoundedRect(360, 240, 400, 300, { tl: 64, tr: 22, bl: 12, br: 0 });
}
```

**Comment by photonstorm** [comment]
@fkoch-tgm does it do it for a _filled_ rounded rectangle as well?

**Comment by fkoch-tgm** [comment]
@photonstorm I haven't tested it yet

**Comment by FloodGames** [comment]
I have seen this behaviour. Thanks for reporting!

**Comment by h2ooooooo** [comment]
@photonstorm Yeah I can confirm that the same happens with a rounded rectangle even after adding fill to it.

The issue seems to happen in the arc method, and only when Phaser is running in WEBGL mode. (Phaser.CANVAS works fine, even in Firefox 89 on Android 11).

The most simple solution at the moment seems to be what @fkoch-tgm suggested, and just go with a lineStyle of 2 or less. Can probably hack multiple 2-px rounded rectangles on top of eachother with varying sizes to get a thicker line, even though it's a crappy solution.

**Comment by sreadixl** [comment]
I am seeing this issue was well, but currently only on older Android devices and on Kindle devices. Android device is a Samsung Galaxy S6 running Android 5, and the Kindle device is a Kindle 7 running FireOS 7. Happens only with `lineStyle` graphics (and maybe also when using Ropes, but haven't been able to confirm it yet).

This seems like it's probably related to https://github.com/photonstorm/phaser/issues/3955. I tried using the "working combination" solution (https://github.com/photonstorm/phaser/issues/3955#issuecomment-416241222) but it doesn't seem to solve it.

![roundedrect](https://user-images.githubusercontent.com/91687421/140090519-034486af-5f4d-4750-aa54-ce4a9d8e8818.png)

**Comment by sreadixl** [comment]
Someone posted some code to fix the rounded rect issue in #3955 and it works for me - the only issue is that it doesn't create the exact same rect size as the functions in Phaser (which is probably easily fixable, I just haven't tried doing it yet): https://github.com/photonstorm/phaser/issues/3955#issuecomment-955203372

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

I've tested this on various old Samsung devices, on old versions of Android, and the fix works fine.

**Comment by ghost** [comment]
I'm using 3.55.2 and experiencing the same, I read the 3.50 changelog and it should be fixed in this version. May I know which one I need to use?

Thanks

**Comment by photonstorm** [comment]
> I'm using 3.55.2 and experiencing the same, I read the 3.50 changelog and it should be fixed in this version. May I know which one I need to use?

It's the 3.60 version it is fixed in.
