### ISSUE TITLE
SVGs look bad

### ISSUE THREAD

**Issue by EddieOne** [photonstorm/phaser#5440]
[hat_button.zip](https://github.com/photonstorm/phaser/files/5669281/hat_button.zip)

## Version

* Phaser Version: Phaser v3.24.1 (WebGL | Web Audio) 
* Operating system: Windows 10
* Browser: Firefox

## Description

SVGs look bad in Phaser. Maybe the plan is to make Phaser Bitmap only. Not sure, I do miss vector art though. The filesize is tiny and it scale like magic.

![image](https://user-images.githubusercontent.com/1835156/101699592-a1ad4980-3a38-11eb-8bd5-0e82e6e1ed31.png)

## Example Test Code

`this.load.svg('hatBtn', 'src/img/hat_button.svg', { scale: 0.25 });`

## Additional Information

When Googling Phaser 3 and SVG it kind of seems like SVG + Phaser might work with the scaling change. May be another issue with anti-alias however.

![image](https://user-images.githubusercontent.com/1835156/101700002-87c03680-3a39-11eb-9af2-17ebe7e97110.png)

See the attached zip file for an example svg file.

**Comment by 16patsle** [comment]
This is due to the fact that Phaser has to convert the SVG to a (bitmap) texture first, since it doesn't parse and render SVGs itself (which would be a lot of work). So you won't get the benefit of real time resizability that you get with vector graphics otherwise. You still get the tiny file size though, and you can still scale up the graphics as much as you want, you just need to plan ahead and set the scale when loading the SVG, so the resolution of the generated texture matches the size it will be on screen.

This example shows the difference quite nicely, both in code and visually:
http://labs.phaser.io/edit.html?src=src/loader\svg\load%20svg%20with%20scale.js

**Comment by photonstorm** [comment]
WebGL1 itself is, by its nature, pixel-based. Anything SVG you want to be displayed has to be rasterized to a texture first. There is no avoiding this. The rasterization process is handled by the browser, not Phaser. So results are mixed depending on target size, the source file, and the browser being used. The smaller the texture being created, the worse it's going to look.

If you need to use SVG files natively and retain their resizing abilities then don't use a WebGL1 based framework. You'd be far better off using native CSS.

**Comment by jsindos** [comment]
@16patsle Hi, I'm wondering if you can explain why the two cartman svgs end up the same size, but use different scales? Whereas the other svgs in the example use the same scale to end up as the same size.

```
this.load.svg('cartman', 'assets/svg/cartman.svg');
this.load.svg('cartman2', 'assets/svg/cartman.svg', { scale: 4.65 });

const svg1 = this.add.image(50, 100, 'cartman').setScale(3).setOrigin(0);
const svg4 = this.add.image(50, 100, 'cartman2').setOrigin(0).setVisible(false);
```
