### ISSUE TITLE
Control video game object which has the same video key independently

### ISSUE THREAD

**Issue by rexrainbow** [photonstorm/phaser#5458]
## Version

* Phaser Version: 3.50, or previous version

* Operating system:  window

* Browser: chrome, firefox

## Description

In this [demo](https://codepen.io/rexrainbow/pen/yLNYJdz), there are 4 video game objects.
- Top left/top right play the same video key 'test', and top right invokes `play()`
- Bottom left plays video key 'v0'
- Bottom right plays video key 'v1', and invokes `play()`

These video keys are loaded from the same url.

In chrome browser on desktop, 
- Top left which dose not `play()` will play with top right.
- Bottom left won't play.

Thus I assume that : *Video game object with the same key will reference the same video element and will be controlled at the same time*

In firefox browser on desktop, 
- 4 video game objects all play

My hypothesis is not true.

**Comment by SlimHajRomdhane** [comment]
It is possible that the behavior you are seeing in Chrome is due to how the browser handles HTML5 video elements. Chrome may be optimizing video playback by reusing the same underlying video element for multiple video game objects with the same key, which can cause unexpected behavior if one video is played or paused.

To avoid this issue, you can try creating separate video elements for each video game object by using the Video class instead of the GameObjectFactory.video method. Here's an example:

// Load the video
this.load.video('test', 'assets/test.mp4');

// Create a video object
const video = this.add.video(x, y, 'test');

// Play the video
video.play();

This will create a new video element for each Video object, which should prevent interference between different videos.
I hope this helps!
- SlimHR

**Comment by photonstorm** [comment]
The Video Game Object has been fully recoded in v3.60 and now works very differently from before, and this bug is no longer present, as each Video Game Object now maintains its own unique video element and doesn't share resources. You can see this here: https://labs.phaser.io/view.html?src=src%5C3.60%5Cgame%20objects%5Cvideo%5Cmultiple%20video%20instances.js&v=dev
