### ISSUE TITLE
extending GameObjects.Image causes error

### ISSUE THREAD

**Issue by DPMakerQB** [photonstorm/phaser#5502]
## Version

* Phaser Version: 3.51.0

* Operating system: Windows

* Browser: Chrome

## Description

I'm trying to extend and create my own Phaser.GameObjects.Image, but when I put that newly created GameObject into the game it causes an error.
`Uncaught TypeError: Cannot read property 'call' of undefined`

## Example Test Code

https://codepen.io/dpmakerqb/pen/PoGxWbK

## Additional Information

Please change Phaser.GameObjects.**Image** to Phaser.GameObjects.**Sprite** and the code will **not** show an error.

**Comment by photonstorm** [comment]
You cannot add your `Button` class to the Update List because you haven't given it a `preUpdate` method, which is required. This is why changing Image to Sprite works because it has one already. Either use the Sprite Game Object, or add a `preUpdate` method to your Button class, or don't add it to the Update List.
