### ISSUE TITLE
Blitter rendering from Atlas / Spritesheet broken as of Phaser 3.52.0

### ISSUE THREAD

**Issue by fazzamatazz** [photonstorm/phaser#5537]
Phaser Version: Phaser 3.52.0
Operating system: Windows 10
Browser: Chrome 88 / Firefox 85

Blitter throws "_Uncaught TypeError: src.setRenderDepth is not a function_" error since 3.52.0 when rendering from atlas / spritesheet. Error does not occur in v3.51.0

Example can be seen in labs.phaser.io blitter multi-atlas example
http://labs.phaser.io/view.html?src=src/game%20objects/blitter/multiple%20atlas%20frame%20bobs.js&v=3.52.0

Error traced to line 166408

```
var BlitterWebGLRenderer = function (renderer, src, camera, parentMatrix)
{
    var list = src.getRenderList();

    if (list.length === 0)
    {
        return src.clearRenderDepth(camera);
    }

    src.setRenderDepth(camera); <--- throws error
```

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).
