### ISSUE TITLE
Documentation: Scale fix in the blog - phaser 3

### ISSUE THREAD

**Issue by ahmad88me** [photonstorm/phaser#5586]
This is about the scale tutorial: https://phaser.io/phaser3/devlog/136

The FIT option seems to have a typo (or maybe I did something wrong)
Using `Phaser.DOM.FIT` didn't work for me. 
instead, `Phaser.Scale.FIT` did work. 

I hope this would help.

**Comment by photonstorm** [comment]
This is a Dev Log from 2 years ago, hence the message at the top of the page:

**Warning**
Due to the rapid pace of change some links or details may no longer be correct.

If it was a proper tutorial I would certainly edit it, but this is how it was going to work 2 year ago - thankfully, you figured out how it changed for yourself.
