### ISSUE TITLE
Container pipelines seem to do nothing, while pipelines on container contents works fine.

### ISSUE THREAD

**Issue by richard-ennuicreative** [photonstorm/phaser#5588]
## Version
* Phaser Version: 3.5x.x (currently 3.52.0, but all 3.5x.x versions have the issue (I believe there were many changes to pipelines within 3.50.0, so it makes sense that that's where it would have broke).
* Operating system: Any
* Browser: Any

## Description
Setting the pipeline on each individual sprite within a container works just fine (albeit each sprite is now it's own draw call, which is what I'm trying to avoid), but changing it so that all the sprites are int he same container and that is what has the pipeline set just does not seem to use the pipeline at all.

## Example Test Code
The issue is present in the Phaser Labs container pipeline example; https://labs.phaser.io/view.html?src=src/renderer/container%20pipeline.js

You'll see that the fish are not actually using the pipeline.

## Additional Information
In my project, I'm not using the same pipeline as the labs example, but the issue is still the same.

**Comment by photonstorm** [comment]
This example should have been removed, it was never meant to make it live as it was just a bit of test code during 3.50 development (it never worked in previous versions, either).

A Container should not (and never has) forced the pipeline for its children to use. It can set a post pipeline for post-render effects, but that is all. It doesn't actually use a pipeline at all, because it never renders. Although it has the Pipeline Component because you can set post pipelines on it. In hindsight, the Pipeline Component shouldn't have had the post functions added to it, but instead, a new Post Pipeline Component should have been created instead, then it would have avoided this confusion (because `setPipeline` would never have been a valid call on a Container like it isn't).

However, it is what it is now, so this will need handling in the documentation instead.
