### ISSUE TITLE
DOM Create Container blocks pointer events

### ISSUE THREAD

**Issue by joep1978** [photonstorm/phaser#5677]
## Version

* Phaser Version: 3.54.0

* Operating system: Mac

* Browser: Chrome, Safari

## Description

When using createContainer to integrate DOM elements, only click/mousedown input events seem to make it through to the Phaser input system.  Cursor or pointer over/out events don't seem to work.  It seems that the DOM container blocks any non click-type events.

I made a hacky workaround by setting the container div to be "display:none" and then immediately back to "display:block" which somehow fixes the issue, but this shouldn't be necessary

You can see the issue in the fiddle below - when the page loads the mouse over events do not work.  However if you click the text "Click to fix with weird hack" the mouseover/out events instantly start working again.

## Example Test Code

https://jsfiddle.net/joep1978/xLk135wp/23/

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. However, we've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).
