### ISSUE TITLE
Better documentation regarding css rules and meta tags expected from Phaser.

### ISSUE THREAD

**Issue by marcusx2** [photonstorm/phaser#5746]
Phaser is great, I like it. This is not a problem with Phaser, but more so a problem with html/css and people like me who don't have a lot of experience with html/css.

I noticed that a lot of phaser's features only work properly on the browsers if your html has the proper meta tags/css. This may be obvious to many people, but I think a lot of people also expect these features to just work, regardless of how the html/css is configured.

For example, see this issue that [I created](https://phaser.discourse.group/t/how-to-avoid-having-to-scroll-on-safari/9769). It was just a missing css rule that was required to make the behavior of the scalemode work properly on Safari.

I ran into other similar issues, and it was all about fiddling with the css rules and/or meta tag until I got the config that made Phaser's features work right.

I would like to kindly ask to add to the documentation the meta tags and CSS rules that Phaser expects to have the proper behavior. I fought a lot because Phaser wasn't working because of some mystic css/meta tag rule that was missing or configured incorrectly.

I think this would help newbies a lot. Thank you for your time.

**Comment by photonstorm** [comment]
Phaser doesn't actually require _any_ CSS or Meta tags to be present on the page. Sometimes, in some cases, it can be handy to add them to override default browser behavior (as you've found out!) - but not always, so I'm a bit reluctant to say, "You need to do this" because it's far more specific than you'd think. Such is the highly annoying and inconsistent way of the browser 😔
