### ISSUE TITLE
Problems changing dirty property due to camera's startFollow method call

### ISSUE THREAD

**Issue by izure1** [photonstorm/phaser#5756]
## Version

* Phaser Version: 3.50.1+

* Operating system: Windows 10

* Browser: Chrome/91

## Description

Hello, I apologize that English is not my first language.  
If you don't understand what I'm saying, please ask. Let me explain again.

Isn't the `dirty` property of the camera affected by the `startFollow` method?

I use the code below to detect the movement of the camera.

```
// did the camera move?
if (camera.dirty) {
  ...
}
```

However, if the camera changes the `scrollX`, `scrollY` property due to the `startFollow` method, the `dirty` property is not set to true.  

Is this intended?
However, it is strange that it works normally when the `scrollX`, `scrollY` property is changed directly.

## Example Test Code

https://jsfiddle.net/7wtksfyc/

**Comment by photonstorm** [comment]
When a Camera follows a Sprite it sets the `scrollX` and `scrollY` properties in the `Camera.preRender` method:

https://github.com/photonstorm/phaser/blob/master/src/cameras/2d/Camera.js#L574-L575

These are setters, so they cause `dirty = false` to be set. So it's definitely being set correctly.

The issue is likely _when_ you're checking this value, as it doesn't get set until `preRender` which happens after `update` has run.

**Comment by photonstorm** [comment]
Change your example so it checks the dirty flag in either `render` or `preRender` rather than `update` and it works fine.
