### ISSUE TITLE
High GPU usage

### ISSUE THREAD

**Issue by wangybg** [photonstorm/phaser#5771]
## Version

* Phaser Version: 3.56.0

* Operating system: IOS 12

* Browser:safari
## Description
I just used a image gameObject,nothing else，GPU usage more than 60%
## Example Test Code
    const width = 750;
    const height = 1624;
    const config = {
        type: Phaser.WEBGL,
        width,
        height,
        scene: [SceneB],
        dom: {
          createContainer: true
        },
        render: {
            clearBeforeRender:false,
            antialias: true,
            transparent: true,
            pixelArt: false,
        },
        scale: {
            mode: Phaser.Scale.WIDTH_CONTROLS_HEIGHT,
        },
        canvas: canvasNode,
    }
this.add.image(0,0,'background').setOrigin(0)  // background image width = 750px height = 1624px;

## Additional Information
the measurement tool is perfDog  https://perfdog.wetest.net/
the same game, using phasr to develop gpu usage rate is higher than cocos and egret，I never figured it out

**Comment by photonstorm** [comment]
GPU performance, especially on mobile, is nearly always down to the canvas size and how well the browser supports your GPU driver. Even with a single image, at 750 x 1624 you're still clearing and drawing 1.2 million pixels every single frame (for the background color) even before it has rendered something. You could (and should) try swapping to use the CANVAS renderer, as lots of devices struggle with large WebGL canvases.

If Cocos can handle that resolution just fine in WebGL and browser (not compiled to native) then I'd suggest just using it.

**Comment by TomorrowToday** [comment]
> GPU performance, especially on mobile, is nearly always down to the canvas size and how well the browser supports your GPU driver. Even with a single image, at 750 x 1624 you're still clearing and drawing 1.2 million pixels every single frame (for the background color) even before it has rendered something. You could (and should) try swapping to use the CANVAS renderer, as lots of devices struggle with large WebGL canvases.
> 
> If Cocos can handle that resolution just fine in WebGL and browser (not compiled to native) then I'd suggest just using it.

Is this still the recommendation with 3.60?

**Comment by photonstorm** [comment]
> Is this still the recommendation with 3.60?

Yes and no.

Mobile performance is _massively_ better under v3.60. Higher than any previous version we've ever released.

However, the fact still remains that a 750 x 1624 sized canvas is _big_ and will take GPU effort to handle rendering in browser. The bigger, the slower.

**Comment by TomorrowToday** [comment]
I would have thought up to ~1080x1920 for a 2d game would be pretty easy. Is it just how pixi is utilizing webgl under the hood that is not well optimized or something fundamental with webgl rendering? Either way, I look forward to trying 3.60 and it being out of beta. We've been using the canvas renderer and it works okay mostly, but struggles on older devices to keep up with our previous game built in the DOM and drains batteries much faster.

**Comment by photonstorm** [comment]
It's not really a valid comparison (DOM vs. WebGL) - DOM will only update when you modify an element. Otherwise, it remains static, so the browser doesn't have to actually do anything. Whereas for most traditional game loops you are clearing and refreshing the WebGL canvas every single frame, which on high-end mobile devices can be 100+ times per second. At 1080 x 1920 that's a lot of grunt work going on.

If your game can survive with mostly static elements, or just a handful of things moving at a time, then DOM will nearly always outperform WebGL (assuming you don't need 3D or shaders)

But it's a very fine tipping point, and it's **100% game specific**. It doesn't take much _at all_ for DOM to buckle and really struggle, causing constant repaints and document flows if you try and throw a decent arcade game at it. Whereas WebGL is optimized for exactly this and can handle hundreds of thousands of sprites before stressing too much. Of course, it will drain battery faster, as it's now doing a load more than it ever was before. That canvas size eats VRAM, and those pixels need refreshing. It all has a cost.

At the end of the day, pick the right tool for the job. It's not a black/white world out there.

**Comment by ddanushkin** [comment]
@TomorrowToday We noticed that a setup like this [https://phaser.io/examples/v3/view/game-config/custom-webgl2-canvas](https://phaser.io/examples/v3/view/game-config/custom-webgl2-canvas) really helps with iOS WebGL performance. (at least on version 3.55.2)
And Geometry Masks don't work) so if you use them, maybe it's not a solution for you.

**Comment by photonstorm** [comment]
This issue has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/what-resolution-is-more-suitable-for-game-development/13542/1
