### ISSUE TITLE
Particle emitter does not stops, even though maxParticles is being set

### ISSUE THREAD

**Issue by ivorcosta** [photonstorm/phaser#5773]
## Version
* Phaser Version: 3.55.2
* Operating system: Windows 10
* Browser: Chrome 91

## Description

Particle emitter does not stop creating particles, even thought the `maxParticles` is being set.
When changing the below codepen from `maxParticles: 30` to `maxParticles: 19`, it stops. From `20` onwards it does not stops.
It is a bit random, just keep playing with the numbers. It also have the same weird behavior if you change the lifespan or speed.

## Example Test Code

https://codepen.io/ivorcosta/pen/qBmZGON

**Comment by samme** [comment]
I'm not sure what's the expected behavior for `maxParticles`. It changed from [v3.15.1](https://labs.phaser.io/view.html?src=src/game%20objects\particle%20emitter\fire%20max%2010%20particles.js&v=3.15.1 "fire max 10 particles (Phaser v3.15.1)") to [v3.16.1](https://labs.phaser.io/view.html?src=src/game%20objects\particle%20emitter\fire%20max%2010%20particles.js&v=3.16.1 "fire max 10 particles (Phaser v3.161)"), but that may have been because of an unrelated bugfix.

In the test code example, [the emitter is never at its limit](https://codepen.io/samme/pen/VwbjbxM?editors=0010) because it never **creates** 30 particles. It creates only 20 or so and then recycles them. If you change lifespan or frequency it may then hit the limit if no dead particles are available.

It does seem peculiar to me that once an emitter reaches its limit (described as a creation limit) it stops emitting particles at all, even if dead ones are available.

**Comment by ivorcosta** [comment]
I thought `maxParticles` was the maximum total allowed amount of particles the emitter could fire.
I want a small animation that fires a few particles and stops. In order to achieve that, I have to start a emitter and use `setTimeout` to stop it after a while? Wouldn't have a more elegant solution?

**Comment by photonstorm** [comment]
`maxParticles` is the maximum amount it can fire in one single burst, not in total.

There is no such feature for 'kill this emitter after X particles are emitted', although I may consider it for a PR.

**Comment by samme** [comment]
@photonstorm Is <https://labs.phaser.io/view.html?src=src/game%20objects%5Cparticle%20emitter%5Cfire%20max%2010%20particles.js&v=3.16.1> the expected behavior then?

**Comment by 2007heaven** [comment]
> There is no such feature for 'kill this emitter after X particles are emitted', although I may consider it for a PR.

@photonstorm The emitter does stop once the sum of the recycling-pending (`dead`) particle count and the `alive` count is greater than `maxParticles`.

>`maxParticles` is the maximum amount it can fire in one single burst, not in total.

By changing `maxParticles` to 15 [in this example](https://labs.phaser.io/edit.html?src=src/game%20objects\particle%20emitter\fire%20max%2010%20particles.js), the sum of dead and alive ones never exceed 15 since the dead ones are recycled.

---

>Set to hard limit the amount of particle objects this emitter is allowed to create.

Docs sentence communicates particle _object_ amount limit. While this is technically true since total amount of _js objects_ (dead + alive) is not greater than that, it is misleading since one expects the option to apply on what they see on screen.

https://github.com/photonstorm/phaser/blob/aa5f54cfa268c86823bf1dd52c83099fa0ef9ac2/src/gameobjects/particles/ParticleEmitter.js#L462-L471

---

By changing the following on the aforementioned example page, one can validate the non-exceeding counts over time:
```js
// ...
        maxParticles: 15,
// ...

function update (time, delta)
{
    fpsText.setText('FPS: ' + (1000/delta).toFixed(3) + '\n' +
       `Alive ${particles.emitters.first.alive.length}` + '\n' + `Dead ${particles.emitters.first.dead.length}`);
}

```
