### ISSUE TITLE
Hand cursor is only displayed after moving the cursor manually

### ISSUE THREAD

**Issue by robinheidrich** [photonstorm/phaser#5783]
If a game object uses the hand cursor and it moves under the cursor, the cursor will only update when you move it yourself.

It would be smoother if, like in Flash, the cursor was dynamically updated without having to move it manually.

I would love to see this in a future update.

![screenshot](https://user-images.githubusercontent.com/23118399/126075766-d6df3db9-34b8-4df6-aa7e-64a0250880f1.gif)

**Comment by photonstorm** [comment]
This feature already exists. It's called pollAlways in the Input Plug-in. It's an expensive feature to enable which is why it's off by default.

**Comment by robinheidrich** [comment]
Tried it and it works perfectly, thank you.

What do you mean by expensive feature, are there any performance issues using this?

**Comment by photonstorm** [comment]
If you only have a few interactive objects, it's ok, but if you have a lot then it costs a lot of processor time checking them every single frame.

**Comment by photonstorm** [comment]
I appreciate "a lot" is a bit vague, but it depends on the platform, so it's best to just test it. But if you've got like 50 objects and under (and they are _not_ pixel perfect input enabled) then it should be just fine turned on. More than this and I would definitely test it carefully on your target devices.

**Comment by robinheidrich** [comment]
Thanks for the explanation. Wouldn't it make sense if Phaser only checks for pointer updates when a game object is moving, rather than every single frame?

**Comment by photonstorm** [comment]
It's not as simple as that. Game Objects can move in a large number of ways, via directly manipulating their position / rotation / scale, or via physics, or via tweens. Changing their animation frame can also cause their size (and pivot) to change. Then you've got the Cameras to factor in, which may be scrolling or repositioning, and input is based on the combination of the Game Object _and_ the Camera you're checking against, because they can be stacked, placed anywhere, etc, plus across potentially multiple simultaneous Scenes as well.

The cost of running checks across all of this and invalidating a Game Object so it knows to re-test for input, vs. you just being careful about using `pollAlways` just doesn't really balance out.

**Comment by robinheidrich** [comment]
I see, then I'll try to use the feature carefully. Thank you.
