### ISSUE TITLE
context restore error

### ISSUE THREAD

**Issue by actionmoon** [photonstorm/phaser#5823]
## Version
* Phaser Version: 3.55.2
* Operating system:  all
* Browser: all

## Description

**WARNING: Too many active WebGL contexts. Oldest context will be lost.**

When encountering this kind of problem, it will trigger the WebGL context loss event, but how to recover from the context loss. 

The function contextRestoredHandler in WebGLRenderer only reinitializes WebGLRender, but it does not restore the related Buffer, Texture, and Shader

## Additional Information

![飞书20210902-100929](https://user-images.githubusercontent.com/6701451/131770014-4f40c448-4f76-454b-82a0-618962a820ca.png)

**Comment by photonstorm** [comment]
Yeah, I'm aware this doesn't work (I'm not sure it _ever_ has, to be honest).

I also don't think this is an easy fix, either. There's so much inside the API now that has no concept of restoring from a context loss that it may be easier just to remove the current handlers and leave it as a known issue rather than half-heartedly try to restore it.

**Comment by photonstorm** [comment]
Ok. I've removed all of the half-baked restore handling and the renderer will now just die gracefully and not spam the console with errors. This isn't something we can put in Phaser 3, so it'll have to be done properly in Phaser 4.
