### ISSUE TITLE
Game gets paused with stage.disableVisibilityChange = true

### ISSUE THREAD

**Issue by Agnostic** [photonstorm/phaser#682]
I am trying to disable the onBlur or pause event, but when the tab is not focused, the game is not updating the player position until gets focused again, I am using socket.io to receive events from server, the events are received correctly in real time.

Here's my code:
https://github.com/Agnostic/js-morpg/blob/master/public/js/app.js

**Comment by SyraTechnologies** [comment]
Chrome and several other browsers will throttle or stop scripts when you lose focus of the page.

Per the documentation, Chrome does not call requestAnimationFrame() when a page is in the background. This behavior has been in place since 2011. Include this polyfill to allow requestAnimationFrame to run while the tab is not active when an audio track is playing.

		var lastTime = new Date().getTime();
		window.requestAnimationFrame = function( callback, element ) {
			var currTime = new Date().getTime();
			var timeToCall = Math.max( 0, 16 - ( currTime - lastTime ) );
			var id = window.setTimeout( function() {
				callback( currTime + timeToCall );
			}, timeToCall );
			lastTime = currTime + timeToCall;
			return id;
		};
		window.cancelAnimationFrame = function( id ) {
			window.clearTimeout( id );
		};

There are a number of automatic exemptions from this throttling:
Applications playing audio are considered foreground and aren’t throttled.

(Running an audio track alone will not solve this issue. You must include the polyfill above in your code. As long as you are running a non silence audio track it will now continue playing your phaser games when you navigate away from the tab.)
